/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Roles técnicos de base de datos
Archivo:               ROLES_DATABASE.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Define perfiles técnicos reutilizables sin crear logins ni almacenar claves.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF DATABASE_PRINCIPAL_ID(N'OXI_APP_EXECUTOR') IS NULL
    EXEC(N'CREATE ROLE [OXI_APP_EXECUTOR] AUTHORIZATION [dbo]');
IF DATABASE_PRINCIPAL_ID(N'OXI_READONLY') IS NULL
    EXEC(N'CREATE ROLE [OXI_READONLY] AUTHORIZATION [dbo]');
IF DATABASE_PRINCIPAL_ID(N'OXI_DEVELOPER') IS NULL
    EXEC(N'CREATE ROLE [OXI_DEVELOPER] AUTHORIZATION [dbo]');
IF DATABASE_PRINCIPAL_ID(N'OXI_DEPLOYER') IS NULL
    EXEC(N'CREATE ROLE [OXI_DEPLOYER] AUTHORIZATION [dbo]');

GRANT EXECUTE ON SCHEMA::[CONFIGURACION] TO [OXI_APP_EXECUTOR];
GRANT EXECUTE ON SCHEMA::[SEGURIDAD] TO [OXI_APP_EXECUTOR];
GRANT EXECUTE ON SCHEMA::[INVENTARIO] TO [OXI_APP_EXECUTOR];
GRANT EXECUTE ON SCHEMA::[COMERCIAL] TO [OXI_APP_EXECUTOR];
GRANT EXECUTE ON SCHEMA::[COMPRAS] TO [OXI_APP_EXECUTOR];
GRANT EXECUTE ON SCHEMA::[LOGISTICA] TO [OXI_APP_EXECUTOR];
GRANT EXECUTE ON SCHEMA::[AUDITORIA] TO [OXI_APP_EXECUTOR];

GRANT SELECT ON SCHEMA::[CONFIGURACION] TO [OXI_READONLY];
GRANT SELECT ON SCHEMA::[SEGURIDAD] TO [OXI_READONLY];
GRANT SELECT ON SCHEMA::[INVENTARIO] TO [OXI_READONLY];
GRANT SELECT ON SCHEMA::[COMERCIAL] TO [OXI_READONLY];
GRANT SELECT ON SCHEMA::[COMPRAS] TO [OXI_READONLY];
GRANT SELECT ON SCHEMA::[LOGISTICA] TO [OXI_READONLY];
GRANT SELECT ON SCHEMA::[AUDITORIA] TO [OXI_READONLY];

GRANT CONTROL TO [OXI_DEVELOPER];
GRANT CONTROL TO [OXI_DEPLOYER];
