/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Datos ficticios no productivos
Archivo: 01_DATOS_FICTICIOS_QA.sql | Versión: 1.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea identidad y maestros ficticios para Testing y Sandbox sin datos personales reales.
Historial: 1.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial idempotente.
===============================================================================
*/
DECLARE @V_ID_EMPRESA BIGINT =
(
    SELECT [ID_EMPRESA]
    FROM [CONFIGURACION].[EMPRESAS]
    WHERE [CODIGO] = N'OXITIGRE'
);

IF NOT EXISTS
(
    SELECT 1
    FROM [SEGURIDAD].[USUARIOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [NOMBRE_USUARIO] = N'QAADMIN'
)
BEGIN
    INSERT INTO [SEGURIDAD].[USUARIOS]
        ([ID_EMPRESA], [NOMBRE_USUARIO], [NOMBRES], [APELLIDO], [EMAIL], [HASH_CLAVE], [SALT_CLAVE],
         [ALGORITMO_CLAVE], [ITERACIONES_CLAVE], [DEBE_CAMBIAR_CLAVE], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_EMPRESA, N'QAADMIN', N'Usuario', N'Pruebas', N'qa.admin@example.invalid',
         0xB7A9B09EACC1635F9337B75EAA57A9F3889AD72BFADA73AFAD3166F0B0916F54D4CFCB5ADD9A88D43C9101B2B4FF6370B8E6277C4D9EF962E1E924A6DD6B7BE6,
         0xFE6E38262CFE21F35048C3673F751A17B574609F86304972F59B3502B13633E3,
         N'PBKDF2-SHA512', 210000, 0, N'ACTIVO', 1);
END;

DECLARE @V_ID_USUARIO BIGINT =
(
    SELECT [ID_USUARIO]
    FROM [SEGURIDAD].[USUARIOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [NOMBRE_USUARIO] = N'QAADMIN'
);
DECLARE @V_ID_ROL BIGINT =
(
    SELECT [ID_ROL]
    FROM [SEGURIDAD].[ROLES]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'ADMINISTRADOR'
);

IF NOT EXISTS
(
    SELECT 1
    FROM [SEGURIDAD].[USUARIOS_ROLES]
    WHERE [ID_USUARIO] = @V_ID_USUARIO
      AND [ID_ROL] = @V_ID_ROL
      AND [CODIGO_ESTADO] = N'ACTIVO'
)
BEGIN
    INSERT INTO [SEGURIDAD].[USUARIOS_ROLES]
        ([ID_USUARIO], [ID_ROL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_USUARIO, @V_ID_ROL, N'ACTIVO', @V_ID_USUARIO);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM [COMERCIAL].[CLIENTES]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'CLI-900001'
)
BEGIN
    INSERT INTO [COMERCIAL].[CLIENTES]
        ([ID_EMPRESA], [CODIGO], [TIPO_PERSONA], [NOMBRE_RAZON_SOCIAL], [APELLIDO], [TIPO_DOCUMENTO],
         [NUMERO_DOCUMENTO], [EMAIL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_EMPRESA, N'CLI-900001', 'F', N'Cliente', N'Ficticio', N'DNI', N'99999999',
         N'cliente.qa@example.invalid', N'Dato exclusivo de Testing y Sandbox.', N'ACTIVO', @V_ID_USUARIO);
END;

IF NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO] = N'QA_UN')
BEGIN
    INSERT INTO [CONFIGURACION].[UNIDADES_MEDIDA]
        ([CODIGO], [NOMBRE], [SIMBOLO], [PERMITE_DECIMALES], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (N'QA_UN', N'Unidad ficticia', N'qa', 0, N'ACTIVO', @V_ID_USUARIO);
END;

IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [CODIGO] = N'QA')
BEGIN
    INSERT INTO [INVENTARIO].[CATEGORIAS_PRODUCTO]
        ([CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (N'QA', N'Pruebas', N'Categoría ficticia no productiva.', N'ACTIVO', @V_ID_USUARIO);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM [INVENTARIO].[DEPOSITOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'QA_CENTRAL'
)
BEGIN
    INSERT INTO [INVENTARIO].[DEPOSITOS]
        ([ID_EMPRESA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_EMPRESA, N'QA_CENTRAL', N'Depósito ficticio', N'Exclusivo de Testing y Sandbox.',
         N'ACTIVO', @V_ID_USUARIO);
END;

DECLARE @V_ID_DEPOSITO BIGINT =
(
    SELECT [ID_DEPOSITO]
    FROM [INVENTARIO].[DEPOSITOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'QA_CENTRAL'
);

IF NOT EXISTS
(
    SELECT 1
    FROM [INVENTARIO].[UBICACIONES]
    WHERE [ID_DEPOSITO] = @V_ID_DEPOSITO
      AND [CODIGO] = N'GENERAL'
)
BEGIN
    INSERT INTO [INVENTARIO].[UBICACIONES]
        ([ID_DEPOSITO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_DEPOSITO, N'GENERAL', N'Ubicación general', N'Ubicación ficticia de QA.', N'ACTIVO', @V_ID_USUARIO);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM [INVENTARIO].[PRODUCTOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'PRD-900001'
)
BEGIN
    INSERT INTO [INVENTARIO].[PRODUCTOS]
        ([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION],
         [CODIGO_BARRAS], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @V_ID_EMPRESA, [CAT].[ID_CATEGORIA_PRODUCTO], [UNI].[ID_UNIDAD_MEDIDA], N'PRD-900001',
           N'Producto ficticio QA', N'Producto exclusivo de ambientes no productivos.', N'QA-000001',
           N'ACTIVO', @V_ID_USUARIO
    FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT]
    CROSS JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI]
    WHERE [CAT].[CODIGO] = N'QA'
      AND [UNI].[CODIGO] = N'QA_UN';
END;

DECLARE @V_ID_PRODUCTO BIGINT =
(
    SELECT [ID_PRODUCTO]
    FROM [INVENTARIO].[PRODUCTOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'PRD-900001'
);

IF NOT EXISTS
(
    SELECT 1
    FROM [INVENTARIO].[EXISTENCIAS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [ID_PRODUCTO] = @V_ID_PRODUCTO
      AND [ID_DEPOSITO] = @V_ID_DEPOSITO
)
BEGIN
    INSERT INTO [INVENTARIO].[EXISTENCIAS]
        ([ID_EMPRESA], [ID_PRODUCTO], [ID_DEPOSITO], [CANTIDAD], [STOCK_MINIMO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_EMPRESA, @V_ID_PRODUCTO, @V_ID_DEPOSITO, 100, 10, N'ACTIVO', @V_ID_USUARIO);
END;
