/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_ORDEN_COMPRA_SAVE
Archivo: SP_ORDEN_COMPRA_SAVE.sql | Procedimiento: COMPRAS.SP_ORDEN_COMPRA_SAVE | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Guarda una orden borrador con importes calculados autoritativamente.
Parámetros de entrada: @I_DETALLES_JSON, @I_FECHA_ENTREGA_ESPERADA, @I_FECHA_ORDEN_UTC, @I_ID_DEPOSITO, @I_ID_EMPRESA, @I_ID_ORDEN_COMPRA, @I_ID_PROVEEDOR, @I_MONEDA, @I_OBSERVACION, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_ORDEN_COMPRA, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMPRAS.ORDENES_COMPRA - INSERT/UPDATE; COMPRAS.ORDENES_COMPRA_DETALLES - DELETE/INSERT/SELECT; COMPRAS.PROVEEDORES - SELECT; INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.PRODUCTOS - SELECT.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Snapshot histórico del proveedor.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMPRAS].[SP_ORDEN_COMPRA_SAVE]
    @I_ID_EMPRESA BIGINT,
    @I_ID_ORDEN_COMPRA BIGINT = NULL,
    @I_ID_PROVEEDOR BIGINT,
    @I_ID_DEPOSITO BIGINT,
    @I_FECHA_ORDEN_UTC DATETIME2(3),
    @I_FECHA_ENTREGA_ESPERADA DATE = NULL,
    @I_MONEDA NVARCHAR(3),
    @I_OBSERVACION NVARCHAR(1000) = NULL,
    @I_DETALLES_JSON NVARCHAR(MAX),
    @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_ORDEN_COMPRA BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    SET @O_ID_ORDEN_COMPRA = NULL; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_ORDEN_UTC IS NULL OR LEN(@I_MONEDA) <> 3 OR ISJSON(@I_DETALLES_JSON) <> 1
        THROW 50000, 'Fecha, moneda y renglones válidos son obligatorios.', 1;
    IF @I_FECHA_ENTREGA_ESPERADA < CONVERT(DATE, @I_FECHA_ORDEN_UTC)
        THROW 50000, 'La entrega esperada no puede ser anterior a la orden.', 1;

    DECLARE @T_DETALLES TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL PRIMARY KEY,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [COSTO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL,
        [SUBTOTAL] DECIMAL(19,4) NOT NULL,
        [DESCUENTO] DECIMAL(19,4) NOT NULL,
        [IMPUESTO] DECIMAL(19,4) NOT NULL,
        [TOTAL] DECIMAL(19,4) NOT NULL
    );
    BEGIN TRY
        INSERT INTO @T_DETALLES
        SELECT [J].[ID_PRODUCTO], [J].[CANTIDAD], [J].[COSTO_UNITARIO], [J].[PORCENTAJE_DESCUENTO],
               [J].[PORCENTAJE_IMPUESTO], [C].[SUBTOTAL], [C].[DESCUENTO], [C].[IMPUESTO], [C].[TOTAL]
        FROM OPENJSON(@I_DETALLES_JSON) WITH
        (
            [ID_PRODUCTO] BIGINT '$.ProductId', [CANTIDAD] DECIMAL(19,4) '$.Quantity',
            [COSTO_UNITARIO] DECIMAL(19,4) '$.UnitCost', [PORCENTAJE_DESCUENTO] DECIMAL(9,6) '$.DiscountRate',
            [PORCENTAJE_IMPUESTO] DECIMAL(9,6) '$.TaxRate'
        ) AS [J]
        CROSS APPLY
        (
            SELECT CONVERT(DECIMAL(19,4), ROUND(CONVERT(DECIMAL(38,8), [J].[CANTIDAD]) * [J].[COSTO_UNITARIO], 4)) AS [SUBTOTAL]
        ) AS [S]
        CROSS APPLY
        (
            SELECT [S].[SUBTOTAL],
                   CONVERT(DECIMAL(19,4), ROUND([S].[SUBTOTAL] * [J].[PORCENTAJE_DESCUENTO], 4)) AS [DESCUENTO]
        ) AS [D]
        CROSS APPLY
        (
            SELECT [D].[SUBTOTAL], [D].[DESCUENTO],
                   CONVERT(DECIMAL(19,4), ROUND(([D].[SUBTOTAL] - [D].[DESCUENTO]) * [J].[PORCENTAJE_IMPUESTO], 4)) AS [IMPUESTO],
                   CONVERT(DECIMAL(19,4), ROUND(([D].[SUBTOTAL] - [D].[DESCUENTO]) * (1 + [J].[PORCENTAJE_IMPUESTO]), 4)) AS [TOTAL]
        ) AS [C];
    END TRY
    BEGIN CATCH
        THROW 50000, 'Las cantidades o importes superan el rango permitido.', 1;
    END CATCH;

    IF NOT EXISTS (SELECT 1 FROM @T_DETALLES) OR (SELECT COUNT(*) FROM @T_DETALLES) > 100
       OR EXISTS (SELECT 1 FROM @T_DETALLES WHERE [CANTIDAD] <= 0 OR [COSTO_UNITARIO] < 0 OR [PORCENTAJE_DESCUENTO] NOT BETWEEN 0 AND 1 OR [PORCENTAJE_IMPUESTO] NOT BETWEEN 0 AND 1)
        THROW 50000, 'La orden debe contener entre 1 y 100 productos con cantidades e importes válidos.', 1;

    BEGIN TRY
        BEGIN TRANSACTION;
        DECLARE @V_PROVEEDOR_RAZON_SOCIAL NVARCHAR(200), @V_PROVEEDOR_CUIT NVARCHAR(30), @V_PROVEEDOR_CONDICION_PAGO NVARCHAR(150);
        SELECT @V_PROVEEDOR_RAZON_SOCIAL=[RAZON_SOCIAL], @V_PROVEEDOR_CUIT=[CUIT], @V_PROVEEDOR_CONDICION_PAGO=[CONDICION_PAGO]
        FROM [COMPRAS].[PROVEEDORES] WITH (UPDLOCK, HOLDLOCK)
        WHERE [ID_PROVEEDOR]=@I_ID_PROVEEDOR AND [ID_EMPRESA]=@I_ID_EMPRESA AND [CODIGO_ESTADO]=N'ACTIVO';
        IF @V_PROVEEDOR_RAZON_SOCIAL IS NULL
           OR NOT EXISTS (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_DEPOSITO] = @I_ID_DEPOSITO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO')
           OR EXISTS (SELECT 1 FROM @T_DETALLES AS [D] WHERE NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] AS [P] WITH (UPDLOCK, HOLDLOCK) WHERE [P].[ID_PRODUCTO] = [D].[ID_PRODUCTO] AND [P].[ID_EMPRESA] = @I_ID_EMPRESA AND [P].[CODIGO_ESTADO] = N'ACTIVO'))
            THROW 50000, 'El proveedor, depósito o uno de los productos no es válido.', 1;

        DECLARE @V_SUBTOTAL DECIMAL(19,4) = (SELECT SUM([SUBTOTAL]) FROM @T_DETALLES);
        DECLARE @V_DESCUENTO DECIMAL(19,4) = (SELECT SUM([DESCUENTO]) FROM @T_DETALLES);
        DECLARE @V_IMPUESTO DECIMAL(19,4) = (SELECT SUM([IMPUESTO]) FROM @T_DETALLES);
        DECLARE @V_TOTAL DECIMAL(19,4) = (SELECT SUM([TOTAL]) FROM @T_DETALLES);

        IF @I_ID_ORDEN_COMPRA IS NULL
        BEGIN
            DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMPRAS].[SEQ_ORDEN_COMPRA_CODIGO];
            DECLARE @V_CODIGO NVARCHAR(30) = N'OC-' + RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6);
            INSERT INTO [COMPRAS].[ORDENES_COMPRA]
                ([ID_EMPRESA], [ID_PROVEEDOR], [PROVEEDOR_RAZON_SOCIAL], [PROVEEDOR_CUIT], [PROVEEDOR_CONDICION_PAGO], [ID_DEPOSITO], [CODIGO], [FECHA_ORDEN_UTC], [FECHA_ENTREGA_ESPERADA], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
            VALUES (@I_ID_EMPRESA, @I_ID_PROVEEDOR, @V_PROVEEDOR_RAZON_SOCIAL, @V_PROVEEDOR_CUIT, @V_PROVEEDOR_CONDICION_PAGO, @I_ID_DEPOSITO, @V_CODIGO, @I_FECHA_ORDEN_UTC, @I_FECHA_ENTREGA_ESPERADA, UPPER(@I_MONEDA), @V_SUBTOTAL, @V_DESCUENTO, @V_IMPUESTO, @V_TOTAL, @I_OBSERVACION, N'BORRADOR', @S_ID_USUARIO);
            SET @O_ID_ORDEN_COMPRA = CONVERT(BIGINT, SCOPE_IDENTITY());
        END
        ELSE
        BEGIN
            UPDATE [COMPRAS].[ORDENES_COMPRA]
            SET [ID_PROVEEDOR] = @I_ID_PROVEEDOR, [PROVEEDOR_RAZON_SOCIAL]=@V_PROVEEDOR_RAZON_SOCIAL,
                [PROVEEDOR_CUIT]=@V_PROVEEDOR_CUIT, [PROVEEDOR_CONDICION_PAGO]=@V_PROVEEDOR_CONDICION_PAGO, [ID_DEPOSITO] = @I_ID_DEPOSITO,
                [FECHA_ORDEN_UTC] = @I_FECHA_ORDEN_UTC, [FECHA_ENTREGA_ESPERADA] = @I_FECHA_ENTREGA_ESPERADA,
                [MONEDA] = UPPER(@I_MONEDA), [SUBTOTAL] = @V_SUBTOTAL, [TOTAL_DESCUENTO] = @V_DESCUENTO,
                [TOTAL_IMPUESTO] = @V_IMPUESTO, [TOTAL] = @V_TOTAL, [OBSERVACION] = @I_OBSERVACION,
                [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
            WHERE [ID_ORDEN_COMPRA] = @I_ID_ORDEN_COMPRA AND [ID_EMPRESA] = @I_ID_EMPRESA
              AND [CODIGO_ESTADO] = N'BORRADOR' AND [ROW_VERSION] = @I_ROW_VERSION;
            IF @@ROWCOUNT = 0
            BEGIN SET @O_CODIGO_ERROR = 50004; SET @O_MENSAJE = N'La orden cambió, no pertenece a la empresa o ya no está en borrador.'; ROLLBACK TRANSACTION; RETURN; END;
            SET @O_ID_ORDEN_COMPRA = @I_ID_ORDEN_COMPRA;
            DELETE FROM [COMPRAS].[ORDENES_COMPRA_DETALLES] WHERE [ID_ORDEN_COMPRA] = @I_ID_ORDEN_COMPRA;
        END;

        INSERT INTO [COMPRAS].[ORDENES_COMPRA_DETALLES]
            ([ID_ORDEN_COMPRA], [ID_PRODUCTO], [CANTIDAD_PEDIDA], [CANTIDAD_RECIBIDA], [CANTIDAD_CERRADA], [COSTO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL_RENGLON], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL_RENGLON], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_ORDEN_COMPRA, [ID_PRODUCTO], [CANTIDAD], 0, 0, [COSTO_UNITARIO], [PORCENTAJE_DESCUENTO],
               [PORCENTAJE_IMPUESTO], [SUBTOTAL], [DESCUENTO], [IMPUESTO], [TOTAL], N'PENDIENTE', @S_ID_USUARIO
        FROM @T_DETALLES;
        SET @O_FILAS_AFECTADAS = 1 + @@ROWCOUNT;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;
END;
