/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PROVEEDOR_SAVE
Archivo: SP_PROVEEDOR_SAVE.sql | Procedimiento: COMPRAS.SP_PROVEEDOR_SAVE | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o actualiza un proveedor de la empresa autenticada.
Parámetros de entrada: @I_CODIGO_ESTADO, @I_CONDICION_PAGO, @I_CONTACTOS_JSON, @I_CORREO, @I_CUIT, @I_ID_EMPRESA, @I_ID_PROVEEDOR, @I_NOMBRE_COMERCIAL, @I_OBSERVACION, @I_RAZON_SOCIAL, @I_ROW_VERSION, @I_TELEFONO, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_PROVEEDOR, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: AUDITORIA.BITACORA_CAMBIOS_ESTADO - INSERT; COMPRAS.PROVEEDORES - INSERT/SELECT/UPDATE; COMPRAS.PROVEEDORES_CONTACTOS - INSERT/UPDATE.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: Registra información mediante objetos del esquema AUDITORIA referenciados por el procedimiento.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Normalización fiscal y auditoría de baja lógica.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMPRAS].[SP_PROVEEDOR_SAVE]
    @I_ID_EMPRESA BIGINT,
    @I_ID_PROVEEDOR BIGINT = NULL,
    @I_RAZON_SOCIAL NVARCHAR(200),
    @I_NOMBRE_COMERCIAL NVARCHAR(200) = NULL,
    @I_CUIT NVARCHAR(30),
    @I_CORREO NVARCHAR(254) = NULL,
    @I_TELEFONO NVARCHAR(50) = NULL,
    @I_CONDICION_PAGO NVARCHAR(150) = NULL,
    @I_OBSERVACION NVARCHAR(1000) = NULL,
    @I_CODIGO_ESTADO NVARCHAR(30),
    @I_CONTACTOS_JSON NVARCHAR(MAX),
    @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_PROVEEDOR BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    SET @I_CUIT = REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(@I_CUIT)), N'-', N''), N'.', N''), N' ', N'');
    IF LEN(@I_CUIT) <> 11 OR @I_CUIT LIKE N'%[^0-9]%'
        THROW 50000, 'El CUIT debe contener once números.', 1;
    SET @I_CUIT = STUFF(STUFF(@I_CUIT, 3, 0, N'-'), 12, 0, N'-');
    IF NULLIF(LTRIM(RTRIM(@I_RAZON_SOCIAL)), N'') IS NULL OR NULLIF(LTRIM(RTRIM(@I_CUIT)), N'') IS NULL
       OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO')
        THROW 50000, 'Razón social, identificación fiscal y estado son obligatorios.', 1;

    DECLARE @T_CONTACTOS TABLE ([NOMBRE] NVARCHAR(200) NOT NULL, [CARGO] NVARCHAR(100) NULL,
        [EMAIL] NVARCHAR(254) NULL, [TELEFONO] NVARCHAR(50) NULL, [ES_PRINCIPAL] BIT NOT NULL);
    IF ISJSON(@I_CONTACTOS_JSON) <> 1 THROW 50000, 'La colección de contactos no es válida.', 1;
    INSERT INTO @T_CONTACTOS
    SELECT [NOMBRE], [CARGO], [EMAIL], [TELEFONO], [ES_PRINCIPAL]
    FROM OPENJSON(@I_CONTACTOS_JSON) WITH ([NOMBRE] NVARCHAR(200) '$.Name', [CARGO] NVARCHAR(100) '$.Position',
        [EMAIL] NVARCHAR(254) '$.Email', [TELEFONO] NVARCHAR(50) '$.Phone', [ES_PRINCIPAL] BIT '$.IsPrimary');
    IF (SELECT COUNT(*) FROM @T_CONTACTOS) > 20 OR (EXISTS (SELECT 1 FROM @T_CONTACTOS) AND (SELECT COUNT(*) FROM @T_CONTACTOS WHERE [ES_PRINCIPAL] = 1) <> 1)
       OR EXISTS (SELECT 1 FROM @T_CONTACTOS WHERE NULLIF(LTRIM(RTRIM([NOMBRE])), N'') IS NULL)
        THROW 50000, 'Informá hasta veinte contactos y exactamente uno principal.', 1;

    BEGIN TRANSACTION;

    IF @I_ID_PROVEEDOR IS NULL
    BEGIN
        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMPRAS].[SEQ_PROVEEDOR_CODIGO];
        DECLARE @V_CODIGO NVARCHAR(30) = N'PRV-' + RIGHT(N'000000' + CONVERT(NVARCHAR(20), @V_NUMERO), 6);
        INSERT INTO [COMPRAS].[PROVEEDORES]
            ([ID_EMPRESA], [CODIGO], [RAZON_SOCIAL], [NOMBRE_COMERCIAL], [CUIT], [CORREO], [TELEFONO],
             [CONDICION_PAGO], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        VALUES (@I_ID_EMPRESA, @V_CODIGO, @I_RAZON_SOCIAL, @I_NOMBRE_COMERCIAL, @I_CUIT, @I_CORREO,
                @I_TELEFONO, @I_CONDICION_PAGO, @I_OBSERVACION, @I_CODIGO_ESTADO, @S_ID_USUARIO);
        SET @O_ID_PROVEEDOR = CONVERT(BIGINT, SCOPE_IDENTITY()); SET @O_FILAS_AFECTADAS = 1;
    END;
    ELSE
    BEGIN
        DECLARE @V_ESTADO_ANTERIOR NVARCHAR(30) =
        (
            SELECT [CODIGO_ESTADO] FROM [COMPRAS].[PROVEEDORES] WITH (UPDLOCK, HOLDLOCK)
            WHERE [ID_PROVEEDOR]=@I_ID_PROVEEDOR AND [ID_EMPRESA]=@I_ID_EMPRESA AND [ROW_VERSION]=@I_ROW_VERSION
        );
        UPDATE [COMPRAS].[PROVEEDORES]
        SET [RAZON_SOCIAL] = @I_RAZON_SOCIAL, [NOMBRE_COMERCIAL] = @I_NOMBRE_COMERCIAL, [CUIT] = @I_CUIT,
            [CORREO] = @I_CORREO, [TELEFONO] = @I_TELEFONO, [CONDICION_PAGO] = @I_CONDICION_PAGO,
            [OBSERVACION] = @I_OBSERVACION, [CODIGO_ESTADO] = @I_CODIGO_ESTADO,
            [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
        WHERE [ID_PROVEEDOR] = @I_ID_PROVEEDOR AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;
        SET @O_FILAS_AFECTADAS = @@ROWCOUNT; SET @O_ID_PROVEEDOR = @I_ID_PROVEEDOR;
        IF @O_FILAS_AFECTADAS = 0 BEGIN SET @O_CODIGO_ERROR = 50004; SET @O_MENSAJE = N'El proveedor fue modificado por otro usuario o no pertenece a la empresa.'; ROLLBACK; RETURN; END;
        IF @V_ESTADO_ANTERIOR <> @I_CODIGO_ESTADO
            INSERT INTO [AUDITORIA].[BITACORA_CAMBIOS_ESTADO]
                ([ENTIDAD], [PKEY], [CODIGO_ESTADO_ANTERIOR], [CODIGO_ESTADO_NUEVO], [MOTIVO], [ID_USUARIO], [ID_CORRELACION], [ID_USUARIO_ALTA])
            VALUES (N'PROVEEDOR', @I_ID_PROVEEDOR, @V_ESTADO_ANTERIOR, @I_CODIGO_ESTADO,
                N'Cambio de estado desde Compras', @S_ID_USUARIO, NEWID(), @S_ID_USUARIO);
        UPDATE [COMPRAS].[PROVEEDORES_CONTACTOS] SET [CODIGO_ESTADO] = N'INACTIVO',
            [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
        WHERE [ID_PROVEEDOR] = @O_ID_PROVEEDOR AND [CODIGO_ESTADO] = N'ACTIVO';
    END;

    INSERT INTO [COMPRAS].[PROVEEDORES_CONTACTOS]
        ([ID_PROVEEDOR], [NOMBRE], [CARGO], [EMAIL], [TELEFONO], [ES_PRINCIPAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @O_ID_PROVEEDOR, [NOMBRE], [CARGO], [EMAIL], [TELEFONO], [ES_PRINCIPAL], N'ACTIVO', @S_ID_USUARIO FROM @T_CONTACTOS;
    SET @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS + @@ROWCOUNT;
    COMMIT;
END;
