/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_RECEPCION_REVERSE
Archivo: SP_RECEPCION_REVERSE.sql | Procedimiento: COMPRAS.SP_RECEPCION_REVERSE | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Compensa una recepción intacta sin eliminar el documento ni su trazabilidad.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: AUDITORIA.BITACORA_CAMBIOS_ESTADO - INSERT; COMPRAS.ORDENES_COMPRA - SELECT/UPDATE; COMPRAS.ORDENES_COMPRA_DETALLES - SELECT; COMPRAS.RECEPCIONES_COMPRA - SELECT/UPDATE; COMPRAS.RECEPCIONES_COMPRA_DETALLES - SELECT/UPDATE; INVENTARIO.ACTIVOS - SELECT; INVENTARIO.ACTIVOS_CONTENIDOS - SELECT; INVENTARIO.ACTIVOS_EVENTOS - INSERT/SELECT; INVENTARIO.LOTES - SELECT; INVENTARIO.LOTES_EXISTENCIAS - SELECT; INVENTARIO.MOVIMIENTOS_DETALLES - SELECT; INVENTARIO.MOVIMIENTOS_DETALLES_ACTIVOS - INSERT; INVENTARIO.MOVIMIENTOS_DETALLES_LOTES - INSERT/SELECT.
Auditoría: Registra información mediante objetos del esquema AUDITORIA referenciados por el procedimiento.
Parámetros de entrada: Empresa, recepción, motivo y versión del documento.
Parámetros de sesión: Sesión y usuario responsables de la reversión.
Parámetros de salida: Código funcional, mensaje y filas afectadas.
Transacción: Movimiento de salida, stock, lotes, activos, recepción y orden se confirman juntos.
Historial: 1.0.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMPRAS].[SP_RECEPCION_REVERSE]
    @I_ID_EMPRESA BIGINT,
    @I_ID_RECEPCION BIGINT,
    @I_MOTIVO_REVERSION NVARCHAR(500),
    @I_ROW_VERSION BINARY(8),
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @O_CODIGO_ERROR=NULL; SET @O_MENSAJE=NULL; SET @O_FILAS_AFECTADAS=0;
    IF @I_ID_RECEPCION<=0 OR NULLIF(LTRIM(RTRIM(@I_MOTIVO_REVERSION)),N'') IS NULL
        THROW 50000, 'La recepción y el motivo de reversión son obligatorios.', 1;

    BEGIN TRY
        DECLARE @V_INICIO_TRANSACCION BIT=0;
        IF @@TRANCOUNT=0
        BEGIN
            BEGIN TRANSACTION;
            SET @V_INICIO_TRANSACCION=1;
        END
        ELSE SAVE TRANSACTION [SP_RECEPCION_REVERSE_SAVEPOINT];
        DECLARE @V_ID_ORDEN BIGINT, @V_ID_MOVIMIENTO_ORIGINAL BIGINT, @V_ID_DEPOSITO BIGINT,
                @V_CODIGO_RECEPCION NVARCHAR(30), @V_ESTADO_RECEPCION NVARCHAR(30), @V_ESTADO_ORDEN NVARCHAR(30);
        SELECT @V_ID_ORDEN=[REC].[ID_ORDEN_COMPRA], @V_ID_MOVIMIENTO_ORIGINAL=[REC].[ID_MOVIMIENTO],
               @V_ID_DEPOSITO=[ORD].[ID_DEPOSITO], @V_CODIGO_RECEPCION=[REC].[CODIGO],
               @V_ESTADO_RECEPCION=[REC].[CODIGO_ESTADO], @V_ESTADO_ORDEN=[ORD].[CODIGO_ESTADO]
        FROM [COMPRAS].[RECEPCIONES_COMPRA] AS [REC] WITH (UPDLOCK,HOLDLOCK)
        INNER JOIN [COMPRAS].[ORDENES_COMPRA] AS [ORD] WITH (UPDLOCK,HOLDLOCK)
            ON [ORD].[ID_ORDEN_COMPRA]=[REC].[ID_ORDEN_COMPRA] AND [ORD].[ID_EMPRESA]=@I_ID_EMPRESA
        WHERE [REC].[ID_RECEPCION]=@I_ID_RECEPCION AND [REC].[ID_EMPRESA]=@I_ID_EMPRESA
          AND [REC].[ROW_VERSION]=@I_ROW_VERSION;

        IF @V_ID_ORDEN IS NULL OR @V_ESTADO_RECEPCION<>N'CONFIRMADA' OR @V_ESTADO_ORDEN=N'CERRADA'
        BEGIN
            SET @O_CODIGO_ERROR=50008;
            SET @O_MENSAJE=N'La recepción cambió, ya fue reversada o su orden fue cerrada.';
            IF @V_INICIO_TRANSACCION=1 ROLLBACK TRANSACTION;
            RETURN;
        END;

        -- INICIO: Una reversión segura exige que cada lote conserve íntegramente la entrada original.
        IF EXISTS
        (
            SELECT 1
            FROM [INVENTARIO].[LOTES] AS [LOT] WITH (UPDLOCK,HOLDLOCK)
            INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE]
                ON [RDE].[ID_RECEPCION_DETALLE]=[LOT].[ID_RECEPCION_DETALLE]
            OUTER APPLY (SELECT SUM([LEX].[CANTIDAD]) AS [CANTIDAD] FROM [INVENTARIO].[LOTES_EXISTENCIAS] AS [LEX] WITH (UPDLOCK,HOLDLOCK) WHERE [LEX].[ID_LOTE]=[LOT].[ID_LOTE] AND [LEX].[ID_DEPOSITO]=@V_ID_DEPOSITO) AS [SAL]
            WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION
              AND ([LOT].[CODIGO_ESTADO]<>N'DISPONIBLE' OR COALESCE([SAL].[CANTIDAD],0)<>[LOT].[CANTIDAD_INICIAL]
                OR EXISTS
                (
                    SELECT 1 FROM [INVENTARIO].[MOVIMIENTOS_DETALLES_LOTES] AS [MDL]
                    INNER JOIN [INVENTARIO].[MOVIMIENTOS_DETALLES] AS [MDE] ON [MDE].[ID_MOVIMIENTO_DETALLE]=[MDL].[ID_MOVIMIENTO_DETALLE]
                    WHERE [MDL].[ID_LOTE]=[LOT].[ID_LOTE] AND [MDE].[ID_MOVIMIENTO]<>@V_ID_MOVIMIENTO_ORIGINAL
                ))
        )
        BEGIN
            SET @O_CODIGO_ERROR=50008;
            SET @O_MENSAJE=N'No se puede reversar: un lote recibido ya fue movido, fraccionado o consumido.';
            IF @V_INICIO_TRANSACCION=1 ROLLBACK TRANSACTION;
            RETURN;
        END;
        -- FIN: Una reversión segura exige que cada lote conserve íntegramente la entrada original.

        -- INICIO: Las series deben continuar disponibles y sin eventos posteriores.
        IF EXISTS
        (
            SELECT 1
            FROM [INVENTARIO].[ACTIVOS] AS [ACT] WITH (UPDLOCK,HOLDLOCK)
            INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE]
                ON [RDE].[ID_RECEPCION_DETALLE]=[ACT].[ID_RECEPCION_DETALLE]
            WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION
              AND ([ACT].[CODIGO_ESTADO]<>N'DISPONIBLE' OR [ACT].[ID_DEPOSITO]<>@V_ID_DEPOSITO OR [ACT].[ID_UBICACION] IS NOT NULL
                OR EXISTS
                (
                    SELECT 1 FROM [INVENTARIO].[ACTIVOS_EVENTOS] AS [EVE]
                    WHERE [EVE].[ID_ACTIVO]=[ACT].[ID_ACTIVO]
                      AND NOT ([EVE].[TIPO_EVENTO]=N'RECEPCION' AND [EVE].[ID_RECEPCION_COMPRA]=@I_ID_RECEPCION)
                ))
        )
        BEGIN
            SET @O_CODIGO_ERROR=50008;
            SET @O_MENSAJE=N'No se puede reversar: una serie recibida ya fue medida, movida, prestada o intervenida.';
            IF @V_INICIO_TRANSACCION=1 ROLLBACK TRANSACTION;
            RETURN;
        END;
        -- FIN: Las series deben continuar disponibles y sin eventos posteriores.

        DECLARE @V_DETALLES_MOVIMIENTO NVARCHAR(MAX)=
        (
            SELECT [RDE].[ID_PRODUCTO] AS [ProductId], @V_ID_DEPOSITO AS [OriginWarehouseId],
                   CONVERT(BIGINT,NULL) AS [DestinationWarehouseId], SUM([RDE].[CANTIDAD_ACEPTADA]) AS [Quantity]
            FROM [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE]
            WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION AND [RDE].[CANTIDAD_ACEPTADA]>0
            GROUP BY [RDE].[ID_PRODUCTO]
            FOR JSON PATH
        );
        DECLARE @V_ID_MOVIMIENTO_REVERSION BIGINT=NULL, @V_ERROR_MOVIMIENTO BIGINT,
                @V_OBSERVACION_MOVIMIENTO NVARCHAR(1000)=CONCAT(N'Reversión de recepción ',@V_CODIGO_RECEPCION),
                @V_FECHA_REVERSION_UTC DATETIME2(3)=SYSUTCDATETIME(),
                @V_MENSAJE_MOVIMIENTO NVARCHAR(4000), @V_FILAS_MOVIMIENTO INT;
        IF @V_DETALLES_MOVIMIENTO<>N'[]'
        BEGIN
            EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE]
                @I_ID_EMPRESA=@I_ID_EMPRESA, @I_TIPO_MOVIMIENTO=N'AJUSTE_SALIDA',
                @I_FECHA_MOVIMIENTO_UTC=@V_FECHA_REVERSION_UTC,
                @I_OBSERVACION=@V_OBSERVACION_MOVIMIENTO,
                @I_DETALLES_JSON=@V_DETALLES_MOVIMIENTO, @S_ID_SESION=@S_ID_SESION,
                @S_ID_USUARIO=@S_ID_USUARIO, @O_ID_MOVIMIENTO=@V_ID_MOVIMIENTO_REVERSION OUTPUT,
                @O_CODIGO_ERROR=@V_ERROR_MOVIMIENTO OUTPUT, @O_MENSAJE=@V_MENSAJE_MOVIMIENTO OUTPUT,
                @O_FILAS_AFECTADAS=@V_FILAS_MOVIMIENTO OUTPUT;
            IF @V_ERROR_MOVIMIENTO IS NOT NULL
            BEGIN
                SET @O_CODIGO_ERROR=50008; SET @O_MENSAJE=COALESCE(@V_MENSAJE_MOVIMIENTO,N'No existe stock suficiente para reversar.');
                IF @V_INICIO_TRANSACCION=1 ROLLBACK TRANSACTION;
                RETURN;
            END;
        END;

        INSERT INTO [INVENTARIO].[MOVIMIENTOS_DETALLES_LOTES]
            ([ID_MOVIMIENTO_DETALLE],[ID_LOTE],[CANTIDAD],[CODIGO_ESTADO],[ID_USUARIO_ALTA])
        SELECT [MDE].[ID_MOVIMIENTO_DETALLE],[LOT].[ID_LOTE],[LOT].[CANTIDAD_INICIAL],N'ACTIVO',@S_ID_USUARIO
        FROM [INVENTARIO].[LOTES] AS [LOT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[LOT].[ID_RECEPCION_DETALLE]
        INNER JOIN [INVENTARIO].[MOVIMIENTOS_DETALLES] AS [MDE] ON [MDE].[ID_MOVIMIENTO]=@V_ID_MOVIMIENTO_REVERSION AND [MDE].[ID_PRODUCTO]=[RDE].[ID_PRODUCTO]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;

        INSERT INTO [INVENTARIO].[MOVIMIENTOS_DETALLES_ACTIVOS]
            ([ID_MOVIMIENTO_DETALLE],[ID_ACTIVO],[CODIGO_ESTADO],[ID_USUARIO_ALTA])
        SELECT [MDE].[ID_MOVIMIENTO_DETALLE],[ACT].[ID_ACTIVO],N'ACTIVO',@S_ID_USUARIO
        FROM [INVENTARIO].[ACTIVOS] AS [ACT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[ACT].[ID_RECEPCION_DETALLE]
        INNER JOIN [INVENTARIO].[MOVIMIENTOS_DETALLES] AS [MDE] ON [MDE].[ID_MOVIMIENTO]=@V_ID_MOVIMIENTO_REVERSION AND [MDE].[ID_PRODUCTO]=[RDE].[ID_PRODUCTO]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;

        INSERT INTO [INVENTARIO].[ACTIVOS_EVENTOS]
            ([ID_EMPRESA],[ID_ACTIVO],[TIPO_EVENTO],[FECHA_EVENTO_UTC],[CODIGO_ESTADO_ANTES],[CODIGO_ESTADO_DESPUES],
             [CONDICION_ANTES],[CONDICION_DESPUES],[CANTIDAD_ANTES],[CANTIDAD_DESPUES],[ID_RECEPCION_COMPRA],
             [OBSERVACION],[ID_CORRELACION],[CODIGO_ESTADO],[ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA,[ACT].[ID_ACTIVO],N'REVERSION_RECEPCION',SYSUTCDATETIME(),[ACT].[CODIGO_ESTADO],N'ANULADO',
               [ACT].[CONDICION_ACTUAL],[ACT].[CONDICION_ACTUAL],[CON].[CANTIDAD_ACTUAL],
               CASE WHEN [CON].[CANTIDAD_ACTUAL] IS NULL THEN NULL ELSE 0 END,@I_ID_RECEPCION,
               @I_MOTIVO_REVERSION,NEWID(),N'CONFIRMADO',@S_ID_USUARIO
        FROM [INVENTARIO].[ACTIVOS] AS [ACT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[ACT].[ID_RECEPCION_DETALLE]
        OUTER APPLY (SELECT SUM([CANTIDAD_ACTUAL]) AS [CANTIDAD_ACTUAL] FROM [INVENTARIO].[ACTIVOS_CONTENIDOS] WHERE [ID_ACTIVO]=[ACT].[ID_ACTIVO] AND [CODIGO_ESTADO]=N'ACTIVO') AS [CON]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;

        UPDATE [LEX] SET [CANTIDAD]=0,[CODIGO_ESTADO]=N'INACTIVO',[FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        FROM [INVENTARIO].[LOTES_EXISTENCIAS] AS [LEX]
        INNER JOIN [INVENTARIO].[LOTES] AS [LOT] ON [LOT].[ID_LOTE]=[LEX].[ID_LOTE]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[LOT].[ID_RECEPCION_DETALLE]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;
        UPDATE [LOT] SET [CODIGO_ESTADO]=N'ANULADO',[FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        FROM [INVENTARIO].[LOTES] AS [LOT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[LOT].[ID_RECEPCION_DETALLE]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;
        UPDATE [CON] SET [CODIGO_ESTADO]=N'INACTIVO',[CANTIDAD_ACTUAL]=0,[FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        FROM [INVENTARIO].[ACTIVOS_CONTENIDOS] AS [CON]
        INNER JOIN [INVENTARIO].[ACTIVOS] AS [ACT] ON [ACT].[ID_ACTIVO]=[CON].[ID_ACTIVO]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[ACT].[ID_RECEPCION_DETALLE]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION AND [CON].[CODIGO_ESTADO]=N'ACTIVO';
        UPDATE [ACT] SET [ID_DEPOSITO]=NULL,[ID_UBICACION]=NULL,[CODIGO_ESTADO]=N'ANULADO',
            [FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        FROM [INVENTARIO].[ACTIVOS] AS [ACT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE]=[ACT].[ID_RECEPCION_DETALLE]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;

        UPDATE [ODE] SET [CANTIDAD_RECIBIDA]=[ODE].[CANTIDAD_RECIBIDA]-[RDE].[CANTIDAD_ACEPTADA],
            [CODIGO_ESTADO]=CASE WHEN [ODE].[CANTIDAD_RECIBIDA]-[RDE].[CANTIDAD_ACEPTADA]+[ODE].[CANTIDAD_CERRADA]>=[ODE].[CANTIDAD_PEDIDA] THEN N'COMPLETO' ELSE N'PENDIENTE' END,
            [FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        FROM [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ODE]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_ORDEN_COMPRA_DETALLE]=[ODE].[ID_ORDEN_COMPRA_DETALLE]
        WHERE [RDE].[ID_RECEPCION]=@I_ID_RECEPCION;

        UPDATE [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] SET [CODIGO_ESTADO]=N'REVERSADA',
            [FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        WHERE [ID_RECEPCION]=@I_ID_RECEPCION;
        UPDATE [COMPRAS].[RECEPCIONES_COMPRA] SET [ID_MOVIMIENTO_REVERSION]=@V_ID_MOVIMIENTO_REVERSION,
            [MOTIVO_REVERSION]=@I_MOTIVO_REVERSION,[FECHA_REVERSION_UTC]=SYSUTCDATETIME(),
            [ID_USUARIO_REVERSION]=@S_ID_USUARIO,[CODIGO_ESTADO]=N'REVERSADA',
            [FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        WHERE [ID_RECEPCION]=@I_ID_RECEPCION;

        DECLARE @V_ESTADO_ORDEN_NUEVO NVARCHAR(30)=CASE
            WHEN NOT EXISTS (SELECT 1 FROM [COMPRAS].[ORDENES_COMPRA_DETALLES] WHERE [ID_ORDEN_COMPRA]=@V_ID_ORDEN AND [CANTIDAD_RECIBIDA]>0) THEN N'APROBADA'
            WHEN EXISTS (SELECT 1 FROM [COMPRAS].[ORDENES_COMPRA_DETALLES] WHERE [ID_ORDEN_COMPRA]=@V_ID_ORDEN AND [CANTIDAD_RECIBIDA]+[CANTIDAD_CERRADA]<[CANTIDAD_PEDIDA]) THEN N'RECIBIDA_PARCIAL'
            ELSE N'RECIBIDA' END;
        UPDATE [COMPRAS].[ORDENES_COMPRA] SET [CODIGO_ESTADO]=@V_ESTADO_ORDEN_NUEVO,
            [FECHA_MODIFICACION_UTC]=SYSUTCDATETIME(),[ID_USUARIO_MODIFICACION]=@S_ID_USUARIO
        WHERE [ID_ORDEN_COMPRA]=@V_ID_ORDEN;

        INSERT INTO [AUDITORIA].[BITACORA_CAMBIOS_ESTADO]
            ([ENTIDAD],[PKEY],[CODIGO_ESTADO_ANTERIOR],[CODIGO_ESTADO_NUEVO],[MOTIVO],[ID_USUARIO],[ID_CORRELACION],[ID_USUARIO_ALTA])
        VALUES (N'RECEPCION_COMPRA',@I_ID_RECEPCION,N'CONFIRMADA',N'REVERSADA',@I_MOTIVO_REVERSION,@S_ID_USUARIO,NEWID(),@S_ID_USUARIO),
               (N'ORDEN_COMPRA',@V_ID_ORDEN,@V_ESTADO_ORDEN,@V_ESTADO_ORDEN_NUEVO,CONCAT(N'Reversión ',@V_CODIGO_RECEPCION),@S_ID_USUARIO,NEWID(),@S_ID_USUARIO);
        SET @O_FILAS_AFECTADAS=2+(SELECT COUNT(*) FROM [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] WHERE [ID_RECEPCION]=@I_ID_RECEPCION);
        IF @V_INICIO_TRANSACCION=1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION=1 AND XACT_STATE()<>0 ROLLBACK TRANSACTION;
        ELSE IF XACT_STATE()=1 ROLLBACK TRANSACTION [SP_RECEPCION_REVERSE_SAVEPOINT];
        THROW;
    END CATCH;
END;
