/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_RECEPCION_CREATE
Archivo: SP_RECEPCION_CREATE.sql | Procedimiento: COMPRAS.SP_RECEPCION_CREATE | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Confirma una recepción parcial; solo lo aceptado ingresa al stock.
Contrato de entrada:
- @I_ID_ORDEN_COMPRA y @I_ROW_VERSION identifican una orden APROBADA o RECIBIDA_PARCIAL sin cambios concurrentes.
- @I_DETALLES_JSON contiene PurchaseOrderLineId, AcceptedQuantity, RejectedQuantity y DamagedQuantity por renglón; la BLL exige DifferenceReason si hay rechazo o daño.
- Lots, SerialNumbers y ContainerContents describen únicamente el material aceptado; las cantidades trazadas deben coincidir con las aceptadas según el tipo de producto.
- @I_NUMERO_REMITO es opcional, pero no puede repetirse dentro de la empresa cuando se informa.
Efecto confirmado: crea el movimiento de entrada solo para cantidades aceptadas; guarda recepción, diferencias, lotes, activos y mediciones; deja pendiente el saldo no aceptado y audita el cambio de estado.
Errores funcionales: 50003 orden o versión no operable; 50005 exceso sobre saldo; 50006 remito duplicado; 50007 trazabilidad inconsistente. Las validaciones generales y errores SQL se propagan con THROW.
Parámetros de entrada: @I_DETALLES_JSON, @I_FECHA_RECEPCION_UTC, @I_ID_EMPRESA, @I_ID_ORDEN_COMPRA, @I_NUMERO_REMITO, @I_OBSERVACION, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_RECEPCION, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: AUDITORIA.BITACORA_CAMBIOS_ESTADO - INSERT; COMPRAS.ORDENES_COMPRA - SELECT/UPDATE; COMPRAS.ORDENES_COMPRA_DETALLES - SELECT; COMPRAS.RECEPCIONES_COMPRA - INSERT/SELECT; COMPRAS.RECEPCIONES_COMPRA_DETALLES - INSERT/SELECT; CONFIGURACION.UNIDADES_MEDIDA - SELECT; INVENTARIO.ACTIVOS - INSERT/SELECT; INVENTARIO.ACTIVOS_CONTENIDOS - INSERT; INVENTARIO.ACTIVOS_EVENTOS - INSERT; INVENTARIO.LOTES - INSERT/SELECT; INVENTARIO.LOTES_EXISTENCIAS - INSERT; INVENTARIO.MEDICIONES_ACTIVOS - INSERT; INVENTARIO.MOVIMIENTOS_DETALLES - SELECT; INVENTARIO.MOVIMIENTOS_DETALLES_ACTIVOS - INSERT; INVENTARIO.MOVIMIENTOS_DETALLES_LOTES - INSERT; INVENTARIO.PRODUCTOS - SELECT.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: Registra información mediante objetos del esquema AUDITORIA referenciados por el procedimiento.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMPRAS].[SP_RECEPCION_CREATE]
    @I_ID_EMPRESA BIGINT,
    @I_ID_ORDEN_COMPRA BIGINT,
    @I_FECHA_RECEPCION_UTC DATETIME2(3),
    @I_NUMERO_REMITO NVARCHAR(80) = NULL,
    @I_OBSERVACION NVARCHAR(1000) = NULL,
    @I_DETALLES_JSON NVARCHAR(MAX),
    @I_ROW_VERSION BINARY(8),
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_RECEPCION BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    SET @O_ID_RECEPCION = NULL; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_RECEPCION_UTC IS NULL OR ISJSON(@I_DETALLES_JSON) <> 1
        THROW 50000, 'La fecha y los renglones de recepción son obligatorios.', 1;

    DECLARE @T_DETALLES TABLE
    (
        [ID_ORDEN_COMPRA_DETALLE] BIGINT NOT NULL PRIMARY KEY,
        [CANTIDAD_ACEPTADA] DECIMAL(19,4) NOT NULL,
        [CANTIDAD_RECHAZADA] DECIMAL(19,4) NOT NULL,
        [CANTIDAD_DANADA] DECIMAL(19,4) NOT NULL,
        [MOTIVO_DIFERENCIA] NVARCHAR(500) NULL
    );
    INSERT INTO @T_DETALLES
    SELECT [ID_ORDEN_COMPRA_DETALLE], [CANTIDAD_ACEPTADA], [CANTIDAD_RECHAZADA], [CANTIDAD_DANADA], [MOTIVO_DIFERENCIA]
    FROM OPENJSON(@I_DETALLES_JSON) WITH
    (
        [ID_ORDEN_COMPRA_DETALLE] BIGINT '$.PurchaseOrderLineId',
        [CANTIDAD_ACEPTADA] DECIMAL(19,4) '$.AcceptedQuantity',
        [CANTIDAD_RECHAZADA] DECIMAL(19,4) '$.RejectedQuantity',
        [CANTIDAD_DANADA] DECIMAL(19,4) '$.DamagedQuantity',
        [MOTIVO_DIFERENCIA] NVARCHAR(500) '$.DifferenceReason'
    );
    IF NOT EXISTS (SELECT 1 FROM @T_DETALLES) OR (SELECT COUNT(*) FROM @T_DETALLES) > 100
       OR EXISTS (SELECT 1 FROM @T_DETALLES WHERE [CANTIDAD_ACEPTADA] < 0 OR [CANTIDAD_RECHAZADA] < 0 OR [CANTIDAD_DANADA] < 0 OR [CANTIDAD_ACEPTADA] + [CANTIDAD_RECHAZADA] + [CANTIDAD_DANADA] <= 0)
        THROW 50000, 'Las cantidades de recepción deben ser válidas y al menos una debe ser mayor que cero.', 1;

    DECLARE @T_LOTES TABLE ([ID_ORDEN_COMPRA_DETALLE] BIGINT NOT NULL, [CODIGO] NVARCHAR(50) NOT NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL, [FECHA_FABRICACION] DATE NULL, [FECHA_VENCIMIENTO] DATE NULL,
        PRIMARY KEY ([ID_ORDEN_COMPRA_DETALLE], [CODIGO]));
    INSERT INTO @T_LOTES
    SELECT CONVERT(BIGINT, JSON_VALUE([REN].[value], '$.PurchaseOrderLineId')), [LOT].[CODIGO], [LOT].[CANTIDAD],
           [LOT].[FECHA_FABRICACION], [LOT].[FECHA_VENCIMIENTO]
    FROM OPENJSON(@I_DETALLES_JSON) AS [REN]
    CROSS APPLY OPENJSON(JSON_QUERY([REN].[value], '$.Lots')) WITH
        ([CODIGO] NVARCHAR(50) '$.Code', [CANTIDAD] DECIMAL(19,4) '$.Quantity',
         [FECHA_FABRICACION] DATE '$.ManufactureDate', [FECHA_VENCIMIENTO] DATE '$.ExpirationDate') AS [LOT];

    DECLARE @T_SERIES TABLE ([ID_ORDEN_COMPRA_DETALLE] BIGINT NOT NULL, [NUMERO_SERIE] NVARCHAR(100) NOT NULL,
        [TIPO_ACTIVO] NVARCHAR(30) NOT NULL, [CAPACIDAD] DECIMAL(19,4) NULL, [PROPIETARIO_CODIGO] NVARCHAR(30) NOT NULL,
        [PROPIETARIO_NOMBRE] NVARCHAR(200) NOT NULL, [CONDICION] NVARCHAR(30) NOT NULL, PRIMARY KEY ([NUMERO_SERIE]));
    INSERT INTO @T_SERIES
    SELECT CONVERT(BIGINT, JSON_VALUE([REN].[value], '$.PurchaseOrderLineId')), [SER].[NUMERO_SERIE], [SER].[TIPO_ACTIVO],
           [SER].[CAPACIDAD], [SER].[PROPIETARIO_CODIGO], [SER].[PROPIETARIO_NOMBRE], [SER].[CONDICION]
    FROM OPENJSON(@I_DETALLES_JSON) AS [REN]
    CROSS APPLY OPENJSON(JSON_QUERY([REN].[value], '$.SerialNumbers')) WITH
        ([NUMERO_SERIE] NVARCHAR(100) '$.SerialNumber', [TIPO_ACTIVO] NVARCHAR(30) '$.AssetType',
         [CAPACIDAD] DECIMAL(19,4) '$.Capacity', [PROPIETARIO_CODIGO] NVARCHAR(30) '$.OwnerCode',
         [PROPIETARIO_NOMBRE] NVARCHAR(200) '$.OwnerName', [CONDICION] NVARCHAR(30) '$.ConditionCode') AS [SER];

    DECLARE @T_CONTENIDOS TABLE ([ID_ORDEN_COMPRA_DETALLE] BIGINT NOT NULL, [NUMERO_SERIE] NVARCHAR(100) NOT NULL,
        [ID_PRODUCTO_CONTENIDO] BIGINT NOT NULL, [CODIGO_LOTE] NVARCHAR(50) NULL, [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [METODO_MEDICION] NVARCHAR(30) NOT NULL);
    INSERT INTO @T_CONTENIDOS
    SELECT CONVERT(BIGINT, JSON_VALUE([REN].[value], '$.PurchaseOrderLineId')), [CON].[NUMERO_SERIE],
           [CON].[ID_PRODUCTO_CONTENIDO], [CON].[CODIGO_LOTE], [CON].[CANTIDAD], [CON].[METODO_MEDICION]
    FROM OPENJSON(@I_DETALLES_JSON) AS [REN]
    CROSS APPLY OPENJSON(JSON_QUERY([REN].[value], '$.ContainerContents')) WITH
        ([NUMERO_SERIE] NVARCHAR(100) '$.AssetSerialNumber', [ID_PRODUCTO_CONTENIDO] BIGINT '$.ContentProductId',
         [CODIGO_LOTE] NVARCHAR(50) '$.LotCode', [CANTIDAD] DECIMAL(19,4) '$.Quantity',
         [METODO_MEDICION] NVARCHAR(30) '$.MeasurementMethod') AS [CON];

    IF EXISTS (SELECT 1 FROM @T_LOTES WHERE [CANTIDAD] <= 0 OR ([FECHA_VENCIMIENTO] IS NOT NULL AND [FECHA_FABRICACION] IS NOT NULL AND [FECHA_VENCIMIENTO] < [FECHA_FABRICACION]))
       OR EXISTS (SELECT 1 FROM @T_SERIES WHERE [CAPACIDAD] IS NOT NULL AND [CAPACIDAD] <= 0)
       OR EXISTS (SELECT 1 FROM @T_CONTENIDOS WHERE [CANTIDAD] <= 0 OR [METODO_MEDICION] NOT IN (N'MANUAL', N'PESAJE', N'CALCULADO'))
        THROW 50000, 'Los lotes, series o contenidos informados no son válidos.', 1;

    BEGIN TRY
        BEGIN TRANSACTION;
        DECLARE @V_ESTADO_ANTERIOR NVARCHAR(30);
        SELECT @V_ESTADO_ANTERIOR = [CODIGO_ESTADO]
        FROM [COMPRAS].[ORDENES_COMPRA] WITH (UPDLOCK, HOLDLOCK)
        WHERE [ID_ORDEN_COMPRA] = @I_ID_ORDEN_COMPRA AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;
        IF @V_ESTADO_ANTERIOR NOT IN (N'APROBADA', N'RECIBIDA_PARCIAL')
        BEGIN SET @O_CODIGO_ERROR = 50003; SET @O_MENSAJE = N'La orden cambió o no admite recepciones en su estado actual.'; ROLLBACK; RETURN; END;
        IF @I_NUMERO_REMITO IS NOT NULL AND EXISTS (SELECT 1 FROM [COMPRAS].[RECEPCIONES_COMPRA] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [NUMERO_DOCUMENTO_PROVEEDOR] = @I_NUMERO_REMITO)
        BEGIN SET @O_CODIGO_ERROR = 50006; SET @O_MENSAJE = N'El número de remito ya fue registrado para esta empresa.'; ROLLBACK; RETURN; END;
        IF EXISTS
        (
            SELECT 1 FROM @T_DETALLES AS [REC]
            LEFT JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD] WITH (UPDLOCK, HOLDLOCK)
              ON [ORD].[ID_ORDEN_COMPRA_DETALLE] = [REC].[ID_ORDEN_COMPRA_DETALLE] AND [ORD].[ID_ORDEN_COMPRA] = @I_ID_ORDEN_COMPRA
            WHERE [ORD].[ID_ORDEN_COMPRA_DETALLE] IS NULL
               OR [REC].[CANTIDAD_ACEPTADA] + [REC].[CANTIDAD_RECHAZADA] + [REC].[CANTIDAD_DANADA] > [ORD].[CANTIDAD_PEDIDA] - [ORD].[CANTIDAD_RECIBIDA] - [ORD].[CANTIDAD_CERRADA]
        )
        BEGIN SET @O_CODIGO_ERROR = 50005; SET @O_MENSAJE = N'Una cantidad recibida supera el saldo pendiente de la orden.'; ROLLBACK; RETURN; END;

        IF EXISTS
        (
            SELECT 1
            FROM @T_DETALLES AS [REC]
            INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD] ON [ORD].[ID_ORDEN_COMPRA_DETALLE] = [REC].[ID_ORDEN_COMPRA_DETALLE]
            INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [ORD].[ID_PRODUCTO]
            OUTER APPLY (SELECT SUM([LOT].[CANTIDAD]) AS [CANTIDAD] FROM @T_LOTES AS [LOT] WHERE [LOT].[ID_ORDEN_COMPRA_DETALLE] = [REC].[ID_ORDEN_COMPRA_DETALLE]) AS [LOT]
            OUTER APPLY (SELECT COUNT(*) AS [CANTIDAD] FROM @T_SERIES AS [SER] WHERE [SER].[ID_ORDEN_COMPRA_DETALLE] = [REC].[ID_ORDEN_COMPRA_DETALLE]) AS [SER]
            WHERE ([PRO].[TIPO_TRAZABILIDAD] = N'NINGUNA' AND (COALESCE([LOT].[CANTIDAD], 0) <> 0 OR [SER].[CANTIDAD] <> 0))
               OR ([PRO].[TIPO_TRAZABILIDAD] IN (N'LOTE', N'SERIE_LOTE') AND COALESCE([LOT].[CANTIDAD], 0) <> [REC].[CANTIDAD_ACEPTADA])
               OR ([PRO].[TIPO_TRAZABILIDAD] IN (N'SERIE', N'SERIE_LOTE') AND CONVERT(DECIMAL(19,4), [SER].[CANTIDAD]) <> [REC].[CANTIDAD_ACEPTADA])
        )
        BEGIN SET @O_CODIGO_ERROR = 50007; SET @O_MENSAJE = N'Los lotes o números de serie no explican exactamente la cantidad aceptada.'; ROLLBACK; RETURN; END;
        IF EXISTS (SELECT 1 FROM @T_SERIES AS [SER] WHERE EXISTS (SELECT 1 FROM [INVENTARIO].[ACTIVOS] AS [ACT] WHERE [ACT].[ID_EMPRESA] = @I_ID_EMPRESA AND [ACT].[NUMERO_SERIE] = [SER].[NUMERO_SERIE]))
        BEGIN SET @O_CODIGO_ERROR = 50007; SET @O_MENSAJE = N'Uno de los números de serie ya existe.'; ROLLBACK; RETURN; END;
        IF EXISTS
        (
            SELECT 1 FROM @T_CONTENIDOS AS [CON]
            WHERE NOT EXISTS (SELECT 1 FROM @T_SERIES AS [SER] WHERE [SER].[NUMERO_SERIE] = [CON].[NUMERO_SERIE])
               OR NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] AS [PRO] WHERE [PRO].[ID_PRODUCTO] = [CON].[ID_PRODUCTO_CONTENIDO] AND [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO')
               OR ([CON].[CODIGO_LOTE] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM @T_LOTES AS [LOT] WHERE [LOT].[CODIGO] = [CON].[CODIGO_LOTE]))
        )
        BEGIN SET @O_CODIGO_ERROR = 50007; SET @O_MENSAJE = N'El contenido no coincide con una serie, producto o lote de esta recepción.'; ROLLBACK; RETURN; END;

        DECLARE @V_ID_MOVIMIENTO BIGINT = NULL;
        IF EXISTS (SELECT 1 FROM @T_DETALLES WHERE [CANTIDAD_ACEPTADA] > 0)
        BEGIN
            DECLARE @V_DETALLES_MOVIMIENTO NVARCHAR(MAX) =
            (
                SELECT [ORD].[ID_PRODUCTO] AS [ProductId], CONVERT(BIGINT, NULL) AS [OriginWarehouseId],
                       [CAB].[ID_DEPOSITO] AS [DestinationWarehouseId], [REC].[CANTIDAD_ACEPTADA] AS [Quantity]
                FROM @T_DETALLES AS [REC]
                INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD] ON [ORD].[ID_ORDEN_COMPRA_DETALLE] = [REC].[ID_ORDEN_COMPRA_DETALLE]
                INNER JOIN [COMPRAS].[ORDENES_COMPRA] AS [CAB] ON [CAB].[ID_ORDEN_COMPRA] = [ORD].[ID_ORDEN_COMPRA]
                WHERE [REC].[CANTIDAD_ACEPTADA] > 0
                FOR JSON PATH
            );
            DECLARE @V_ERROR_MOVIMIENTO BIGINT, @V_MENSAJE_MOVIMIENTO NVARCHAR(4000), @V_FILAS_MOVIMIENTO INT;
            EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE]
                @I_ID_EMPRESA = @I_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'ENTRADA',
                @I_FECHA_MOVIMIENTO_UTC = @I_FECHA_RECEPCION_UTC, @I_OBSERVACION = N'Recepción de orden de compra',
                @I_DETALLES_JSON = @V_DETALLES_MOVIMIENTO, @S_ID_SESION = @S_ID_SESION, @S_ID_USUARIO = @S_ID_USUARIO,
                @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_ERROR_MOVIMIENTO OUTPUT,
                @O_MENSAJE = @V_MENSAJE_MOVIMIENTO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_MOVIMIENTO OUTPUT;
            IF @V_ERROR_MOVIMIENTO IS NOT NULL THROW 50000, @V_MENSAJE_MOVIMIENTO, 1;
        END;

        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMPRAS].[SEQ_RECEPCION_CODIGO];
        DECLARE @V_CODIGO NVARCHAR(30) = N'RC-' + RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6);
        INSERT INTO [COMPRAS].[RECEPCIONES_COMPRA]
            ([ID_EMPRESA], [ID_ORDEN_COMPRA], [ID_MOVIMIENTO], [CODIGO], [FECHA_RECEPCION_UTC], [NUMERO_DOCUMENTO_PROVEEDOR], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        VALUES (@I_ID_EMPRESA, @I_ID_ORDEN_COMPRA, @V_ID_MOVIMIENTO, @V_CODIGO, @I_FECHA_RECEPCION_UTC, @I_NUMERO_REMITO, @I_OBSERVACION, N'CONFIRMADA', @S_ID_USUARIO);
        SET @O_ID_RECEPCION = CONVERT(BIGINT, SCOPE_IDENTITY());

        INSERT INTO [COMPRAS].[RECEPCIONES_COMPRA_DETALLES]
            ([ID_RECEPCION], [ID_ORDEN_COMPRA_DETALLE], [ID_PRODUCTO], [CANTIDAD_ACEPTADA], [CANTIDAD_RECHAZADA], [CANTIDAD_DANADA], [MOTIVO_DIFERENCIA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_RECEPCION, [REC].[ID_ORDEN_COMPRA_DETALLE], [ORD].[ID_PRODUCTO], [REC].[CANTIDAD_ACEPTADA],
               [REC].[CANTIDAD_RECHAZADA], [REC].[CANTIDAD_DANADA], [REC].[MOTIVO_DIFERENCIA], N'ACTIVO', @S_ID_USUARIO
        FROM @T_DETALLES AS [REC]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD] ON [ORD].[ID_ORDEN_COMPRA_DETALLE] = [REC].[ID_ORDEN_COMPRA_DETALLE];
        SET @O_FILAS_AFECTADAS = 1 + @@ROWCOUNT;

        INSERT INTO [INVENTARIO].[LOTES]
            ([ID_EMPRESA], [ID_PRODUCTO], [ID_PROVEEDOR], [ID_RECEPCION_DETALLE], [CODIGO], [CODIGO_LOTE_PROVEEDOR],
             [CANTIDAD_INICIAL], [FECHA_FABRICACION], [FECHA_VENCIMIENTO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, [ORD].[ID_PRODUCTO], [CAB].[ID_PROVEEDOR], [RDE].[ID_RECEPCION_DETALLE],
               [LOT].[CODIGO], [LOT].[CODIGO], [LOT].[CANTIDAD], [LOT].[FECHA_FABRICACION], [LOT].[FECHA_VENCIMIENTO], N'DISPONIBLE', @S_ID_USUARIO
        FROM @T_LOTES AS [LOT]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD] ON [ORD].[ID_ORDEN_COMPRA_DETALLE] = [LOT].[ID_ORDEN_COMPRA_DETALLE]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA] AS [CAB] ON [CAB].[ID_ORDEN_COMPRA] = [ORD].[ID_ORDEN_COMPRA]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION] = @O_ID_RECEPCION AND [RDE].[ID_ORDEN_COMPRA_DETALLE] = [ORD].[ID_ORDEN_COMPRA_DETALLE];

        INSERT INTO [INVENTARIO].[LOTES_EXISTENCIAS]
            ([ID_EMPRESA], [ID_LOTE], [ID_DEPOSITO], [CANTIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, [LOT].[ID_LOTE], [CAB].[ID_DEPOSITO], [LOT].[CANTIDAD_INICIAL], N'ACTIVO', @S_ID_USUARIO
        FROM [INVENTARIO].[LOTES] AS [LOT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE] = [LOT].[ID_RECEPCION_DETALLE]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ODE] ON [ODE].[ID_ORDEN_COMPRA_DETALLE] = [RDE].[ID_ORDEN_COMPRA_DETALLE]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA] AS [CAB] ON [CAB].[ID_ORDEN_COMPRA] = [ODE].[ID_ORDEN_COMPRA]
        WHERE [RDE].[ID_RECEPCION] = @O_ID_RECEPCION;

        INSERT INTO [INVENTARIO].[ACTIVOS]
            ([ID_EMPRESA], [ID_PRODUCTO], [ID_DEPOSITO], [ID_RECEPCION_DETALLE], [CODIGO], [NUMERO_SERIE], [TIPO_ACTIVO],
             [CAPACIDAD], [PROPIETARIO_CODIGO], [PROPIETARIO_NOMBRE], [CONDICION_ACTUAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, [ORD].[ID_PRODUCTO], [CAB].[ID_DEPOSITO], [RDE].[ID_RECEPCION_DETALLE],
               N'ACT-' + RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), NEXT VALUE FOR [INVENTARIO].[SEQ_ACTIVO_CODIGO]), 6),
               [SER].[NUMERO_SERIE], [SER].[TIPO_ACTIVO], [SER].[CAPACIDAD], [SER].[PROPIETARIO_CODIGO],
               [SER].[PROPIETARIO_NOMBRE], [SER].[CONDICION], N'DISPONIBLE', @S_ID_USUARIO
        FROM @T_SERIES AS [SER]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD] ON [ORD].[ID_ORDEN_COMPRA_DETALLE] = [SER].[ID_ORDEN_COMPRA_DETALLE]
        INNER JOIN [COMPRAS].[ORDENES_COMPRA] AS [CAB] ON [CAB].[ID_ORDEN_COMPRA] = [ORD].[ID_ORDEN_COMPRA]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION] = @O_ID_RECEPCION AND [RDE].[ID_ORDEN_COMPRA_DETALLE] = [ORD].[ID_ORDEN_COMPRA_DETALLE];

        INSERT INTO [INVENTARIO].[ACTIVOS_CONTENIDOS]
            ([ID_EMPRESA], [ID_ACTIVO], [ID_PRODUCTO_CONTENIDO], [ID_LOTE], [CANTIDAD_ACTUAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, [ACT].[ID_ACTIVO], [CON].[ID_PRODUCTO_CONTENIDO], [LOT].[ID_LOTE], [CON].[CANTIDAD], N'ACTIVO', @S_ID_USUARIO
        FROM @T_CONTENIDOS AS [CON]
        INNER JOIN [INVENTARIO].[ACTIVOS] AS [ACT] ON [ACT].[ID_EMPRESA] = @I_ID_EMPRESA AND [ACT].[NUMERO_SERIE] = [CON].[NUMERO_SERIE]
        LEFT JOIN [INVENTARIO].[LOTES] AS [LOT] ON [LOT].[ID_EMPRESA] = @I_ID_EMPRESA AND [LOT].[ID_PRODUCTO] = [CON].[ID_PRODUCTO_CONTENIDO] AND [LOT].[CODIGO] = [CON].[CODIGO_LOTE]
        WHERE [ACT].[ID_RECEPCION_DETALLE] IN (SELECT [ID_RECEPCION_DETALLE] FROM [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] WHERE [ID_RECEPCION] = @O_ID_RECEPCION);

        INSERT INTO [INVENTARIO].[MEDICIONES_ACTIVOS]
            ([ID_EMPRESA], [ID_ACTIVO], [FECHA_MEDICION_UTC], [TIPO_MEDICION], [VALOR], [UNIDAD], [METODO_MEDICION], [ORIGEN_MEDICION], [ES_ESTIMADA], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, [ACT].[ID_ACTIVO], @I_FECHA_RECEPCION_UTC, N'CONTENIDO', [CON].[CANTIDAD], [UNI].[SIMBOLO],
               [CON].[METODO_MEDICION], [CON].[METODO_MEDICION], 0, N'Medición inicial de recepción', N'CONFIRMADA', @S_ID_USUARIO
        FROM @T_CONTENIDOS AS [CON]
        INNER JOIN [INVENTARIO].[ACTIVOS] AS [ACT] ON [ACT].[ID_EMPRESA] = @I_ID_EMPRESA AND [ACT].[NUMERO_SERIE] = [CON].[NUMERO_SERIE]
        INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [CON].[ID_PRODUCTO_CONTENIDO]
        INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA];

        INSERT INTO [INVENTARIO].[ACTIVOS_EVENTOS]
            ([ID_EMPRESA], [ID_ACTIVO], [TIPO_EVENTO], [FECHA_EVENTO_UTC], [CODIGO_ESTADO_DESPUES], [CONDICION_DESPUES],
             [ID_RECEPCION_COMPRA], [OBSERVACION], [ID_CORRELACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, [ACT].[ID_ACTIVO], N'RECEPCION', @I_FECHA_RECEPCION_UTC, [ACT].[CODIGO_ESTADO],
               [ACT].[CONDICION_ACTUAL], @O_ID_RECEPCION, N'Alta por recepción de compra', NEWID(), N'CONFIRMADO', @S_ID_USUARIO
        FROM [INVENTARIO].[ACTIVOS] AS [ACT]
        WHERE [ACT].[ID_RECEPCION_DETALLE] IN (SELECT [ID_RECEPCION_DETALLE] FROM [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] WHERE [ID_RECEPCION] = @O_ID_RECEPCION);

        INSERT INTO [INVENTARIO].[MOVIMIENTOS_DETALLES_LOTES]
            ([ID_MOVIMIENTO_DETALLE], [ID_LOTE], [CANTIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT [MOV].[ID_MOVIMIENTO_DETALLE], [LOT].[ID_LOTE], [LOT].[CANTIDAD_INICIAL], N'ACTIVO', @S_ID_USUARIO
        FROM [INVENTARIO].[LOTES] AS [LOT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE] = [LOT].[ID_RECEPCION_DETALLE]
        INNER JOIN [INVENTARIO].[MOVIMIENTOS_DETALLES] AS [MOV] ON [MOV].[ID_MOVIMIENTO] = @V_ID_MOVIMIENTO AND [MOV].[ID_PRODUCTO] = [RDE].[ID_PRODUCTO]
        WHERE [RDE].[ID_RECEPCION] = @O_ID_RECEPCION;

        INSERT INTO [INVENTARIO].[MOVIMIENTOS_DETALLES_ACTIVOS]
            ([ID_MOVIMIENTO_DETALLE], [ID_ACTIVO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT [MOV].[ID_MOVIMIENTO_DETALLE], [ACT].[ID_ACTIVO], N'ACTIVO', @S_ID_USUARIO
        FROM [INVENTARIO].[ACTIVOS] AS [ACT]
        INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [RDE] ON [RDE].[ID_RECEPCION_DETALLE] = [ACT].[ID_RECEPCION_DETALLE]
        INNER JOIN [INVENTARIO].[MOVIMIENTOS_DETALLES] AS [MOV] ON [MOV].[ID_MOVIMIENTO] = @V_ID_MOVIMIENTO AND [MOV].[ID_PRODUCTO] = [RDE].[ID_PRODUCTO]
        WHERE [RDE].[ID_RECEPCION] = @O_ID_RECEPCION;

        UPDATE [ORD] SET [CANTIDAD_RECIBIDA] = [ORD].[CANTIDAD_RECIBIDA] + [REC].[CANTIDAD_ACEPTADA],
            [CODIGO_ESTADO] = CASE WHEN [ORD].[CANTIDAD_RECIBIDA] + [REC].[CANTIDAD_ACEPTADA] + [ORD].[CANTIDAD_CERRADA] >= [ORD].[CANTIDAD_PEDIDA] THEN N'COMPLETO' ELSE N'PENDIENTE' END,
            [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
        FROM [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [ORD]
        INNER JOIN @T_DETALLES AS [REC] ON [REC].[ID_ORDEN_COMPRA_DETALLE] = [ORD].[ID_ORDEN_COMPRA_DETALLE];

        DECLARE @V_ESTADO_NUEVO NVARCHAR(30) = CASE WHEN EXISTS
        (
            SELECT 1 FROM [COMPRAS].[ORDENES_COMPRA_DETALLES]
            WHERE [ID_ORDEN_COMPRA] = @I_ID_ORDEN_COMPRA AND [CANTIDAD_RECIBIDA] + [CANTIDAD_CERRADA] < [CANTIDAD_PEDIDA]
        ) THEN N'RECIBIDA_PARCIAL' ELSE N'RECIBIDA' END;
        UPDATE [COMPRAS].[ORDENES_COMPRA] SET [CODIGO_ESTADO] = @V_ESTADO_NUEVO,
            [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
        WHERE [ID_ORDEN_COMPRA] = @I_ID_ORDEN_COMPRA;
    INSERT INTO [AUDITORIA].[BITACORA_CAMBIOS_ESTADO] ([ENTIDAD], [PKEY], [CODIGO_ESTADO_ANTERIOR], [CODIGO_ESTADO_NUEVO], [MOTIVO], [ID_USUARIO], [ID_CORRELACION], [ID_USUARIO_ALTA])
        VALUES (N'ORDEN_COMPRA', @I_ID_ORDEN_COMPRA, @V_ESTADO_ANTERIOR, @V_ESTADO_NUEVO, CONCAT(N'Recepción ', @V_CODIGO), @S_ID_USUARIO, NEWID(), @S_ID_USUARIO);
        COMMIT;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK;
        THROW;
    END CATCH;
END;
