/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_DEPOSITO_SAVE
Archivo: SP_DEPOSITO_SAVE.sql | Procedimiento: INVENTARIO.SP_DEPOSITO_SAVE | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o modifica un depósito aislado por empresa.
Parámetros de entrada: @I_CODIGO, @I_CODIGO_ESTADO, @I_DESCRIPCION, @I_DOMICILIO, @I_ID_DEPOSITO, @I_ID_EMPRESA, @I_ID_SUCURSAL, @I_NOMBRE, @I_ROW_VERSION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_DEPOSITO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: CONFIGURACION.SUCURSALES - SELECT; INVENTARIO.DEPOSITOS - INSERT/UPDATE; INVENTARIO.EXISTENCIAS - SELECT; INVENTARIO.UBICACIONES - SELECT.
Transacción: No abre una transacción explícita.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_DEPOSITO_SAVE]
    @I_ID_DEPOSITO BIGINT = NULL, @I_ID_EMPRESA BIGINT, @I_ID_SUCURSAL BIGINT = NULL, @I_CODIGO NVARCHAR(30),
    @I_NOMBRE NVARCHAR(150), @I_DOMICILIO NVARCHAR(250) = NULL, @I_DESCRIPCION NVARCHAR(500) = NULL,
    @I_CODIGO_ESTADO NVARCHAR(30), @I_ROW_VERSION BINARY(8) = NULL, @S_ID_USUARIO BIGINT,
    @O_ID_DEPOSITO BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF NULLIF(LTRIM(RTRIM(@I_CODIGO)), N'') IS NULL OR NULLIF(LTRIM(RTRIM(@I_NOMBRE)), N'') IS NULL OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO') THROW 50000, 'Código, nombre y estado son obligatorios.', 1;
    IF @I_ID_SUCURSAL IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[SUCURSALES] WHERE [ID_SUCURSAL] = @I_ID_SUCURSAL AND [ID_EMPRESA] = @I_ID_EMPRESA) THROW 50001, 'La sucursal no pertenece a la empresa.', 1;
    IF @I_ID_DEPOSITO IS NULL
    BEGIN
        INSERT INTO [INVENTARIO].[DEPOSITOS] ([ID_EMPRESA], [ID_SUCURSAL], [CODIGO], [NOMBRE], [DOMICILIO], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_EMPRESA, @I_ID_SUCURSAL, @I_CODIGO, @I_NOMBRE, @I_DOMICILIO, @I_DESCRIPCION, @I_CODIGO_ESTADO, @S_ID_USUARIO);
        SET @O_ID_DEPOSITO = CONVERT(BIGINT, SCOPE_IDENTITY()); SET @O_FILAS_AFECTADAS = 1; RETURN;
    END;
    IF @I_CODIGO_ESTADO = N'INACTIVO' AND (EXISTS (SELECT 1 FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_DEPOSITO] = @I_ID_DEPOSITO AND [CANTIDAD] > 0) OR EXISTS (SELECT 1 FROM [INVENTARIO].[UBICACIONES] WHERE [ID_DEPOSITO] = @I_ID_DEPOSITO AND [CODIGO_ESTADO] = N'ACTIVO'))
        THROW 50002, 'No se puede inactivar un depósito con existencias o ubicaciones activas.', 1;
    UPDATE [INVENTARIO].[DEPOSITOS] SET [ID_SUCURSAL] = @I_ID_SUCURSAL, [NOMBRE] = @I_NOMBRE, [DOMICILIO] = @I_DOMICILIO, [DESCRIPCION] = @I_DESCRIPCION, [CODIGO_ESTADO] = @I_CODIGO_ESTADO, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_DEPOSITO] = @I_ID_DEPOSITO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;
    SET @O_FILAS_AFECTADAS = @@ROWCOUNT; SET @O_ID_DEPOSITO = @I_ID_DEPOSITO;
    IF @O_FILAS_AFECTADAS = 0 BEGIN SET @O_CODIGO_ERROR = 30003; SET @O_MENSAJE = N'El depósito fue modificado por otro usuario o no pertenece a la empresa.'; END;
END;
