/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_MOVIMIENTO_CREATE
Archivo: SP_MOVIMIENTO_CREATE.sql | Procedimiento: INVENTARIO.SP_MOVIMIENTO_CREATE | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Confirma un movimiento y actualiza los saldos por depósito en una transacción.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.EXISTENCIAS - SELECT; INVENTARIO.MOVIMIENTOS - INSERT; INVENTARIO.MOVIMIENTOS_DETALLES - INSERT; INVENTARIO.PRODUCTOS - SELECT; INVENTARIO.RESERVAS_STOCK - SELECT; INVENTARIO.UBICACIONES - SELECT.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Parámetros de entrada: Empresa, tipo, fecha, observación y renglones JSON.
Parámetros de sesión: Sesión y usuario responsables.
Parámetros de salida: Movimiento, código funcional, mensaje y filas afectadas.
Transacción: Encabezado, detalles y existencias se confirman o revierten juntos.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Respeta reservas activas y permite aplicar la del pedido vendido.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_MOVIMIENTO_CREATE]
    @I_ID_EMPRESA BIGINT,
    @I_TIPO_MOVIMIENTO NVARCHAR(30),
    @I_FECHA_MOVIMIENTO_UTC DATETIME2(3),
    @I_OBSERVACION NVARCHAR(500) = NULL,
    @I_DETALLES_JSON NVARCHAR(MAX),
    @I_ID_PEDIDO_RESERVADO BIGINT = NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_MOVIMIENTO BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @O_ID_MOVIMIENTO = NULL;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;
    SET @O_FILAS_AFECTADAS = 0;

    IF @I_TIPO_MOVIMIENTO NOT IN (N'ENTRADA', N'SALIDA', N'TRANSFERENCIA', N'AJUSTE_ENTRADA', N'AJUSTE_SALIDA')
       OR @I_FECHA_MOVIMIENTO_UTC IS NULL OR ISJSON(@I_DETALLES_JSON) <> 1
        THROW 50000, 'Tipo, fecha y renglones válidos son obligatorios.', 1;

    DECLARE @T_DETALLES TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO_ORIGEN] BIGINT NULL,
        [ID_UBICACION_ORIGEN] BIGINT NULL,
        [ID_DEPOSITO_DESTINO] BIGINT NULL,
        [ID_UBICACION_DESTINO] BIGINT NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL
    );

    INSERT INTO @T_DETALLES ([ID_PRODUCTO], [ID_DEPOSITO_ORIGEN], [ID_UBICACION_ORIGEN], [ID_DEPOSITO_DESTINO], [ID_UBICACION_DESTINO], [CANTIDAD])
    SELECT [DET].[ID_PRODUCTO], [DET].[ID_DEPOSITO_ORIGEN], [DET].[ID_UBICACION_ORIGEN], [DET].[ID_DEPOSITO_DESTINO], [DET].[ID_UBICACION_DESTINO], [DET].[CANTIDAD]
    FROM OPENJSON(@I_DETALLES_JSON) WITH
    (
        [ID_PRODUCTO] BIGINT '$.ProductId', [ID_DEPOSITO_ORIGEN] BIGINT '$.OriginWarehouseId',
        [ID_UBICACION_ORIGEN] BIGINT '$.OriginLocationId', [ID_DEPOSITO_DESTINO] BIGINT '$.DestinationWarehouseId',
        [ID_UBICACION_DESTINO] BIGINT '$.DestinationLocationId', [CANTIDAD] DECIMAL(19,4) '$.Quantity'
    ) AS [DET];

    IF NOT EXISTS (SELECT 1 FROM @T_DETALLES) OR (SELECT COUNT(*) FROM @T_DETALLES) > 100 OR EXISTS (SELECT 1 FROM @T_DETALLES WHERE [CANTIDAD] <= 0)
        THROW 50001, 'El movimiento debe contener entre 1 y 100 renglones con cantidades positivas.', 1;

    IF EXISTS
    (
        SELECT 1 FROM @T_DETALLES AS [DET]
        WHERE NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] AS [PRO] WHERE [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO] AND [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO')
           OR ([DET].[ID_DEPOSITO_ORIGEN] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] AS [DEP] WHERE [DEP].[ID_DEPOSITO] = [DET].[ID_DEPOSITO_ORIGEN] AND [DEP].[ID_EMPRESA] = @I_ID_EMPRESA AND [DEP].[CODIGO_ESTADO] = N'ACTIVO'))
           OR ([DET].[ID_DEPOSITO_DESTINO] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] AS [DEP] WHERE [DEP].[ID_DEPOSITO] = [DET].[ID_DEPOSITO_DESTINO] AND [DEP].[ID_EMPRESA] = @I_ID_EMPRESA AND [DEP].[CODIGO_ESTADO] = N'ACTIVO'))
           OR ([DET].[ID_UBICACION_ORIGEN] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[UBICACIONES] AS [UBI] WHERE [UBI].[ID_UBICACION] = [DET].[ID_UBICACION_ORIGEN] AND [UBI].[ID_DEPOSITO] = [DET].[ID_DEPOSITO_ORIGEN] AND [UBI].[CODIGO_ESTADO] = N'ACTIVO'))
           OR ([DET].[ID_UBICACION_DESTINO] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[UBICACIONES] AS [UBI] WHERE [UBI].[ID_UBICACION] = [DET].[ID_UBICACION_DESTINO] AND [UBI].[ID_DEPOSITO] = [DET].[ID_DEPOSITO_DESTINO] AND [UBI].[CODIGO_ESTADO] = N'ACTIVO'))
    ) THROW 50002, 'Producto, depósito o ubicación no válidos para la empresa.', 1;

    IF EXISTS
    (
        SELECT 1 FROM @T_DETALLES
        WHERE (@I_TIPO_MOVIMIENTO IN (N'ENTRADA', N'AJUSTE_ENTRADA') AND ([ID_DEPOSITO_ORIGEN] IS NOT NULL OR [ID_DEPOSITO_DESTINO] IS NULL))
           OR (@I_TIPO_MOVIMIENTO IN (N'SALIDA', N'AJUSTE_SALIDA') AND ([ID_DEPOSITO_ORIGEN] IS NULL OR [ID_DEPOSITO_DESTINO] IS NOT NULL))
           OR (@I_TIPO_MOVIMIENTO = N'TRANSFERENCIA' AND ([ID_DEPOSITO_ORIGEN] IS NULL OR [ID_DEPOSITO_DESTINO] IS NULL OR ([ID_DEPOSITO_ORIGEN] = [ID_DEPOSITO_DESTINO] AND ISNULL([ID_UBICACION_ORIGEN], 0) = ISNULL([ID_UBICACION_DESTINO], 0))))
    ) THROW 50003, 'El origen y destino no corresponden al tipo de movimiento.', 1;

    BEGIN TRY
        DECLARE @V_INICIO_TRANSACCION BIT = 0;
        IF @@TRANCOUNT = 0
        BEGIN
            BEGIN TRANSACTION;
            SET @V_INICIO_TRANSACCION = 1;
        END
        ELSE SAVE TRANSACTION [SP_MOVIMIENTO_CREATE_SAVEPOINT];

        -- INICIO: Verificación agrupada para impedir saldos negativos.
        IF EXISTS
        (
        SELECT 1
        FROM (SELECT [ID_PRODUCTO], [ID_DEPOSITO_ORIGEN] AS [ID_DEPOSITO], SUM([CANTIDAD]) AS [CANTIDAD] FROM @T_DETALLES WHERE [ID_DEPOSITO_ORIGEN] IS NOT NULL GROUP BY [ID_PRODUCTO], [ID_DEPOSITO_ORIGEN]) AS [SAL]
        LEFT JOIN [INVENTARIO].[EXISTENCIAS] AS [EXI] WITH (UPDLOCK, HOLDLOCK) ON [EXI].[ID_PRODUCTO] = [SAL].[ID_PRODUCTO] AND [EXI].[ID_DEPOSITO] = [SAL].[ID_DEPOSITO] AND [EXI].[ID_EMPRESA] = @I_ID_EMPRESA
        OUTER APPLY (SELECT SUM([RES].[CANTIDAD]) AS [CANTIDAD] FROM [INVENTARIO].[RESERVAS_STOCK] AS [RES] WITH (UPDLOCK, HOLDLOCK) WHERE [RES].[ID_EMPRESA] = @I_ID_EMPRESA AND [RES].[ID_PRODUCTO] = [SAL].[ID_PRODUCTO] AND [RES].[ID_DEPOSITO] = [SAL].[ID_DEPOSITO] AND [RES].[CODIGO_ESTADO] = N'RESERVADA' AND (@I_ID_PEDIDO_RESERVADO IS NULL OR [RES].[ID_PEDIDO] <> @I_ID_PEDIDO_RESERVADO)) AS [RES]
        WHERE COALESCE([EXI].[CANTIDAD], 0) - COALESCE([RES].[CANTIDAD], 0) < [SAL].[CANTIDAD]
        )
        BEGIN
            SET @O_CODIGO_ERROR = 30004;
            SET @O_MENSAJE = N'No existe stock suficiente en uno de los depósitos de origen.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION;
            RETURN;
        END;
        -- FIN: Verificación agrupada para impedir saldos negativos.
        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [INVENTARIO].[SEQ_MOVIMIENTO_CODIGO];
        DECLARE @V_CODIGO NVARCHAR(30) = N'MOV-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;

        INSERT INTO [INVENTARIO].[MOVIMIENTOS] ([ID_EMPRESA], [CODIGO], [TIPO_MOVIMIENTO], [FECHA_MOVIMIENTO_UTC], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        VALUES (@I_ID_EMPRESA, @V_CODIGO, @I_TIPO_MOVIMIENTO, @I_FECHA_MOVIMIENTO_UTC, @I_OBSERVACION, N'CONFIRMADO', @S_ID_USUARIO);
        SET @O_ID_MOVIMIENTO = CONVERT(BIGINT, SCOPE_IDENTITY());

        INSERT INTO [INVENTARIO].[MOVIMIENTOS_DETALLES] ([ID_MOVIMIENTO], [ID_PRODUCTO], [ID_DEPOSITO_ORIGEN], [ID_UBICACION_ORIGEN], [ID_DEPOSITO_DESTINO], [ID_UBICACION_DESTINO], [CANTIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_MOVIMIENTO, [ID_PRODUCTO], [ID_DEPOSITO_ORIGEN], [ID_UBICACION_ORIGEN], [ID_DEPOSITO_DESTINO], [ID_UBICACION_DESTINO], [CANTIDAD], N'ACTIVO', @S_ID_USUARIO FROM @T_DETALLES;

        UPDATE [EXI] SET [CANTIDAD] = [EXI].[CANTIDAD] - [SAL].[CANTIDAD], [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
        FROM [INVENTARIO].[EXISTENCIAS] AS [EXI]
        INNER JOIN (SELECT [ID_PRODUCTO], [ID_DEPOSITO_ORIGEN] AS [ID_DEPOSITO], SUM([CANTIDAD]) AS [CANTIDAD] FROM @T_DETALLES WHERE [ID_DEPOSITO_ORIGEN] IS NOT NULL GROUP BY [ID_PRODUCTO], [ID_DEPOSITO_ORIGEN]) AS [SAL] ON [SAL].[ID_PRODUCTO] = [EXI].[ID_PRODUCTO] AND [SAL].[ID_DEPOSITO] = [EXI].[ID_DEPOSITO]
        WHERE [EXI].[ID_EMPRESA] = @I_ID_EMPRESA;

        MERGE [INVENTARIO].[EXISTENCIAS] WITH (HOLDLOCK) AS [EXI]
        USING (SELECT [ID_PRODUCTO], [ID_DEPOSITO_DESTINO] AS [ID_DEPOSITO], SUM([CANTIDAD]) AS [CANTIDAD] FROM @T_DETALLES WHERE [ID_DEPOSITO_DESTINO] IS NOT NULL GROUP BY [ID_PRODUCTO], [ID_DEPOSITO_DESTINO]) AS [ENT]
        ON [EXI].[ID_PRODUCTO] = [ENT].[ID_PRODUCTO] AND [EXI].[ID_DEPOSITO] = [ENT].[ID_DEPOSITO]
        WHEN MATCHED THEN UPDATE SET [CANTIDAD] = [EXI].[CANTIDAD] + [ENT].[CANTIDAD], [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
        WHEN NOT MATCHED THEN INSERT ([ID_EMPRESA], [ID_PRODUCTO], [ID_DEPOSITO], [CANTIDAD], [STOCK_MINIMO], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_EMPRESA, [ENT].[ID_PRODUCTO], [ENT].[ID_DEPOSITO], [ENT].[CANTIDAD], 0, N'ACTIVO', @S_ID_USUARIO);

        SET @O_FILAS_AFECTADAS = 1 + (SELECT COUNT(*) FROM @T_DETALLES);
        IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION;
        ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_MOVIMIENTO_CREATE_SAVEPOINT];
        SET @O_MENSAJE = ERROR_MESSAGE();
        THROW;
    END CATCH;
END;
