/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_MANTENIMIENTO_CREATE
Archivo: SP_MANTENIMIENTO_CREATE.sql | Procedimiento: INVENTARIO.SP_MANTENIMIENTO_CREATE | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Inicia mantenimiento y bloquea el activo.
Parámetros de entrada: @I_COSTO, @I_DESCRIPCION_TRABAJO, @I_FECHA_INICIO_UTC, @I_ID_ACTIVO, @I_ID_EMPRESA, @I_ID_INCIDENTE, @I_ID_PROVEEDOR, @I_TIPO_MANTENIMIENTO, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_MANTENIMIENTO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: INVENTARIO.ACTIVOS - SELECT/UPDATE; INVENTARIO.ACTIVOS_EVENTOS - INSERT; INVENTARIO.MANTENIMIENTOS - INSERT/SELECT.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_MANTENIMIENTO_CREATE]
    @I_ID_EMPRESA BIGINT,
    @I_ID_ACTIVO BIGINT,
    @I_ID_INCIDENTE BIGINT=NULL,
    @I_ID_PROVEEDOR BIGINT=NULL,
    @I_TIPO_MANTENIMIENTO NVARCHAR (30),
    @I_FECHA_INICIO_UTC DATETIME2 (3),
    @I_DESCRIPCION_TRABAJO NVARCHAR (1000),
    @I_COSTO DECIMAL (19, 4)=NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_MANTENIMIENTO BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR (4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;
    SET @O_FILAS_AFECTADAS = 0;
    BEGIN TRANSACTION;
    DECLARE @V_ESTADO AS NVARCHAR (30), @V_CONDICION AS NVARCHAR (30);
    SELECT @V_ESTADO = [CODIGO_ESTADO],
           @V_CONDICION = [CONDICION_ACTUAL]
    FROM   [INVENTARIO].[ACTIVOS] WITH (UPDLOCK, HOLDLOCK)
    WHERE  [ID_ACTIVO] = @I_ID_ACTIVO
           AND [ID_EMPRESA] = @I_ID_EMPRESA;
    IF @V_ESTADO IS NULL
       OR EXISTS (SELECT 1
                  FROM   [INVENTARIO].[MANTENIMIENTOS]
                  WHERE  [ID_ACTIVO] = @I_ID_ACTIVO
                         AND [CODIGO_ESTADO] = N'EN_CURSO')
        BEGIN
            SET @O_CODIGO_ERROR = 30008;
            SET @O_MENSAJE = N'El activo no existe o ya tiene mantenimiento abierto.';
            ROLLBACK;
            RETURN;
        END
    DECLARE @V_CODIGO AS NVARCHAR (30) = N'MAN-' + RIGHT(REPLICATE(N'0', 6) + CONVERT (NVARCHAR (20),  NEXT VALUE FOR [INVENTARIO].[SEQ_MANTENIMIENTO_CODIGO]), 6);
    INSERT  [INVENTARIO].[MANTENIMIENTOS] ([ID_EMPRESA], [ID_ACTIVO], [ID_INCIDENTE], [ID_PROVEEDOR], [CODIGO], [TIPO_MANTENIMIENTO], [FECHA_INICIO_UTC], [DESCRIPCION_TRABAJO], [COSTO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES                               (@I_ID_EMPRESA, @I_ID_ACTIVO, @I_ID_INCIDENTE, @I_ID_PROVEEDOR, @V_CODIGO, @I_TIPO_MANTENIMIENTO, @I_FECHA_INICIO_UTC, @I_DESCRIPCION_TRABAJO, @I_COSTO, N'EN_CURSO', @S_ID_USUARIO);
    SET @O_ID_MANTENIMIENTO = SCOPE_IDENTITY();
    UPDATE [INVENTARIO].[ACTIVOS]
    SET    [CODIGO_ESTADO]           = N'BLOQUEADO',
           [CONDICION_ACTUAL]        = N'EN_MANTENIMIENTO',
           [FECHA_MODIFICACION_UTC]  = SYSUTCDATETIME(),
           [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
    WHERE  [ID_ACTIVO] = @I_ID_ACTIVO;
    INSERT  [INVENTARIO].[ACTIVOS_EVENTOS] ([ID_EMPRESA], [ID_ACTIVO], [TIPO_EVENTO], [FECHA_EVENTO_UTC], [CODIGO_ESTADO_ANTES], [CODIGO_ESTADO_DESPUES], [CONDICION_ANTES], [CONDICION_DESPUES], [ID_MANTENIMIENTO], [OBSERVACION], [ID_CORRELACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES                                (@I_ID_EMPRESA, @I_ID_ACTIVO, N'MANTENIMIENTO_INICIO', @I_FECHA_INICIO_UTC, @V_ESTADO, N'BLOQUEADO', @V_CONDICION, N'EN_MANTENIMIENTO', @O_ID_MANTENIMIENTO, @I_DESCRIPCION_TRABAJO, NEWID(), N'CONFIRMADO', @S_ID_USUARIO);
    SET @O_FILAS_AFECTADAS = 3;
    COMMIT TRANSACTION;
END
