/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_MEDICION_ACTIVO_CREATE
Archivo: SP_MEDICION_ACTIVO_CREATE.sql | Procedimiento: INVENTARIO.SP_MEDICION_ACTIVO_CREATE | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra una medición inmutable y su evento de activo.
Parámetros de entrada: @I_ES_ESTIMADA, @I_FECHA_MEDICION_UTC, @I_ID_ACTIVO, @I_ID_EMPRESA, @I_METODO_MEDICION, @I_OBSERVACION, @I_ORIGEN_MEDICION, @I_REFERENCIA_DISPOSITIVO, @I_TIPO_MEDICION, @I_UNIDAD, @I_VALOR, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_MEDICION_ACTIVO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: INVENTARIO.ACTIVOS - SELECT; INVENTARIO.ACTIVOS_CONTENIDOS - SELECT; INVENTARIO.ACTIVOS_EVENTOS - INSERT; INVENTARIO.MEDICIONES_ACTIVOS - INSERT.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_MEDICION_ACTIVO_CREATE]
    @I_ID_EMPRESA BIGINT,
    @I_ID_ACTIVO BIGINT,
    @I_FECHA_MEDICION_UTC DATETIME2 (3),
    @I_TIPO_MEDICION NVARCHAR (30),
    @I_VALOR DECIMAL (19, 4),
    @I_UNIDAD NVARCHAR (20),
    @I_METODO_MEDICION NVARCHAR (30),
    @I_ORIGEN_MEDICION NVARCHAR (30),
    @I_ES_ESTIMADA BIT,
    @I_REFERENCIA_DISPOSITIVO NVARCHAR (100)=NULL,
    @I_OBSERVACION NVARCHAR (500)=NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_MEDICION_ACTIVO BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR (4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;
    SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_MEDICION_UTC IS NULL
       OR @I_ORIGEN_MEDICION NOT IN (N'MANUAL', N'PESAJE', N'CALCULADO', N'SENSOR')
        THROW 50008, 'La medición no es válida.', 1;
    BEGIN TRANSACTION;
    DECLARE @V_ESTADO AS NVARCHAR (30), @V_CONDICION AS NVARCHAR (30), @V_CANTIDAD AS DECIMAL (19, 4);
    SELECT @V_ESTADO = [CODIGO_ESTADO],
           @V_CONDICION = [CONDICION_ACTUAL]
    FROM   [INVENTARIO].[ACTIVOS] WITH (UPDLOCK, HOLDLOCK)
    WHERE  [ID_ACTIVO] = @I_ID_ACTIVO
           AND [ID_EMPRESA] = @I_ID_EMPRESA;
    IF @V_ESTADO IS NULL
        BEGIN
            SET @O_CODIGO_ERROR = 30005;
            SET @O_MENSAJE = N'El activo no existe en la empresa de la sesión.';
            ROLLBACK;
            RETURN;
        END
    SELECT @V_CANTIDAD = [CANTIDAD_ACTUAL]
    FROM   [INVENTARIO].[ACTIVOS_CONTENIDOS]
    WHERE  [ID_ACTIVO] = @I_ID_ACTIVO
           AND [CODIGO_ESTADO] = N'ACTIVO';
    INSERT  [INVENTARIO].[MEDICIONES_ACTIVOS] ([ID_EMPRESA], [ID_ACTIVO], [FECHA_MEDICION_UTC], [TIPO_MEDICION], [VALOR], [UNIDAD], [METODO_MEDICION], [ORIGEN_MEDICION], [ES_ESTIMADA], [REFERENCIA_DISPOSITIVO], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES                                   (@I_ID_EMPRESA, @I_ID_ACTIVO, @I_FECHA_MEDICION_UTC, @I_TIPO_MEDICION, @I_VALOR, @I_UNIDAD, @I_METODO_MEDICION, @I_ORIGEN_MEDICION, @I_ES_ESTIMADA, @I_REFERENCIA_DISPOSITIVO, @I_OBSERVACION, N'CONFIRMADA', @S_ID_USUARIO);
    SET @O_ID_MEDICION_ACTIVO = SCOPE_IDENTITY();
    INSERT  [INVENTARIO].[ACTIVOS_EVENTOS] ([ID_EMPRESA], [ID_ACTIVO], [TIPO_EVENTO], [FECHA_EVENTO_UTC], [CODIGO_ESTADO_ANTES], [CODIGO_ESTADO_DESPUES], [CONDICION_ANTES], [CONDICION_DESPUES], [CANTIDAD_ANTES], [CANTIDAD_DESPUES], [ID_MEDICION_ACTIVO], [OBSERVACION], [ID_CORRELACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES                                (@I_ID_EMPRESA, @I_ID_ACTIVO, N'MEDICION', @I_FECHA_MEDICION_UTC, @V_ESTADO, @V_ESTADO, @V_CONDICION, @V_CONDICION, @V_CANTIDAD, @V_CANTIDAD, @O_ID_MEDICION_ACTIVO, @I_OBSERVACION, NEWID(), N'CONFIRMADO', @S_ID_USUARIO);
    SET @O_FILAS_AFECTADAS = 2;
    COMMIT TRANSACTION;
END
