/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PRODUCTO_SAVE
Archivo: SP_PRODUCTO_SAVE.sql | Procedimiento: INVENTARIO.SP_PRODUCTO_SAVE | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea un producto numerado o modifica sus datos editables.
Parámetros de entrada: @I_ADMITE_MEDICIONES, @I_ADMITE_PRESTAMO, @I_CODIGO_BARRAS, @I_CODIGO_ESTADO, @I_DESCRIPCION, @I_ES_REUTILIZABLE, @I_ID_CATEGORIA_PRODUCTO, @I_ID_EMPRESA, @I_ID_PRODUCTO, @I_ID_UNIDAD_MEDIDA, @I_NOMBRE, @I_REQUIERE_MANTENIMIENTO, @I_ROW_VERSION, @I_TIPO_ITEM, @I_TIPO_TRAZABILIDAD, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_PRODUCTO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: CONFIGURACION.UNIDADES_MEDIDA - SELECT; INVENTARIO.CATEGORIAS_PRODUCTO - SELECT; INVENTARIO.EXISTENCIAS - SELECT; INVENTARIO.PRODUCTOS - INSERT/UPDATE.
Transacción: No abre una transacción explícita.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Clasificación de trazabilidad industrial por producto.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_PRODUCTO_SAVE]
    @I_ID_PRODUCTO BIGINT = NULL, @I_ID_EMPRESA BIGINT, @I_ID_CATEGORIA_PRODUCTO BIGINT, @I_ID_UNIDAD_MEDIDA BIGINT,
    @I_NOMBRE NVARCHAR(200), @I_DESCRIPCION NVARCHAR(1000) = NULL, @I_CODIGO_BARRAS NVARCHAR(80) = NULL,
    @I_TIPO_ITEM NVARCHAR(20), @I_TIPO_TRAZABILIDAD NVARCHAR(20), @I_ES_REUTILIZABLE BIT, @I_ADMITE_PRESTAMO BIT,
    @I_REQUIERE_MANTENIMIENTO BIT, @I_ADMITE_MEDICIONES BIT,
    @I_CODIGO_ESTADO NVARCHAR(30), @I_ROW_VERSION BINARY(8) = NULL, @S_ID_USUARIO BIGINT,
    @O_ID_PRODUCTO BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF NULLIF(LTRIM(RTRIM(@I_NOMBRE)), N'') IS NULL OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO') OR @I_TIPO_ITEM NOT IN (N'PRODUCTO', N'SERVICIO') OR @I_TIPO_TRAZABILIDAD NOT IN (N'NINGUNA', N'LOTE', N'SERIE', N'SERIE_LOTE') THROW 50000, 'Categoría, unidad, nombre, tipo, trazabilidad y estado son obligatorios.', 1;
    IF @I_TIPO_ITEM = N'SERVICIO' AND (@I_TIPO_TRAZABILIDAD <> N'NINGUNA' OR @I_ES_REUTILIZABLE = 1 OR @I_ADMITE_PRESTAMO = 1 OR @I_REQUIERE_MANTENIMIENTO = 1 OR @I_ADMITE_MEDICIONES = 1) THROW 50000, 'Un servicio no puede administrar stock ni trazabilidad física.', 1;
    IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [ID_CATEGORIA_PRODUCTO] = @I_ID_CATEGORIA_PRODUCTO) OR NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [ID_UNIDAD_MEDIDA] = @I_ID_UNIDAD_MEDIDA) THROW 50001, 'La categoría o unidad seleccionada no existe.', 1;
    IF @I_CODIGO_ESTADO = N'ACTIVO' AND (NOT EXISTS (SELECT 1 FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [ID_CATEGORIA_PRODUCTO] = @I_ID_CATEGORIA_PRODUCTO AND [CODIGO_ESTADO] = N'ACTIVO') OR NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [ID_UNIDAD_MEDIDA] = @I_ID_UNIDAD_MEDIDA AND [CODIGO_ESTADO] = N'ACTIVO')) THROW 50002, 'La categoría o unidad seleccionada no está activa.', 1;
    IF @I_ID_PRODUCTO IS NULL
    BEGIN
        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [INVENTARIO].[SEQ_PRODUCTO_CODIGO];
        DECLARE @V_CODIGO NVARCHAR(30) = N'PRD-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;
        INSERT INTO [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_BARRAS], [TIPO_ITEM], [TIPO_TRAZABILIDAD], [ES_REUTILIZABLE], [ADMITE_PRESTAMO], [REQUIERE_MANTENIMIENTO], [ADMITE_MEDICIONES], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_EMPRESA, @I_ID_CATEGORIA_PRODUCTO, @I_ID_UNIDAD_MEDIDA, @V_CODIGO, @I_NOMBRE, @I_DESCRIPCION, @I_CODIGO_BARRAS, @I_TIPO_ITEM, @I_TIPO_TRAZABILIDAD, @I_ES_REUTILIZABLE, @I_ADMITE_PRESTAMO, @I_REQUIERE_MANTENIMIENTO, @I_ADMITE_MEDICIONES, @I_CODIGO_ESTADO, @S_ID_USUARIO);
        SET @O_ID_PRODUCTO = CONVERT(BIGINT, SCOPE_IDENTITY()); SET @O_FILAS_AFECTADAS = 1; RETURN;
    END;
    IF @I_CODIGO_ESTADO = N'INACTIVO' AND EXISTS (SELECT 1 FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_PRODUCTO] = @I_ID_PRODUCTO AND [CANTIDAD] > 0)
        THROW 50003, 'No se puede inactivar un producto que todavía posee existencias.', 1;
    UPDATE [INVENTARIO].[PRODUCTOS] SET [ID_CATEGORIA_PRODUCTO] = @I_ID_CATEGORIA_PRODUCTO, [ID_UNIDAD_MEDIDA] = @I_ID_UNIDAD_MEDIDA, [NOMBRE] = @I_NOMBRE, [DESCRIPCION] = @I_DESCRIPCION, [CODIGO_BARRAS] = @I_CODIGO_BARRAS, [TIPO_ITEM] = @I_TIPO_ITEM, [TIPO_TRAZABILIDAD] = @I_TIPO_TRAZABILIDAD, [ES_REUTILIZABLE] = @I_ES_REUTILIZABLE, [ADMITE_PRESTAMO] = @I_ADMITE_PRESTAMO, [REQUIERE_MANTENIMIENTO] = @I_REQUIERE_MANTENIMIENTO, [ADMITE_MEDICIONES] = @I_ADMITE_MEDICIONES, [CODIGO_ESTADO] = @I_CODIGO_ESTADO, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PRODUCTO] = @I_ID_PRODUCTO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;
    SET @O_FILAS_AFECTADAS = @@ROWCOUNT; SET @O_ID_PRODUCTO = @I_ID_PRODUCTO;
    IF @O_FILAS_AFECTADAS = 0 BEGIN SET @O_CODIGO_ERROR = 30003; SET @O_MENSAJE = N'El producto fue modificado por otro usuario o no pertenece a la empresa.'; END;
END;
