/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_INVENTARIO_GET
Archivo: SP_INVENTARIO_GET.sql | Procedimiento: INVENTARIO.SP_INVENTARIO_GET | Tipo: QUERY
Versión: 1.2.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera maestros, saldos, alertas y trazabilidad de la empresa autenticada.
Parámetros de entrada: @I_ID_EMPRESA, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_MENSAJE.
Retorno: Devuelve los conjuntos de filas definidos por sus SELECT finales.
Tablas utilizadas: CONFIGURACION.TRADUCCIONES_CATALOGO - SELECT; CONFIGURACION.UNIDADES_MEDIDA - SELECT; CONFIGURACION.USUARIOS_PREFERENCIAS - SELECT; INVENTARIO.CATEGORIAS_PRODUCTO - SELECT; INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.EXISTENCIAS - SELECT; INVENTARIO.MOVIMIENTOS - SELECT; INVENTARIO.MOVIMIENTOS_DETALLES - SELECT; INVENTARIO.PRODUCTOS - SELECT; INVENTARIO.RESERVAS_STOCK - SELECT; INVENTARIO.UBICACIONES - SELECT.
Transacción: No abre una transacción explícita; realiza operaciones de lectura.
Auditoría: No registra auditoría explícita porque no modifica estado.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Exposición de stock físico, reservado y disponible.
Historial: 1.2.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Clasificación de trazabilidad industrial por producto.
Historial: 1.2.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_INVENTARIO_GET]
    @I_ID_EMPRESA BIGINT,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;
    DECLARE @V_CULTURA NVARCHAR(10) = COALESCE((SELECT [CULTURA] FROM [CONFIGURACION].[USUARIOS_PREFERENCIAS] WHERE [ID_USUARIO] = @S_ID_USUARIO AND [CODIGO_ESTADO] = N'ACTIVO'), N'es-AR');

    -- INICIO: Catálogos y maestros visibles del inventario.
    SELECT [UNI].[ID_UNIDAD_MEDIDA], [UNI].[CODIGO], COALESCE([TRA].[NOMBRE], [UNI].[NOMBRE]) AS [NOMBRE],
           [UNI].[SIMBOLO], [UNI].[PERMITE_DECIMALES], [UNI].[CODIGO_ESTADO], [UNI].[ROW_VERSION]
    FROM [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI]
    LEFT JOIN [CONFIGURACION].[TRADUCCIONES_CATALOGO] AS [TRA] ON [TRA].[ENTIDAD] = N'UNIDADES_MEDIDA' AND [TRA].[CODIGO] = [UNI].[CODIGO] AND [TRA].[CULTURA] = @V_CULTURA AND [TRA].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [UNI].[NOMBRE];

    SELECT [CAT].[ID_CATEGORIA_PRODUCTO], [CAT].[CODIGO], COALESCE([TRA].[NOMBRE], [CAT].[NOMBRE]) AS [NOMBRE],
           COALESCE([TRA].[DESCRIPCION], [CAT].[DESCRIPCION]) AS [DESCRIPCION], [CAT].[CODIGO_ESTADO], [CAT].[ROW_VERSION]
    FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT]
    LEFT JOIN [CONFIGURACION].[TRADUCCIONES_CATALOGO] AS [TRA] ON [TRA].[ENTIDAD] = N'CATEGORIAS_PRODUCTO' AND [TRA].[CODIGO] = [CAT].[CODIGO] AND [TRA].[CULTURA] = @V_CULTURA AND [TRA].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [CAT].[NOMBRE];

    SELECT [PRO].[ID_PRODUCTO], [PRO].[ID_CATEGORIA_PRODUCTO], [PRO].[ID_UNIDAD_MEDIDA], [PRO].[CODIGO], [PRO].[NOMBRE],
           [PRO].[DESCRIPCION], [PRO].[CODIGO_BARRAS], [CAT].[NOMBRE] AS [CATEGORIA], [UNI].[SIMBOLO],
           [PRO].[CODIGO_ESTADO], [PRO].[ROW_VERSION], [PRO].[TIPO_ITEM], [PRO].[TIPO_TRAZABILIDAD], [PRO].[ES_REUTILIZABLE],
           [PRO].[ADMITE_PRESTAMO], [PRO].[REQUIERE_MANTENIMIENTO], [PRO].[ADMITE_MEDICIONES]
    FROM [INVENTARIO].[PRODUCTOS] AS [PRO]
    INNER JOIN [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT] ON [CAT].[ID_CATEGORIA_PRODUCTO] = [PRO].[ID_CATEGORIA_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    WHERE [PRO].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [PRO].[CODIGO];

    SELECT [DEP].[ID_DEPOSITO], [DEP].[ID_SUCURSAL], [DEP].[CODIGO], [DEP].[NOMBRE], [DEP].[DOMICILIO],
           [DEP].[DESCRIPCION], [DEP].[CODIGO_ESTADO], [DEP].[ROW_VERSION]
    FROM [INVENTARIO].[DEPOSITOS] AS [DEP] WHERE [DEP].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [DEP].[CODIGO];

    SELECT [UBI].[ID_UBICACION], [UBI].[ID_DEPOSITO], [UBI].[CODIGO], [UBI].[NOMBRE], [UBI].[DESCRIPCION],
           [UBI].[CODIGO_ESTADO], [UBI].[ROW_VERSION]
    FROM [INVENTARIO].[UBICACIONES] AS [UBI]
    INNER JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [UBI].[ID_DEPOSITO]
    WHERE [DEP].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [DEP].[CODIGO], [UBI].[CODIGO];

    SELECT [EXI].[ID_EXISTENCIA], [EXI].[ID_PRODUCTO], [EXI].[ID_DEPOSITO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO],
           [PRO].[NOMBRE] AS [PRODUCTO], [DEP].[NOMBRE] AS [DEPOSITO], [UNI].[SIMBOLO], [EXI].[CANTIDAD],
           COALESCE([RES].[CANTIDAD], 0) AS [CANTIDAD_RESERVADA], [EXI].[CANTIDAD] - COALESCE([RES].[CANTIDAD], 0) AS [CANTIDAD_DISPONIBLE],
           [EXI].[STOCK_MINIMO], CONVERT(BIT, CASE WHEN [EXI].[CANTIDAD] - COALESCE([RES].[CANTIDAD], 0) <= [EXI].[STOCK_MINIMO] THEN 1 ELSE 0 END) AS [BAJO_MINIMO],
           [EXI].[ROW_VERSION]
    FROM [INVENTARIO].[EXISTENCIAS] AS [EXI]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [EXI].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    INNER JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [EXI].[ID_DEPOSITO]
    OUTER APPLY
    (
        SELECT SUM([RST].[CANTIDAD]) AS [CANTIDAD]
        FROM [INVENTARIO].[RESERVAS_STOCK] AS [RST]
        WHERE [RST].[ID_EMPRESA] = [EXI].[ID_EMPRESA] AND [RST].[ID_PRODUCTO] = [EXI].[ID_PRODUCTO]
          AND [RST].[ID_DEPOSITO] = [EXI].[ID_DEPOSITO] AND [RST].[CODIGO_ESTADO] = N'RESERVADA'
    ) AS [RES]
    WHERE [EXI].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [PRO].[CODIGO], [DEP].[CODIGO];

    SELECT [MOV].[ID_MOVIMIENTO], [MOV].[CODIGO], [MOV].[TIPO_MOVIMIENTO], [MOV].[FECHA_MOVIMIENTO_UTC], [MOV].[OBSERVACION],
           [MOV].[CODIGO_ESTADO], [DET].[ID_MOVIMIENTO_DETALLE], [DET].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO],
           [PRO].[NOMBRE] AS [PRODUCTO], [DET].[ID_DEPOSITO_ORIGEN], [DOR].[NOMBRE] AS [DEPOSITO_ORIGEN],
           [DET].[ID_UBICACION_ORIGEN], [UOR].[NOMBRE] AS [UBICACION_ORIGEN], [DET].[ID_DEPOSITO_DESTINO],
           [DDE].[NOMBRE] AS [DEPOSITO_DESTINO], [DET].[ID_UBICACION_DESTINO], [UDE].[NOMBRE] AS [UBICACION_DESTINO],
           [DET].[CANTIDAD], [UNI].[SIMBOLO]
    FROM [INVENTARIO].[MOVIMIENTOS] AS [MOV]
    INNER JOIN [INVENTARIO].[MOVIMIENTOS_DETALLES] AS [DET] ON [DET].[ID_MOVIMIENTO] = [MOV].[ID_MOVIMIENTO]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    LEFT JOIN [INVENTARIO].[DEPOSITOS] AS [DOR] ON [DOR].[ID_DEPOSITO] = [DET].[ID_DEPOSITO_ORIGEN]
    LEFT JOIN [INVENTARIO].[UBICACIONES] AS [UOR] ON [UOR].[ID_UBICACION] = [DET].[ID_UBICACION_ORIGEN]
    LEFT JOIN [INVENTARIO].[DEPOSITOS] AS [DDE] ON [DDE].[ID_DEPOSITO] = [DET].[ID_DEPOSITO_DESTINO]
    LEFT JOIN [INVENTARIO].[UBICACIONES] AS [UDE] ON [UDE].[ID_UBICACION] = [DET].[ID_UBICACION_DESTINO]
    WHERE [MOV].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [MOV].[FECHA_MOVIMIENTO_UTC] DESC, [DET].[ID_MOVIMIENTO_DETALLE];
    -- FIN: Catálogos y maestros visibles del inventario.
END;
