/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_TRAZABILIDAD_GET
Archivo: SP_TRAZABILIDAD_GET.sql | Procedimiento: INVENTARIO.SP_TRAZABILIDAD_GET | Tipo: QUERY
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Devuelve estado actual almacenado e historial industrial de la empresa autenticada.
Parámetros de entrada: @I_ID_EMPRESA, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_MENSAJE.
Retorno: Devuelve los conjuntos de filas definidos por sus SELECT finales.
Tablas utilizadas: COMERCIAL.CLIENTES - SELECT; CONFIGURACION.SUCURSALES - SELECT; CONFIGURACION.UNIDADES_MEDIDA - SELECT; INVENTARIO.ACTIVOS - SELECT; INVENTARIO.ACTIVOS_CONTENIDOS - SELECT; INVENTARIO.ACTIVOS_EVENTOS - SELECT; INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.INCIDENTES - SELECT; INVENTARIO.LOTES - SELECT; INVENTARIO.LOTES_EXISTENCIAS - SELECT; INVENTARIO.MANTENIMIENTOS - SELECT; INVENTARIO.MEDICIONES_ACTIVOS - SELECT; INVENTARIO.PRESTAMOS - SELECT; INVENTARIO.PRESTAMOS_DETALLES - SELECT; INVENTARIO.PRODUCTOS - SELECT; INVENTARIO.TRANSFORMACIONES - SELECT; INVENTARIO.TRANSFORMACIONES_DETALLES - SELECT; INVENTARIO.UBICACIONES - SELECT.
Transacción: No abre una transacción explícita; realiza operaciones de lectura.
Auditoría: No registra auditoría explícita porque no modifica estado.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [INVENTARIO].[SP_TRAZABILIDAD_GET]
    @I_ID_EMPRESA BIGINT, @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL;
    SELECT [L].[ID_LOTE], [L].[ID_PRODUCTO], [L].[CODIGO], [L].[CODIGO_LOTE_PROVEEDOR], [P].[NOMBRE] AS [PRODUCTO],
           [E].[ID_DEPOSITO], [D].[NOMBRE] AS [DEPOSITO], [E].[CANTIDAD], [L].[FECHA_VENCIMIENTO], [L].[CODIGO_ESTADO]
    FROM [INVENTARIO].[LOTES] [L] JOIN [INVENTARIO].[LOTES_EXISTENCIAS] [E] ON [E].[ID_LOTE]=[L].[ID_LOTE]
    JOIN [INVENTARIO].[PRODUCTOS] [P] ON [P].[ID_PRODUCTO]=[L].[ID_PRODUCTO]
    JOIN [INVENTARIO].[DEPOSITOS] [D] ON [D].[ID_DEPOSITO]=[E].[ID_DEPOSITO]
    WHERE [L].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [L].[CODIGO];

    SELECT [A].[ID_ACTIVO], [A].[ID_PRODUCTO], [A].[ID_CLIENTE_PROPIETARIO], [A].[CODIGO], [A].[NUMERO_SERIE], [P].[NOMBRE] AS [PRODUCTO],
           [A].[TIPO_ACTIVO], [A].[ID_DEPOSITO], [D].[NOMBRE] AS [DEPOSITO], [A].[ID_UBICACION], [U].[NOMBRE] AS [UBICACION],
           COALESCE([A].[PROPIETARIO_NOMBRE],N'Propio') AS [PROPIETARIO_NOMBRE], [A].[CONDICION_ACTUAL], [A].[CODIGO_ESTADO],
           [A].[CAPACIDAD], [A].[UNIDAD_CAPACIDAD], [C].[ID_PRODUCTO_CONTENIDO], [PC].[NOMBRE] AS [PRODUCTO_CONTENIDO],
           [C].[ID_LOTE] AS [ID_LOTE_CONTENIDO], [L].[CODIGO] AS [LOTE_CONTENIDO], [C].[CANTIDAD_ACTUAL] AS [CANTIDAD_CONTENIDO],
           [UM].[SIMBOLO] AS [UNIDAD_CONTENIDO], [A].[ROW_VERSION]
    FROM [INVENTARIO].[ACTIVOS] [A] JOIN [INVENTARIO].[PRODUCTOS] [P] ON [P].[ID_PRODUCTO]=[A].[ID_PRODUCTO]
    LEFT JOIN [INVENTARIO].[DEPOSITOS] [D] ON [D].[ID_DEPOSITO]=[A].[ID_DEPOSITO]
    LEFT JOIN [INVENTARIO].[UBICACIONES] [U] ON [U].[ID_UBICACION]=[A].[ID_UBICACION]
    LEFT JOIN [INVENTARIO].[ACTIVOS_CONTENIDOS] [C] ON [C].[ID_ACTIVO]=[A].[ID_ACTIVO] AND [C].[CODIGO_ESTADO]=N'ACTIVO'
    LEFT JOIN [INVENTARIO].[PRODUCTOS] [PC] ON [PC].[ID_PRODUCTO]=[C].[ID_PRODUCTO_CONTENIDO]
    LEFT JOIN [CONFIGURACION].[UNIDADES_MEDIDA] [UM] ON [UM].[ID_UNIDAD_MEDIDA]=[PC].[ID_UNIDAD_MEDIDA]
    LEFT JOIN [INVENTARIO].[LOTES] [L] ON [L].[ID_LOTE]=[C].[ID_LOTE]
    WHERE [A].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [A].[CODIGO];

    SELECT [M].[ID_MEDICION_ACTIVO], [M].[ID_ACTIVO], [A].[CODIGO] AS [ACTIVO], [M].[FECHA_MEDICION_UTC],
           [M].[TIPO_MEDICION], [M].[VALOR], [M].[UNIDAD], [M].[METODO_MEDICION], [M].[ORIGEN_MEDICION],
           [M].[ES_ESTIMADA], [M].[REFERENCIA_DISPOSITIVO], [M].[OBSERVACION]
    FROM [INVENTARIO].[MEDICIONES_ACTIVOS] [M] JOIN [INVENTARIO].[ACTIVOS] [A] ON [A].[ID_ACTIVO]=[M].[ID_ACTIVO]
    WHERE [M].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [M].[FECHA_MEDICION_UTC] DESC;

    SELECT [T].[ID_TRANSFORMACION], [T].[CODIGO], [T].[FECHA_TRANSFORMACION_UTC], [T].[ID_LOTE_ORIGEN],
           [LO].[CODIGO] AS [LOTE_ORIGEN], [T].[ID_ACTIVO_ORIGEN], [AO].[CODIGO] AS [ACTIVO_ORIGEN],
           [P].[NOMBRE] AS [PRODUCTO], [T].[CANTIDAD_ORIGEN], [T].[CANTIDAD_MERMA], [T].[METODO_MEDICION],
           [T].[MOTIVO_MERMA], [TD].[ID_ACTIVO_DESTINO], [AD].[CODIGO] AS [ACTIVO_DESTINO], [TD].[CANTIDAD_CARGADA]
    FROM [INVENTARIO].[TRANSFORMACIONES] [T] JOIN [INVENTARIO].[TRANSFORMACIONES_DETALLES] [TD] ON [TD].[ID_TRANSFORMACION]=[T].[ID_TRANSFORMACION]
    JOIN [INVENTARIO].[LOTES] [LO] ON [LO].[ID_LOTE]=[T].[ID_LOTE_ORIGEN]
    JOIN [INVENTARIO].[PRODUCTOS] [P] ON [P].[ID_PRODUCTO]=[T].[ID_PRODUCTO_CONTENIDO]
    JOIN [INVENTARIO].[ACTIVOS] [AD] ON [AD].[ID_ACTIVO]=[TD].[ID_ACTIVO_DESTINO]
    LEFT JOIN [INVENTARIO].[ACTIVOS] [AO] ON [AO].[ID_ACTIVO]=[T].[ID_ACTIVO_ORIGEN]
    WHERE [T].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [T].[FECHA_TRANSFORMACION_UTC] DESC;

    SELECT [I].[ID_INCIDENTE], [I].[CODIGO], [I].[FECHA_INCIDENTE_UTC], [I].[TIPO_INCIDENTE], [P].[NOMBRE] AS [PRODUCTO],
           [D].[NOMBRE] AS [DEPOSITO], [I].[ID_ACTIVO], [A].[CODIGO] AS [ACTIVO], [I].[CANTIDAD_PERDIDA],
           [I].[ES_ESTIMADA], [I].[CAUSA], [I].[ACCION_TOMADA], [I].[CODIGO_ESTADO]
    FROM [INVENTARIO].[INCIDENTES] [I] JOIN [INVENTARIO].[PRODUCTOS] [P] ON [P].[ID_PRODUCTO]=[I].[ID_PRODUCTO]
    JOIN [INVENTARIO].[DEPOSITOS] [D] ON [D].[ID_DEPOSITO]=[I].[ID_DEPOSITO]
    LEFT JOIN [INVENTARIO].[ACTIVOS] [A] ON [A].[ID_ACTIVO]=[I].[ID_ACTIVO]
    WHERE [I].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [I].[FECHA_INCIDENTE_UTC] DESC;

    SELECT [M].[ID_MANTENIMIENTO], [M].[CODIGO], [M].[ID_ACTIVO], [A].[CODIGO] AS [ACTIVO], [M].[TIPO_MANTENIMIENTO],
           [M].[FECHA_INICIO_UTC], [M].[FECHA_FIN_UTC], [M].[DESCRIPCION_TRABAJO], [M].[RESULTADO], [M].[COSTO],
           [M].[FECHA_PROXIMA_REVISION], [M].[CODIGO_ESTADO], [M].[ROW_VERSION]
    FROM [INVENTARIO].[MANTENIMIENTOS] [M] JOIN [INVENTARIO].[ACTIVOS] [A] ON [A].[ID_ACTIVO]=[M].[ID_ACTIVO]
    WHERE [M].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [M].[FECHA_INICIO_UTC] DESC;

    SELECT [P].[ID_PRESTAMO], [P].[CODIGO], COALESCE([S].[NOMBRE],[C].[NOMBRE_RAZON_SOCIAL],[P].[DESTINO_EXTERNO]) AS [DESTINO],
           [P].[MODALIDAD_ENTREGA], [P].[FECHA_SALIDA_UTC], [P].[FECHA_DEVOLUCION_PREVISTA], [P].[FECHA_DEVOLUCION_REAL_UTC],
           [P].[CODIGO_ESTADO], [P].[ROW_VERSION], [PD].[ID_PRESTAMO_DETALLE], [PD].[ID_ACTIVO], [A].[CODIGO] AS [ACTIVO],
           [PD].[CANTIDAD_SALIDA], [PD].[CONDICION_SALIDA], [PD].[CANTIDAD_DEVUELTA], [PD].[CONDICION_DEVOLUCION]
    FROM [INVENTARIO].[PRESTAMOS] [P] JOIN [INVENTARIO].[PRESTAMOS_DETALLES] [PD] ON [PD].[ID_PRESTAMO]=[P].[ID_PRESTAMO]
    JOIN [INVENTARIO].[ACTIVOS] [A] ON [A].[ID_ACTIVO]=[PD].[ID_ACTIVO]
    LEFT JOIN [CONFIGURACION].[SUCURSALES] [S] ON [S].[ID_SUCURSAL]=[P].[ID_SUCURSAL_DESTINO]
    LEFT JOIN [COMERCIAL].[CLIENTES] [C] ON [C].[ID_CLIENTE]=[P].[ID_CLIENTE_DESTINO]
    WHERE [P].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [P].[FECHA_SALIDA_UTC] DESC;

    SELECT [E].[ID_ACTIVO_EVENTO], [E].[ID_ACTIVO], [A].[CODIGO] AS [ACTIVO], [E].[TIPO_EVENTO], [E].[FECHA_EVENTO_UTC],
           [E].[CODIGO_ESTADO_ANTES], [E].[CODIGO_ESTADO_DESPUES], [E].[CONDICION_ANTES], [E].[CONDICION_DESPUES],
           [E].[CANTIDAD_ANTES], [E].[CANTIDAD_DESPUES], [E].[OBSERVACION], [E].[ID_CORRELACION], [E].[ID_USUARIO_ALTA]
    FROM [INVENTARIO].[ACTIVOS_EVENTOS] [E] JOIN [INVENTARIO].[ACTIVOS] [A] ON [A].[ID_ACTIVO]=[E].[ID_ACTIVO]
    WHERE [E].[ID_EMPRESA]=@I_ID_EMPRESA ORDER BY [E].[FECHA_EVENTO_UTC] DESC, [E].[ID_ACTIVO_EVENTO] DESC;

    SELECT [ID_SUCURSAL] AS [ID_DESTINO], [CODIGO], [NOMBRE]
    FROM [CONFIGURACION].[SUCURSALES]
    WHERE [ID_EMPRESA]=@I_ID_EMPRESA AND [CODIGO_ESTADO]=N'ACTIVO' ORDER BY [NOMBRE];

    SELECT [ID_CLIENTE] AS [ID_DESTINO], [CODIGO], [NOMBRE_RAZON_SOCIAL] AS [NOMBRE]
    FROM [COMERCIAL].[CLIENTES]
    WHERE [ID_EMPRESA]=@I_ID_EMPRESA AND [CODIGO_ESTADO]=N'ACTIVO' ORDER BY [NOMBRE_RAZON_SOCIAL];
END;
