/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SMOKE_INVENTARIO
Archivo: SMOKE_INVENTARIO.sql | Versión: 1.0.0 | Fecha: 2026-08-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica saldos, alertas, concurrencia e insuficiencia sin conservar cambios.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
BEGIN TRY
    DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');
    DECLARE @V_ID_USUARIO BIGINT = (SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [NOMBRE_USUARIO] = N'AOCAUZI');
    DECLARE @V_ID_PRODUCTO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-TUBO-001');
    DECLARE @V_ID_DEPOSITO BIGINT = (SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CENTRAL');
    DECLARE @V_ID_EXISTENCIA BIGINT = (SELECT [ID_EXISTENCIA] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_PRODUCTO] = @V_ID_PRODUCTO AND [ID_DEPOSITO] = @V_ID_DEPOSITO);
    IF @V_ID_PRODUCTO IS NULL OR @V_ID_DEPOSITO IS NULL OR @V_ID_EXISTENCIA IS NULL THROW 51000, 'Faltan datos mínimos de Development.', 1;

    DECLARE @V_CANTIDAD_INICIAL DECIMAL(19,4) = (SELECT [CANTIDAD] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EXISTENCIA] = @V_ID_EXISTENCIA);
    DECLARE @V_JSON NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"OriginWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":5.0}]';
    DECLARE @V_ID_MOVIMIENTO BIGINT, @V_CODIGO_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000), @V_FILAS INT;
    DECLARE @V_FECHA DATETIME2(3) = SYSUTCDATETIME();
    EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'SALIDA', @I_FECHA_MOVIMIENTO_UTC = @V_FECHA, @I_OBSERVACION = N'SMOKE', @I_DETALLES_JSON = @V_JSON, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL OR (SELECT [CANTIDAD] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EXISTENCIA] = @V_ID_EXISTENCIA) <> @V_CANTIDAD_INICIAL - 5 THROW 51001, 'La salida no actualizó el saldo esperado.', 1;

    SET @V_JSON = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"OriginWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":999999.0}]';
    SET @V_ID_MOVIMIENTO = NULL; SET @V_CODIGO_ERROR = NULL; SET @V_MENSAJE = NULL; SET @V_FILAS = 0;
    EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'SALIDA', @I_FECHA_MOVIMIENTO_UTC = @V_FECHA, @I_OBSERVACION = N'SMOKE SIN STOCK', @I_DETALLES_JSON = @V_JSON, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 30004 OR @V_ID_MOVIMIENTO IS NOT NULL THROW 51002, 'La insuficiencia de stock no fue controlada.', 1;

    DECLARE @V_ROW_VERSION BINARY(8) = (SELECT [ROW_VERSION] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EXISTENCIA] = @V_ID_EXISTENCIA);
    SET @V_CODIGO_ERROR = NULL; SET @V_MENSAJE = NULL; SET @V_FILAS = 0;
    EXEC [INVENTARIO].[SP_EXISTENCIA_MINIMO_UPDATE] @I_ID_EXISTENCIA = @V_ID_EXISTENCIA, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_STOCK_MINIMO = 10, @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_USUARIO = @V_ID_USUARIO, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL OR @V_FILAS <> 1 THROW 51003, 'No se pudo actualizar el mínimo.', 1;
    SET @V_CODIGO_ERROR = NULL; SET @V_MENSAJE = NULL; SET @V_FILAS = 0;
    EXEC [INVENTARIO].[SP_EXISTENCIA_MINIMO_UPDATE] @I_ID_EXISTENCIA = @V_ID_EXISTENCIA, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_STOCK_MINIMO = 11, @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_USUARIO = @V_ID_USUARIO, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 30003 THROW 51004, 'No se detectó la versión desactualizada.', 1;

    ROLLBACK TRANSACTION;
    SELECT N'SMOKE_INVENTARIO_OK' AS [RESULTADO];
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
