/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SMOKE_VENTAS
Archivo: SMOKE_VENTAS.sql | Versión: 1.2.0 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica pedido, reserva, protección del disponible, venta y descuento físico sin conservar cambios.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Fórmulas promocionales, acumulación y rechazo de mezcla manual.
Historial: 1.2.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Rechazo controlado de una suma de cantidades fuera de rango.
===============================================================================
*/
SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
BEGIN TRY
    DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');
    DECLARE @V_ID_USUARIO BIGINT = (SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [NOMBRE_USUARIO] = N'AOCAUZI');
    DECLARE @V_ID_CLIENTE BIGINT = (SELECT TOP (1) [ID_CLIENTE] FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO');
    DECLARE @V_ID_PRODUCTO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-TUBO-001');
    DECLARE @V_ID_DEPOSITO BIGINT = (SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CENTRAL');
    DECLARE @V_ID_LISTA BIGINT = (SELECT [ID_LISTA_PRECIO] FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'GENERAL');
    DECLARE @V_STOCK_INICIAL DECIMAL(19,4) = (SELECT [CANTIDAD] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [ID_PRODUCTO] = @V_ID_PRODUCTO AND [ID_DEPOSITO] = @V_ID_DEPOSITO);
    IF @V_ID_CLIENTE IS NULL OR @V_ID_PRODUCTO IS NULL OR @V_ID_DEPOSITO IS NULL OR @V_ID_LISTA IS NULL OR @V_STOCK_INICIAL < 5 THROW 51000, 'Faltan datos mínimos de Development.', 1;

    DECLARE @V_CODIGO_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000), @V_FILAS INT;
    DECLARE @V_FECHA_UTC DATETIME2(3) = SYSUTCDATETIME();

    -- INICIO: Todas las fórmulas promocionales se calculan en SQL y las entradas repetidas se acumulan.
    DECLARE @V_ID_CODO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-CODO-001');
    DECLARE @V_ID_VALVULA BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-VALVULA-001');
    DECLARE @V_ID_PVC BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-PVC-040');
    DECLARE @V_PROMO_2X1 BIGINT = (SELECT [ID_PROMOCION] FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-2X1-TUBO');
    DECLARE @V_PROMO_4X3 BIGINT = (SELECT [ID_PROMOCION] FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-4X3-CODO');
    DECLARE @V_PROMO_2DA50 BIGINT = (SELECT [ID_PROMOCION] FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-2DA-50-VALVULA');
    DECLARE @V_PROMO_UNIDAD50 BIGINT = (SELECT [ID_PROMOCION] FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-UNIDAD-50-PVC');
    DECLARE @V_PROMO_PAQUETE BIGINT = (SELECT [ID_PROMOCION] FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-PACK3-TUBO');
    IF @V_ID_CODO IS NULL OR @V_ID_VALVULA IS NULL OR @V_ID_PVC IS NULL OR @V_PROMO_2X1 IS NULL OR @V_PROMO_4X3 IS NULL OR @V_PROMO_2DA50 IS NULL OR @V_PROMO_UNIDAD50 IS NULL OR @V_PROMO_PAQUETE IS NULL THROW 51008, 'Faltan productos o promociones demostrativas.', 1;

    DECLARE @V_JSON_PROMOCIONES NVARCHAR(MAX) =
        N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_2X1) + N',"Quantity":1,"UnitPrice":100,"DiscountRate":0,"TaxRate":0},' +
        N'{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_2X1) + N',"Quantity":1,"UnitPrice":100,"DiscountRate":0,"TaxRate":0},' +
        N'{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_CODO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_4X3) + N',"Quantity":5,"UnitPrice":550,"DiscountRate":0,"TaxRate":0},' +
        N'{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_VALVULA) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_2DA50) + N',"Quantity":2,"UnitPrice":2400,"DiscountRate":0,"TaxRate":0},' +
        N'{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PVC) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_UNIDAD50) + N',"Quantity":2,"UnitPrice":180,"DiscountRate":0,"TaxRate":0},' +
        N'{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_PAQUETE) + N',"Quantity":4,"UnitPrice":100,"DiscountRate":0,"TaxRate":0}]';
    DECLARE @V_ID_PEDIDO_PROMO BIGINT;
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'SMOKE PROMOCIONES', @I_DETALLES_JSON = @V_JSON_PROMOCIONES, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_PROMO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL OR (SELECT [TOTAL_DESCUENTO] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO) <> 2090 OR (SELECT [TOTAL] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO) <> 6420 THROW 51009, 'El total promocional no coincide con las cinco reglas.', 1;
    IF (SELECT COUNT(*) FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO AND [CODIGO_ESTADO] = N'ACTIVO') <> 5 THROW 51010, 'Las dos entradas 2x1 no se acumularon en un renglón.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO AND [ID_PROMOCION] = @V_PROMO_2X1 AND [CANTIDAD] = 2 AND [IMPORTE_DESCUENTO] = 100 AND [TOTAL] = 100 AND [CODIGO_PROMOCION] = N'DEMO-2X1-TUBO') THROW 51011, 'La fórmula 2x1 o su fotografía es incorrecta.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO AND [ID_PROMOCION] = @V_PROMO_4X3 AND [CANTIDAD] = 5 AND [IMPORTE_DESCUENTO] = 550 AND [TOTAL] = 2200) THROW 51012, 'La fórmula 4x3 con sobrante es incorrecta.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO AND [ID_PROMOCION] = @V_PROMO_2DA50 AND [IMPORTE_DESCUENTO] = 1200 AND [TOTAL] = 3600) THROW 51013, 'La segunda unidad al 50% es incorrecta.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO AND [ID_PROMOCION] = @V_PROMO_UNIDAD50 AND [IMPORTE_DESCUENTO] = 180 AND [TOTAL] = 180) THROW 51014, 'El 50% por unidad es incorrecto.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_PROMO AND [ID_PROMOCION] = @V_PROMO_PAQUETE AND [CANTIDAD] = 4 AND [IMPORTE_DESCUENTO] = 60 AND [TOTAL] = 340) THROW 51015, 'El precio fijo de paquete con sobrante es incorrecto.', 1;

    SET @V_CODIGO_ERROR = NULL;
    SET @V_ID_PEDIDO_PROMO = NULL;
    SET @V_JSON_PROMOCIONES = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_2X1) + N',"Quantity":2,"UnitPrice":100,"DiscountRate":0.10,"TaxRate":0}]';
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'SMOKE MEZCLA INVÁLIDA', @I_DETALLES_JSON = @V_JSON_PROMOCIONES, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_PROMO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 40008 OR @V_ID_PEDIDO_PROMO IS NOT NULL THROW 51016, 'Se aceptó indebidamente una promoción con descuento manual.', 1;

    INSERT INTO [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_PAGADA], [FECHA_VIGENCIA_HASTA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES (@V_ID_EMPRESA, @V_ID_PRODUCTO, N'SMOKE-VENCIDA', N'Promoción vencida de prueba', N'CANTIDAD_PAGADA', 2, 1, DATEADD(DAY, -1, CONVERT(DATE, @V_FECHA_UTC)), N'ACTIVO', @V_ID_USUARIO);
    DECLARE @V_PROMO_VENCIDA BIGINT = CONVERT(BIGINT, SCOPE_IDENTITY());
    SET @V_CODIGO_ERROR = NULL; SET @V_ID_PEDIDO_PROMO = NULL;
    SET @V_JSON_PROMOCIONES = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_VENCIDA) + N',"Quantity":2,"UnitPrice":100,"DiscountRate":0,"TaxRate":0}]';
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'SMOKE PROMOCIÓN VENCIDA', @I_DETALLES_JSON = @V_JSON_PROMOCIONES, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_PROMO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 40009 OR @V_ID_PEDIDO_PROMO IS NOT NULL THROW 51017, 'Se aceptó indebidamente una promoción vencida.', 1;

    SET @V_CODIGO_ERROR = NULL; SET @V_ID_PEDIDO_PROMO = NULL;
    SET @V_JSON_PROMOCIONES = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":999999999999999,"UnitPrice":999999999999999,"DiscountRate":0,"TaxRate":0}]';
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'SMOKE IMPORTE EXTREMO', @I_DETALLES_JSON = @V_JSON_PROMOCIONES, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_PROMO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 40008 OR @V_ID_PEDIDO_PROMO IS NOT NULL THROW 51019, 'Un importe fuera de rango no fue rechazado de forma controlada.', 1;

    SET @V_CODIGO_ERROR = NULL; SET @V_ID_PEDIDO_PROMO = NULL;
    SET @V_JSON_PROMOCIONES = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":600000000000000,"UnitPrice":0,"DiscountRate":0,"TaxRate":0},{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":600000000000000,"UnitPrice":0,"DiscountRate":0,"TaxRate":0}]';
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'SMOKE CANTIDAD ACUMULADA EXTREMA', @I_DETALLES_JSON = @V_JSON_PROMOCIONES, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_PROMO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 40008 OR @V_ID_PEDIDO_PROMO IS NOT NULL OR EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [OBSERVACION] = N'SMOKE CANTIDAD ACUMULADA EXTREMA') THROW 51020, 'Una suma de cantidades fuera de rango no fue rechazada sin persistir.', 1;
    -- FIN: Todas las fórmulas promocionales se calculan en SQL y las entradas repetidas se acumulan.

    DECLARE @V_JSON NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_PROMO_2X1) + N',"Quantity":5,"UnitPrice":100,"DiscountRate":0,"TaxRate":0.21}]';
    DECLARE @V_ID_PEDIDO BIGINT; SET @V_CODIGO_ERROR = NULL;
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'SMOKE VENTAS', @I_DETALLES_JSON = @V_JSON, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL OR (SELECT [TOTAL] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO) <> 363 THROW 51001, 'El pedido o sus totales promocionales son incorrectos.', 1;

    DECLARE @V_ROW_VERSION BINARY(8) = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO);
    EXEC [COMERCIAL].[SP_PEDIDO_CONFIRM] @I_ID_PEDIDO = @V_ID_PEDIDO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL OR NOT EXISTS (SELECT 1 FROM [INVENTARIO].[RESERVAS_STOCK] WHERE [ID_PEDIDO] = @V_ID_PEDIDO AND [CANTIDAD] = 5 AND [CODIGO_ESTADO] = N'RESERVADA') THROW 51002, 'La confirmación no reservó el stock.', 1;
    IF (SELECT [CANTIDAD] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [ID_PRODUCTO] = @V_ID_PRODUCTO AND [ID_DEPOSITO] = @V_ID_DEPOSITO) <> @V_STOCK_INICIAL THROW 51003, 'La reserva alteró indebidamente el stock físico.', 1;

    DECLARE @V_ID_MOVIMIENTO BIGINT; SET @V_CODIGO_ERROR = NULL;
    SET @V_JSON = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"OriginWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":' + CONVERT(NVARCHAR(30), @V_STOCK_INICIAL - 4) + N'}]';
    EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'SALIDA', @I_FECHA_MOVIMIENTO_UTC = @V_FECHA_UTC, @I_OBSERVACION = N'SMOKE RESERVA', @I_DETALLES_JSON = @V_JSON, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR <> 30004 THROW 51004, 'Una salida manual consumió stock reservado.', 1;

    SET @V_ROW_VERSION = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO); SET @V_CODIGO_ERROR = NULL;
    DECLARE @V_ID_VENTA BIGINT;
    EXEC [COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO] @I_ID_PEDIDO = @V_ID_PEDIDO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_FECHA_VENTA_UTC = @V_FECHA_UTC, @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_VENTA = @V_ID_VENTA OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL OR @V_ID_VENTA IS NULL OR (SELECT [CODIGO_ESTADO] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO) <> N'VENDIDO' THROW 51005, 'No se generó la venta esperada.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[VENTAS_DETALLES] WHERE [ID_VENTA] = @V_ID_VENTA AND [ID_PROMOCION] = @V_PROMO_2X1 AND [CODIGO_PROMOCION] = N'DEMO-2X1-TUBO' AND [NOMBRE_PROMOCION] IS NOT NULL AND [IMPORTE_DESCUENTO] = 200 AND [TOTAL] = 363) THROW 51018, 'La venta no conservó la fotografía promocional del pedido.', 1;
    IF (SELECT [CANTIDAD] FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [ID_PRODUCTO] = @V_ID_PRODUCTO AND [ID_DEPOSITO] = @V_ID_DEPOSITO) <> @V_STOCK_INICIAL - 5 THROW 51006, 'La venta no descontó el stock físico.', 1;
    IF EXISTS (SELECT 1 FROM [INVENTARIO].[RESERVAS_STOCK] WHERE [ID_PEDIDO] = @V_ID_PEDIDO AND [CODIGO_ESTADO] <> N'APLICADA') THROW 51007, 'La reserva no quedó aplicada.', 1;

    ROLLBACK TRANSACTION; SELECT N'SMOKE_VENTAS_OK' AS [RESULTADO];
END TRY
BEGIN CATCH IF XACT_STATE() <> 0 ROLLBACK TRANSACTION; THROW; END CATCH;
