/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Prueba de humo Seguridad Fase 2
Archivo: SMOKE_SEGURIDAD_FASE2.sql | Versión: 1.1.0 | Fecha: 2026-08-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Valida usuarios, roles, credenciales, bloqueo y sesiones con rollback final.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Valida código catalogado de sesión no vigente.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

BEGIN TRY
    DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');
    DECLARE @S_ID_USUARIO BIGINT = (SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [NOMBRE_USUARIO] = N'AOCAUZI');
    DECLARE @O_ID_USUARIO BIGINT, @O_ID_SESION BIGINT, @O_ID_ERROR_APLICACION BIGINT,
            @O_CODIGO_ERROR BIGINT, @O_MENSAJE NVARCHAR(4000), @O_FILAS_AFECTADAS INT;
    DECLARE @V_HASH VARBINARY(64) = CONVERT(VARBINARY(64), REPLICATE('H', 64));
    DECLARE @V_SALT VARBINARY(32) = CONVERT(VARBINARY(32), REPLICATE('S', 32));
    DECLARE @V_TOKEN_HASH VARBINARY(64);
    DECLARE @V_FECHA_EXPIRACION_UTC DATETIME2(3);
    DECLARE @V_ID_CORRELACION UNIQUEIDENTIFIER;

    -- INICIO: Validación controlada de un token sin sesión vigente.
    SET @V_TOKEN_HASH = HASHBYTES('SHA2_512', N'SESION_INEXISTENTE');
    EXEC [SEGURIDAD].[SP_SESION_VALIDATE]
        @I_HASH_TOKEN = @V_TOKEN_HASH, @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT,
        @O_MENSAJE = @O_MENSAJE OUTPUT;
    IF @O_CODIGO_ERROR <> 10005 OR NULLIF(@O_MENSAJE, N'') IS NULL
        THROW 51008, 'La sesión inválida no devolvió código y descripción.', 1;
    -- FIN: Validación controlada de un token sin sesión vigente.

    -- INICIO: Alta con dos roles y validación de asignaciones.
    EXEC [SEGURIDAD].[SP_USUARIO_CREATE]
        @I_ID_EMPRESA = @V_ID_EMPRESA, @I_NOMBRE_USUARIO = N'FASE2TEST', @I_NOMBRES = N'Prueba',
        @I_APELLIDO = N'Seguridad', @I_EMAIL = N'fase2.test@oxitigre.local',
        @I_ROLES_JSON = N'["ADMINISTRADOR","CONSULTA"]', @I_HASH_CLAVE = @V_HASH,
        @I_SALT_CLAVE = @V_SALT, @I_ALGORITMO_CLAVE = N'PBKDF2-SHA512', @I_ITERACIONES_CLAVE = 210000,
        @S_ID_USUARIO = @S_ID_USUARIO, @O_ID_USUARIO = @O_ID_USUARIO OUTPUT,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF (SELECT COUNT(*) FROM [SEGURIDAD].[USUARIOS_ROLES] WHERE [ID_USUARIO] = @O_ID_USUARIO AND [CODIGO_ESTADO] = N'ACTIVO') <> 2
        THROW 51000, 'El alta no asignó los dos roles solicitados.', 1;
    -- FIN: Alta con dos roles y validación de asignaciones.

    -- INICIO: Edición y reemplazo de roles conservando el historial.
    EXEC [SEGURIDAD].[SP_USUARIO_UPDATE]
        @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_USUARIO = @O_ID_USUARIO, @I_NOMBRES = N'Prueba Editada',
        @I_APELLIDO = N'Seguridad', @I_EMAIL = N'fase2.editada@oxitigre.local', @I_CODIGO_ESTADO = N'ACTIVO',
        @I_ROLES_JSON = N'["CONSULTA"]', @S_ID_USUARIO = @S_ID_USUARIO,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF (SELECT COUNT(*) FROM [SEGURIDAD].[USUARIOS_ROLES] WHERE [ID_USUARIO] = @O_ID_USUARIO AND [CODIGO_ESTADO] = N'ACTIVO') <> 1
        THROW 51001, 'La edición no reemplazó los roles activos.', 1;
    -- FIN: Edición y reemplazo de roles conservando el historial.

    -- INICIO: Sesión, reinicio temporal y revocación automática.
    SET @V_TOKEN_HASH = HASHBYTES('SHA2_512', CONVERT(NVARCHAR(36), NEWID()));
    SET @V_FECHA_EXPIRACION_UTC = DATEADD(HOUR, 8, SYSUTCDATETIME());
    SET @V_ID_CORRELACION = NEWID();
    EXEC [SEGURIDAD].[SP_SESION_CREATE]
        @I_ID_USUARIO = @O_ID_USUARIO, @I_HASH_TOKEN = @V_TOKEN_HASH,
        @I_FECHA_EXPIRACION_UTC = @V_FECHA_EXPIRACION_UTC, @S_IP_ORIGEN = N'127.0.0.1',
        @S_APLICACION_ORIGEN = N'SMOKE_SEGURIDAD', @S_ID_CORRELACION = @V_ID_CORRELACION, @O_ID_SESION = @O_ID_SESION OUTPUT,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    EXEC [SEGURIDAD].[SP_USUARIO_PASSWORD_RESET]
        @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_USUARIO = @O_ID_USUARIO, @I_HASH_CLAVE = @V_HASH,
        @I_SALT_CLAVE = @V_SALT, @I_ALGORITMO_CLAVE = N'PBKDF2-SHA512', @I_ITERACIONES_CLAVE = 210000,
        @S_ID_USUARIO = @S_ID_USUARIO, @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT,
        @O_MENSAJE = @O_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[SESIONES] WHERE [ID_SESION] = @O_ID_SESION AND [CODIGO_ESTADO] = N'REVOCADA')
        THROW 51002, 'El reinicio de contraseña no revocó la sesión.', 1;
    -- FIN: Sesión, reinicio temporal y revocación automática.

    -- INICIO: Bloqueo al quinto fallo y limpieza posterior por acceso correcto.
    DECLARE @V_CONTADOR INT = 0;
    WHILE @V_CONTADOR < 5
    BEGIN
        EXEC [SEGURIDAD].[SP_USUARIO_LOGIN_RESULT] @I_ID_USUARIO = @O_ID_USUARIO, @I_ES_EXITOSO = 0,
            @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
            @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
        SET @V_CONTADOR += 1;
    END;
    IF NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[USUARIOS] WHERE [ID_USUARIO] = @O_ID_USUARIO AND [INTENTOS_FALLIDOS] = 5 AND [FECHA_BLOQUEO_UTC] IS NOT NULL)
        THROW 51003, 'La cuenta no se bloqueó al quinto intento.', 1;
    EXEC [SEGURIDAD].[SP_USUARIO_LOGIN_RESULT] @I_ID_USUARIO = @O_ID_USUARIO, @I_ES_EXITOSO = 1,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[USUARIOS] WHERE [ID_USUARIO] = @O_ID_USUARIO AND [INTENTOS_FALLIDOS] = 0 AND [FECHA_BLOQUEO_UTC] IS NULL)
        THROW 51004, 'El acceso correcto no limpió el bloqueo.', 1;
    -- FIN: Bloqueo al quinto fallo y limpieza posterior por acceso correcto.

    -- INICIO: Cierre voluntario y revocación administrativa de sesiones.
    SET @V_TOKEN_HASH = HASHBYTES('SHA2_512', CONVERT(NVARCHAR(36), NEWID()));
    SET @V_FECHA_EXPIRACION_UTC = DATEADD(HOUR, 8, SYSUTCDATETIME());
    SET @V_ID_CORRELACION = NEWID();
    EXEC [SEGURIDAD].[SP_SESION_CREATE]
        @I_ID_USUARIO = @O_ID_USUARIO, @I_HASH_TOKEN = @V_TOKEN_HASH,
        @I_FECHA_EXPIRACION_UTC = @V_FECHA_EXPIRACION_UTC, @S_IP_ORIGEN = N'127.0.0.1',
        @S_APLICACION_ORIGEN = N'SMOKE_SEGURIDAD', @S_ID_CORRELACION = @V_ID_CORRELACION, @O_ID_SESION = @O_ID_SESION OUTPUT,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    EXEC [SEGURIDAD].[SP_SESION_CLOSE] @I_ID_SESION = @O_ID_SESION, @S_ID_USUARIO = @O_ID_USUARIO,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[SESIONES] WHERE [ID_SESION] = @O_ID_SESION AND [CODIGO_ESTADO] = N'CERRADA')
        THROW 51005, 'El cierre voluntario no finalizó la sesión.', 1;

    SET @V_TOKEN_HASH = HASHBYTES('SHA2_512', CONVERT(NVARCHAR(36), NEWID()));
    SET @V_FECHA_EXPIRACION_UTC = DATEADD(HOUR, 8, SYSUTCDATETIME());
    SET @V_ID_CORRELACION = NEWID();
    EXEC [SEGURIDAD].[SP_SESION_CREATE]
        @I_ID_USUARIO = @O_ID_USUARIO, @I_HASH_TOKEN = @V_TOKEN_HASH,
        @I_FECHA_EXPIRACION_UTC = @V_FECHA_EXPIRACION_UTC, @S_IP_ORIGEN = N'127.0.0.1',
        @S_APLICACION_ORIGEN = N'SMOKE_SEGURIDAD', @S_ID_CORRELACION = @V_ID_CORRELACION, @O_ID_SESION = @O_ID_SESION OUTPUT,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    EXEC [SEGURIDAD].[SP_USUARIO_SESIONES_REVOKE] @I_ID_EMPRESA = @V_ID_EMPRESA,
        @I_ID_USUARIO = @O_ID_USUARIO, @S_ID_USUARIO = @S_ID_USUARIO,
        @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT, @O_MENSAJE = @O_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[SESIONES] WHERE [ID_SESION] = @O_ID_SESION AND [CODIGO_ESTADO] = N'REVOCADA')
        THROW 51006, 'La revocación administrativa no finalizó la sesión.', 1;
    -- FIN: Cierre voluntario y revocación administrativa de sesiones.

    -- INICIO: Registro central de una ocurrencia técnica controlada.
    SET @V_ID_CORRELACION = NEWID();
    EXEC [AUDITORIA].[SP_ERROR_OCURRENCIA_CREATE]
        @I_CODIGO_ERROR = 70002, @I_COMPONENTE = N'SMOKE_SEGURIDAD', @I_MENSAJE = N'Prueba controlada',
        @I_DETALLE_TECNICO = NULL, @I_STACK_TRACE = NULL, @S_IP_ORIGEN = N'127.0.0.1',
        @S_APLICACION_ORIGEN = N'SMOKE', @S_ID_CORRELACION = @V_ID_CORRELACION,
        @O_ID_ERROR_APLICACION = @O_ID_ERROR_APLICACION OUTPUT, @O_CODIGO_ERROR = @O_CODIGO_ERROR OUTPUT,
        @O_MENSAJE = @O_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @O_FILAS_AFECTADAS OUTPUT;
    IF @O_ID_ERROR_APLICACION IS NULL THROW 51007, 'No se registró la ocurrencia técnica controlada.', 1;
    -- FIN: Registro central de una ocurrencia técnica controlada.

    ROLLBACK TRANSACTION;
    SELECT N'OK' AS [RESULTADO], N'Seguridad Fase 2 validada con rollback.' AS [DETALLE];
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
