/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Smoke test de pedidos con servicios y activos
Archivo: SMOKE_PEDIDO_SERVICIOS_ACTIVOS.sql | Versión: 1.0.0 | Fecha: 2026-08-28 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica que un pedido mixto cobre servicios, vincule un tubo y mueva stock solo por productos.
Historial: 1.0.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

BEGIN TRANSACTION;

DECLARE @V_ID_EMPRESA BIGINT = 1, @V_ID_USUARIO BIGINT = 1, @V_ID_CLIENTE BIGINT = 1;
DECLARE @V_ID_PRODUCTO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = 1 AND [CODIGO] = N'PRD-000001');
DECLARE @V_ID_SERVICIO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = 1 AND [CODIGO] = N'SRV-RECARGA');
DECLARE @V_ID_ACTIVO_PRODUCTO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = 1 AND [CODIGO] = N'PRD-CIL10');
DECLARE @V_ID_LISTA BIGINT = (SELECT [ID_LISTA_PRECIO] FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = 1 AND [CODIGO] = N'GENERAL');
DECLARE @V_ID_DEPOSITO BIGINT = (SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = 1 AND [CODIGO] = N'CENTRAL');

IF @V_ID_PRODUCTO IS NULL OR @V_ID_SERVICIO IS NULL OR @V_ID_ACTIVO_PRODUCTO IS NULL OR @V_ID_LISTA IS NULL OR @V_ID_DEPOSITO IS NULL
    THROW 50000, 'Faltan datos de desarrollo para ejecutar el smoke comercial.', 1;

INSERT INTO [INVENTARIO].[ACTIVOS]
([ID_EMPRESA], [ID_PRODUCTO], [ID_CLIENTE_PROPIETARIO], [CODIGO], [NUMERO_SERIE], [TIPO_ACTIVO],
 [PROPIETARIO_CODIGO], [PROPIETARIO_NOMBRE], [CONDICION_ACTUAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
VALUES
(@V_ID_EMPRESA, @V_ID_ACTIVO_PRODUCTO, @V_ID_CLIENTE, N'ACT-SMOKE-SERVICIO', N'SERIE-SMOKE-SERVICIO',
 N'CILINDRO', N'CLI-000001', N'Cliente', N'OPERATIVO', N'EN_CLIENTE', @V_ID_USUARIO);

DECLARE @V_ID_ACTIVO BIGINT = CONVERT(BIGINT, SCOPE_IDENTITY());
DECLARE @V_DETALLES NVARCHAR(MAX) = CONCAT
(
    N'[{"ProductId":', @V_ID_PRODUCTO, N',"WarehouseId":', @V_ID_DEPOSITO,
    N',"Quantity":1,"UnitPrice":1000,"DiscountRate":0,"TaxRate":0.21},',
    N'{"ProductId":', @V_ID_SERVICIO,
    N',"WarehouseId":null,"Quantity":1,"UnitPrice":12000,"DiscountRate":0,"TaxRate":0.21}]'
);
DECLARE @V_ACTIVOS NVARCHAR(MAX) = CONCAT
(
    N'[{"AssetId":', @V_ID_ACTIVO, N',"ProductLineId":', @V_ID_SERVICIO,
    N',"LinkType":"CLIENTE_SERVICIO","InboundMode":"ENTREGA_CLIENTE","ReturnMode":"RETIRO_CLIENTE",',
    N'"Observation":"Tubo recibido para recarga y retiro del cliente."}]'
);
DECLARE @V_ID_PEDIDO BIGINT, @V_ID_VENTA BIGINT, @V_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000), @V_FILAS INT;

EXEC [COMERCIAL].[SP_PEDIDO_SAVE]
    @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA,
    @I_FECHA_PEDIDO_UTC = '2026-08-28T12:00:00', @I_MONEDA = 'ARS',
    @I_OBSERVACION = N'Prueba mixta de producto, servicio y activo.', @I_DETALLES_JSON = @V_DETALLES,
    @I_ACTIVOS_JSON = @V_ACTIVOS, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO,
    @O_ID_PEDIDO = @V_ID_PEDIDO OUTPUT, @O_CODIGO_ERROR = @V_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_ERROR IS NOT NULL OR (SELECT COUNT(*) FROM [COMERCIAL].[PEDIDOS_ACTIVOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO') <> 1
    THROW 50000, 'El pedido no guardó correctamente el activo vinculado.', 1;

DECLARE @V_VERSION BINARY(8) = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO);
EXEC [COMERCIAL].[SP_PEDIDO_CONFIRM]
    @I_ID_PEDIDO = @V_ID_PEDIDO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ROW_VERSION = @V_VERSION,
    @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_ERROR IS NOT NULL OR (SELECT COUNT(*) FROM [INVENTARIO].[RESERVAS_STOCK] WHERE [ID_PEDIDO] = @V_ID_PEDIDO AND [CODIGO_ESTADO] = N'RESERVADA') <> 1
    THROW 50000, 'La confirmación no reservó exactamente el producto físico.', 1;

SET @V_VERSION = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO);
EXEC [COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO]
    @I_ID_PEDIDO = @V_ID_PEDIDO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_FECHA_VENTA_UTC = '2026-08-28T12:05:00',
    @I_ROW_VERSION = @V_VERSION, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO,
    @O_ID_VENTA = @V_ID_VENTA OUTPUT, @O_CODIGO_ERROR = @V_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_ERROR IS NOT NULL
   OR (SELECT COUNT(*) FROM [COMERCIAL].[VENTAS_DETALLES] WHERE [ID_VENTA] = @V_ID_VENTA) <> 2
   OR (SELECT COUNT(*) FROM [INVENTARIO].[MOVIMIENTOS_DETALLES] WHERE [ID_MOVIMIENTO] = (SELECT [ID_MOVIMIENTO] FROM [COMERCIAL].[VENTAS] WHERE [ID_VENTA] = @V_ID_VENTA)) <> 1
   OR NOT EXISTS (SELECT 1 FROM [FINANZAS].[MOVIMIENTOS_CUENTA] WHERE [ID_VENTA] = @V_ID_VENTA AND [TIPO_MOVIMIENTO] = N'DEBITO')
    THROW 50000, 'La venta no separó correctamente servicio, stock y cuenta corriente.', 1;

SELECT N'OK' AS [RESULTADO], @V_ID_PEDIDO AS [PEDIDO], @V_ID_VENTA AS [VENTA],
       (SELECT COUNT(*) FROM [INVENTARIO].[RESERVAS_STOCK] WHERE [ID_PEDIDO] = @V_ID_PEDIDO) AS [RESERVAS_PRODUCTO],
       (SELECT COUNT(*) FROM [COMERCIAL].[PEDIDOS_ACTIVOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO) AS [ACTIVOS_VINCULADOS];

ROLLBACK TRANSACTION;
