/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Smoke test de activos propiedad de clientes
Archivo: SMOKE_ACTIVOS_CLIENTES.sql | Versión: 1.0.0 | Fecha: 2026-08-28 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica alta, ingreso y entrega sin conservar datos de prueba.
Historial: 1.0.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Prueba transaccional inicial.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @V_ID_EMPRESA BIGINT = (SELECT TOP (1) [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO_ESTADO] = N'ACTIVO');
DECLARE @V_ID_CLIENTE BIGINT = (SELECT TOP (1) [ID_CLIENTE] FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO');
DECLARE @V_ID_PRODUCTO BIGINT = (SELECT TOP (1) [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' AND ([TIPO_TRAZABILIDAD] = N'SERIE' OR [ES_REUTILIZABLE] = 1));
DECLARE @V_ID_DEPOSITO BIGINT = (SELECT TOP (1) [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO');
DECLARE @V_ID_USUARIO BIGINT = (SELECT TOP (1) [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [CODIGO_ESTADO] = N'ACTIVO');
DECLARE @V_ID_ACTIVO BIGINT;
DECLARE @V_CODIGO_ERROR BIGINT;
DECLARE @V_MENSAJE NVARCHAR(4000);
DECLARE @V_FILAS INT;
DECLARE @V_ROW_VERSION BINARY(8);
DECLARE @V_SERIE NVARCHAR(100) = N'SMOKE-' + CONVERT(NVARCHAR(36), NEWID());

IF @V_ID_EMPRESA IS NULL OR @V_ID_CLIENTE IS NULL OR @V_ID_PRODUCTO IS NULL OR @V_ID_DEPOSITO IS NULL OR @V_ID_USUARIO IS NULL
BEGIN
    THROW 50000, 'Faltan datos maestros para ejecutar SMOKE_ACTIVOS_CLIENTES.', 1;
END;

BEGIN TRANSACTION;

EXEC [INVENTARIO].[SP_ACTIVO_CLIENTE_SAVE]
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @I_ID_CLIENTE = @V_ID_CLIENTE,
    @I_ID_PRODUCTO = @V_ID_PRODUCTO,
    @I_ID_DEPOSITO = NULL,
    @I_NUMERO_SERIE = @V_SERIE,
    @I_TIPO_ACTIVO = N'CILINDRO',
    @I_CAPACIDAD = 10,
    @I_UNIDAD_CAPACIDAD = N'kg',
    @I_CONDICION = N'OPERATIVO',
    @I_EN_CUSTODIA = 0,
    @I_OBSERVACION = N'Alta controlada por smoke test.',
    @S_ID_SESION = 1,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @O_ID_ACTIVO = @V_ID_ACTIVO OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL
BEGIN
    THROW 50000, @V_MENSAJE, 1;
END;

IF NOT EXISTS
(
    SELECT 1
    FROM [INVENTARIO].[ACTIVOS]
    WHERE [ID_ACTIVO] = @V_ID_ACTIVO
      AND [ID_CLIENTE_PROPIETARIO] = @V_ID_CLIENTE
      AND [CODIGO_ESTADO] = N'EN_CLIENTE'
      AND [ID_DEPOSITO] IS NULL
)
BEGIN
    THROW 50000, 'El activo no quedó registrado en poder del cliente.', 1;
END;

SELECT @V_ROW_VERSION = [ROW_VERSION] FROM [INVENTARIO].[ACTIVOS] WHERE [ID_ACTIVO] = @V_ID_ACTIVO;

EXEC [INVENTARIO].[SP_ACTIVO_CLIENTE_CUSTODIA]
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @I_ID_ACTIVO = @V_ID_ACTIVO,
    @I_ACCION = N'INGRESAR',
    @I_ID_DEPOSITO = @V_ID_DEPOSITO,
    @I_OBSERVACION = N'Ingreso controlado por smoke test.',
    @I_ROW_VERSION = @V_ROW_VERSION,
    @S_ID_SESION = 1,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @O_ID_ACTIVO = @V_ID_ACTIVO OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL OR NOT EXISTS
(
    SELECT 1 FROM [INVENTARIO].[ACTIVOS]
    WHERE [ID_ACTIVO] = @V_ID_ACTIVO AND [CODIGO_ESTADO] = N'DISPONIBLE' AND [ID_DEPOSITO] = @V_ID_DEPOSITO
)
BEGIN
    THROW 50000, 'No se confirmó el ingreso del activo del cliente.', 1;
END;

SELECT @V_ROW_VERSION = [ROW_VERSION] FROM [INVENTARIO].[ACTIVOS] WHERE [ID_ACTIVO] = @V_ID_ACTIVO;

EXEC [INVENTARIO].[SP_ACTIVO_CLIENTE_CUSTODIA]
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @I_ID_ACTIVO = @V_ID_ACTIVO,
    @I_ACCION = N'ENTREGAR',
    @I_ID_DEPOSITO = NULL,
    @I_OBSERVACION = N'Entrega controlada por smoke test.',
    @I_ROW_VERSION = @V_ROW_VERSION,
    @S_ID_SESION = 1,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @O_ID_ACTIVO = @V_ID_ACTIVO OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL OR NOT EXISTS
(
    SELECT 1 FROM [INVENTARIO].[ACTIVOS]
    WHERE [ID_ACTIVO] = @V_ID_ACTIVO AND [CODIGO_ESTADO] = N'EN_CLIENTE' AND [ID_DEPOSITO] IS NULL
)
BEGIN
    THROW 50000, 'No se confirmó la entrega del activo al cliente.', 1;
END;

IF (SELECT COUNT(*) FROM [INVENTARIO].[ACTIVOS_EVENTOS] WHERE [ID_ACTIVO] = @V_ID_ACTIVO) <> 3
BEGIN
    THROW 50000, 'El historial de custodia no contiene los tres eventos esperados.', 1;
END;

ROLLBACK TRANSACTION;
PRINT N'SMOKE_ACTIVOS_CLIENTES OK';
