/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Prueba transaccional de Configuración
Archivo: SMOKE_CONFIGURACION.sql | Versión: 1.0.0 | Fecha: 2026-08-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Valida concurrencia, estructura, parámetros, idioma y códigos de error sin conservar datos.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @V_ID_USUARIO BIGINT = (SELECT TOP (1) ID_USUARIO FROM SEGURIDAD.USUARIOS ORDER BY ID_USUARIO);
    DECLARE @V_ID_EMPRESA BIGINT = (SELECT TOP (1) ID_EMPRESA FROM CONFIGURACION.EMPRESAS ORDER BY ID_EMPRESA);
    DECLARE @V_ROW_VERSION BINARY(8), @V_ID BIGINT, @V_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000), @V_FILAS INT;

    IF @V_ID_USUARIO IS NULL OR @V_ID_EMPRESA IS NULL THROW 51000, N'Faltan datos base para la prueba de Configuración.', 1;

    /* Inicio: concurrencia optimista de empresa. */
    SELECT @V_ROW_VERSION = ROW_VERSION FROM CONFIGURACION.EMPRESAS WHERE ID_EMPRESA = @V_ID_EMPRESA;
    EXEC CONFIGURACION.SP_EMPRESA_UPDATE @I_ID_EMPRESA = @V_ID_EMPRESA,
        @I_RAZON_SOCIAL = N'OxiTigre QA', @I_NOMBRE_FANTASIA = N'OxiTigre QA', @I_CUIT = NULL,
        @I_EMAIL = N'qa@oxitigre.local', @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_USUARIO = @V_ID_USUARIO,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR @V_FILAS <> 1 THROW 51001, N'Falló la actualización válida de empresa.', 1;

    SET @V_ERROR = NULL; SET @V_FILAS = 0;
    EXEC CONFIGURACION.SP_EMPRESA_UPDATE @I_ID_EMPRESA = @V_ID_EMPRESA,
        @I_RAZON_SOCIAL = N'OxiTigre QA obsoleto', @I_NOMBRE_FANTASIA = NULL, @I_CUIT = NULL, @I_EMAIL = NULL,
        @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_USUARIO = @V_ID_USUARIO,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR <> 20003 OR @V_FILAS <> 0 THROW 51002, N'No se detectó la edición concurrente de empresa.', 1;
    /* Fin: concurrencia optimista de empresa. */

    /* Inicio: sucursal, unidad y protección de dependencias. */
    SET @V_ERROR = NULL; SET @V_ID = NULL;
    EXEC CONFIGURACION.SP_SUCURSAL_SAVE @I_ID_EMPRESA = @V_ID_EMPRESA, @I_CODIGO = N'QA_FASE4',
        @I_NOMBRE = N'Sucursal QA', @I_DOMICILIO = NULL, @I_LOCALIDAD = NULL, @I_PROVINCIA = NULL,
        @I_CODIGO_POSTAL = NULL, @I_CODIGO_ESTADO = N'ACTIVO', @S_ID_USUARIO = @V_ID_USUARIO,
        @O_ID_SUCURSAL = @V_ID OUTPUT, @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR @V_ID IS NULL THROW 51003, N'Falló el alta de sucursal.', 1;
    DECLARE @V_ID_SUCURSAL BIGINT = @V_ID;

    SET @V_ERROR = NULL; SET @V_ID = NULL;
    EXEC CONFIGURACION.SP_UNIDAD_OPERATIVA_SAVE @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_SUCURSAL = @V_ID_SUCURSAL,
        @I_CODIGO = N'QA_UNIDAD', @I_NOMBRE = N'Unidad QA', @I_DESCRIPCION = NULL, @I_CODIGO_ESTADO = N'ACTIVO',
        @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_UNIDAD_OPERATIVA = @V_ID OUTPUT, @O_CODIGO_ERROR = @V_ERROR OUTPUT,
        @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR @V_ID IS NULL THROW 51004, N'Falló el alta de unidad operativa.', 1;

    SELECT @V_ROW_VERSION = ROW_VERSION FROM CONFIGURACION.SUCURSALES WHERE ID_SUCURSAL = @V_ID_SUCURSAL;
    SET @V_ERROR = NULL;
    EXEC CONFIGURACION.SP_SUCURSAL_SAVE @I_ID_SUCURSAL = @V_ID_SUCURSAL, @I_ID_EMPRESA = @V_ID_EMPRESA,
        @I_CODIGO = N'QA_FASE4', @I_NOMBRE = N'Sucursal QA', @I_CODIGO_ESTADO = N'INACTIVO',
        @I_ROW_VERSION = @V_ROW_VERSION, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_SUCURSAL = @V_ID OUTPUT,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR <> 20004 THROW 51005, N'No se protegió la sucursal con unidades activas.', 1;
    /* Fin: sucursal, unidad y protección de dependencias. */

    /* Inicio: parámetros tipados y referencias secretas. */
    SET @V_ERROR = NULL; SET @V_ID = NULL;
    EXEC CONFIGURACION.SP_PARAMETRO_SISTEMA_SAVE @I_CLAVE = N'QA_ENTERO', @I_VALOR = N'12', @I_TIPO_DATO = N'ENTERO',
        @I_ES_SECRETO = 0, @I_DESCRIPCION = N'Prueba', @I_CODIGO_ESTADO = N'ACTIVO', @S_ID_USUARIO = @V_ID_USUARIO,
        @O_ID_PARAMETRO_SISTEMA = @V_ID OUTPUT, @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT,
        @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL THROW 51006, N'Falló el parámetro entero.', 1;

    SET @V_ERROR = NULL; SET @V_ID = NULL;
    EXEC CONFIGURACION.SP_PARAMETRO_SISTEMA_SAVE @I_CLAVE = N'QA_SECRETO', @I_VALOR = NULL, @I_TIPO_DATO = N'TEXTO',
        @I_ES_SECRETO = 1, @I_REFERENCIA_SECRETO = N'vault://qa/secret', @I_DESCRIPCION = N'Prueba segura',
        @I_CODIGO_ESTADO = N'ACTIVO', @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PARAMETRO_SISTEMA = @V_ID OUTPUT,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR EXISTS (SELECT 1 FROM CONFIGURACION.PARAMETROS_SISTEMA WHERE ID_PARAMETRO_SISTEMA = @V_ID AND VALOR IS NOT NULL)
        THROW 51007, N'El parámetro secreto expuso un valor.', 1;
    /* Fin: parámetros tipados y referencias secretas. */

    /* Inicio: módulo, código correlativo e idioma. */
    SET @V_ERROR = NULL; SET @V_ID = NULL;
    EXEC CONFIGURACION.SP_MODULO_SAVE @I_NUMERO_MODULO = 999, @I_CODIGO = N'QA_FASE4', @I_NOMBRE = N'Módulo QA',
        @I_DESCRIPCION = N'Prueba transaccional', @I_ORDEN = 999, @I_CODIGO_ESTADO = N'ACTIVO',
        @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_MODULO = @V_ID OUTPUT, @O_CODIGO_ERROR = @V_ERROR OUTPUT,
        @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR @V_ID IS NULL THROW 51008, N'Falló el alta de módulo.', 1;
    DECLARE @V_CODIGO_GENERADO BIGINT;

    SET @V_ERROR = NULL;
    EXEC AUDITORIA.SP_ERROR_CREATE @I_ID_MODULO = @V_ID, @I_NOMBRE = N'Error QA', @I_DESCRIPCION = N'Descripción QA',
        @I_CAUSA_PROBABLE = N'Prueba', @I_ACCION_RECOMENDADA = N'Rollback', @I_SEVERIDAD = N'ERROR',
        @S_ID_USUARIO = @V_ID_USUARIO, @O_CODIGO_GENERADO = @V_CODIGO_GENERADO OUTPUT,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR @V_CODIGO_GENERADO <> 9990001 THROW 51009, N'El código de error no respetó módulo + cuatro dígitos.', 1;

    SET @V_ERROR = NULL;
    EXEC CONFIGURACION.SP_USUARIO_PREFERENCIA_SAVE @I_CULTURA = N'en-US', @S_ID_USUARIO = @V_ID_USUARIO,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_ERROR IS NOT NULL OR NOT EXISTS (SELECT 1 FROM CONFIGURACION.USUARIOS_PREFERENCIAS WHERE ID_USUARIO = @V_ID_USUARIO AND CULTURA = N'en-US')
        THROW 51010, N'Falló la preferencia de idioma.', 1;
    /* Fin: módulo, código correlativo e idioma. */

    ROLLBACK TRANSACTION;
    SELECT N'OK - Configuración Fase 4 validada con ROLLBACK.' AS RESULTADO;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
