/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Smoke test de pedido derivado a Logística
Archivo: SMOKE_PEDIDO_LOGISTICA.sql | Versión: 1.1.0 | Fecha: 2026-08-28 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica retiro y devolución del mismo activo sin volver a escribir su identidad.
Historial: 1.0.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Confirmación parcial con selección exacta del activo operado.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

BEGIN TRANSACTION;

DECLARE @V_ID_EMPRESA BIGINT = 1,
        @V_ID_USUARIO BIGINT = 1,
        @V_ID_CLIENTE BIGINT = 1,
        @V_ID_SESION BIGINT = 1;
DECLARE @V_ID_SERVICIO BIGINT =
(
    SELECT [ID_PRODUCTO]
    FROM [INVENTARIO].[PRODUCTOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'SRV-RECARGA'
);
DECLARE @V_ID_PRODUCTO_ACTIVO BIGINT =
(
    SELECT [ID_PRODUCTO]
    FROM [INVENTARIO].[PRODUCTOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'PRD-CIL10'
);
DECLARE @V_ID_LISTA BIGINT =
(
    SELECT [ID_LISTA_PRECIO]
    FROM [COMERCIAL].[LISTAS_PRECIOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO] = N'GENERAL'
);
DECLARE @V_ID_DIRECCION BIGINT =
(
    SELECT TOP (1) [ID_DIRECCION]
    FROM [LOGISTICA].[CLIENTES_DIRECCIONES]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [ID_CLIENTE] = @V_ID_CLIENTE
      AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_DIRECCION]
);
DECLARE @V_ID_DEPOSITO BIGINT =
(
    SELECT TOP (1) [ID_DEPOSITO]
    FROM [INVENTARIO].[DEPOSITOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_DEPOSITO]
);
DECLARE @V_ID_TRANSPORTISTA BIGINT =
(
    SELECT TOP (1) [ID_TRANSPORTISTA]
    FROM [LOGISTICA].[TRANSPORTISTAS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_TRANSPORTISTA]
);
DECLARE @V_ID_VEHICULO BIGINT =
(
    SELECT TOP (1) [ID_VEHICULO]
    FROM [LOGISTICA].[VEHICULOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_VEHICULO]
);

IF @V_ID_SERVICIO IS NULL OR @V_ID_PRODUCTO_ACTIVO IS NULL
   OR @V_ID_LISTA IS NULL OR @V_ID_DIRECCION IS NULL OR @V_ID_DEPOSITO IS NULL
   OR @V_ID_TRANSPORTISTA IS NULL OR @V_ID_VEHICULO IS NULL
BEGIN
    THROW 50000, 'Faltan datos de desarrollo para probar la integración logística.', 1;
END;

-- Aísla la prueba del recorrido que el transportista esté usando en Desarrollo.
UPDATE [LOGISTICA].[HOJAS_RUTA]
SET [CODIGO_ESTADO] = N'COMPLETADA'
WHERE [ID_EMPRESA] = @V_ID_EMPRESA
  AND [ID_TRANSPORTISTA] = @V_ID_TRANSPORTISTA
  AND [CODIGO_ESTADO] IN (N'DESPACHADA', N'PAUSADA');

INSERT INTO [INVENTARIO].[ACTIVOS]
(
    [ID_EMPRESA], [ID_PRODUCTO], [ID_CLIENTE_PROPIETARIO], [CODIGO], [NUMERO_SERIE],
    [TIPO_ACTIVO], [PROPIETARIO_CODIGO], [PROPIETARIO_NOMBRE], [CONDICION_ACTUAL],
    [CODIGO_ESTADO], [ID_USUARIO_ALTA]
)
VALUES
(
    @V_ID_EMPRESA, @V_ID_PRODUCTO_ACTIVO, @V_ID_CLIENTE, N'ACT-SMOKE-LOGISTICA',
    N'SERIE-SMOKE-LOGISTICA', N'CILINDRO', N'CLI-000001', N'Cliente', N'OPERATIVO',
    N'EN_CLIENTE', @V_ID_USUARIO
);

DECLARE @V_ID_ACTIVO BIGINT = CONVERT(BIGINT, SCOPE_IDENTITY());
DECLARE @V_DETALLES NVARCHAR(MAX) = CONCAT
(
    N'[{"ProductId":', @V_ID_SERVICIO,
    N',"WarehouseId":null,"Quantity":1,"UnitPrice":12000,"DiscountRate":0,"TaxRate":0.21}]'
);
DECLARE @V_ACTIVOS NVARCHAR(MAX) = CONCAT
(
    N'[{"AssetId":', @V_ID_ACTIVO, N',"ProductLineId":', @V_ID_SERVICIO,
    N',"LinkType":"CLIENTE_SERVICIO","InboundMode":"RETIRO_OXITIGRE",',
    N'"ReturnMode":"ENTREGA_OXITIGRE","ExpectedReturnDate":null,',
    N'"Observation":"Retirar, recargar y devolver el tubo exacto del cliente."}]'
);
DECLARE @V_ID_PEDIDO BIGINT,
        @V_ID_SOLICITUD_RETIRO BIGINT,
        @V_ID_SOLICITUD_ENTREGA BIGINT,
        @V_ERROR BIGINT,
        @V_MENSAJE NVARCHAR(4000),
        @V_FILAS INT;

EXEC [COMERCIAL].[SP_PEDIDO_SAVE]
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @I_ID_CLIENTE = @V_ID_CLIENTE,
    @I_ID_LISTA_PRECIO = @V_ID_LISTA,
    @I_FECHA_PEDIDO_UTC = '2026-08-28T12:00:00',
    @I_MONEDA = N'ARS',
    @I_OBSERVACION = N'Prueba de retiro y devolución derivados.',
    @I_DETALLES_JSON = @V_DETALLES,
    @I_ACTIVOS_JSON = @V_ACTIVOS,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @O_ID_PEDIDO = @V_ID_PEDIDO OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

IF @V_ERROR IS NOT NULL
BEGIN
    THROW 50000, 'No se pudo crear el pedido de prueba logística.', 1;
END;

DECLARE @V_VERSION BINARY(8) =
(
    SELECT [ROW_VERSION]
    FROM [COMERCIAL].[PEDIDOS]
    WHERE [ID_PEDIDO] = @V_ID_PEDIDO
);

EXEC [COMERCIAL].[SP_PEDIDO_CONFIRM]
    @I_ID_PEDIDO = @V_ID_PEDIDO,
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @I_ROW_VERSION = @V_VERSION,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'SOLICITUD_CREAR',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID_CLIENTE = @V_ID_CLIENTE,
    @I_ID_DIRECCION = @V_ID_DIRECCION,
    @I_ID_PEDIDO = @V_ID_PEDIDO,
    @I_ID_DEPOSITO = @V_ID_DEPOSITO,
    @I_TIPO = N'RETIRO_RECARGA',
    @I_PRIORIDAD = N'ALTA',
    @I_FECHA = '2026-08-29',
    @I_INSTRUCCIONES = N'Retirar el tubo identificado en el pedido.',
    @I_OBSERVACION = N'Prueba automática de retiro.',
    @O_ID = @V_ID_SOLICITUD_RETIRO OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_ERROR IS NOT NULL
BEGIN
    THROW 50000, 'No se pudo derivar el retiro desde el pedido.', 1;
END;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'SOLICITUD_CREAR',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID_CLIENTE = @V_ID_CLIENTE,
    @I_ID_DIRECCION = @V_ID_DIRECCION,
    @I_ID_PEDIDO = @V_ID_PEDIDO,
    @I_TIPO = N'ENTREGA_PEDIDO',
    @I_PRIORIDAD = N'NORMAL',
    @I_FECHA = '2026-08-30',
    @I_INSTRUCCIONES = N'Devolver al cliente el mismo tubo identificado.',
    @I_OBSERVACION = N'Prueba automática de devolución.',
    @O_ID = @V_ID_SOLICITUD_ENTREGA OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_ERROR IS NOT NULL
   OR NOT EXISTS
   (
       SELECT 1
       FROM [LOGISTICA].[SOLICITUDES_ACTIVOS]
       WHERE [ID_SOLICITUD] = @V_ID_SOLICITUD_RETIRO
         AND [ID_ACTIVO] = @V_ID_ACTIVO
         AND [ROL] = N'RETIRO_CLIENTE'
   )
   OR NOT EXISTS
   (
       SELECT 1
       FROM [LOGISTICA].[SOLICITUDES_ACTIVOS]
       WHERE [ID_SOLICITUD] = @V_ID_SOLICITUD_ENTREGA
         AND [ID_ACTIVO] = @V_ID_ACTIVO
         AND [ROL] = N'DEVOLUCION'
   )
BEGIN
    THROW 50000, 'Logística no conservó el activo exacto entre retiro y devolución.', 1;
END;

-- INICIO: La confirmación física actualiza custodia y deja eventos inmutables.
DECLARE @V_ID_RUTA BIGINT,
        @V_ID_PARADA BIGINT,
        @V_VERSION_LOGISTICA BINARY(8),
        @V_RUTA_JSON NVARCHAR(MAX) = CONCAT
        (
            N'[{"Order":1,"RequestId":', @V_ID_SOLICITUD_RETIRO, N'}]'
        );

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_CREAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_FECHA = '2026-08-29', @I_TIPO = N'NORMAL', @I_TIPO_ASIGNACION = N'DIRECTA',
    @I_ID_TRANSPORTISTA = @V_ID_TRANSPORTISTA, @I_ID_VEHICULO = @V_ID_VEHICULO,
    @I_OBSERVACION = N'Ruta de prueba para retirar el activo.', @I_JSON = @V_RUTA_JSON,
    @O_ID = @V_ID_RUTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SET @V_VERSION_LOGISTICA =
(
    SELECT [ROW_VERSION] FROM [LOGISTICA].[HOJAS_RUTA] WHERE [ID_HOJA_RUTA] = @V_ID_RUTA
);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_DESPACHAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_RUTA, @I_ROW_VERSION = @V_VERSION_LOGISTICA,
    @O_ID = @V_ID_RUTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SELECT @V_ID_PARADA = [ID_PARADA], @V_VERSION_LOGISTICA = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA_PARADAS]
WHERE [ID_HOJA_RUTA] = @V_ID_RUTA;

DECLARE @V_ACTIVOS_CONFIRMADOS_JSON NVARCHAR(MAX) =
(
    SELECT CONCAT(N'[', [ID_SOLICITUD_ACTIVO], N']')
    FROM [LOGISTICA].[SOLICITUDES_ACTIVOS]
    WHERE [ID_SOLICITUD] = @V_ID_SOLICITUD_RETIRO
      AND [ID_ACTIVO] = @V_ID_ACTIVO
);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'PARADA_CONFIRMAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_PARADA, @I_RESULTADO = N'PARCIAL',
    @I_OBSERVACION = N'Activo retirado y recibido en depósito.', @I_ROW_VERSION = @V_VERSION_LOGISTICA,
    @I_JSON = @V_ACTIVOS_CONFIRMADOS_JSON,
    @O_ID = @V_ID_PARADA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_ERROR IS NOT NULL
   OR NOT EXISTS
   (
       SELECT 1 FROM [INVENTARIO].[ACTIVOS]
       WHERE [ID_ACTIVO] = @V_ID_ACTIVO
         AND [CODIGO_ESTADO] = N'DISPONIBLE'
         AND [ID_DEPOSITO] = @V_ID_DEPOSITO
   )
BEGIN
    THROW 50000, 'La parada de retiro no actualizó la custodia del activo.', 1;
END;

SET @V_RUTA_JSON = CONCAT(N'[{"Order":1,"RequestId":', @V_ID_SOLICITUD_ENTREGA, N'}]');

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_CREAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_FECHA = '2026-08-30', @I_TIPO = N'NORMAL', @I_TIPO_ASIGNACION = N'DIRECTA',
    @I_ID_TRANSPORTISTA = @V_ID_TRANSPORTISTA, @I_ID_VEHICULO = @V_ID_VEHICULO,
    @I_OBSERVACION = N'Ruta de prueba para devolver el activo.', @I_JSON = @V_RUTA_JSON,
    @O_ID = @V_ID_RUTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SET @V_VERSION_LOGISTICA =
(
    SELECT [ROW_VERSION] FROM [LOGISTICA].[HOJAS_RUTA] WHERE [ID_HOJA_RUTA] = @V_ID_RUTA
);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_DESPACHAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_RUTA, @I_ROW_VERSION = @V_VERSION_LOGISTICA,
    @O_ID = @V_ID_RUTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SELECT @V_ID_PARADA = [ID_PARADA], @V_VERSION_LOGISTICA = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA_PARADAS]
WHERE [ID_HOJA_RUTA] = @V_ID_RUTA;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'PARADA_CONFIRMAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_PARADA, @I_RESULTADO = N'ENTREGADA',
    @I_OBSERVACION = N'Activo exacto devuelto al cliente.', @I_ROW_VERSION = @V_VERSION_LOGISTICA,
    @O_ID = @V_ID_PARADA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_ERROR IS NOT NULL
   OR NOT EXISTS
   (
       SELECT 1 FROM [INVENTARIO].[ACTIVOS]
       WHERE [ID_ACTIVO] = @V_ID_ACTIVO
         AND [CODIGO_ESTADO] = N'EN_CLIENTE'
         AND [ID_DEPOSITO] IS NULL
   )
   OR (SELECT COUNT(*) FROM [INVENTARIO].[ACTIVOS_EVENTOS]
       WHERE [ID_ACTIVO] = @V_ID_ACTIVO
         AND [TIPO_EVENTO] IN (N'CLIENTE_INGRESO', N'CLIENTE_ENTREGA')) <> 2
BEGIN
    THROW 50000, 'La devolución no cerró el ciclo inmutable de custodia.', 1;
END;
-- FIN: La confirmación física actualiza custodia y deja eventos inmutables.

SELECT N'OK' AS [RESULTADO], @V_ID_PEDIDO AS [PEDIDO],
       @V_ID_SOLICITUD_RETIRO AS [RETIRO], @V_ID_SOLICITUD_ENTREGA AS [ENTREGA],
       @V_ID_ACTIVO AS [ACTIVO_TRAZADO];

ROLLBACK TRANSACTION;
