/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Smoke test de préstamo confirmado por Logística
Archivo: SMOKE_LOGISTICA_PRESTAMO.sql | Versión: 1.1.0 | Fecha: 2026-08-29 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica que la entrega de un activo propio origine préstamo, detalle y evento inmutable.
Historial: 1.0.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-29 | FABRICA | Agustin Omar Cauzi | Llegada e incidencia previas a la confirmación móvil.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

BEGIN TRANSACTION;

DECLARE @V_ID_EMPRESA BIGINT = 1,
        @V_ID_USUARIO BIGINT = 1,
        @V_ID_SESION BIGINT = 1,
        @V_ID_CLIENTE BIGINT = 1;
DECLARE @V_ID_DIRECCION BIGINT =
(
    SELECT TOP (1) [ID_DIRECCION]
    FROM [LOGISTICA].[CLIENTES_DIRECCIONES]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA
      AND [ID_CLIENTE] = @V_ID_CLIENTE
      AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_DIRECCION]
);
DECLARE @V_ID_ACTIVO BIGINT =
(
    SELECT TOP (1) [ACT].[ID_ACTIVO]
    FROM [INVENTARIO].[ACTIVOS] AS [ACT]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO]
        ON [PRO].[ID_PRODUCTO] = [ACT].[ID_PRODUCTO]
    WHERE [ACT].[ID_EMPRESA] = @V_ID_EMPRESA
      AND [ACT].[ID_CLIENTE_PROPIETARIO] IS NULL
      AND [ACT].[CODIGO_ESTADO] = N'DISPONIBLE'
      AND [PRO].[ADMITE_PRESTAMO] = 1
    ORDER BY [ACT].[ID_ACTIVO]
);
DECLARE @V_ID_TRANSPORTISTA BIGINT =
(
    SELECT TOP (1) [ID_TRANSPORTISTA]
    FROM [LOGISTICA].[TRANSPORTISTAS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_TRANSPORTISTA]
);
DECLARE @V_ID_VEHICULO BIGINT =
(
    SELECT TOP (1) [ID_VEHICULO]
    FROM [LOGISTICA].[VEHICULOS]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [ID_VEHICULO]
);

IF @V_ID_DIRECCION IS NULL OR @V_ID_ACTIVO IS NULL
   OR @V_ID_TRANSPORTISTA IS NULL OR @V_ID_VEHICULO IS NULL
BEGIN
    THROW 50000, 'Faltan datos de desarrollo para probar el préstamo logístico.', 1;
END;

-- Aísla la prueba del recorrido que el transportista esté usando en Desarrollo.
UPDATE [LOGISTICA].[HOJAS_RUTA]
SET [CODIGO_ESTADO] = N'COMPLETADA'
WHERE [ID_EMPRESA] = @V_ID_EMPRESA
  AND [ID_TRANSPORTISTA] = @V_ID_TRANSPORTISTA
  AND [CODIGO_ESTADO] IN (N'DESPACHADA', N'PAUSADA');

DECLARE @V_ACTIVOS_JSON NVARCHAR(MAX) = CONCAT
(
    N'[{"AssetId":', @V_ID_ACTIVO,
    N',"Owner":"OXITIGRE","Role":"PRESTAMO_TEMPORAL",',
    N'"SerialNumber":"PRESTAMO-SMOKE","Product":"Cilindro de préstamo",',
    N'"ContentQuantity":10,"Unit":"kg","Condition":"OPERATIVO",',
    N'"Observation":"Préstamo confirmado durante la entrega.",',
    N'"ExpectedReturnDate":"2026-09-15"}]'
);
DECLARE @V_ID_SOLICITUD BIGINT,
        @V_ID_RUTA BIGINT,
        @V_ID_PARADA BIGINT,
        @V_ERROR BIGINT,
        @V_MENSAJE NVARCHAR(4000),
        @V_FILAS INT,
        @V_VERSION BINARY(8);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'SOLICITUD_CREAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_DIRECCION = @V_ID_DIRECCION,
    @I_TIPO = N'ENTREGA_PEDIDO', @I_PRIORIDAD = N'NORMAL', @I_FECHA = '2026-08-29',
    @I_INSTRUCCIONES = N'Entregar el activo como préstamo temporal.',
    @I_OBSERVACION = N'Prueba de préstamo logístico.', @I_JSON = @V_ACTIVOS_JSON,
    @O_ID = @V_ID_SOLICITUD OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_ERROR IS NOT NULL
BEGIN
    THROW 50000, 'No se pudo crear la solicitud de préstamo.', 1;
END;

DECLARE @V_RUTA_JSON NVARCHAR(MAX) = CONCAT
(
    N'[{"Order":1,"RequestId":', @V_ID_SOLICITUD, N'}]'
);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_CREAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_FECHA = '2026-08-29', @I_TIPO = N'NORMAL', @I_TIPO_ASIGNACION = N'DIRECTA',
    @I_ID_TRANSPORTISTA = @V_ID_TRANSPORTISTA, @I_ID_VEHICULO = @V_ID_VEHICULO,
    @I_OBSERVACION = N'Ruta de préstamo de prueba.', @I_JSON = @V_RUTA_JSON,
    @O_ID = @V_ID_RUTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SET @V_VERSION =
(
    SELECT [ROW_VERSION] FROM [LOGISTICA].[HOJAS_RUTA] WHERE [ID_HOJA_RUTA] = @V_ID_RUTA
);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_DESPACHAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_RUTA, @I_ROW_VERSION = @V_VERSION,
    @O_ID = @V_ID_RUTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SELECT @V_ID_PARADA = [ID_PARADA], @V_VERSION = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA_PARADAS]
WHERE [ID_HOJA_RUTA] = @V_ID_RUTA;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'PARADA_LLEGADA', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_PARADA, @I_ROW_VERSION = @V_VERSION,
    @O_ID = @V_ID_PARADA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

SET @V_VERSION =
(
    SELECT [ROW_VERSION]
    FROM [LOGISTICA].[HOJAS_RUTA_PARADAS]
    WHERE [ID_PARADA] = @V_ID_PARADA
);

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'PARADA_INCIDENCIA', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_PARADA, @I_RESULTADO = N'DEMORA',
    @I_OBSERVACION = N'Demora operativa informada desde la aplicación.',
    @I_ROW_VERSION = @V_VERSION,
    @O_ID = @V_ID_PARADA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'PARADA_CONFIRMAR', @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION, @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_PARADA, @I_RESULTADO = N'ENTREGADA',
    @I_OBSERVACION = N'El cliente recibió el tubo prestado.', @I_ROW_VERSION = @V_VERSION,
    @O_ID = @V_ID_PARADA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;

DECLARE @V_ID_PRESTAMO BIGINT =
(
    SELECT [ID_PRESTAMO]
    FROM [LOGISTICA].[SOLICITUDES_ACTIVOS]
    WHERE [ID_SOLICITUD] = @V_ID_SOLICITUD
      AND [ID_ACTIVO] = @V_ID_ACTIVO
);

IF @V_ERROR IS NOT NULL OR @V_ID_PRESTAMO IS NULL
   OR NOT EXISTS
   (
       SELECT 1
       FROM [INVENTARIO].[PRESTAMOS] AS [PRE]
       INNER JOIN [INVENTARIO].[PRESTAMOS_DETALLES] AS [DET]
           ON [DET].[ID_PRESTAMO] = [PRE].[ID_PRESTAMO]
       WHERE [PRE].[ID_PRESTAMO] = @V_ID_PRESTAMO
         AND [PRE].[ID_CLIENTE_DESTINO] = @V_ID_CLIENTE
         AND [PRE].[FECHA_DEVOLUCION_PREVISTA] = '2026-09-15'
         AND [DET].[ID_ACTIVO] = @V_ID_ACTIVO
   )
   OR NOT EXISTS
   (
       SELECT 1 FROM [INVENTARIO].[ACTIVOS]
       WHERE [ID_ACTIVO] = @V_ID_ACTIVO AND [CODIGO_ESTADO] = N'PRESTADO'
   )
   OR NOT EXISTS
   (
       SELECT 1
       FROM [LOGISTICA].[HOJAS_RUTA_PARADAS]
       WHERE [ID_PARADA] = @V_ID_PARADA
         AND [FECHA_LLEGADA_UTC] IS NOT NULL
         AND [FECHA_SALIDA_UTC] IS NOT NULL
   )
   OR NOT EXISTS
   (
       SELECT 1
       FROM [LOGISTICA].[EVENTOS]
       WHERE [ID_PARADA] = @V_ID_PARADA
         AND [TIPO_EVENTO] = N'PARADA_INCIDENCIA'
         AND [OBSERVACION] LIKE N'DEMORA:%'
   )
BEGIN
    THROW 50000, 'La entrega no generó el préstamo formal esperado.', 1;
END;

SELECT N'OK' AS [RESULTADO], @V_ID_SOLICITUD AS [SOLICITUD],
       @V_ID_PRESTAMO AS [PRESTAMO], @V_ID_ACTIVO AS [ACTIVO];

ROLLBACK TRANSACTION;
