/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Smoke test de ofertas logísticas
Archivo: SMOKE_LOGISTICA_OFERTAS.sql | Versión: 1.0.0 | Fecha: 2026-09-01 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Verifica publicación, toma atómica, control de versión y trazabilidad.
Historial: 1.0.0 | 2026-09-01 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @V_ID_EMPRESA BIGINT = 1;
DECLARE @V_ID_USUARIO BIGINT;
DECLARE @V_ID_TRANSPORTISTA BIGINT;
DECLARE @V_ID_SESION BIGINT;
DECLARE @V_ID_VEHICULO BIGINT;
DECLARE @V_ID_SOLICITUD BIGINT;
DECLARE @V_ID_HOJA BIGINT;
DECLARE @V_FILAS INT;
DECLARE @V_CODIGO_ERROR BIGINT;
DECLARE @V_MENSAJE NVARCHAR(4000);
DECLARE @V_ROW_VERSION VARBINARY(8);
DECLARE @V_JSON NVARCHAR(MAX);

SELECT TOP (1)
       @V_ID_USUARIO = [TRA].[ID_USUARIO],
       @V_ID_TRANSPORTISTA = [TRA].[ID_TRANSPORTISTA]
FROM [LOGISTICA].[TRANSPORTISTAS] AS [TRA]
WHERE [TRA].[ID_EMPRESA] = @V_ID_EMPRESA
  AND [TRA].[CODIGO_ESTADO] = N'ACTIVO';

SELECT TOP (1)
       @V_ID_SESION = [SES].[ID_SESION]
FROM [SEGURIDAD].[SESIONES] AS [SES]
WHERE [SES].[ID_USUARIO] = @V_ID_USUARIO
ORDER BY [SES].[ID_SESION] DESC;

SELECT TOP (1)
       @V_ID_VEHICULO = [VEH].[ID_VEHICULO]
FROM [LOGISTICA].[VEHICULOS] AS [VEH]
WHERE [VEH].[ID_EMPRESA] = @V_ID_EMPRESA
  AND [VEH].[CODIGO_ESTADO] = N'ACTIVO'
ORDER BY [VEH].[ID_VEHICULO];

SELECT TOP (1)
       @V_ID_SOLICITUD = [SOL].[ID_SOLICITUD]
FROM [LOGISTICA].[SOLICITUDES] AS [SOL]
WHERE [SOL].[ID_EMPRESA] = @V_ID_EMPRESA
ORDER BY [SOL].[ID_SOLICITUD] DESC;

IF @V_ID_USUARIO IS NULL OR @V_ID_SESION IS NULL OR @V_ID_VEHICULO IS NULL OR @V_ID_SOLICITUD IS NULL
BEGIN
    THROW 51000, N'Faltan datos de desarrollo para probar ofertas logísticas.', 1;
END;

BEGIN TRANSACTION;

UPDATE [LOGISTICA].[SOLICITUDES]
SET [CODIGO_ESTADO] = N'PENDIENTE'
WHERE [ID_SOLICITUD] = @V_ID_SOLICITUD;

UPDATE [LOGISTICA].[HOJAS_RUTA]
SET [CODIGO_ESTADO] = N'COMPLETADA'
WHERE [ID_EMPRESA] = @V_ID_EMPRESA
  AND [ID_TRANSPORTISTA] = @V_ID_TRANSPORTISTA
  AND [CODIGO_ESTADO] IN (N'DESPACHADA', N'PAUSADA');

SET @V_JSON = N'[{"Order":1,"RequestId":' +
    CONVERT(NVARCHAR(30), @V_ID_SOLICITUD) + N'}]';

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_CREAR',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_FECHA = '2026-09-01',
    @I_TIPO = N'NORMAL',
    @I_TIPO_ASIGNACION = N'OFERTA',
    @I_OBSERVACION = N'Prueba transaccional de oferta.',
    @I_JSON = @V_JSON,
    @O_ID = @V_ID_HOJA OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL
BEGIN
    THROW 51000, @V_MENSAJE, 1;
END;

SELECT @V_ROW_VERSION = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA]
WHERE [ID_HOJA_RUTA] = @V_ID_HOJA;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_TOMAR_OFERTA',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_HOJA,
    @I_ID_VEHICULO = @V_ID_VEHICULO,
    @I_ROW_VERSION = @V_ROW_VERSION,
    @O_ID = @V_ID_HOJA OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL OR NOT EXISTS
(
    SELECT 1
    FROM [LOGISTICA].[HOJAS_RUTA]
    WHERE [ID_HOJA_RUTA] = @V_ID_HOJA
      AND [TIPO_ASIGNACION] = N'OFERTA'
      AND [CODIGO_ESTADO] = N'PLANIFICADA'
      AND [ID_TRANSPORTISTA] IS NOT NULL
      AND [ID_VEHICULO] = @V_ID_VEHICULO
      AND [FECHA_ASIGNACION_UTC] IS NOT NULL
)
BEGIN
    THROW 51000, N'La oferta no quedó asignada correctamente.', 1;
END;

IF NOT EXISTS
(
    SELECT 1
    FROM [LOGISTICA].[EVENTOS]
    WHERE [ID_HOJA_RUTA] = @V_ID_HOJA
      AND [TIPO_EVENTO] = N'RUTA_TOMAR_OFERTA'
)
BEGIN
    THROW 51000, N'No se conservó el evento de autoselección.', 1;
END;

SELECT @V_ROW_VERSION = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA]
WHERE [ID_HOJA_RUTA] = @V_ID_HOJA;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_DESPACHAR',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_HOJA,
    @I_ROW_VERSION = @V_ROW_VERSION,
    @O_ID = @V_ID_HOJA OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

SELECT @V_ROW_VERSION = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA]
WHERE [ID_HOJA_RUTA] = @V_ID_HOJA;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_PAUSAR',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_HOJA,
    @I_OBSERVACION = N'Control preventivo del vehículo.',
    @I_ROW_VERSION = @V_ROW_VERSION,
    @O_ID = @V_ID_HOJA OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL OR NOT EXISTS
(
    SELECT 1
    FROM [LOGISTICA].[HOJAS_RUTA]
    WHERE [ID_HOJA_RUTA] = @V_ID_HOJA
      AND [CODIGO_ESTADO] = N'PAUSADA'
)
BEGIN
    THROW 51000, N'La hoja no quedó pausada.', 1;
END;

SELECT @V_ROW_VERSION = [ROW_VERSION]
FROM [LOGISTICA].[HOJAS_RUTA]
WHERE [ID_HOJA_RUTA] = @V_ID_HOJA;

EXEC [LOGISTICA].[SP_LOGISTICA_COMMAND]
    @I_ACCION = N'RUTA_REANUDAR',
    @I_ID_EMPRESA = @V_ID_EMPRESA,
    @S_ID_SESION = @V_ID_SESION,
    @S_ID_USUARIO = @V_ID_USUARIO,
    @I_ID = @V_ID_HOJA,
    @I_OBSERVACION = N'Control finalizado sin novedades.',
    @I_ROW_VERSION = @V_ROW_VERSION,
    @O_ID = @V_ID_HOJA OUTPUT,
    @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
    @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT,
    @O_MENSAJE = @V_MENSAJE OUTPUT;

IF @V_CODIGO_ERROR IS NOT NULL OR NOT EXISTS
(
    SELECT 1
    FROM [LOGISTICA].[HOJAS_RUTA]
    WHERE [ID_HOJA_RUTA] = @V_ID_HOJA
      AND [CODIGO_ESTADO] = N'DESPACHADA'
)
BEGIN
    THROW 51000, N'La hoja no se reanudó.', 1;
END;

IF CHARINDEX(N'[ROW_VERSION] = @I_ROW_VERSION',
    OBJECT_DEFINITION(OBJECT_ID(N'LOGISTICA.SP_LOGISTICA_COMMAND'))) = 0
BEGIN
    THROW 51000, N'La toma no conserva control de concurrencia optimista.', 1;
END;

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRANSACTION;
END;

SELECT N'SMOKE_LOGISTICA_OFERTAS_OK' AS [RESULTADO];
