/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Núcleo financiero no fiscal
Archivo: FASE11_FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra medios, cajas, turnos, cobros, aplicaciones y cuenta corriente.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF OBJECT_ID(N'[FINANZAS].[MEDIOS_PAGO]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[MEDIOS_PAGO]
(
    [ID_MEDIO_PAGO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(100) NOT NULL,
    [TIPO] NVARCHAR(30) NOT NULL,
    [AFECTA_EFECTIVO] BIT NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_AFECTA_EFECTIVO] DEFAULT (0),
    [REQUIERE_REFERENCIA] BIT NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_REQUIERE_REFERENCIA] DEFAULT (0),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_MEDIOS_PAGO] PRIMARY KEY CLUSTERED ([ID_MEDIO_PAGO])
);
END;

IF OBJECT_ID(N'[FINANZAS].[CAJAS]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[CAJAS]
(
    [ID_CAJA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_SUCURSAL] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(100) NOT NULL,
    [MONEDA] CHAR(3) NOT NULL CONSTRAINT [DF_CAJAS_MONEDA] DEFAULT ('ARS'),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_CAJAS_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_CAJAS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_CAJAS] PRIMARY KEY CLUSTERED ([ID_CAJA])
);
END;

IF OBJECT_ID(N'[FINANZAS].[SESIONES_CAJA]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[SESIONES_CAJA]
(
    [ID_SESION_CAJA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CAJA] BIGINT NOT NULL,
    [ID_USUARIO_APERTURA] BIGINT NOT NULL,
    [FECHA_APERTURA_UTC] DATETIME2(3) NOT NULL,
    [IMPORTE_APERTURA] DECIMAL(19,4) NOT NULL,
    [FECHA_CIERRE_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_CIERRE] BIGINT NULL,
    [IMPORTE_ESPERADO] DECIMAL(19,4) NULL,
    [IMPORTE_CONTADO] DECIMAL(19,4) NULL,
    [DIFERENCIA] DECIMAL(19,4) NULL,
    [OBSERVACION_APERTURA] NVARCHAR(500) NULL,
    [OBSERVACION_CIERRE] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_SESIONES_CAJA_ESTADO] DEFAULT (N'ABIERTA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_SESIONES_CAJA_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_SESIONES_CAJA] PRIMARY KEY CLUSTERED ([ID_SESION_CAJA])
);
END;

IF OBJECT_ID(N'[FINANZAS].[PAGOS]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[PAGOS]
(
    [ID_PAGO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CLIENTE] BIGINT NOT NULL,
    [ID_SESION_CAJA] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [FECHA_PAGO_UTC] DATETIME2(3) NOT NULL,
    [MONEDA] CHAR(3) NOT NULL,
    [TOTAL] DECIMAL(19,4) NOT NULL,
    [OBSERVACION] NVARCHAR(500) NULL,
    [MOTIVO_REVERSION] NVARCHAR(500) NULL,
    [FECHA_REVERSION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_REVERSION] BIGINT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PAGOS_ESTADO] DEFAULT (N'CONFIRMADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PAGOS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PAGOS] PRIMARY KEY CLUSTERED ([ID_PAGO])
);
END;

IF OBJECT_ID(N'[FINANZAS].[PAGOS_MEDIOS]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[PAGOS_MEDIOS]
(
    [ID_PAGO_MEDIO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_PAGO] BIGINT NOT NULL,
    [ID_MEDIO_PAGO] BIGINT NOT NULL,
    [IMPORTE] DECIMAL(19,4) NOT NULL,
    [REFERENCIA] NVARCHAR(100) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PAGOS_MEDIOS_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PAGOS_MEDIOS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    CONSTRAINT [PK_PAGOS_MEDIOS] PRIMARY KEY CLUSTERED ([ID_PAGO_MEDIO])
);
END;

IF OBJECT_ID(N'[FINANZAS].[APLICACIONES_PAGO_VENTA]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA]
(
    [ID_APLICACION_PAGO_VENTA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_PAGO] BIGINT NOT NULL,
    [ID_VENTA] BIGINT NOT NULL,
    [IMPORTE] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_APLICACIONES_PAGO_ESTADO] DEFAULT (N'APLICADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_APLICACIONES_PAGO_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    CONSTRAINT [PK_APLICACIONES_PAGO_VENTA] PRIMARY KEY CLUSTERED ([ID_APLICACION_PAGO_VENTA])
);
END;

IF OBJECT_ID(N'[FINANZAS].[MOVIMIENTOS_CUENTA]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[MOVIMIENTOS_CUENTA]
(
    [ID_MOVIMIENTO_CUENTA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CLIENTE] BIGINT NOT NULL,
    [ID_VENTA] BIGINT NULL,
    [ID_PAGO] BIGINT NULL,
    [TIPO_MOVIMIENTO] NVARCHAR(20) NOT NULL,
    [ORIGEN] NVARCHAR(30) NOT NULL,
    [FECHA_MOVIMIENTO_UTC] DATETIME2(3) NOT NULL,
    [MONEDA] CHAR(3) NOT NULL,
    [IMPORTE] DECIMAL(19,4) NOT NULL,
    [DESCRIPCION] NVARCHAR(300) NOT NULL,
    [CORRELACION] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_MOVIMIENTOS_CUENTA_CORRELACION] DEFAULT (NEWID()),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_CUENTA_ESTADO] DEFAULT (N'CONFIRMADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_CUENTA_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    CONSTRAINT [PK_MOVIMIENTOS_CUENTA] PRIMARY KEY CLUSTERED ([ID_MOVIMIENTO_CUENTA])
);
END;
