/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_COMPRAS_GET
Archivo: SP_COMPRAS_GET.sql | Procedimiento: COMPRAS.SP_COMPRAS_GET | Tipo: QUERY
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera proveedores, productos, depósitos, órdenes y recepciones de la empresa autenticada.
Parámetros de entrada: @I_ID_EMPRESA, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_MENSAJE.
Retorno: Devuelve los conjuntos de filas definidos por sus SELECT finales.
Tablas utilizadas: COMPRAS.ORDENES_COMPRA - SELECT; COMPRAS.ORDENES_COMPRA_DETALLES - SELECT; COMPRAS.PROVEEDORES - SELECT; COMPRAS.PROVEEDORES_CONTACTOS - SELECT; COMPRAS.RECEPCIONES_COMPRA - SELECT; COMPRAS.RECEPCIONES_COMPRA_DETALLES - SELECT; CONFIGURACION.UNIDADES_MEDIDA - SELECT; INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.PRODUCTOS - SELECT.
Transacción: No abre una transacción explícita; realiza operaciones de lectura.
Auditoría: No registra auditoría explícita porque no modifica estado.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Snapshots de orden y metadatos de reversión.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMPRAS].[SP_COMPRAS_GET]
    @I_ID_EMPRESA BIGINT,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;

    SELECT [PRO].[ID_PROVEEDOR], [PRO].[CODIGO], [PRO].[RAZON_SOCIAL], [PRO].[NOMBRE_COMERCIAL], [PRO].[CUIT],
           [PRO].[CORREO], [PRO].[TELEFONO], [PRO].[CONDICION_PAGO], [PRO].[OBSERVACION],
           [PRO].[CODIGO_ESTADO], [PRO].[ROW_VERSION]
    FROM [COMPRAS].[PROVEEDORES] AS [PRO]
    WHERE [PRO].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PRO].[RAZON_SOCIAL];

    SELECT [PRO].[ID_PRODUCTO], [PRO].[CODIGO], [PRO].[NOMBRE], [UNI].[SIMBOLO],
           [PRO].[TIPO_TRAZABILIDAD], [PRO].[ES_REUTILIZABLE], [PRO].[ADMITE_PRESTAMO],
           [PRO].[REQUIERE_MANTENIMIENTO], [PRO].[ADMITE_MEDICIONES]
    FROM [INVENTARIO].[PRODUCTOS] AS [PRO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    WHERE [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [PRO].[NOMBRE];

    SELECT [DEP].[ID_DEPOSITO], [DEP].[CODIGO], [DEP].[NOMBRE]
    FROM [INVENTARIO].[DEPOSITOS] AS [DEP]
    WHERE [DEP].[ID_EMPRESA] = @I_ID_EMPRESA AND [DEP].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [DEP].[NOMBRE];

    SELECT [ORD].[ID_ORDEN_COMPRA], [ORD].[ID_PROVEEDOR], [ORD].[ID_DEPOSITO], [ORD].[CODIGO],
           [ORD].[FECHA_ORDEN_UTC], [ORD].[FECHA_ENTREGA_ESPERADA], [ORD].[PROVEEDOR_RAZON_SOCIAL] AS [PROVEEDOR],
           [ORD].[PROVEEDOR_CUIT], [ORD].[PROVEEDOR_CONDICION_PAGO],
           [DEP].[NOMBRE] AS [DEPOSITO], [ORD].[MONEDA], [ORD].[SUBTOTAL], [ORD].[TOTAL_DESCUENTO],
           [ORD].[TOTAL_IMPUESTO], [ORD].[TOTAL], [ORD].[OBSERVACION], [ORD].[CODIGO_ESTADO], [ORD].[ROW_VERSION],
           [DET].[ID_ORDEN_COMPRA_DETALLE], [DET].[ID_PRODUCTO], [PRD].[CODIGO] AS [CODIGO_PRODUCTO],
           [PRD].[NOMBRE] AS [PRODUCTO], [DET].[CANTIDAD_PEDIDA], [DET].[CANTIDAD_RECIBIDA],
           [DET].[CANTIDAD_PEDIDA] - [DET].[CANTIDAD_RECIBIDA] - [DET].[CANTIDAD_CERRADA] AS [CANTIDAD_PENDIENTE],
           [DET].[COSTO_UNITARIO], [DET].[PORCENTAJE_DESCUENTO], [DET].[PORCENTAJE_IMPUESTO],
           [DET].[SUBTOTAL_RENGLON], [DET].[IMPORTE_DESCUENTO], [DET].[IMPORTE_IMPUESTO],
           [DET].[TOTAL_RENGLON], [UNI].[SIMBOLO]
    FROM [COMPRAS].[ORDENES_COMPRA] AS [ORD]
    INNER JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [ORD].[ID_DEPOSITO]
    INNER JOIN [COMPRAS].[ORDENES_COMPRA_DETALLES] AS [DET] ON [DET].[ID_ORDEN_COMPRA] = [ORD].[ID_ORDEN_COMPRA]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRD] ON [PRD].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRD].[ID_UNIDAD_MEDIDA]
    WHERE [ORD].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [ORD].[FECHA_ORDEN_UTC] DESC, [DET].[ID_ORDEN_COMPRA_DETALLE];

    SELECT [REC].[ID_RECEPCION], [REC].[ID_ORDEN_COMPRA], [REC].[ID_MOVIMIENTO], [REC].[ID_MOVIMIENTO_REVERSION], [REC].[CODIGO],
           [REC].[FECHA_RECEPCION_UTC], [REC].[NUMERO_DOCUMENTO_PROVEEDOR] AS [NUMERO_REMITO],
           [REC].[OBSERVACION], [REC].[MOTIVO_REVERSION], [REC].[FECHA_REVERSION_UTC], [REC].[ID_USUARIO_REVERSION],
           [REC].[CODIGO_ESTADO], [REC].[ROW_VERSION], [DET].[ID_RECEPCION_DETALLE],
           [DET].[ID_ORDEN_COMPRA_DETALLE], [DET].[ID_PRODUCTO], [PRD].[CODIGO] AS [CODIGO_PRODUCTO],
           [PRD].[NOMBRE] AS [PRODUCTO], [DET].[CANTIDAD_ACEPTADA], [DET].[CANTIDAD_RECHAZADA],
           [DET].[CANTIDAD_DANADA], [DET].[MOTIVO_DIFERENCIA], [UNI].[SIMBOLO]
    FROM [COMPRAS].[RECEPCIONES_COMPRA] AS [REC]
    INNER JOIN [COMPRAS].[RECEPCIONES_COMPRA_DETALLES] AS [DET] ON [DET].[ID_RECEPCION] = [REC].[ID_RECEPCION]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRD] ON [PRD].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRD].[ID_UNIDAD_MEDIDA]
    WHERE [REC].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [REC].[FECHA_RECEPCION_UTC] DESC, [DET].[ID_RECEPCION_DETALLE];

    SELECT [CON].[ID_PROVEEDOR_CONTACTO], [CON].[ID_PROVEEDOR], [CON].[NOMBRE], [CON].[CARGO],
           [CON].[EMAIL], [CON].[TELEFONO], [CON].[ES_PRINCIPAL], [CON].[CODIGO_ESTADO], [CON].[ROW_VERSION]
    FROM [COMPRAS].[PROVEEDORES_CONTACTOS] AS [CON]
    INNER JOIN [COMPRAS].[PROVEEDORES] AS [PRO] ON [PRO].[ID_PROVEEDOR] = [CON].[ID_PROVEEDOR]
    WHERE [PRO].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PRO].[RAZON_SOCIAL], [CON].[ES_PRINCIPAL] DESC, [CON].[NOMBRE];
END;
