/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_FINANZAS_GET
Archivo: SP_FINANZAS_GET.sql | Procedimiento: FINANZAS.SP_FINANZAS_GET | Tipo: QUERY
Versión: 11.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera cajas, cobros, deuda por venta y cuenta corriente de una empresa.
Parámetros de entrada: @I_ID_EMPRESA, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_MENSAJE.
Retorno: Devuelve los conjuntos de filas definidos por sus SELECT finales.
Tablas utilizadas: COMERCIAL.CLIENTES - SELECT; COMERCIAL.VENTAS - SELECT; CONFIGURACION.SUCURSALES - SELECT; FINANZAS.APLICACIONES_PAGO_VENTA - SELECT; FINANZAS.CAJAS - SELECT; FINANZAS.MEDIOS_PAGO - SELECT; FINANZAS.MOVIMIENTOS_CUENTA - SELECT; FINANZAS.PAGOS - SELECT; FINANZAS.PAGOS_MEDIOS - SELECT; FINANZAS.SESIONES_CAJA - SELECT; SEGURIDAD.USUARIOS - SELECT.
Transacción: No abre una transacción explícita; realiza operaciones de lectura.
Auditoría: No registra auditoría explícita porque no modifica estado.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 11.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [FINANZAS].[SP_FINANZAS_GET]
    @I_ID_EMPRESA BIGINT,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;

    -- INICIO: Sucursales disponibles para asignar una caja física.
    SELECT [ID_SUCURSAL], [CODIGO], [NOMBRE]
    FROM [CONFIGURACION].[SUCURSALES]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [NOMBRE];
    -- FIN: Sucursales disponibles para asignar una caja física.

    -- INICIO: Clientes y su saldo contable actual por moneda.
    SELECT [CLI].[ID_CLIENTE], [CLI].[CODIGO],
           CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           COALESCE(SUM(CASE WHEN [MOV].[TIPO_MOVIMIENTO] = N'DEBITO' THEN [MOV].[IMPORTE] ELSE -[MOV].[IMPORTE] END), 0) AS [SALDO]
    FROM [COMERCIAL].[CLIENTES] AS [CLI]
    LEFT JOIN [FINANZAS].[MOVIMIENTOS_CUENTA] AS [MOV]
        ON [MOV].[ID_CLIENTE] = [CLI].[ID_CLIENTE]
       AND [MOV].[ID_EMPRESA] = @I_ID_EMPRESA
       AND [MOV].[MONEDA] = 'ARS'
       AND [MOV].[CODIGO_ESTADO] = N'CONFIRMADO'
    WHERE [CLI].[ID_EMPRESA] = @I_ID_EMPRESA AND [CLI].[CODIGO_ESTADO] = N'ACTIVO'
    GROUP BY [CLI].[ID_CLIENTE], [CLI].[CODIGO], [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]
    ORDER BY [CLIENTE];
    -- FIN: Clientes y su saldo contable actual por moneda.

    SELECT [ID_MEDIO_PAGO], [CODIGO], [NOMBRE], [TIPO], [AFECTA_EFECTIVO],
           [REQUIERE_REFERENCIA], [CODIGO_ESTADO], [ROW_VERSION]
    FROM [FINANZAS].[MEDIOS_PAGO]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [NOMBRE];

    SELECT [CAJ].[ID_CAJA], [CAJ].[ID_SUCURSAL], [CAJ].[CODIGO], [CAJ].[NOMBRE],
           [SUC].[NOMBRE] AS [SUCURSAL], [CAJ].[MONEDA], [CAJ].[CODIGO_ESTADO], [CAJ].[ROW_VERSION]
    FROM [FINANZAS].[CAJAS] AS [CAJ]
    INNER JOIN [CONFIGURACION].[SUCURSALES] AS [SUC] ON [SUC].[ID_SUCURSAL] = [CAJ].[ID_SUCURSAL]
    WHERE [CAJ].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [SUCURSAL], [CAJ].[NOMBRE];

    -- INICIO: Aperturas y cierres conservan los importes declarados y calculados.
    SELECT [SES].[ID_SESION_CAJA], [SES].[ID_CAJA], [CAJ].[NOMBRE] AS [CAJA],
           [SES].[ID_USUARIO_APERTURA], [USR].[NOMBRE_USUARIO] AS [USUARIO],
           [SES].[FECHA_APERTURA_UTC], [SES].[IMPORTE_APERTURA], [SES].[FECHA_CIERRE_UTC],
           [SES].[IMPORTE_ESPERADO], [SES].[IMPORTE_CONTADO], [SES].[DIFERENCIA],
           [SES].[OBSERVACION_APERTURA], [SES].[OBSERVACION_CIERRE],
           [SES].[CODIGO_ESTADO], [SES].[ROW_VERSION]
    FROM [FINANZAS].[SESIONES_CAJA] AS [SES]
    INNER JOIN [FINANZAS].[CAJAS] AS [CAJ] ON [CAJ].[ID_CAJA] = [SES].[ID_CAJA]
    INNER JOIN [SEGURIDAD].[USUARIOS] AS [USR] ON [USR].[ID_USUARIO] = [SES].[ID_USUARIO_APERTURA]
    WHERE [SES].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [SES].[FECHA_APERTURA_UTC] DESC;
    -- FIN: Aperturas y cierres conservan los importes declarados y calculados.

    -- INICIO: Ventas internas y saldo pendiente derivado de aplicaciones vigentes.
    SELECT [VEN].[ID_VENTA], [VEN].[ID_CLIENTE], [VEN].[CODIGO], [VEN].[FECHA_VENTA_UTC],
           CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [VEN].[MONEDA], [VEN].[TOTAL],
           [VEN].[TOTAL] - COALESCE(SUM(CASE WHEN [PAG].[CODIGO_ESTADO] = N'CONFIRMADO' AND [APL].[CODIGO_ESTADO] = N'APLICADA' THEN [APL].[IMPORTE] ELSE 0 END), 0) AS [SALDO_PENDIENTE],
           [VEN].[CODIGO_ESTADO]
    FROM [COMERCIAL].[VENTAS] AS [VEN]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [VEN].[ID_CLIENTE]
    LEFT JOIN [FINANZAS].[APLICACIONES_PAGO_VENTA] AS [APL] ON [APL].[ID_VENTA] = [VEN].[ID_VENTA]
    LEFT JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [APL].[ID_PAGO]
    WHERE [VEN].[ID_EMPRESA] = @I_ID_EMPRESA
    GROUP BY [VEN].[ID_VENTA], [VEN].[ID_CLIENTE], [VEN].[CODIGO], [VEN].[FECHA_VENTA_UTC],
             [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO], [VEN].[MONEDA], [VEN].[TOTAL], [VEN].[CODIGO_ESTADO]
    ORDER BY [VEN].[FECHA_VENTA_UTC] DESC;
    -- FIN: Ventas internas y saldo pendiente derivado de aplicaciones vigentes.

    SELECT [PAG].[ID_PAGO], [PAG].[ID_CLIENTE], [PAG].[ID_SESION_CAJA], [PAG].[CODIGO],
           [PAG].[FECHA_PAGO_UTC], CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [PAG].[MONEDA], [PAG].[TOTAL], [PAG].[OBSERVACION], [PAG].[MOTIVO_REVERSION],
           [PAG].[FECHA_REVERSION_UTC], [PAG].[CODIGO_ESTADO], [PAG].[ROW_VERSION]
    FROM [FINANZAS].[PAGOS] AS [PAG]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [PAG].[ID_CLIENTE]
    WHERE [PAG].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PAG].[FECHA_PAGO_UTC] DESC;

    SELECT [PM].[ID_PAGO_MEDIO], [PM].[ID_PAGO], [PM].[ID_MEDIO_PAGO], [MED].[NOMBRE] AS [MEDIO_PAGO],
           [PM].[IMPORTE], [PM].[REFERENCIA], [PM].[CODIGO_ESTADO]
    FROM [FINANZAS].[PAGOS_MEDIOS] AS [PM]
    INNER JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [PM].[ID_PAGO]
    INNER JOIN [FINANZAS].[MEDIOS_PAGO] AS [MED] ON [MED].[ID_MEDIO_PAGO] = [PM].[ID_MEDIO_PAGO]
    WHERE [PAG].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PM].[ID_PAGO], [PM].[ID_PAGO_MEDIO];

    SELECT [APL].[ID_APLICACION_PAGO_VENTA], [APL].[ID_PAGO], [APL].[ID_VENTA],
           [VEN].[CODIGO] AS [VENTA], [APL].[IMPORTE], [APL].[CODIGO_ESTADO]
    FROM [FINANZAS].[APLICACIONES_PAGO_VENTA] AS [APL]
    INNER JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [APL].[ID_PAGO]
    INNER JOIN [COMERCIAL].[VENTAS] AS [VEN] ON [VEN].[ID_VENTA] = [APL].[ID_VENTA]
    WHERE [PAG].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [APL].[ID_PAGO], [APL].[ID_APLICACION_PAGO_VENTA];

    SELECT TOP (1000) [MOV].[ID_MOVIMIENTO_CUENTA], [MOV].[ID_CLIENTE], [MOV].[ID_VENTA],
           [MOV].[ID_PAGO], [MOV].[TIPO_MOVIMIENTO], [MOV].[ORIGEN], [MOV].[FECHA_MOVIMIENTO_UTC],
           [MOV].[MONEDA], [MOV].[IMPORTE], [MOV].[DESCRIPCION], [MOV].[CORRELACION], [MOV].[CODIGO_ESTADO]
    FROM [FINANZAS].[MOVIMIENTOS_CUENTA] AS [MOV]
    WHERE [MOV].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [MOV].[FECHA_MOVIMIENTO_UTC] DESC, [MOV].[ID_MOVIMIENTO_CUENTA] DESC;
END;
