/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Tablas de Trazabilidad Fase 7
Archivo: FASE7_TRAZABILIDAD.sql | Versión: 1.0.0 | Fecha: 2026-08-24 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra lotes, activos, mediciones, genealogía, incidentes, mantenimiento y préstamos.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
CREATE TABLE [INVENTARIO].[LOTES]
(
    [ID_LOTE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_PRODUCTO] BIGINT NOT NULL,
    [ID_PROVEEDOR] BIGINT NULL,
    [ID_RECEPCION_DETALLE] BIGINT NULL,
    [CODIGO] NVARCHAR(50) NOT NULL,
    [CODIGO_LOTE_PROVEEDOR] NVARCHAR(100) NULL,
    [CANTIDAD_INICIAL] DECIMAL(19,4) NOT NULL,
    [FECHA_FABRICACION] DATE NULL,
    [FECHA_VENCIMIENTO] DATE NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOTES_CODIGO_ESTADO] DEFAULT (N'DISPONIBLE'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOTES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_LOTES] PRIMARY KEY CLUSTERED ([ID_LOTE])
);

CREATE TABLE [INVENTARIO].[LOTES_EXISTENCIAS]
(
    [ID_LOTE_EXISTENCIA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_LOTE] BIGINT NOT NULL,
    [ID_DEPOSITO] BIGINT NOT NULL,
    [ID_UBICACION] BIGINT NULL,
    [CANTIDAD] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOTES_EXISTENCIAS_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOTES_EXISTENCIAS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_LOTES_EXISTENCIAS] PRIMARY KEY CLUSTERED ([ID_LOTE_EXISTENCIA])
);

CREATE TABLE [INVENTARIO].[ACTIVOS]
(
    [ID_ACTIVO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_PRODUCTO] BIGINT NOT NULL,
    [ID_CLIENTE_PROPIETARIO] BIGINT NULL,
    [ID_DEPOSITO] BIGINT NULL,
    [ID_UBICACION] BIGINT NULL,
    [ID_RECEPCION_DETALLE] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NUMERO_SERIE] NVARCHAR(100) NOT NULL,
    [TIPO_ACTIVO] NVARCHAR(30) NOT NULL,
    [CAPACIDAD] DECIMAL(19,4) NULL,
    [UNIDAD_CAPACIDAD] NVARCHAR(20) NULL,
    [PROPIETARIO_CODIGO] NVARCHAR(30) NULL,
    [PROPIETARIO_NOMBRE] NVARCHAR(200) NULL,
    [CONDICION_ACTUAL] NVARCHAR(30) NOT NULL CONSTRAINT [DF_ACTIVOS_CONDICION_ACTUAL] DEFAULT (N'OPERATIVO'),
    [FECHA_GARANTIA_HASTA] DATE NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_ACTIVOS_CODIGO_ESTADO] DEFAULT (N'DISPONIBLE'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_ACTIVOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_ACTIVOS] PRIMARY KEY CLUSTERED ([ID_ACTIVO])
);

CREATE TABLE [INVENTARIO].[ACTIVOS_CONTENIDOS]
(
    [ID_ACTIVO_CONTENIDO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NOT NULL,
    [ID_PRODUCTO_CONTENIDO] BIGINT NOT NULL,
    [ID_LOTE] BIGINT NULL,
    [CANTIDAD_ACTUAL] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_ACTIVOS_CONTENIDOS_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_ACTIVOS_CONTENIDOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_ACTIVOS_CONTENIDOS] PRIMARY KEY CLUSTERED ([ID_ACTIVO_CONTENIDO])
);

CREATE TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES_LOTES]
(
    [ID_MOVIMIENTO_DETALLE_LOTE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_MOVIMIENTO_DETALLE] BIGINT NOT NULL,
    [ID_LOTE] BIGINT NOT NULL,
    [CANTIDAD] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_DETALLES_LOTES_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_DETALLES_LOTES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_MOVIMIENTOS_DETALLES_LOTES] PRIMARY KEY CLUSTERED ([ID_MOVIMIENTO_DETALLE_LOTE])
);

CREATE TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES_ACTIVOS]
(
    [ID_MOVIMIENTO_DETALLE_ACTIVO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_MOVIMIENTO_DETALLE] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_DETALLES_ACTIVOS_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_DETALLES_ACTIVOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_MOVIMIENTOS_DETALLES_ACTIVOS] PRIMARY KEY CLUSTERED ([ID_MOVIMIENTO_DETALLE_ACTIVO])
);

CREATE TABLE [INVENTARIO].[MEDICIONES_ACTIVOS]
(
    [ID_MEDICION_ACTIVO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NOT NULL,
    [FECHA_MEDICION_UTC] DATETIME2(3) NOT NULL,
    [TIPO_MEDICION] NVARCHAR(30) NOT NULL,
    [VALOR] DECIMAL(19,4) NOT NULL,
    [UNIDAD] NVARCHAR(20) NOT NULL,
    [METODO_MEDICION] NVARCHAR(30) NOT NULL,
    [ORIGEN_MEDICION] NVARCHAR(30) NOT NULL,
    [ES_ESTIMADA] BIT NOT NULL,
    [REFERENCIA_DISPOSITIVO] NVARCHAR(100) NULL,
    [OBSERVACION] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MEDICIONES_ACTIVOS_CODIGO_ESTADO] DEFAULT (N'CONFIRMADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MEDICIONES_ACTIVOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_MEDICIONES_ACTIVOS] PRIMARY KEY CLUSTERED ([ID_MEDICION_ACTIVO])
);

CREATE TABLE [INVENTARIO].[TRANSFORMACIONES]
(
    [ID_TRANSFORMACION] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_LOTE_ORIGEN] BIGINT NOT NULL,
    [ID_PRODUCTO_CONTENIDO] BIGINT NOT NULL,
    [ID_ACTIVO_ORIGEN] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [FECHA_TRANSFORMACION_UTC] DATETIME2(3) NOT NULL,
    [CANTIDAD_ORIGEN] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_MERMA] DECIMAL(19,4) NOT NULL,
    [METODO_MEDICION] NVARCHAR(30) NOT NULL,
    [MOTIVO_MERMA] NVARCHAR(500) NULL,
    [OBSERVACION] NVARCHAR(1000) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_TRANSFORMACIONES_CODIGO_ESTADO] DEFAULT (N'CONFIRMADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_TRANSFORMACIONES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_TRANSFORMACIONES] PRIMARY KEY CLUSTERED ([ID_TRANSFORMACION])
);

CREATE TABLE [INVENTARIO].[TRANSFORMACIONES_DETALLES]
(
    [ID_TRANSFORMACION_DETALLE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_TRANSFORMACION] BIGINT NOT NULL,
    [ID_ACTIVO_DESTINO] BIGINT NOT NULL,
    [ID_LOTE_DESTINO] BIGINT NOT NULL,
    [CANTIDAD_ANTES] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_CARGADA] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_DESPUES] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_TRANSFORMACIONES_DETALLES_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_TRANSFORMACIONES_DETALLES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_TRANSFORMACIONES_DETALLES] PRIMARY KEY CLUSTERED ([ID_TRANSFORMACION_DETALLE])
);

CREATE TABLE [INVENTARIO].[INCIDENTES]
(
    [ID_INCIDENTE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_PRODUCTO] BIGINT NOT NULL,
    [ID_DEPOSITO] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NULL,
    [ID_LOTE] BIGINT NULL,
    [ID_MOVIMIENTO] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [TIPO_INCIDENTE] NVARCHAR(30) NOT NULL,
    [FECHA_INCIDENTE_UTC] DATETIME2(3) NOT NULL,
    [CANTIDAD_ANTES] DECIMAL(19,4) NULL,
    [CANTIDAD_PERDIDA] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_DESPUES] DECIMAL(19,4) NULL,
    [ES_ESTIMADA] BIT NOT NULL,
    [METODO_MEDICION] NVARCHAR(30) NULL,
    [CAUSA] NVARCHAR(1000) NOT NULL,
    [ACCION_TOMADA] NVARCHAR(1000) NULL,
    [EVIDENCIA_REFERENCIA] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_INCIDENTES_CODIGO_ESTADO] DEFAULT (N'CONFIRMADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_INCIDENTES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_INCIDENTES] PRIMARY KEY CLUSTERED ([ID_INCIDENTE])
);

CREATE TABLE [INVENTARIO].[MANTENIMIENTOS]
(
    [ID_MANTENIMIENTO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NOT NULL,
    [ID_INCIDENTE] BIGINT NULL,
    [ID_PROVEEDOR] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [TIPO_MANTENIMIENTO] NVARCHAR(30) NOT NULL,
    [FECHA_INICIO_UTC] DATETIME2(3) NOT NULL,
    [FECHA_FIN_UTC] DATETIME2(3) NULL,
    [DESCRIPCION_TRABAJO] NVARCHAR(1000) NOT NULL,
    [RESULTADO] NVARCHAR(1000) NULL,
    [COMPONENTE_ANTERIOR] NVARCHAR(200) NULL,
    [COMPONENTE_NUEVO] NVARCHAR(200) NULL,
    [COSTO] DECIMAL(19,4) NULL,
    [CERTIFICADO_REFERENCIA] NVARCHAR(500) NULL,
    [FECHA_PROXIMA_REVISION] DATE NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MANTENIMIENTOS_CODIGO_ESTADO] DEFAULT (N'EN_CURSO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MANTENIMIENTOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_MANTENIMIENTOS] PRIMARY KEY CLUSTERED ([ID_MANTENIMIENTO])
);

CREATE TABLE [INVENTARIO].[PRESTAMOS]
(
    [ID_PRESTAMO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [TIPO_DESTINO] NVARCHAR(30) NOT NULL,
    [ID_SUCURSAL_DESTINO] BIGINT NULL,
    [ID_CLIENTE_DESTINO] BIGINT NULL,
    [DESTINO_EXTERNO] NVARCHAR(200) NULL,
    [MODALIDAD_ENTREGA] NVARCHAR(30) NOT NULL,
    [FECHA_SALIDA_UTC] DATETIME2(3) NOT NULL,
    [FECHA_DEVOLUCION_PREVISTA] DATETIME2(3) NULL,
    [FECHA_DEVOLUCION_REAL_UTC] DATETIME2(3) NULL,
    [OBSERVACION] NVARCHAR(1000) NULL,
    [EMPRESA_DESTINO_CODIGO] NVARCHAR(30) NULL,
    [ID_CORRELACION_INTEREMPRESA] UNIQUEIDENTIFIER NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PRESTAMOS_CODIGO_ESTADO] DEFAULT (N'PRESTADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PRESTAMOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PRESTAMOS] PRIMARY KEY CLUSTERED ([ID_PRESTAMO])
);

CREATE TABLE [INVENTARIO].[PRESTAMOS_DETALLES]
(
    [ID_PRESTAMO_DETALLE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_PRESTAMO] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NOT NULL,
    [ID_LOTE_SALIDA] BIGINT NULL,
    [CANTIDAD_SALIDA] DECIMAL(19,4) NULL,
    [CONDICION_SALIDA] NVARCHAR(30) NOT NULL,
    [CANTIDAD_DEVUELTA] DECIMAL(19,4) NULL,
    [CONDICION_DEVOLUCION] NVARCHAR(30) NULL,
    [OBSERVACION_DEVOLUCION] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PRESTAMOS_DETALLES_CODIGO_ESTADO] DEFAULT (N'PRESTADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PRESTAMOS_DETALLES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PRESTAMOS_DETALLES] PRIMARY KEY CLUSTERED ([ID_PRESTAMO_DETALLE])
);

CREATE TABLE [INVENTARIO].[ACTIVOS_EVENTOS]
(
    [ID_ACTIVO_EVENTO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NOT NULL,
    [TIPO_EVENTO] NVARCHAR(30) NOT NULL,
    [FECHA_EVENTO_UTC] DATETIME2(3) NOT NULL,
    [CODIGO_ESTADO_ANTES] NVARCHAR(30) NULL,
    [CODIGO_ESTADO_DESPUES] NVARCHAR(30) NOT NULL,
    [CONDICION_ANTES] NVARCHAR(30) NULL,
    [CONDICION_DESPUES] NVARCHAR(30) NOT NULL,
    [CANTIDAD_ANTES] DECIMAL(19,4) NULL,
    [CANTIDAD_DESPUES] DECIMAL(19,4) NULL,
    [ID_RECEPCION_COMPRA] BIGINT NULL,
    [ID_MEDICION_ACTIVO] BIGINT NULL,
    [ID_TRANSFORMACION] BIGINT NULL,
    [ID_INCIDENTE] BIGINT NULL,
    [ID_MANTENIMIENTO] BIGINT NULL,
    [ID_PRESTAMO] BIGINT NULL,
    [OBSERVACION] NVARCHAR(500) NULL,
    [ID_CORRELACION] UNIQUEIDENTIFIER NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_ACTIVOS_EVENTOS_CODIGO_ESTADO] DEFAULT (N'CONFIRMADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_ACTIVOS_EVENTOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_ACTIVOS_EVENTOS] PRIMARY KEY CLUSTERED ([ID_ACTIVO_EVENTO])
);
