/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: INVENTARIO.PRODUCTOS
Archivo: PRODUCTOS.sql | Versión: 1.1.0 | Fecha: 2026-08-24 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Mantiene el maestro de artículos controlados por inventario.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Modos de control por cantidad, lote o serie.
===============================================================================
*/
CREATE TABLE [INVENTARIO].[PRODUCTOS]
(
    [ID_PRODUCTO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CATEGORIA_PRODUCTO] BIGINT NOT NULL,
    [ID_UNIDAD_MEDIDA] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(200) NOT NULL,
    [DESCRIPCION] NVARCHAR(1000) NULL,
    [CODIGO_BARRAS] NVARCHAR(80) NULL,
    [TIPO_ITEM] NVARCHAR(20) NOT NULL CONSTRAINT [DF_PRODUCTOS_TIPO_ITEM] DEFAULT (N'PRODUCTO'),
    [TIPO_TRAZABILIDAD] NVARCHAR(20) NOT NULL CONSTRAINT [DF_PRODUCTOS_TIPO_TRAZABILIDAD] DEFAULT (N'NINGUNA'),
    [ES_REUTILIZABLE] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_ES_REUTILIZABLE] DEFAULT (0),
    [ADMITE_PRESTAMO] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_ADMITE_PRESTAMO] DEFAULT (0),
    [REQUIERE_MANTENIMIENTO] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_REQUIERE_MANTENIMIENTO] DEFAULT (0),
    [ADMITE_MEDICIONES] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_ADMITE_MEDICIONES] DEFAULT (0),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PRODUCTOS_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PRODUCTOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED ([ID_PRODUCTO])
);
