/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_CONFIGURACION_GET
Procedimiento: CONFIGURACION.SP_CONFIGURACION_GET
Tipo:                  QUERY
Archivo: SP_CONFIGURACION_GET.sql | Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera la configuración administrable aislada por empresa y localizada por usuario.
Parámetros de entrada: Empresa y usuario de la sesión.
Parámetros de salida: Código y mensaje controlados.
Retorno: Empresa, sucursales, unidades, teléfonos, estados, parámetros, módulos, errores y traducciones.
Tablas utilizadas: Catálogos CONFIGURACION y AUDITORIA.CATALOGO_ERRORES - READ.
Transacción: No aplica; solo lectura.
Auditoría: La DAL registra la consulta funcional.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [CONFIGURACION].[SP_CONFIGURACION_GET]
    @I_ID_EMPRESA BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;

    DECLARE @V_CULTURA NVARCHAR(10) = COALESCE
    (
        (SELECT [CULTURA] FROM [CONFIGURACION].[USUARIOS_PREFERENCIAS]
         WHERE [ID_USUARIO] = @S_ID_USUARIO AND [CODIGO_ESTADO] = N'ACTIVO'),
        N'es-AR'
    );

    SELECT [ID_EMPRESA], [CODIGO], [RAZON_SOCIAL], [NOMBRE_FANTASIA], [CUIT], [EMAIL],
           [CODIGO_ESTADO], CONVERT(VARBINARY(8), [ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[EMPRESAS]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA;
    IF @@ROWCOUNT = 0
    BEGIN
        SET @O_CODIGO_ERROR = 20002;
        EXEC [AUDITORIA].[SP_ERROR_MESSAGE_RESOLVE] @I_CODIGO_ERROR = @O_CODIGO_ERROR,
            @I_MENSAJE_PERSONALIZADO = NULL, @O_MENSAJE = @O_MENSAJE OUTPUT;
        RETURN;
    END;

    SELECT [ID_SUCURSAL], [ID_EMPRESA], [CODIGO], [NOMBRE], [DOMICILIO], [LOCALIDAD], [PROVINCIA],
           [CODIGO_POSTAL], [CODIGO_ESTADO], CONVERT(VARBINARY(8), [ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[SUCURSALES]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [NOMBRE];

    SELECT [U].[ID_UNIDAD_OPERATIVA], [U].[ID_SUCURSAL], [U].[CODIGO], [U].[NOMBRE], [U].[DESCRIPCION],
           [U].[CODIGO_ESTADO], CONVERT(VARBINARY(8), [U].[ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[UNIDADES_OPERATIVAS] AS [U]
    INNER JOIN [CONFIGURACION].[SUCURSALES] AS [S] ON [S].[ID_SUCURSAL] = [U].[ID_SUCURSAL]
    WHERE [S].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [S].[NOMBRE], [U].[NOMBRE];

    SELECT [T].[ID_TIPO_TELEFONO], [T].[CODIGO], COALESCE([TR].[NOMBRE], [T].[NOMBRE]) AS [NOMBRE],
           COALESCE([TR].[DESCRIPCION], [T].[DESCRIPCION]) AS [DESCRIPCION], [T].[CODIGO_ESTADO],
           CONVERT(VARBINARY(8), [T].[ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[TIPOS_TELEFONO] AS [T]
    LEFT JOIN [CONFIGURACION].[TRADUCCIONES_CATALOGO] AS [TR]
      ON [TR].[ENTIDAD] = N'TIPOS_TELEFONO' AND [TR].[CODIGO] = [T].[CODIGO]
     AND [TR].[CULTURA] = @V_CULTURA AND [TR].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [T].[NOMBRE];

    SELECT [E].[ID_ESTADO], [E].[ENTIDAD], [E].[CODIGO_ESTADO], COALESCE([TR].[NOMBRE], [E].[NOMBRE]) AS [NOMBRE],
           COALESCE([TR].[DESCRIPCION], [E].[DESCRIPCION]) AS [DESCRIPCION], [E].[ES_INICIAL], [E].[ES_FINAL],
           [E].[ORDEN], [E].[FECHA_VIGENCIA_HASTA_UTC], CONVERT(VARBINARY(8), [E].[ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[ESTADOS] AS [E]
    LEFT JOIN [CONFIGURACION].[TRADUCCIONES_CATALOGO] AS [TR]
      ON [TR].[ENTIDAD] = N'ESTADOS:' + [E].[ENTIDAD] AND [TR].[CODIGO] = [E].[CODIGO_ESTADO]
     AND [TR].[CULTURA] = @V_CULTURA AND [TR].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [E].[ENTIDAD], [E].[ORDEN], [E].[CODIGO_ESTADO];

    SELECT [P].[ID_PARAMETRO_SISTEMA], [P].[ID_MODULO], [M].[CODIGO] AS [CODIGO_MODULO], [P].[CLAVE],
           CASE WHEN [P].[ES_SECRETO] = 1 THEN NULL ELSE [P].[VALOR] END AS [VALOR], [P].[TIPO_DATO],
           [P].[ES_SECRETO], CONVERT(BIT, CASE WHEN NULLIF([P].[REFERENCIA_SECRETO], N'') IS NULL THEN 0 ELSE 1 END) AS [TIENE_REFERENCIA_SECRETO],
           [P].[DESCRIPCION], [P].[CODIGO_ESTADO], CONVERT(VARBINARY(8), [P].[ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[PARAMETROS_SISTEMA] AS [P]
    LEFT JOIN [CONFIGURACION].[MODULOS] AS [M] ON [M].[ID_MODULO] = [P].[ID_MODULO]
    ORDER BY [M].[ORDEN], [P].[CLAVE];

    SELECT [M].[ID_MODULO], [M].[NUMERO_MODULO], [M].[CODIGO], COALESCE([TR].[NOMBRE], [M].[NOMBRE]) AS [NOMBRE],
           COALESCE([TR].[DESCRIPCION], [M].[DESCRIPCION]) AS [DESCRIPCION], [M].[ORDEN], [M].[CODIGO_ESTADO],
           CONVERT(VARBINARY(8), [M].[ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[MODULOS] AS [M]
    LEFT JOIN [CONFIGURACION].[TRADUCCIONES_CATALOGO] AS [TR]
      ON [TR].[ENTIDAD] = N'MODULOS' AND [TR].[CODIGO] = [M].[CODIGO]
     AND [TR].[CULTURA] = @V_CULTURA AND [TR].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [M].[ORDEN], [M].[NUMERO_MODULO];

    SELECT [C].[ID_CATALOGO_ERROR], [C].[ID_MODULO], [M].[CODIGO] AS [CODIGO_MODULO], [C].[NUMERO_ERROR],
           [C].[CODIGO_ERROR], [C].[NOMBRE], [C].[DESCRIPCION], [C].[CAUSA_PROBABLE], [C].[ACCION_RECOMENDADA],
           [C].[SEVERIDAD], [C].[CODIGO_ESTADO], CONVERT(VARBINARY(8), [C].[ROW_VERSION]) AS [ROW_VERSION]
    FROM [AUDITORIA].[CATALOGO_ERRORES] AS [C]
    INNER JOIN [CONFIGURACION].[MODULOS] AS [M] ON [M].[ID_MODULO] = [C].[ID_MODULO]
    ORDER BY [M].[NUMERO_MODULO], [C].[NUMERO_ERROR];

    SELECT [ID_TRADUCCION_CATALOGO], [ENTIDAD], [CODIGO], [CULTURA], [NOMBRE], [DESCRIPCION],
           [CODIGO_ESTADO], CONVERT(VARBINARY(8), [ROW_VERSION]) AS [ROW_VERSION]
    FROM [CONFIGURACION].[TRADUCCIONES_CATALOGO]
    ORDER BY [ENTIDAD], [CODIGO], [CULTURA];

    SELECT @V_CULTURA AS [CULTURA];
END;
