/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Datos de ejemplo de Inventario
Archivo: 03_INVENTARIO_EJEMPLO.sql | Versión: 1.1.0 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Proporciona maestros, depósitos, existencias y movimientos variados para probar Inventario en Development.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Datos variados para probar grillas, alertas y depósitos.
===============================================================================
*/
DECLARE @V_ID_USUARIO BIGINT = (SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [NOMBRE_USUARIO] = N'AOCAUZI');
DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');

IF NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO] = N'UN')
    INSERT INTO [CONFIGURACION].[UNIDADES_MEDIDA] ([CODIGO], [NOMBRE], [SIMBOLO], [PERMITE_DECIMALES], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (N'UN', N'Unidad', N'un', 0, N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO] = N'M')
    INSERT INTO [CONFIGURACION].[UNIDADES_MEDIDA] ([CODIGO], [NOMBRE], [SIMBOLO], [PERMITE_DECIMALES], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (N'M', N'Metro', N'm', 1, N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [CODIGO] = N'TUBOS')
    INSERT INTO [INVENTARIO].[CATEGORIAS_PRODUCTO] ([CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (N'TUBOS', N'Tubos', N'Productos tubulares de ejemplo.', N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [CODIGO] = N'ACCESORIOS')
    INSERT INTO [INVENTARIO].[CATEGORIAS_PRODUCTO] ([CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (N'ACCESORIOS', N'Accesorios', N'Conexiones y válvulas de ejemplo.', N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CENTRAL')
    INSERT INTO [INVENTARIO].[DEPOSITOS] ([ID_EMPRESA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_EMPRESA, N'CENTRAL', N'Depósito central', N'Depósito inicial de Development.', N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'SECUNDARIO')
    INSERT INTO [INVENTARIO].[DEPOSITOS] ([ID_EMPRESA], [CODIGO], [NOMBRE], [DOMICILIO], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_EMPRESA, N'SECUNDARIO', N'Depósito secundario', N'Av. de prueba 250', N'Depósito ficticio para transferencias.', N'ACTIVO', @V_ID_USUARIO);

DECLARE @V_ID_DEPOSITO BIGINT = (SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CENTRAL');
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[UBICACIONES] WHERE [ID_DEPOSITO] = @V_ID_DEPOSITO AND [CODIGO] = N'GENERAL')
    INSERT INTO [INVENTARIO].[UBICACIONES] ([ID_DEPOSITO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_DEPOSITO, N'GENERAL', N'Ubicación general', N'Posición inicial de Development.', N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[UBICACIONES] WHERE [ID_DEPOSITO] = @V_ID_DEPOSITO AND [CODIGO] = N'PASILLO-A')
    INSERT INTO [INVENTARIO].[UBICACIONES] ([ID_DEPOSITO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_DEPOSITO, N'PASILLO-A', N'Pasillo A', N'Estantería para productos tubulares.', N'ACTIVO', @V_ID_USUARIO);
DECLARE @V_ID_DEPOSITO_SECUNDARIO BIGINT = (SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'SECUNDARIO');
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[UBICACIONES] WHERE [ID_DEPOSITO] = @V_ID_DEPOSITO_SECUNDARIO AND [CODIGO] = N'RECEPCION')
    INSERT INTO [INVENTARIO].[UBICACIONES] ([ID_DEPOSITO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_DEPOSITO_SECUNDARIO, N'RECEPCION', N'Recepción', N'Área de ingreso y control.', N'ACTIVO', @V_ID_USUARIO);

IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-TUBO-001')
BEGIN
    DECLARE @V_NUMERO_PRODUCTO BIGINT = NEXT VALUE FOR [INVENTARIO].[SEQ_PRODUCTO_CODIGO];
    INSERT INTO [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_BARRAS], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @V_ID_EMPRESA, [CAT].[ID_CATEGORIA_PRODUCTO], [UNI].[ID_UNIDAD_MEDIDA], N'PRD-' + RIGHT(N'000000' + CONVERT(NVARCHAR(20), @V_NUMERO_PRODUCTO), 6), N'Tubo de ejemplo', N'Producto ficticio para validar la pantalla.', N'DEV-TUBO-001', N'ACTIVO', @V_ID_USUARIO
    FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT] CROSS JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI]
    WHERE [CAT].[CODIGO] = N'TUBOS' AND [UNI].[CODIGO] = N'M';
END;

IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-CODO-001')
BEGIN
    DECLARE @V_NUMERO_CODO BIGINT = NEXT VALUE FOR [INVENTARIO].[SEQ_PRODUCTO_CODIGO];
    INSERT INTO [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_BARRAS], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @V_ID_EMPRESA, [CAT].[ID_CATEGORIA_PRODUCTO], [UNI].[ID_UNIDAD_MEDIDA], N'PRD-' + RIGHT(N'000000' + CONVERT(NVARCHAR(20), @V_NUMERO_CODO), 6), N'Codo galvanizado 1 pulgada', N'Accesorio ficticio vendido por unidad.', N'DEV-CODO-001', N'ACTIVO', @V_ID_USUARIO
    FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT] CROSS JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI]
    WHERE [CAT].[CODIGO] = N'ACCESORIOS' AND [UNI].[CODIGO] = N'UN';
END;
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-VALVULA-001')
BEGIN
    DECLARE @V_NUMERO_VALVULA BIGINT = NEXT VALUE FOR [INVENTARIO].[SEQ_PRODUCTO_CODIGO];
    INSERT INTO [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_BARRAS], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @V_ID_EMPRESA, [CAT].[ID_CATEGORIA_PRODUCTO], [UNI].[ID_UNIDAD_MEDIDA], N'PRD-' + RIGHT(N'000000' + CONVERT(NVARCHAR(20), @V_NUMERO_VALVULA), 6), N'Válvula esférica 1 pulgada', N'Válvula ficticia para alertas de mínimo.', N'DEV-VALVULA-001', N'ACTIVO', @V_ID_USUARIO
    FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT] CROSS JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI]
    WHERE [CAT].[CODIGO] = N'ACCESORIOS' AND [UNI].[CODIGO] = N'UN';
END;
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-PVC-040')
BEGIN
    DECLARE @V_NUMERO_PVC BIGINT = NEXT VALUE FOR [INVENTARIO].[SEQ_PRODUCTO_CODIGO];
    INSERT INTO [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_BARRAS], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @V_ID_EMPRESA, [CAT].[ID_CATEGORIA_PRODUCTO], [UNI].[ID_UNIDAD_MEDIDA], N'PRD-' + RIGHT(N'000000' + CONVERT(NVARCHAR(20), @V_NUMERO_PVC), 6), N'Caño PVC 40 mm', N'Producto ficticio vendido por metro.', N'DEV-PVC-040', N'ACTIVO', @V_ID_USUARIO
    FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] AS [CAT] CROSS JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI]
    WHERE [CAT].[CODIGO] = N'TUBOS' AND [UNI].[CODIGO] = N'M';
END;

DECLARE @V_ID_PRODUCTO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-TUBO-001');
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[MOVIMIENTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Carga inicial de Development')
BEGIN
    DECLARE @V_ID_MOVIMIENTO BIGINT, @V_CODIGO_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000), @V_FILAS INT;
    DECLARE @V_FECHA_MOVIMIENTO_UTC DATETIME2(3) = SYSUTCDATETIME();
    DECLARE @V_JSON NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"DestinationWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":25.0}]';
    EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'ENTRADA', @I_FECHA_MOVIMIENTO_UTC = @V_FECHA_MOVIMIENTO_UTC, @I_OBSERVACION = N'Carga inicial de Development', @I_DETALLES_JSON = @V_JSON, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
    IF @V_CODIGO_ERROR IS NOT NULL THROW 50000, @V_MENSAJE, 1;
END;

DECLARE @V_ID_CODO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-CODO-001');
DECLARE @V_ID_VALVULA BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-VALVULA-001');
DECLARE @V_ID_PVC BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-PVC-040');
IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[MOVIMIENTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Carga ampliada para pruebas de Development')
BEGIN
    DECLARE @V_ID_MOVIMIENTO_AMPLIADO BIGINT, @V_CODIGO_ERROR_AMPLIADO BIGINT, @V_MENSAJE_AMPLIADO NVARCHAR(4000), @V_FILAS_AMPLIADO INT;
    DECLARE @V_FECHA_AMPLIADO_UTC DATETIME2(3) = SYSUTCDATETIME();
    DECLARE @V_JSON_AMPLIADO NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_CODO) + N',"DestinationWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":40},{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_VALVULA) + N',"DestinationWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":8},{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PVC) + N',"DestinationWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":60},{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"DestinationWarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO_SECUNDARIO) + N',"Quantity":10}]';
    EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'ENTRADA', @I_FECHA_MOVIMIENTO_UTC = @V_FECHA_AMPLIADO_UTC, @I_OBSERVACION = N'Carga ampliada para pruebas de Development', @I_DETALLES_JSON = @V_JSON_AMPLIADO, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO_AMPLIADO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR_AMPLIADO OUTPUT, @O_MENSAJE = @V_MENSAJE_AMPLIADO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_AMPLIADO OUTPUT;
    IF @V_CODIGO_ERROR_AMPLIADO IS NOT NULL THROW 50000, @V_MENSAJE_AMPLIADO, 1;
END;

UPDATE [EXI]
SET [STOCK_MINIMO] = CASE [PRO].[CODIGO_BARRAS] WHEN N'DEV-TUBO-001' THEN 5 WHEN N'DEV-CODO-001' THEN 10 WHEN N'DEV-VALVULA-001' THEN 10 WHEN N'DEV-PVC-040' THEN 15 END,
    [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @V_ID_USUARIO
FROM [INVENTARIO].[EXISTENCIAS] AS [EXI]
INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [EXI].[ID_PRODUCTO]
WHERE [EXI].[ID_EMPRESA] = @V_ID_EMPRESA AND [EXI].[STOCK_MINIMO] = 0
  AND [PRO].[CODIGO_BARRAS] IN (N'DEV-TUBO-001', N'DEV-CODO-001', N'DEV-VALVULA-001', N'DEV-PVC-040');
