/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Datos de ejemplo de Pedidos y Ventas
Archivo: 04_VENTAS_EJEMPLO.sql | Versión: 1.2.0 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea listas, precios, pedidos en distintos estados y una venta interna para revisión en Development.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Listas, precios y pedidos en estados borrador, confirmado y vendido.
Historial: 1.2.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Promociones configurables y pedido demostrativo acumulado.
===============================================================================
*/
DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');
DECLARE @V_ID_USUARIO BIGINT = (SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [NOMBRE_USUARIO] = N'AOCAUZI');
DECLARE @V_ID_PRODUCTO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-TUBO-001');
DECLARE @V_ID_DEPOSITO BIGINT = (SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CENTRAL');
DECLARE @V_FECHA_DEMO_UTC DATETIME2(3) = SYSUTCDATETIME();

IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'GENERAL')
    INSERT INTO [COMERCIAL].[LISTAS_PRECIOS] ([ID_EMPRESA], [CODIGO], [NOMBRE], [MONEDA], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_EMPRESA, N'GENERAL', N'Lista general', N'ARS', N'ACTIVO', @V_ID_USUARIO);
DECLARE @V_ID_LISTA BIGINT = (SELECT [ID_LISTA_PRECIO] FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'GENERAL');
IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] WHERE [ID_LISTA_PRECIO] = @V_ID_LISTA AND [ID_PRODUCTO] = @V_ID_PRODUCTO)
    INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_LISTA, @V_ID_PRODUCTO, 100, N'ACTIVO', @V_ID_USUARIO);

DECLARE @V_ID_CODO BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-CODO-001');
DECLARE @V_ID_VALVULA BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-VALVULA-001');
DECLARE @V_ID_PVC BIGINT = (SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_BARRAS] = N'DEV-PVC-040');
IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] WHERE [ID_LISTA_PRECIO] = @V_ID_LISTA AND [ID_PRODUCTO] = @V_ID_CODO)
    INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_LISTA, @V_ID_CODO, 550, N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] WHERE [ID_LISTA_PRECIO] = @V_ID_LISTA AND [ID_PRODUCTO] = @V_ID_VALVULA)
    INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_LISTA, @V_ID_VALVULA, 2400, N'ACTIVO', @V_ID_USUARIO);
IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] WHERE [ID_LISTA_PRECIO] = @V_ID_LISTA AND [ID_PRODUCTO] = @V_ID_PVC)
    INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_LISTA, @V_ID_PVC, 180, N'ACTIVO', @V_ID_USUARIO);

IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'MAYORISTA')
    INSERT INTO [COMERCIAL].[LISTAS_PRECIOS] ([ID_EMPRESA], [CODIGO], [NOMBRE], [MONEDA], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@V_ID_EMPRESA, N'MAYORISTA', N'Lista mayorista', N'ARS', N'ACTIVO', @V_ID_USUARIO);
DECLARE @V_ID_LISTA_MAYORISTA BIGINT = (SELECT [ID_LISTA_PRECIO] FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'MAYORISTA');
INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_LISTA_MAYORISTA, [DAT].[ID_PRODUCTO], [DAT].[PRECIO], N'ACTIVO', @V_ID_USUARIO
FROM (VALUES (@V_ID_PRODUCTO, CONVERT(DECIMAL(19,4), 90)), (@V_ID_CODO, CONVERT(DECIMAL(19,4), 495)), (@V_ID_VALVULA, CONVERT(DECIMAL(19,4), 2160)), (@V_ID_PVC, CONVERT(DECIMAL(19,4), 162))) AS [DAT] ([ID_PRODUCTO], [PRECIO])
WHERE NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] AS [LPP] WHERE [LPP].[ID_LISTA_PRECIO] = @V_ID_LISTA_MAYORISTA AND [LPP].[ID_PRODUCTO] = [DAT].[ID_PRODUCTO]);

-- INICIO: Promociones de ejemplo que cubren todas las reglas admitidas.
INSERT INTO [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_PAGADA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, @V_ID_PRODUCTO, N'DEMO-2X1-TUBO', N'2x1 en tubos', N'Cada dos tubos se paga uno.', N'CANTIDAD_PAGADA', 2, 1, N'ACTIVO', @V_ID_USUARIO
WHERE @V_ID_PRODUCTO IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-2X1-TUBO');

INSERT INTO [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_PAGADA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, @V_ID_CODO, N'DEMO-4X3-CODO', N'4x3 en codos', N'Cada cuatro codos se pagan tres.', N'CANTIDAD_PAGADA', 4, 3, N'ACTIVO', @V_ID_USUARIO
WHERE @V_ID_CODO IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-4X3-CODO');

INSERT INTO [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_BONIFICADA], [PORCENTAJE_DESCUENTO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, @V_ID_VALVULA, N'DEMO-2DA-50-VALVULA', N'50% en segunda válvula', N'Cada segunda unidad recibe cincuenta por ciento.', N'PORCENTAJE_UNIDADES', 2, 1, 0.5, N'ACTIVO', @V_ID_USUARIO
WHERE @V_ID_VALVULA IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-2DA-50-VALVULA');

INSERT INTO [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_BONIFICADA], [PORCENTAJE_DESCUENTO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, @V_ID_PVC, N'DEMO-UNIDAD-50-PVC', N'50% en cada PVC', N'Cada unidad recibe cincuenta por ciento.', N'PORCENTAJE_UNIDADES', 1, 1, 0.5, N'ACTIVO', @V_ID_USUARIO
WHERE @V_ID_PVC IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-UNIDAD-50-PVC');

INSERT INTO [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [PRECIO_PAQUETE], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, @V_ID_PRODUCTO, N'DEMO-PACK3-TUBO', N'Paquete de 3 tubos a 240', N'Cada paquete completo de tres unidades cuesta 240.', N'PRECIO_PAQUETE', 3, 240, N'ACTIVO', @V_ID_USUARIO
WHERE @V_ID_PRODUCTO IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-PACK3-TUBO');
-- FIN: Promociones de ejemplo que cubren todas las reglas admitidas.

IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Pedido de ejemplo de Development')
BEGIN
    DECLARE @V_ID_CLIENTE BIGINT = (SELECT TOP (1) [ID_CLIENTE] FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [ID_CLIENTE]);
    IF @V_ID_CLIENTE IS NOT NULL AND @V_ID_PRODUCTO IS NOT NULL AND @V_ID_DEPOSITO IS NOT NULL
    BEGIN
        DECLARE @V_JSON NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":2,"UnitPrice":100,"DiscountRate":0,"TaxRate":0.21}]';
        DECLARE @V_ID_PEDIDO BIGINT, @V_CODIGO_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000), @V_FILAS INT;
        DECLARE @V_FECHA_PEDIDO_UTC DATETIME2(3) = SYSUTCDATETIME();
        EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_PEDIDO_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'Pedido de ejemplo de Development', @I_DETALLES_JSON = @V_JSON, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT;
        IF @V_CODIGO_ERROR IS NOT NULL THROW 50000, @V_MENSAJE, 1;
    END;
END;

-- INICIO: Dos entradas del mismo producto demuestran que el 2x1 se acumula en un único renglón.
IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Pedido promocional acumulado de Development')
BEGIN
    DECLARE @V_ID_CLIENTE_PROMO BIGINT = (SELECT TOP (1) [ID_CLIENTE] FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [ID_CLIENTE]);
    DECLARE @V_ID_PROMOCION_2X1 BIGINT = (SELECT [ID_PROMOCION] FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'DEMO-2X1-TUBO');
    IF @V_ID_CLIENTE_PROMO IS NOT NULL AND @V_ID_PROMOCION_2X1 IS NOT NULL
    BEGIN
        DECLARE @V_JSON_PROMO NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_ID_PROMOCION_2X1) + N',"Quantity":1,"UnitPrice":100,"DiscountRate":0,"TaxRate":0.21},{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_PRODUCTO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"PromotionId":' + CONVERT(NVARCHAR(20), @V_ID_PROMOCION_2X1) + N',"Quantity":1,"UnitPrice":100,"DiscountRate":0,"TaxRate":0.21}]';
        DECLARE @V_ID_PEDIDO_PROMO BIGINT, @V_ERROR_PROMO BIGINT, @V_MENSAJE_PROMO NVARCHAR(4000), @V_FILAS_PROMO INT;
        EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE_PROMO, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_DEMO_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'Pedido promocional acumulado de Development', @I_DETALLES_JSON = @V_JSON_PROMO, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_PROMO OUTPUT, @O_CODIGO_ERROR = @V_ERROR_PROMO OUTPUT, @O_MENSAJE = @V_MENSAJE_PROMO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_PROMO OUTPUT;
        IF @V_ERROR_PROMO IS NOT NULL THROW 50000, @V_MENSAJE_PROMO, 1;
    END;
END;
-- FIN: Dos entradas del mismo producto demuestran que el 2x1 se acumula en un único renglón.

DECLARE @V_ID_CLIENTE_DEMO BIGINT = (SELECT TOP (1) [ID_CLIENTE] FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [ID_CLIENTE]);

-- INICIO: Pedido confirmado que permite probar reservas y generación manual de venta.
DECLARE @V_ID_PEDIDO_CONFIRMADO BIGINT = (SELECT [ID_PEDIDO] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Pedido confirmado para probar reservas');
IF @V_ID_PEDIDO_CONFIRMADO IS NULL AND @V_ID_CLIENTE_DEMO IS NOT NULL
BEGIN
    DECLARE @V_JSON_CONFIRMADO NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_VALVULA) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":2,"UnitPrice":2400,"DiscountRate":0.05,"TaxRate":0.21}]';
    DECLARE @V_ERROR_CONFIRMADO BIGINT, @V_MENSAJE_CONFIRMADO NVARCHAR(4000), @V_FILAS_CONFIRMADO INT;
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE_DEMO, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_DEMO_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'Pedido confirmado para probar reservas', @I_DETALLES_JSON = @V_JSON_CONFIRMADO, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_CONFIRMADO OUTPUT, @O_CODIGO_ERROR = @V_ERROR_CONFIRMADO OUTPUT, @O_MENSAJE = @V_MENSAJE_CONFIRMADO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_CONFIRMADO OUTPUT;
    IF @V_ERROR_CONFIRMADO IS NOT NULL THROW 50000, @V_MENSAJE_CONFIRMADO, 1;
END;
IF EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_CONFIRMADO AND [CODIGO_ESTADO] = N'BORRADOR')
BEGIN
    DECLARE @V_VERSION_CONFIRMADO BINARY(8) = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_CONFIRMADO);
    DECLARE @V_ERROR_RESERVA BIGINT, @V_MENSAJE_RESERVA NVARCHAR(4000), @V_FILAS_RESERVA INT;
    EXEC [COMERCIAL].[SP_PEDIDO_CONFIRM] @I_ID_PEDIDO = @V_ID_PEDIDO_CONFIRMADO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ROW_VERSION = @V_VERSION_CONFIRMADO, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_CODIGO_ERROR = @V_ERROR_RESERVA OUTPUT, @O_MENSAJE = @V_MENSAJE_RESERVA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_RESERVA OUTPUT;
    IF @V_ERROR_RESERVA IS NOT NULL THROW 50000, @V_MENSAJE_RESERVA, 1;
END;
-- FIN: Pedido confirmado que permite probar reservas y generación manual de venta.

-- INICIO: Venta interna completa que alimenta la grilla de ventas y el movimiento de salida.
DECLARE @V_ID_PEDIDO_VENDIDO BIGINT = (SELECT [ID_PEDIDO] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Venta interna demostrativa de Development');
IF @V_ID_PEDIDO_VENDIDO IS NULL AND @V_ID_CLIENTE_DEMO IS NOT NULL
BEGIN
    DECLARE @V_JSON_VENDIDO NVARCHAR(MAX) = N'[{"ProductId":' + CONVERT(NVARCHAR(20), @V_ID_CODO) + N',"WarehouseId":' + CONVERT(NVARCHAR(20), @V_ID_DEPOSITO) + N',"Quantity":3,"UnitPrice":550,"DiscountRate":0.10,"TaxRate":0.21}]';
    DECLARE @V_ERROR_VENDIDO BIGINT, @V_MENSAJE_VENDIDO NVARCHAR(4000), @V_FILAS_VENDIDO INT;
    EXEC [COMERCIAL].[SP_PEDIDO_SAVE] @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ID_CLIENTE = @V_ID_CLIENTE_DEMO, @I_ID_LISTA_PRECIO = @V_ID_LISTA, @I_FECHA_PEDIDO_UTC = @V_FECHA_DEMO_UTC, @I_MONEDA = N'ARS', @I_OBSERVACION = N'Venta interna demostrativa de Development', @I_DETALLES_JSON = @V_JSON_VENDIDO, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_PEDIDO = @V_ID_PEDIDO_VENDIDO OUTPUT, @O_CODIGO_ERROR = @V_ERROR_VENDIDO OUTPUT, @O_MENSAJE = @V_MENSAJE_VENDIDO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_VENDIDO OUTPUT;
    IF @V_ERROR_VENDIDO IS NOT NULL THROW 50000, @V_MENSAJE_VENDIDO, 1;
END;
IF EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_VENDIDO AND [CODIGO_ESTADO] = N'BORRADOR')
BEGIN
    DECLARE @V_VERSION_VENDIDO BINARY(8) = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_VENDIDO);
    DECLARE @V_ERROR_CONFIRMAR_VENDIDO BIGINT, @V_MENSAJE_CONFIRMAR_VENDIDO NVARCHAR(4000), @V_FILAS_CONFIRMAR_VENDIDO INT;
    EXEC [COMERCIAL].[SP_PEDIDO_CONFIRM] @I_ID_PEDIDO = @V_ID_PEDIDO_VENDIDO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_ROW_VERSION = @V_VERSION_VENDIDO, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_CODIGO_ERROR = @V_ERROR_CONFIRMAR_VENDIDO OUTPUT, @O_MENSAJE = @V_MENSAJE_CONFIRMAR_VENDIDO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_CONFIRMAR_VENDIDO OUTPUT;
    IF @V_ERROR_CONFIRMAR_VENDIDO IS NOT NULL THROW 50000, @V_MENSAJE_CONFIRMAR_VENDIDO, 1;
END;
IF EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_VENDIDO AND [CODIGO_ESTADO] = N'CONFIRMADO')
BEGIN
    DECLARE @V_VERSION_VENTA BINARY(8) = (SELECT [ROW_VERSION] FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @V_ID_PEDIDO_VENDIDO);
    DECLARE @V_ID_VENTA_DEMO BIGINT, @V_ERROR_VENTA BIGINT, @V_MENSAJE_VENTA NVARCHAR(4000), @V_FILAS_VENTA INT;
    EXEC [COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO] @I_ID_PEDIDO = @V_ID_PEDIDO_VENDIDO, @I_ID_EMPRESA = @V_ID_EMPRESA, @I_FECHA_VENTA_UTC = @V_FECHA_DEMO_UTC, @I_ROW_VERSION = @V_VERSION_VENTA, @S_ID_SESION = 1, @S_ID_USUARIO = @V_ID_USUARIO, @O_ID_VENTA = @V_ID_VENTA_DEMO OUTPUT, @O_CODIGO_ERROR = @V_ERROR_VENTA OUTPUT, @O_MENSAJE = @V_MENSAJE_VENTA OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_VENTA OUTPUT;
    IF @V_ERROR_VENTA IS NOT NULL THROW 50000, @V_MENSAJE_VENTA, 1;
END;
-- FIN: Venta interna completa que alimenta la grilla de ventas y el movimiento de salida.
