/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Datos de ejemplo Fase 7
Archivo: 05_COMPRAS_TRAZABILIDAD_EJEMPLO.sql | Versión: 1.0.0 | Fecha: 2026-08-24 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Proporciona proveedores, compras parciales, lotes, cilindros, incidentes, mantenimiento y préstamos para pruebas.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
DECLARE @V_EMPRESA BIGINT=(SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO]=N'OXITIGRE');
DECLARE @V_USUARIO BIGINT=(SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [NOMBRE_USUARIO]=N'AOCAUZI');
DECLARE @V_DEPOSITO BIGINT=(SELECT [ID_DEPOSITO] FROM [INVENTARIO].[DEPOSITOS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [CODIGO]=N'CENTRAL');
IF NOT EXISTS(SELECT 1 FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO]=N'KG') INSERT [CONFIGURACION].[UNIDADES_MEDIDA]([CODIGO],[NOMBRE],[SIMBOLO],[PERMITE_DECIMALES],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(N'KG',N'Kilogramo',N'kg',1,N'ACTIVO',@V_USUARIO);
DECLARE @V_UNIDAD_KG BIGINT=(SELECT [ID_UNIDAD_MEDIDA] FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO]=N'KG');
DECLARE @V_UNIDAD_UN BIGINT=(SELECT [ID_UNIDAD_MEDIDA] FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO]=N'UN');
DECLARE @V_CATEGORIA BIGINT=(SELECT [ID_CATEGORIA_PRODUCTO] FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [CODIGO]=N'TUBOS');
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [CODIGO_BARRAS]=N'DEV-CO2-GRANEL') INSERT [INVENTARIO].[PRODUCTOS]([ID_EMPRESA],[ID_CATEGORIA_PRODUCTO],[ID_UNIDAD_MEDIDA],[CODIGO],[NOMBRE],[DESCRIPCION],[CODIGO_BARRAS],[TIPO_TRAZABILIDAD],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CATEGORIA,@V_UNIDAD_KG,N'PRD-CO2',N'CO2 a granel',N'Contenido trazable por lote.',N'DEV-CO2-GRANEL',N'LOTE',N'ACTIVO',@V_USUARIO);
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [CODIGO_BARRAS]=N'DEV-CILINDRO-10') INSERT [INVENTARIO].[PRODUCTOS]([ID_EMPRESA],[ID_CATEGORIA_PRODUCTO],[ID_UNIDAD_MEDIDA],[CODIGO],[NOMBRE],[DESCRIPCION],[CODIGO_BARRAS],[TIPO_TRAZABILIDAD],[ES_REUTILIZABLE],[ADMITE_PRESTAMO],[REQUIERE_MANTENIMIENTO],[ADMITE_MEDICIONES],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CATEGORIA,@V_UNIDAD_UN,N'PRD-CIL10',N'Cilindro CO2 10 kg',N'Envase reutilizable individual.',N'DEV-CILINDRO-10',N'SERIE',1,1,1,1,N'ACTIVO',@V_USUARIO);
DECLARE @V_CO2 BIGINT=(SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [CODIGO_BARRAS]=N'DEV-CO2-GRANEL');
DECLARE @V_CIL BIGINT=(SELECT [ID_PRODUCTO] FROM [INVENTARIO].[PRODUCTOS] WHERE [CODIGO_BARRAS]=N'DEV-CILINDRO-10');
UPDATE [INVENTARIO].[PRODUCTOS] SET [TIPO_TRAZABILIDAD]=N'SERIE',[ES_REUTILIZABLE]=1,[ADMITE_PRESTAMO]=1,[REQUIERE_MANTENIMIENTO]=1,[ADMITE_MEDICIONES]=1 WHERE [ID_PRODUCTO]=@V_CIL;
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [ID_PRODUCTO]=@V_CO2 AND [ID_DEPOSITO]=@V_DEPOSITO) INSERT [INVENTARIO].[EXISTENCIAS]([ID_EMPRESA],[ID_PRODUCTO],[ID_DEPOSITO],[CANTIDAD],[STOCK_MINIMO],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CO2,@V_DEPOSITO,1000,150,N'ACTIVO',@V_USUARIO);
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[EXISTENCIAS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [ID_PRODUCTO]=@V_CIL AND [ID_DEPOSITO]=@V_DEPOSITO) INSERT [INVENTARIO].[EXISTENCIAS]([ID_EMPRESA],[ID_PRODUCTO],[ID_DEPOSITO],[CANTIDAD],[STOCK_MINIMO],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CIL,@V_DEPOSITO,2,1,N'ACTIVO',@V_USUARIO);
UPDATE [COMPRAS].[PROVEEDORES] SET [CUIT]=N'30-70000001-6' WHERE [ID_EMPRESA]=@V_EMPRESA AND [CODIGO]=N'PROV-000001' AND [CUIT]=N'30-70000001-5';
IF NOT EXISTS(SELECT 1 FROM [COMPRAS].[PROVEEDORES] WHERE [ID_EMPRESA]=@V_EMPRESA AND [CUIT]=N'30-70000001-6') BEGIN INSERT [COMPRAS].[PROVEEDORES]([ID_EMPRESA],[CODIGO],[RAZON_SOCIAL],[NOMBRE_COMERCIAL],[CUIT],[CORREO],[TELEFONO],[CONDICION_PAGO],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,N'PROV-000001',N'Gases Industriales Demo SA',N'Gases Demo',N'30-70000001-6',N'ventas@gases.demo',N'11-5555-0101',N'Cuenta corriente 30 días',N'ACTIVO',@V_USUARIO);DECLARE @V_PROV_NUEVO BIGINT=SCOPE_IDENTITY();INSERT [COMPRAS].[PROVEEDORES_CONTACTOS]([ID_PROVEEDOR],[NOMBRE],[CARGO],[EMAIL],[TELEFONO],[ES_PRINCIPAL],[CODIGO_ESTADO],[ID_USUARIO_ALTA])VALUES(@V_PROV_NUEVO,N'Laura Gómez',N'Ventas',N'laura@gases.demo',N'11-5555-0102',1,N'ACTIVO',@V_USUARIO);END;
DECLARE @V_PROVEEDOR BIGINT =
(
    SELECT [ID_PROVEEDOR]
    FROM [COMPRAS].[PROVEEDORES]
    WHERE [ID_EMPRESA] = @V_EMPRESA
      AND [CUIT] = N'30-70000001-6'
);

IF NOT EXISTS
(
    SELECT 1
    FROM [COMPRAS].[ORDENES_COMPRA]
    WHERE [ID_EMPRESA] = @V_EMPRESA
      AND [CODIGO] = N'OC-DEMO-001'
)
BEGIN
    INSERT INTO [COMPRAS].[ORDENES_COMPRA]
    (
        [ID_EMPRESA], [ID_PROVEEDOR], [PROVEEDOR_RAZON_SOCIAL], [PROVEEDOR_CUIT],
        [PROVEEDOR_CONDICION_PAGO], [ID_DEPOSITO], [CODIGO], [FECHA_ORDEN_UTC],
        [FECHA_ENTREGA_ESPERADA], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO],
        [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [FECHA_APROBACION_UTC],
        [ID_USUARIO_APROBACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]
    )
    SELECT
        @V_EMPRESA, [ID_PROVEEDOR], [RAZON_SOCIAL], [CUIT], [CONDICION_PAGO],
        @V_DEPOSITO, N'OC-DEMO-001', DATEADD(DAY, -5, SYSUTCDATETIME()),
        CONVERT(DATE, DATEADD(DAY, 2, SYSUTCDATETIME())), N'ARS', 250000, 0,
        52500, 302500, N'Orden parcial para probar faltantes.',
        DATEADD(DAY, -4, SYSUTCDATETIME()), @V_USUARIO, N'RECIBIDA_PARCIAL', @V_USUARIO
    FROM [COMPRAS].[PROVEEDORES]
    WHERE [ID_PROVEEDOR] = @V_PROVEEDOR;

    DECLARE @V_OC BIGINT = SCOPE_IDENTITY();

    INSERT INTO [COMPRAS].[ORDENES_COMPRA_DETALLES]
    (
        [ID_ORDEN_COMPRA], [ID_PRODUCTO], [CANTIDAD_PEDIDA], [CANTIDAD_RECIBIDA],
        [CANTIDAD_CERRADA], [COSTO_UNITARIO], [PORCENTAJE_DESCUENTO],
        [PORCENTAJE_IMPUESTO], [SUBTOTAL_RENGLON], [IMPORTE_DESCUENTO],
        [IMPORTE_IMPUESTO], [TOTAL_RENGLON], [CODIGO_ESTADO], [ID_USUARIO_ALTA]
    )
    VALUES
    (
        @V_OC, @V_CO2, 1000, 800, 0, 250, 0, .21, 250000, 0, 52500, 302500,
        N'PENDIENTE', @V_USUARIO
    );

    DECLARE @V_LINEA BIGINT = SCOPE_IDENTITY();

    INSERT INTO [COMPRAS].[RECEPCIONES_COMPRA]
    (
        [ID_EMPRESA], [ID_ORDEN_COMPRA], [CODIGO], [FECHA_RECEPCION_UTC],
        [NUMERO_DOCUMENTO_PROVEEDOR], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]
    )
    VALUES
    (
        @V_EMPRESA, @V_OC, N'RC-DEMO-001', DATEADD(DAY, -2, SYSUTCDATETIME()),
        N'REM-00081', N'Llegaron 800 kg; quedan 200 kg pendientes.', N'CONFIRMADA', @V_USUARIO
    );

    INSERT INTO [COMPRAS].[RECEPCIONES_COMPRA_DETALLES]
    (
        [ID_RECEPCION], [ID_ORDEN_COMPRA_DETALLE], [ID_PRODUCTO], [CANTIDAD_ACEPTADA],
        [CANTIDAD_RECHAZADA], [CANTIDAD_DANADA], [MOTIVO_DIFERENCIA],
        [CODIGO_ESTADO], [ID_USUARIO_ALTA]
    )
    VALUES
    (
        SCOPE_IDENTITY(), @V_LINEA, @V_CO2, 800, 0, 0,
        N'Proveedor entregó parcialmente.', N'ACTIVO', @V_USUARIO
    );
END;
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[LOTES] WHERE [ID_EMPRESA]=@V_EMPRESA AND [CODIGO]=N'LOT-CO2-2026-001') BEGIN INSERT [INVENTARIO].[LOTES]([ID_EMPRESA],[ID_PRODUCTO],[ID_PROVEEDOR],[CODIGO],[CODIGO_LOTE_PROVEEDOR],[CANTIDAD_INICIAL],[FECHA_FABRICACION],[FECHA_VENCIMIENTO],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CO2,@V_PROVEEDOR,N'LOT-CO2-2026-001',N'FAB-CO2-081',1000,DATEADD(DAY,-30,CONVERT(DATE,SYSUTCDATETIME())),DATEADD(YEAR,2,CONVERT(DATE,SYSUTCDATETIME())),N'DISPONIBLE',@V_USUARIO);DECLARE @V_LOTE_N BIGINT=SCOPE_IDENTITY();INSERT [INVENTARIO].[LOTES_EXISTENCIAS]([ID_EMPRESA],[ID_LOTE],[ID_DEPOSITO],[CANTIDAD],[CODIGO_ESTADO],[ID_USUARIO_ALTA])VALUES(@V_EMPRESA,@V_LOTE_N,@V_DEPOSITO,985,N'ACTIVO',@V_USUARIO);END;
DECLARE @V_LOTE BIGINT=(SELECT [ID_LOTE] FROM [INVENTARIO].[LOTES] WHERE [ID_EMPRESA]=@V_EMPRESA AND [CODIGO]=N'LOT-CO2-2026-001');
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[ACTIVOS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [NUMERO_SERIE]=N'CIL-000101') INSERT [INVENTARIO].[ACTIVOS]([ID_EMPRESA],[ID_PRODUCTO],[ID_DEPOSITO],[CODIGO],[NUMERO_SERIE],[TIPO_ACTIVO],[CAPACIDAD],[UNIDAD_CAPACIDAD],[PROPIETARIO_CODIGO],[PROPIETARIO_NOMBRE],[CONDICION_ACTUAL],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CIL,@V_DEPOSITO,N'ACT-000101',N'CIL-000101',N'ENVASE',10,N'kg',N'OXITIGRE',N'OxiTigre',N'OPERATIVO',N'DISPONIBLE',@V_USUARIO);
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[ACTIVOS] WHERE [ID_EMPRESA]=@V_EMPRESA AND [NUMERO_SERIE]=N'CIL-000102') INSERT [INVENTARIO].[ACTIVOS]([ID_EMPRESA],[ID_PRODUCTO],[ID_DEPOSITO],[CODIGO],[NUMERO_SERIE],[TIPO_ACTIVO],[CAPACIDAD],[UNIDAD_CAPACIDAD],[PROPIETARIO_CODIGO],[PROPIETARIO_NOMBRE],[CONDICION_ACTUAL],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CIL,@V_DEPOSITO,N'ACT-000102',N'CIL-000102',N'ENVASE',10,N'kg',N'OXITIGRE',N'OxiTigre',N'EN_MANTENIMIENTO',N'BLOQUEADO',@V_USUARIO);
DECLARE @V_A1 BIGINT=(SELECT [ID_ACTIVO] FROM [INVENTARIO].[ACTIVOS] WHERE [NUMERO_SERIE]=N'CIL-000101'),@V_A2 BIGINT=(SELECT [ID_ACTIVO] FROM [INVENTARIO].[ACTIVOS] WHERE [NUMERO_SERIE]=N'CIL-000102');
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[ACTIVOS_CONTENIDOS] WHERE [ID_ACTIVO]=@V_A1) INSERT [INVENTARIO].[ACTIVOS_CONTENIDOS]([ID_EMPRESA],[ID_ACTIVO],[ID_PRODUCTO_CONTENIDO],[ID_LOTE],[CANTIDAD_ACTUAL],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_A1,@V_CO2,@V_LOTE,10,N'ACTIVO',@V_USUARIO);
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[ACTIVOS_CONTENIDOS] WHERE [ID_ACTIVO]=@V_A2) INSERT [INVENTARIO].[ACTIVOS_CONTENIDOS]([ID_EMPRESA],[ID_ACTIVO],[ID_PRODUCTO_CONTENIDO],[ID_LOTE],[CANTIDAD_ACTUAL],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_A2,@V_CO2,@V_LOTE,5,N'ACTIVO',@V_USUARIO);
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[MEDICIONES_ACTIVOS] WHERE [ID_ACTIVO]=@V_A1) INSERT [INVENTARIO].[MEDICIONES_ACTIVOS]([ID_EMPRESA],[ID_ACTIVO],[FECHA_MEDICION_UTC],[TIPO_MEDICION],[VALOR],[UNIDAD],[METODO_MEDICION],[ORIGEN_MEDICION],[ES_ESTIMADA],[OBSERVACION],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_A1,DATEADD(HOUR,-6,SYSUTCDATETIME()),N'CONTENIDO',10,N'kg',N'PESAJE',N'MANUAL',0,N'Pesaje confirmado de ejemplo.',N'CONFIRMADA',@V_USUARIO);
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[INCIDENTES] WHERE [ID_ACTIVO]=@V_A2) BEGIN INSERT [INVENTARIO].[INCIDENTES]([ID_EMPRESA],[ID_PRODUCTO],[ID_DEPOSITO],[ID_ACTIVO],[ID_LOTE],[CODIGO],[TIPO_INCIDENTE],[FECHA_INCIDENTE_UTC],[CANTIDAD_ANTES],[CANTIDAD_PERDIDA],[CANTIDAD_DESPUES],[ES_ESTIMADA],[METODO_MEDICION],[CAUSA],[ACCION_TOMADA],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_CO2,@V_DEPOSITO,@V_A2,@V_LOTE,N'INC-DEMO-001',N'VALVULA_DEFECTUOSA',DATEADD(DAY,-1,SYSUTCDATETIME()),5.5,.5,5,1,N'ESTIMADO',N'Pérdida detectada en la válvula.',N'Se aisló el cilindro.',N'CONFIRMADO',@V_USUARIO);DECLARE @V_INC BIGINT=SCOPE_IDENTITY();INSERT [INVENTARIO].[MANTENIMIENTOS]([ID_EMPRESA],[ID_ACTIVO],[ID_INCIDENTE],[ID_PROVEEDOR],[CODIGO],[TIPO_MANTENIMIENTO],[FECHA_INICIO_UTC],[DESCRIPCION_TRABAJO],[COSTO],[FECHA_PROXIMA_REVISION],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_A2,@V_INC,@V_PROVEEDOR,N'MAN-DEMO-001',N'CORRECTIVO',DATEADD(HOUR,-20,SYSUTCDATETIME()),N'Reemplazo de válvula y prueba hidráulica.',45000,DATEADD(YEAR,1,CONVERT(DATE,SYSUTCDATETIME())),N'EN_CURSO',@V_USUARIO);END;
IF NOT EXISTS(SELECT 1 FROM [INVENTARIO].[ACTIVOS_EVENTOS] WHERE [ID_ACTIVO]=@V_A1) BEGIN DECLARE @V_MED BIGINT=(SELECT TOP(1)[ID_MEDICION_ACTIVO] FROM [INVENTARIO].[MEDICIONES_ACTIVOS] WHERE [ID_ACTIVO]=@V_A1);INSERT [INVENTARIO].[ACTIVOS_EVENTOS]([ID_EMPRESA],[ID_ACTIVO],[TIPO_EVENTO],[FECHA_EVENTO_UTC],[CODIGO_ESTADO_ANTES],[CODIGO_ESTADO_DESPUES],[CONDICION_ANTES],[CONDICION_DESPUES],[CANTIDAD_ANTES],[CANTIDAD_DESPUES],[ID_MEDICION_ACTIVO],[OBSERVACION],[ID_CORRELACION],[CODIGO_ESTADO],[ID_USUARIO_ALTA]) VALUES(@V_EMPRESA,@V_A1,N'MEDICION',DATEADD(HOUR,-6,SYSUTCDATETIME()),N'DISPONIBLE',N'DISPONIBLE',N'OPERATIVO',N'OPERATIVO',10,10,@V_MED,N'Información almacenada por pesaje.',NEWID(),N'CONFIRMADO',@V_USUARIO);END;
