/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Datos demostrativos de Finanzas
Archivo: 09_FINANZAS_EJEMPLO.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea una caja abierta y un cobro parcial mixto para pruebas de Development.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');
DECLARE @V_ID_USUARIO BIGINT = (SELECT [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [NOMBRE_USUARIO] = N'AOCAUZI');
DECLARE @V_ID_SUCURSAL BIGINT = (SELECT TOP (1) [ID_SUCURSAL] FROM [CONFIGURACION].[SUCURSALES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CENTRAL');

IF @V_ID_SUCURSAL IS NULL
    SET @V_ID_SUCURSAL = (SELECT TOP (1) [ID_SUCURSAL] FROM [CONFIGURACION].[SUCURSALES] WHERE [ID_EMPRESA] = @V_ID_EMPRESA ORDER BY [ID_SUCURSAL]);

IF NOT EXISTS (SELECT 1 FROM [FINANZAS].[CAJAS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CAJA-CENTRAL')
    INSERT INTO [FINANZAS].[CAJAS]
        ([ID_EMPRESA], [ID_SUCURSAL], [CODIGO], [NOMBRE], [MONEDA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_EMPRESA, @V_ID_SUCURSAL, N'CAJA-CENTRAL', N'Caja central', 'ARS', N'ACTIVO', @V_ID_USUARIO);

DECLARE @V_ID_CAJA BIGINT = (SELECT [ID_CAJA] FROM [FINANZAS].[CAJAS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'CAJA-CENTRAL');
IF NOT EXISTS (SELECT 1 FROM [FINANZAS].[SESIONES_CAJA] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [ID_USUARIO_APERTURA] = @V_ID_USUARIO AND [CODIGO_ESTADO] = N'ABIERTA')
    INSERT INTO [FINANZAS].[SESIONES_CAJA]
        ([ID_EMPRESA], [ID_CAJA], [ID_USUARIO_APERTURA], [FECHA_APERTURA_UTC], [IMPORTE_APERTURA],
         [OBSERVACION_APERTURA], [ID_USUARIO_ALTA])
    VALUES
        (@V_ID_EMPRESA, @V_ID_CAJA, @V_ID_USUARIO, SYSUTCDATETIME(), 10000,
         N'Apertura demostrativa de Development', @V_ID_USUARIO);

DECLARE @V_ID_SESION_CAJA BIGINT =
(
    SELECT [ID_SESION_CAJA] FROM [FINANZAS].[SESIONES_CAJA]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [ID_USUARIO_APERTURA] = @V_ID_USUARIO AND [CODIGO_ESTADO] = N'ABIERTA'
);
DECLARE @V_ID_VENTA BIGINT =
(
    SELECT TOP (1) [VEN].[ID_VENTA]
    FROM [COMERCIAL].[VENTAS] AS [VEN]
    WHERE [VEN].[ID_EMPRESA] = @V_ID_EMPRESA
      AND NOT EXISTS (SELECT 1 FROM [FINANZAS].[APLICACIONES_PAGO_VENTA] WHERE [ID_VENTA] = [VEN].[ID_VENTA])
    ORDER BY [VEN].[ID_VENTA]
);

IF @V_ID_VENTA IS NOT NULL AND NOT EXISTS
    (SELECT 1 FROM [FINANZAS].[PAGOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [OBSERVACION] = N'Cobro mixto demostrativo de Development')
BEGIN
    DECLARE @V_ID_CLIENTE BIGINT = (SELECT [ID_CLIENTE] FROM [COMERCIAL].[VENTAS] WHERE [ID_VENTA] = @V_ID_VENTA);
    DECLARE @V_TOTAL_VENTA DECIMAL(19,4) = (SELECT [TOTAL] FROM [COMERCIAL].[VENTAS] WHERE [ID_VENTA] = @V_ID_VENTA);
    DECLARE @V_IMPORTE DECIMAL(19,4) = CASE WHEN @V_TOTAL_VENTA > 1000 THEN 1000 ELSE @V_TOTAL_VENTA END;
    DECLARE @V_EFECTIVO DECIMAL(19,4) = ROUND(@V_IMPORTE / 2, 2);
    DECLARE @V_TRANSFERENCIA DECIMAL(19,4) = @V_IMPORTE - @V_EFECTIVO;
    DECLARE @V_ID_EFECTIVO BIGINT = (SELECT [ID_MEDIO_PAGO] FROM [FINANZAS].[MEDIOS_PAGO] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'EFECTIVO');
    DECLARE @V_ID_TRANSFERENCIA BIGINT = (SELECT [ID_MEDIO_PAGO] FROM [FINANZAS].[MEDIOS_PAGO] WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = N'TRANSFERENCIA');
    DECLARE @V_JSON_MEDIOS NVARCHAR(MAX) = N'[{"PaymentMethodId":' + CONVERT(NVARCHAR(20), @V_ID_EFECTIVO) +
        N',"Amount":' + CONVERT(NVARCHAR(40), @V_EFECTIVO) + N'},{"PaymentMethodId":' +
        CONVERT(NVARCHAR(20), @V_ID_TRANSFERENCIA) + N',"Amount":' + CONVERT(NVARCHAR(40), @V_TRANSFERENCIA) +
        N',"Reference":"TR-DEMO-001"}]';
    DECLARE @V_JSON_APLICACIONES NVARCHAR(MAX) = N'[{"SaleId":' + CONVERT(NVARCHAR(20), @V_ID_VENTA) +
        N',"Amount":' + CONVERT(NVARCHAR(40), @V_IMPORTE) + N'}]';
    DECLARE @V_ID_PAGO BIGINT, @V_FILAS INT, @V_ERROR BIGINT, @V_MENSAJE NVARCHAR(4000);
    DECLARE @V_FECHA_PAGO_UTC DATETIME2(3) = SYSUTCDATETIME();

    EXEC [FINANZAS].[SP_FINANZAS_COMMAND]
        @I_ACCION = N'PAGO_REGISTRAR', @I_ID_EMPRESA = @V_ID_EMPRESA, @S_ID_SESION = 1,
        @S_ID_USUARIO = @V_ID_USUARIO, @I_ID_CLIENTE = @V_ID_CLIENTE,
        @I_ID_SESION_CAJA = @V_ID_SESION_CAJA, @I_MONEDA = 'ARS', @I_FECHA_UTC = @V_FECHA_PAGO_UTC,
        @I_IMPORTE = @V_IMPORTE, @I_OBSERVACION = N'Cobro mixto demostrativo de Development',
        @I_JSON_MEDIOS = @V_JSON_MEDIOS, @I_JSON_APLICACIONES = @V_JSON_APLICACIONES,
        @O_ID = @V_ID_PAGO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS OUTPUT,
        @O_CODIGO_ERROR = @V_ERROR OUTPUT, @O_MENSAJE = @V_MENSAJE OUTPUT;
    IF @V_ERROR IS NOT NULL THROW 50000, @V_MENSAJE, 1;
END;
