/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Datos de desarrollo para servicios comerciales
Archivo: 10_SERVICIOS_COMERCIALES_EJEMPLO.sql | Versión: 1.0.0 | Fecha: 2026-08-28 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea servicios y precios ficticios para probar pedidos sin movimiento de stock.
Historial: 1.0.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
SET NOCOUNT ON;

DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');
DECLARE @V_ID_UNIDAD BIGINT = (SELECT [ID_UNIDAD_MEDIDA] FROM [CONFIGURACION].[UNIDADES_MEDIDA] WHERE [CODIGO] = N'UN');
DECLARE @V_ID_USUARIO BIGINT = (SELECT TOP (1) [ID_USUARIO] FROM [SEGURIDAD].[USUARIOS] WHERE [ID_EMPRESA] = @V_ID_EMPRESA ORDER BY [ID_USUARIO]);
DECLARE @V_ID_CATEGORIA BIGINT = (SELECT [ID_CATEGORIA_PRODUCTO] FROM [INVENTARIO].[CATEGORIAS_PRODUCTO] WHERE [CODIGO] = N'SERVICIOS');

IF @V_ID_CATEGORIA IS NULL
BEGIN
    INSERT INTO [INVENTARIO].[CATEGORIAS_PRODUCTO]
    ([CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES (N'SERVICIOS', N'Servicios', N'Trabajos y cargos sin existencia física.', N'ACTIVO', @V_ID_USUARIO);

    SET @V_ID_CATEGORIA = CONVERT(BIGINT, SCOPE_IDENTITY());
END;

DECLARE @T_SERVICIOS TABLE ([CODIGO] NVARCHAR(30), [NOMBRE] NVARCHAR(200), [DESCRIPCION] NVARCHAR(1000), [PRECIO] DECIMAL(19,4));
INSERT INTO @T_SERVICIOS VALUES
    (N'SRV-RECARGA', N'Recarga de tubo', N'Recarga del contenido del tubo identificado en el pedido.', 12000),
    (N'SRV-VALVULA', N'Cambio de válvula', N'Reemplazo y control de válvula del tubo identificado.', 8500),
    (N'SRV-MANO-OBRA', N'Mano de obra', N'Trabajo técnico adicional documentado en el pedido.', 5000),
    (N'SRV-ENVIO', N'Envío', N'Retiro o entrega coordinada por OxiTigre.', 6500);

INSERT INTO [INVENTARIO].[PRODUCTOS]
([ID_EMPRESA], [ID_CATEGORIA_PRODUCTO], [ID_UNIDAD_MEDIDA], [CODIGO], [NOMBRE], [DESCRIPCION],
 [TIPO_ITEM], [TIPO_TRAZABILIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, @V_ID_CATEGORIA, @V_ID_UNIDAD, [SRC].[CODIGO], [SRC].[NOMBRE], [SRC].[DESCRIPCION],
       N'SERVICIO', N'NINGUNA', N'ACTIVO', @V_ID_USUARIO
FROM @T_SERVICIOS AS [SRC]
WHERE NOT EXISTS
(
    SELECT 1 FROM [INVENTARIO].[PRODUCTOS] AS [PRO]
    WHERE [PRO].[ID_EMPRESA] = @V_ID_EMPRESA AND [PRO].[CODIGO] = [SRC].[CODIGO]
);

INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS]
([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [LIS].[ID_LISTA_PRECIO], [PRO].[ID_PRODUCTO],
       CASE WHEN [LIS].[CODIGO] = N'MAYORISTA' THEN ROUND([SRC].[PRECIO] * 0.9, 4) ELSE [SRC].[PRECIO] END,
       N'ACTIVO', @V_ID_USUARIO
FROM @T_SERVICIOS AS [SRC]
INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO]
    ON [PRO].[ID_EMPRESA] = @V_ID_EMPRESA AND [PRO].[CODIGO] = [SRC].[CODIGO]
INNER JOIN [COMERCIAL].[LISTAS_PRECIOS] AS [LIS]
    ON [LIS].[ID_EMPRESA] = @V_ID_EMPRESA AND [LIS].[CODIGO_ESTADO] = N'ACTIVO'
WHERE NOT EXISTS
(
    SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] AS [LPP]
    WHERE [LPP].[ID_LISTA_PRECIO] = [LIS].[ID_LISTA_PRECIO]
      AND [LPP].[ID_PRODUCTO] = [PRO].[ID_PRODUCTO]
);

SELECT [PRO].[CODIGO], [PRO].[NOMBRE], [PRO].[TIPO_ITEM], [LIS].[CODIGO] AS [LISTA], [LPP].[PRECIO_UNITARIO]
FROM [INVENTARIO].[PRODUCTOS] AS [PRO]
INNER JOIN [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] AS [LPP] ON [LPP].[ID_PRODUCTO] = [PRO].[ID_PRODUCTO]
INNER JOIN [COMERCIAL].[LISTAS_PRECIOS] AS [LIS] ON [LIS].[ID_LISTA_PRECIO] = [LPP].[ID_LISTA_PRECIO]
WHERE [PRO].[ID_EMPRESA] = @V_ID_EMPRESA AND [PRO].[TIPO_ITEM] = N'SERVICIO'
ORDER BY [PRO].[CODIGO], [LIS].[CODIGO];
