/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Maestros de transporte de Logística Fase 8
Archivo: FASE8_TRANSPORTE.sql | Versión: 1.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra perfiles transportistas, vehículos y su vínculo histórico con hojas de ruta.
Historial: 1.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial idempotente.
===============================================================================
*/
IF OBJECT_ID(N'[LOGISTICA].[TRANSPORTISTAS]', N'U') IS NULL
BEGIN
    CREATE TABLE [LOGISTICA].[TRANSPORTISTAS]
    (
        [ID_TRANSPORTISTA] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_TRANSPORTISTAS] PRIMARY KEY,
        [ID_EMPRESA] BIGINT NOT NULL,
        [ID_USUARIO] BIGINT NOT NULL,
        [CODIGO] NVARCHAR(30) NOT NULL,
        [TIPO_VINCULO] NVARCHAR(20) NOT NULL,
        [DOCUMENTO] NVARCHAR(30) NULL,
        [TELEFONO] NVARCHAR(50) NULL,
        [LICENCIA] NVARCHAR(50) NOT NULL,
        [CATEGORIA_LICENCIA] NVARCHAR(30) NULL,
        [VENCIMIENTO_LICENCIA] DATE NULL,
        [OBSERVACION] NVARCHAR(1000) NULL,
        [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_TRANSPORTISTA_ESTADO] DEFAULT (N'ACTIVO'),
        [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_TRANSPORTISTA_ALTA] DEFAULT (SYSUTCDATETIME()),
        [ID_USUARIO_ALTA] BIGINT NOT NULL,
        [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
        [ID_USUARIO_MODIFICACION] BIGINT NULL,
        [ROW_VERSION] ROWVERSION NOT NULL,
        CONSTRAINT [UQ_LOG_TRANSPORTISTA_CODIGO] UNIQUE ([ID_EMPRESA], [CODIGO]),
        CONSTRAINT [UQ_LOG_TRANSPORTISTA_USUARIO] UNIQUE ([ID_EMPRESA], [ID_USUARIO]),
        CONSTRAINT [CK_LOG_TRANSPORTISTA_VINCULO] CHECK ([TIPO_VINCULO] IN (N'EMPRESA', N'PARTICULAR'))
    );
END;

IF OBJECT_ID(N'[LOGISTICA].[VEHICULOS]', N'U') IS NULL
BEGIN
    CREATE TABLE [LOGISTICA].[VEHICULOS]
    (
        [ID_VEHICULO] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_VEHICULOS] PRIMARY KEY,
        [ID_EMPRESA] BIGINT NOT NULL,
        [ID_TRANSPORTISTA_PROPIETARIO] BIGINT NULL,
        [CODIGO] NVARCHAR(30) NOT NULL,
        [PATENTE] NVARCHAR(10) NOT NULL,
        [TIPO_VEHICULO] NVARCHAR(30) NOT NULL,
        [TIPO_PROPIEDAD] NVARCHAR(20) NOT NULL,
        [MARCA] NVARCHAR(80) NULL,
        [MODELO] NVARCHAR(80) NULL,
        [ANIO] SMALLINT NULL,
        [CAPACIDAD_CARGA_KG] DECIMAL(19,4) NULL,
        [POLIZA_SEGURO] NVARCHAR(100) NULL,
        [VENCIMIENTO_SEGURO] DATE NULL,
        [VENCIMIENTO_REVISION] DATE NULL,
        [OBSERVACION] NVARCHAR(1000) NULL,
        [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_VEHICULO_ESTADO] DEFAULT (N'ACTIVO'),
        [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_VEHICULO_ALTA] DEFAULT (SYSUTCDATETIME()),
        [ID_USUARIO_ALTA] BIGINT NOT NULL,
        [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
        [ID_USUARIO_MODIFICACION] BIGINT NULL,
        [ROW_VERSION] ROWVERSION NOT NULL,
        CONSTRAINT [UQ_LOG_VEHICULO_CODIGO] UNIQUE ([ID_EMPRESA], [CODIGO]),
        CONSTRAINT [UQ_LOG_VEHICULO_PATENTE] UNIQUE ([ID_EMPRESA], [PATENTE]),
        CONSTRAINT [CK_LOG_VEHICULO_TIPO] CHECK ([TIPO_VEHICULO] IN (N'CAMION', N'CAMIONETA', N'UTILITARIO', N'AUTO', N'OTRO')),
        CONSTRAINT [CK_LOG_VEHICULO_PROPIEDAD] CHECK
        (
            ([TIPO_PROPIEDAD] = N'EMPRESA' AND [ID_TRANSPORTISTA_PROPIETARIO] IS NULL)
            OR
            ([TIPO_PROPIEDAD] = N'TRANSPORTISTA' AND [ID_TRANSPORTISTA_PROPIETARIO] IS NOT NULL)
        ),
        CONSTRAINT [CK_LOG_VEHICULO_ANIO] CHECK ([ANIO] IS NULL OR [ANIO] BETWEEN 1950 AND 2200),
        CONSTRAINT [CK_LOG_VEHICULO_CAPACIDAD] CHECK ([CAPACIDAD_CARGA_KG] IS NULL OR [CAPACIDAD_CARGA_KG] > 0)
    );
END;

IF COL_LENGTH(N'[LOGISTICA].[HOJAS_RUTA]', N'ID_TRANSPORTISTA') IS NULL
BEGIN
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA] ADD [ID_TRANSPORTISTA] BIGINT NULL;
END;

IF COL_LENGTH(N'[LOGISTICA].[HOJAS_RUTA]', N'ID_VEHICULO') IS NULL
BEGIN
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA] ADD [ID_VEHICULO] BIGINT NULL;
END;

IF COL_LENGTH(N'[LOGISTICA].[HOJAS_RUTA]', N'TIPO_ASIGNACION') IS NULL
BEGIN
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA]
        ADD [TIPO_ASIGNACION] NVARCHAR(20) NOT NULL
            CONSTRAINT [DF_LOG_HOJA_TIPO_ASIGNACION] DEFAULT (N'DIRECTA');
END;

IF COL_LENGTH(N'[LOGISTICA].[HOJAS_RUTA]', N'FECHA_ASIGNACION_UTC') IS NULL
BEGIN
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA] ADD [FECHA_ASIGNACION_UTC] DATETIME2(3) NULL;
END;
GO

IF OBJECT_ID(N'[LOGISTICA].[CK_LOG_HOJA_TIPO_ASIGNACION]', N'C') IS NULL
BEGIN
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA]
        ADD CONSTRAINT [CK_LOG_HOJA_TIPO_ASIGNACION]
            CHECK ([TIPO_ASIGNACION] IN (N'DIRECTA', N'OFERTA'));
END;
