/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Tablas de Logística Fase 8
Archivo: FASE8_LOGISTICA.sql | Versión: 1.0.0 | Fecha: 2026-08-26 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Conserva solicitudes, custodia, hojas de ruta históricas, eventos y avisos operativos.
Historial: 1.0.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
CREATE TABLE [LOGISTICA].[CLIENTES_DIRECCIONES]
(
    [ID_DIRECCION] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_CLIENTES_DIRECCIONES] PRIMARY KEY,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CLIENTE] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(100) NOT NULL,
    [DOMICILIO] NVARCHAR(300) NOT NULL,
    [LOCALIDAD] NVARCHAR(100) NULL,
    [PROVINCIA] NVARCHAR(100) NULL,
    [CODIGO_POSTAL] NVARCHAR(20) NULL,
    [LATITUD] DECIMAL(9,6) NULL,
    [LONGITUD] DECIMAL(9,6) NULL,
    [CONTACTO] NVARCHAR(200) NOT NULL,
    [TELEFONO] NVARCHAR(50) NOT NULL,
    [CORREO] NVARCHAR(254) NULL,
    [HORA_DESDE] TIME(0) NULL,
    [HORA_HASTA] TIME(0) NULL,
    [MINUTOS_SERVICIO] SMALLINT NOT NULL CONSTRAINT [DF_LOG_DIRECCION_MINUTOS] DEFAULT (15),
    [RESTRICCIONES] NVARCHAR(1000) NULL,
    [INSTRUCCIONES] NVARCHAR(1000) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_DIRECCION_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_DIRECCION_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [UQ_LOG_DIRECCION_CODIGO] UNIQUE ([ID_EMPRESA], [CODIGO]),
    CONSTRAINT [CK_LOG_DIRECCION_HORARIO]
        CHECK ([HORA_DESDE] IS NULL AND [HORA_HASTA] IS NULL OR [HORA_DESDE] < [HORA_HASTA]),
    CONSTRAINT [CK_LOG_DIRECCION_MINUTOS] CHECK ([MINUTOS_SERVICIO] BETWEEN 1 AND 1440),
    CONSTRAINT [CK_LOG_DIRECCION_COORDENADAS]
        CHECK
        (
            ([LATITUD] IS NULL AND [LONGITUD] IS NULL)
            OR ([LATITUD] BETWEEN -90 AND 90 AND [LONGITUD] BETWEEN -180 AND 180)
        )
);

CREATE TABLE [LOGISTICA].[SOLICITUDES]
(
    [ID_SOLICITUD] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_SOLICITUDES] PRIMARY KEY,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CLIENTE] BIGINT NOT NULL,
    [ID_DIRECCION] BIGINT NOT NULL,
    [ID_PEDIDO] BIGINT NULL,
    [ID_DEPOSITO_DESTINO] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [TIPO_SERVICIO] NVARCHAR(30) NOT NULL,
    [PRIORIDAD] NVARCHAR(20) NOT NULL CONSTRAINT [DF_LOG_SOLICITUD_PRIORIDAD] DEFAULT (N'NORMAL'),
    [FECHA_SOLICITADA] DATE NOT NULL,
    [HORA_DESDE] TIME(0) NULL,
    [HORA_HASTA] TIME(0) NULL,
    [INSTRUCCIONES] NVARCHAR(1000) NOT NULL,
    [OBSERVACION] NVARCHAR(1000) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_SOLICITUD_ESTADO] DEFAULT (N'PENDIENTE'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_SOLICITUD_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [UQ_LOG_SOLICITUD_CODIGO] UNIQUE ([ID_EMPRESA], [CODIGO]),
    CONSTRAINT [CK_LOG_SOLICITUD_TIPO]
        CHECK
        (
            [TIPO_SERVICIO] IN
            (
                N'ENTREGA_PEDIDO',
                N'RETIRO_RECARGA',
                N'DEVOLUCION_CLIENTE',
                N'INTERCAMBIO_TEMPORAL',
                N'TRASLADO_SUCURSAL',
                N'URGENCIA'
            )
        ),
    CONSTRAINT [CK_LOG_SOLICITUD_PRIORIDAD]
        CHECK ([PRIORIDAD] IN (N'NORMAL', N'ALTA', N'URGENTE', N'EMERGENCIA')),
    CONSTRAINT [CK_LOG_SOLICITUD_HORARIO] CHECK ([HORA_DESDE] IS NULL AND [HORA_HASTA] IS NULL OR [HORA_DESDE] < [HORA_HASTA])
);

CREATE TABLE [LOGISTICA].[SOLICITUDES_ACTIVOS]
(
    [ID_SOLICITUD_ACTIVO] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_SOLICITUDES_ACTIVOS] PRIMARY KEY,
    [ID_SOLICITUD] BIGINT NOT NULL,
    [ID_ACTIVO] BIGINT NULL,
    [PROPIETARIO] NVARCHAR(20) NOT NULL,
    [ROL] NVARCHAR(30) NOT NULL,
    [NUMERO_SERIE] NVARCHAR(100) NOT NULL,
    [PRODUCTO] NVARCHAR(200) NULL,
    [CANTIDAD_CONTENIDO] DECIMAL(19,4) NULL,
    [UNIDAD] NVARCHAR(20) NULL,
    [CONDICION] NVARCHAR(30) NOT NULL,
    [OBSERVACION] NVARCHAR(500) NULL,
    [FECHA_DEVOLUCION_PREVISTA] DATE NULL,
    [ID_PRESTAMO] BIGINT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_SOLICITUD_ACTIVO_ESTADO] DEFAULT (N'PENDIENTE'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_SOLICITUD_ACTIVO_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    CONSTRAINT [CK_LOG_SOLICITUD_ACTIVO_OWNER] CHECK ([PROPIETARIO] IN (N'CLIENTE',N'OXITIGRE')),
    CONSTRAINT [CK_LOG_SOLICITUD_ACTIVO_ROL] CHECK ([ROL] IN (N'RETIRO_CLIENTE',N'PRESTAMO_TEMPORAL',N'ENTREGA',N'DEVOLUCION')),
    CONSTRAINT [CK_LOG_SOLICITUD_ACTIVO_CANTIDAD] CHECK ([CANTIDAD_CONTENIDO] IS NULL OR [CANTIDAD_CONTENIDO] >= 0)
);

CREATE TABLE [LOGISTICA].[HOJAS_RUTA]
(
    [ID_HOJA_RUTA] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_HOJAS_RUTA] PRIMARY KEY,
    [ID_EMPRESA] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [FECHA_RUTA] DATE NOT NULL,
    [TIPO_RUTA] NVARCHAR(20) NOT NULL,
    [CHOFER] NVARCHAR(200) NULL,
    [PATENTE] NVARCHAR(20) NULL,
    [OBSERVACION] NVARCHAR(1000) NOT NULL,
    [FECHA_SALIDA_UTC] DATETIME2(3) NULL,
    [FECHA_CIERRE_UTC] DATETIME2(3) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_HOJA_ESTADO] DEFAULT (N'PLANIFICADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_HOJA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [UQ_LOG_HOJA_CODIGO] UNIQUE ([ID_EMPRESA], [CODIGO]),
    CONSTRAINT [CK_LOG_HOJA_TIPO] CHECK ([TIPO_RUTA] IN (N'NORMAL',N'URGENTE'))
);

CREATE TABLE [LOGISTICA].[HOJAS_RUTA_PARADAS]
(
    [ID_PARADA] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_HOJAS_RUTA_PARADAS] PRIMARY KEY,
    [ID_HOJA_RUTA] BIGINT NOT NULL,
    [ID_SOLICITUD] BIGINT NOT NULL,
    [ORDEN] SMALLINT NOT NULL,
    [CLIENTE] NVARCHAR(200) NOT NULL,
    [DOMICILIO] NVARCHAR(300) NOT NULL,
    [CONTACTO] NVARCHAR(200) NOT NULL,
    [TELEFONO] NVARCHAR(50) NOT NULL,
    [HORA_DESDE] TIME(0) NULL,
    [HORA_HASTA] TIME(0) NULL,
    [PRIORIDAD] NVARCHAR(20) NOT NULL,
    [INSTRUCCIONES] NVARCHAR(1000) NOT NULL,
    [FECHA_LLEGADA_UTC] DATETIME2(3) NULL,
    [FECHA_SALIDA_UTC] DATETIME2(3) NULL,
    [RESULTADO] NVARCHAR(30) NULL,
    [OBSERVACION_RESULTADO] NVARCHAR(1000) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_PARADA_ESTADO] DEFAULT (N'PLANIFICADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_PARADA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [UQ_LOG_PARADA_ORDEN] UNIQUE ([ID_HOJA_RUTA], [ORDEN]),
    CONSTRAINT [CK_LOG_PARADA_ORDEN] CHECK ([ORDEN] > 0),
    CONSTRAINT [CK_LOG_PARADA_RESULTADO] CHECK ([RESULTADO] IS NULL OR [RESULTADO] IN (N'ENTREGADA',N'PARCIAL',N'FALLIDA',N'REPROGRAMADA'))
);

CREATE TABLE [LOGISTICA].[EVENTOS]
(
    [ID_EVENTO] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_EVENTOS] PRIMARY KEY,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_SOLICITUD] BIGINT NULL,
    [ID_HOJA_RUTA] BIGINT NULL,
    [ID_PARADA] BIGINT NULL,
    [TIPO_EVENTO] NVARCHAR(50) NOT NULL,
    [ESTADO_ANTERIOR] NVARCHAR(30) NULL,
    [ESTADO_NUEVO] NVARCHAR(30) NULL,
    [OBSERVACION] NVARCHAR(1000) NOT NULL,
    [ID_USUARIO] BIGINT NOT NULL,
    [ID_SESION] BIGINT NOT NULL,
    [CORRELACION] UNIQUEIDENTIFIER NOT NULL,
    [FECHA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_EVENTO_FECHA] DEFAULT (SYSUTCDATETIME())
);

CREATE TABLE [LOGISTICA].[NOTIFICACIONES]
(
    [ID_NOTIFICACION] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_LOG_NOTIFICACIONES] PRIMARY KEY,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_SOLICITUD] BIGINT NULL,
    [ID_HOJA_RUTA] BIGINT NULL,
    [TIPO_EVENTO] NVARCHAR(50) NOT NULL,
    [CANAL] NVARCHAR(20) NOT NULL,
    [DESTINATARIO] NVARCHAR(254) NOT NULL,
    [MENSAJE] NVARCHAR(1000) NOT NULL,
    [INTENTOS] SMALLINT NOT NULL CONSTRAINT [DF_LOG_NOTIFICACION_INTENTOS] DEFAULT (0),
    [PROXIMO_INTENTO_UTC] DATETIME2(3) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_LOG_NOTIFICACION_ESTADO] DEFAULT (N'PENDIENTE'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_LOG_NOTIFICACION_ALTA] DEFAULT (SYSUTCDATETIME()),
    [FECHA_ENVIO_UTC] DATETIME2(3) NULL,
    CONSTRAINT [CK_LOG_NOTIFICACION_CANAL] CHECK ([CANAL] IN (N'EMAIL',N'WHATSAPP',N'SIMULADO'))
);
