/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Migración de producto Fase 7
Archivo: 20260824_FASE7_PRODUCT_COLUMNS.sql | Versión: 1.0.0 | Fecha: 2026-08-24 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Agrega configuración trazable a productos existentes sin perder información.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'TIPO_TRAZABILIDAD') IS NULL
    ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD [TIPO_TRAZABILIDAD] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PRODUCTOS_TIPO_TRAZABILIDAD] DEFAULT(N'NINGUNA');
IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'ES_REUTILIZABLE') IS NULL
    ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD [ES_REUTILIZABLE] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_ES_REUTILIZABLE] DEFAULT(0);
IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'ADMITE_PRESTAMO') IS NULL
    ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD [ADMITE_PRESTAMO] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_ADMITE_PRESTAMO] DEFAULT(0);
IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'REQUIERE_MANTENIMIENTO') IS NULL
    ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD [REQUIERE_MANTENIMIENTO] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_REQUIERE_MANTENIMIENTO] DEFAULT(0);
IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'ADMITE_MEDICIONES') IS NULL
    ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD [ADMITE_MEDICIONES] BIT NOT NULL CONSTRAINT [DF_PRODUCTOS_ADMITE_MEDICIONES] DEFAULT(0);
