/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Migración incremental Fase 11
Archivo: 20260827_FASE11_FINANZAS.sql | Versión: 11.0.1 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Incorpora caja, cobros y cuenta corriente a una base operativa existente.
Historial: 11.0.1 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Migración idempotente completa.
===============================================================================
*/

-- Fuente versionada: database/01_Schemas/FINANZAS.sql
/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Esquema Finanzas
Archivo: FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Aísla caja, cobros y cuenta corriente de la facturación fiscal.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF SCHEMA_ID(N'FINANZAS') IS NULL
BEGIN
    EXEC sys.sp_executesql N'CREATE SCHEMA [FINANZAS] AUTHORIZATION [dbo];';
END;
GO

-- Fuente versionada: database/02_Tables/FINANZAS/FASE11_FINANZAS.sql
/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Núcleo financiero no fiscal
Archivo: FASE11_FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra medios, cajas, turnos, cobros, aplicaciones y cuenta corriente.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF OBJECT_ID(N'[FINANZAS].[MEDIOS_PAGO]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[MEDIOS_PAGO]
(
    [ID_MEDIO_PAGO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(100) NOT NULL,
    [TIPO] NVARCHAR(30) NOT NULL,
    [AFECTA_EFECTIVO] BIT NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_AFECTA_EFECTIVO] DEFAULT (0),
    [REQUIERE_REFERENCIA] BIT NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_REQUIERE_REFERENCIA] DEFAULT (0),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MEDIOS_PAGO_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_MEDIOS_PAGO] PRIMARY KEY CLUSTERED ([ID_MEDIO_PAGO])
);
END;

IF OBJECT_ID(N'[FINANZAS].[CAJAS]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[CAJAS]
(
    [ID_CAJA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_SUCURSAL] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [NOMBRE] NVARCHAR(100) NOT NULL,
    [MONEDA] CHAR(3) NOT NULL CONSTRAINT [DF_CAJAS_MONEDA] DEFAULT ('ARS'),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_CAJAS_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_CAJAS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_CAJAS] PRIMARY KEY CLUSTERED ([ID_CAJA])
);
END;

IF OBJECT_ID(N'[FINANZAS].[SESIONES_CAJA]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[SESIONES_CAJA]
(
    [ID_SESION_CAJA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CAJA] BIGINT NOT NULL,
    [ID_USUARIO_APERTURA] BIGINT NOT NULL,
    [FECHA_APERTURA_UTC] DATETIME2(3) NOT NULL,
    [IMPORTE_APERTURA] DECIMAL(19,4) NOT NULL,
    [FECHA_CIERRE_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_CIERRE] BIGINT NULL,
    [IMPORTE_ESPERADO] DECIMAL(19,4) NULL,
    [IMPORTE_CONTADO] DECIMAL(19,4) NULL,
    [DIFERENCIA] DECIMAL(19,4) NULL,
    [OBSERVACION_APERTURA] NVARCHAR(500) NULL,
    [OBSERVACION_CIERRE] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_SESIONES_CAJA_ESTADO] DEFAULT (N'ABIERTA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_SESIONES_CAJA_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_SESIONES_CAJA] PRIMARY KEY CLUSTERED ([ID_SESION_CAJA])
);
END;

IF OBJECT_ID(N'[FINANZAS].[PAGOS]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[PAGOS]
(
    [ID_PAGO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CLIENTE] BIGINT NOT NULL,
    [ID_SESION_CAJA] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [FECHA_PAGO_UTC] DATETIME2(3) NOT NULL,
    [MONEDA] CHAR(3) NOT NULL,
    [TOTAL] DECIMAL(19,4) NOT NULL,
    [OBSERVACION] NVARCHAR(500) NULL,
    [MOTIVO_REVERSION] NVARCHAR(500) NULL,
    [FECHA_REVERSION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_REVERSION] BIGINT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PAGOS_ESTADO] DEFAULT (N'CONFIRMADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PAGOS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PAGOS] PRIMARY KEY CLUSTERED ([ID_PAGO])
);
END;

IF OBJECT_ID(N'[FINANZAS].[PAGOS_MEDIOS]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[PAGOS_MEDIOS]
(
    [ID_PAGO_MEDIO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_PAGO] BIGINT NOT NULL,
    [ID_MEDIO_PAGO] BIGINT NOT NULL,
    [IMPORTE] DECIMAL(19,4) NOT NULL,
    [REFERENCIA] NVARCHAR(100) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PAGOS_MEDIOS_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PAGOS_MEDIOS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    CONSTRAINT [PK_PAGOS_MEDIOS] PRIMARY KEY CLUSTERED ([ID_PAGO_MEDIO])
);
END;

IF OBJECT_ID(N'[FINANZAS].[APLICACIONES_PAGO_VENTA]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA]
(
    [ID_APLICACION_PAGO_VENTA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_PAGO] BIGINT NOT NULL,
    [ID_VENTA] BIGINT NOT NULL,
    [IMPORTE] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_APLICACIONES_PAGO_ESTADO] DEFAULT (N'APLICADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_APLICACIONES_PAGO_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    CONSTRAINT [PK_APLICACIONES_PAGO_VENTA] PRIMARY KEY CLUSTERED ([ID_APLICACION_PAGO_VENTA])
);
END;

IF OBJECT_ID(N'[FINANZAS].[MOVIMIENTOS_CUENTA]', N'U') IS NULL
BEGIN
CREATE TABLE [FINANZAS].[MOVIMIENTOS_CUENTA]
(
    [ID_MOVIMIENTO_CUENTA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_CLIENTE] BIGINT NOT NULL,
    [ID_VENTA] BIGINT NULL,
    [ID_PAGO] BIGINT NULL,
    [TIPO_MOVIMIENTO] NVARCHAR(20) NOT NULL,
    [ORIGEN] NVARCHAR(30) NOT NULL,
    [FECHA_MOVIMIENTO_UTC] DATETIME2(3) NOT NULL,
    [MONEDA] CHAR(3) NOT NULL,
    [IMPORTE] DECIMAL(19,4) NOT NULL,
    [DESCRIPCION] NVARCHAR(300) NOT NULL,
    [CORRELACION] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_MOVIMIENTOS_CUENTA_CORRELACION] DEFAULT (NEWID()),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_CUENTA_ESTADO] DEFAULT (N'CONFIRMADO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_MOVIMIENTOS_CUENTA_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    CONSTRAINT [PK_MOVIMIENTOS_CUENTA] PRIMARY KEY CLUSTERED ([ID_MOVIMIENTO_CUENTA])
);
END;
GO

-- Fuente versionada: database/03_Types/FINANZAS/SEQ_PAGO_CODIGO.sql
/* Fase 11: numeración interna de recibos no fiscales. */
IF OBJECT_ID(N'[FINANZAS].[SEQ_PAGO_CODIGO]', N'SO') IS NULL
BEGIN
    EXEC sys.sp_executesql N'CREATE SEQUENCE [FINANZAS].[SEQ_PAGO_CODIGO] AS BIGINT START WITH 1 INCREMENT BY 1;';
END;
GO

-- Fuente versionada: database/07_Indexes/IX_FASE11_FINANZAS.sql
/* Fase 11: unicidad operativa y consultas de saldos. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[MEDIOS_PAGO]') AND [name] = N'UX_MEDIOS_PAGO_EMPRESA_CODIGO')
BEGIN
    CREATE UNIQUE INDEX [UX_MEDIOS_PAGO_EMPRESA_CODIGO] ON [FINANZAS].[MEDIOS_PAGO] ([ID_EMPRESA], [CODIGO]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[CAJAS]') AND [name] = N'UX_CAJAS_EMPRESA_CODIGO')
BEGIN
    CREATE UNIQUE INDEX [UX_CAJAS_EMPRESA_CODIGO] ON [FINANZAS].[CAJAS] ([ID_EMPRESA], [CODIGO]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[SESIONES_CAJA]') AND [name] = N'UX_SESIONES_CAJA_CAJA_ABIERTA')
BEGIN
    CREATE UNIQUE INDEX [UX_SESIONES_CAJA_CAJA_ABIERTA] ON [FINANZAS].[SESIONES_CAJA] ([ID_CAJA]) WHERE [CODIGO_ESTADO] = N'ABIERTA';
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[SESIONES_CAJA]') AND [name] = N'UX_SESIONES_CAJA_USUARIO_ABIERTA')
BEGIN
    CREATE UNIQUE INDEX [UX_SESIONES_CAJA_USUARIO_ABIERTA] ON [FINANZAS].[SESIONES_CAJA] ([ID_EMPRESA], [ID_USUARIO_APERTURA]) WHERE [CODIGO_ESTADO] = N'ABIERTA';
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[PAGOS]') AND [name] = N'UX_PAGOS_EMPRESA_CODIGO')
BEGIN
    CREATE UNIQUE INDEX [UX_PAGOS_EMPRESA_CODIGO] ON [FINANZAS].[PAGOS] ([ID_EMPRESA], [CODIGO]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[APLICACIONES_PAGO_VENTA]') AND [name] = N'UX_APLICACIONES_PAGO_VENTA')
BEGIN
    CREATE UNIQUE INDEX [UX_APLICACIONES_PAGO_VENTA] ON [FINANZAS].[APLICACIONES_PAGO_VENTA] ([ID_PAGO], [ID_VENTA]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[MOVIMIENTOS_CUENTA]') AND [name] = N'UX_MOVIMIENTO_CUENTA_VENTA')
BEGIN
    CREATE UNIQUE INDEX [UX_MOVIMIENTO_CUENTA_VENTA] ON [FINANZAS].[MOVIMIENTOS_CUENTA] ([ID_VENTA]) WHERE [ID_VENTA] IS NOT NULL AND [ORIGEN] = N'VENTA';
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[PAGOS]') AND [name] = N'IX_PAGOS_CLIENTE_FECHA')
BEGIN
    CREATE INDEX [IX_PAGOS_CLIENTE_FECHA] ON [FINANZAS].[PAGOS] ([ID_CLIENTE], [FECHA_PAGO_UTC] DESC);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[MOVIMIENTOS_CUENTA]') AND [name] = N'IX_MOVIMIENTOS_CUENTA_CLIENTE_FECHA')
BEGIN
    CREATE INDEX [IX_MOVIMIENTOS_CUENTA_CLIENTE_FECHA] ON [FINANZAS].[MOVIMIENTOS_CUENTA] ([ID_CLIENTE], [FECHA_MOVIMIENTO_UTC] DESC);
END;
GO

-- Fuente versionada: database/08_Constraints/CK_FASE11_FINANZAS.sql
/* Fase 11: dominios de caja, pagos y cuenta corriente. */
IF OBJECT_ID(N'[FINANZAS].[CK_MEDIOS_PAGO_TIPO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MEDIOS_PAGO] ADD CONSTRAINT [CK_MEDIOS_PAGO_TIPO] CHECK ([TIPO] IN (N'EFECTIVO', N'TRANSFERENCIA', N'TARJETA', N'CHEQUE', N'OTRO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_MEDIOS_PAGO_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MEDIOS_PAGO] ADD CONSTRAINT [CK_MEDIOS_PAGO_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_CAJAS_MONEDA]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [CK_CAJAS_MONEDA] CHECK ([MONEDA] = UPPER([MONEDA]) AND LEN([MONEDA]) = 3);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_CAJAS_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [CK_CAJAS_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_SESIONES_CAJA_IMPORTES]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [CK_SESIONES_CAJA_IMPORTES] CHECK ([IMPORTE_APERTURA] >= 0 AND ([IMPORTE_CONTADO] IS NULL OR [IMPORTE_CONTADO] >= 0));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_SESIONES_CAJA_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [CK_SESIONES_CAJA_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ABIERTA', N'CERRADA'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_PAGOS_TOTAL]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [CK_PAGOS_TOTAL] CHECK ([TOTAL] > 0);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_PAGOS_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [CK_PAGOS_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'CONFIRMADO', N'REVERTIDO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_PAGOS_MEDIOS_IMPORTE]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS_MEDIOS] ADD CONSTRAINT [CK_PAGOS_MEDIOS_IMPORTE] CHECK ([IMPORTE] > 0);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_APLICACIONES_PAGO_IMPORTE]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA] ADD CONSTRAINT [CK_APLICACIONES_PAGO_IMPORTE] CHECK ([IMPORTE] > 0);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_MOVIMIENTOS_CUENTA]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [CK_MOVIMIENTOS_CUENTA] CHECK ([TIPO_MOVIMIENTO] IN (N'DEBITO', N'CREDITO') AND [IMPORTE] > 0);
END;
GO

-- Fuente versionada: database/08_Constraints/FK_FASE11_FINANZAS.sql
/* Fase 11: relaciones financieras explícitas. */
IF OBJECT_ID(N'[FINANZAS].[FK_MEDIOS_PAGO_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MEDIOS_PAGO] ADD CONSTRAINT [FK_MEDIOS_PAGO_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_CAJAS_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [FK_CAJAS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_CAJAS_SUCURSALES]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [FK_CAJAS_SUCURSALES] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [CONFIGURACION].[SUCURSALES] ([ID_SUCURSAL]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_SESIONES_CAJA_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [FK_SESIONES_CAJA_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_SESIONES_CAJA_CAJAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [FK_SESIONES_CAJA_CAJAS] FOREIGN KEY ([ID_CAJA]) REFERENCES [FINANZAS].[CAJAS] ([ID_CAJA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [FK_PAGOS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_CLIENTES]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [FK_PAGOS_CLIENTES] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [COMERCIAL].[CLIENTES] ([ID_CLIENTE]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_SESIONES_CAJA]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [FK_PAGOS_SESIONES_CAJA] FOREIGN KEY ([ID_SESION_CAJA]) REFERENCES [FINANZAS].[SESIONES_CAJA] ([ID_SESION_CAJA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_MEDIOS_PAGOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS_MEDIOS] ADD CONSTRAINT [FK_PAGOS_MEDIOS_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [FINANZAS].[PAGOS] ([ID_PAGO]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_MEDIOS_MEDIOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS_MEDIOS] ADD CONSTRAINT [FK_PAGOS_MEDIOS_MEDIOS] FOREIGN KEY ([ID_MEDIO_PAGO]) REFERENCES [FINANZAS].[MEDIOS_PAGO] ([ID_MEDIO_PAGO]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_APLICACIONES_PAGO_PAGOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA] ADD CONSTRAINT [FK_APLICACIONES_PAGO_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [FINANZAS].[PAGOS] ([ID_PAGO]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_APLICACIONES_PAGO_VENTAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA] ADD CONSTRAINT [FK_APLICACIONES_PAGO_VENTAS] FOREIGN KEY ([ID_VENTA]) REFERENCES [COMERCIAL].[VENTAS] ([ID_VENTA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_CLIENTES]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_CLIENTES] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [COMERCIAL].[CLIENTES] ([ID_CLIENTE]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_VENTAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_VENTAS] FOREIGN KEY ([ID_VENTA]) REFERENCES [COMERCIAL].[VENTAS] ([ID_VENTA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_PAGOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [FINANZAS].[PAGOS] ([ID_PAGO]);
END;
GO

-- Fuente versionada: database/09_Seeds/01_MODULOS.sql
/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Seed de módulos
Archivo:               01_MODULOS.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Registra los módulos iniciales y su prefijo de error.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
MERGE [CONFIGURACION].[MODULOS] AS [DESTINO]
USING
(
    VALUES
        (1, N'SEGURIDAD', N'Seguridad', N'Usuarios, autenticación y permisos', 0),
        (2, N'CONFIGURACION', N'Configuración', N'Parámetros y catálogos comunes', 1),
        (3, N'INVENTARIO', N'Inventario', N'Existencias y movimientos', 2),
        (4, N'COMERCIAL', N'Comercial', N'Clientes, ventas y pedidos', 3),
        (5, N'COMPRAS', N'Compras', N'Proveedores y adquisiciones', 4),
        (6, N'LOGISTICA', N'Logística', N'Preparación y distribución', 5),
        (7, N'AUDITORIA', N'Auditoría', N'Errores y trazabilidad funcional', 6),
        (8, N'FINANZAS', N'Finanzas', N'Cajas, cobros y cuenta corriente no fiscal', 7)
) AS [ORIGEN] ([NUMERO_MODULO], [CODIGO], [NOMBRE], [DESCRIPCION], [ORDEN])
ON [DESTINO].[CODIGO] = [ORIGEN].[CODIGO]
WHEN NOT MATCHED THEN
    INSERT ([NUMERO_MODULO], [CODIGO], [NOMBRE], [DESCRIPCION], [ORDEN], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    VALUES ([ORIGEN].[NUMERO_MODULO], [ORIGEN].[CODIGO], [ORIGEN].[NOMBRE], [ORIGEN].[DESCRIPCION], [ORIGEN].[ORDEN], N'ACTIVO', 1);
GO

-- Fuente versionada: database/09_Seeds/05_ROLES_PERMISOS.sql
/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Seed de autorización
Archivo:               05_ROLES_PERMISOS.sql
Versión:               11.0.0
Fecha:                 2026-08-27
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Registra roles y permisos mínimos de administración y consulta.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
1.1.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Permiso exclusivo COMERCIAL.GESTIONAR para administradores.
1.2.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Gestión restringida de Configuración y catálogo de errores.
1.3.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Consulta y gestión separadas para Inventario.
1.4.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Gestión separada para pedidos, precios y ventas.
1.5.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Consulta, gestión y despacho del circuito logístico.
1.6.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Rol transportista con acceso operativo acotado.
11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Rol cajero y permisos financieros segregados.
===============================================================================
*/
DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');

INSERT INTO [SEGURIDAD].[ROLES] ([ID_EMPRESA], [CODIGO], [NOMBRE], [DESCRIPCION], [ES_SISTEMA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, [R].[CODIGO], [R].[NOMBRE], [R].[DESCRIPCION], 1, N'ACTIVO', 1
FROM (VALUES
    (N'ADMINISTRADOR', N'Administrador', N'Administración funcional completa de la empresa.'),
    (N'CONSULTA', N'Consulta', N'Acceso de solo lectura autorizado.'),
    (N'TRANSPORTISTA', N'Transportista', N'Acceso al despacho y confirmación de recorridos asignados.'),
    (N'CAJERO', N'Cajero', N'Acceso a la apertura, cobro y cierre de su propia caja.')
) AS [R] ([CODIGO], [NOMBRE], [DESCRIPCION])
WHERE NOT EXISTS
(
    SELECT 1 FROM [SEGURIDAD].[ROLES] AS [ACT]
    WHERE [ACT].[ID_EMPRESA] = @V_ID_EMPRESA AND [ACT].[CODIGO] = [R].[CODIGO]
);

INSERT INTO [SEGURIDAD].[PERMISOS]
    ([ID_MODULO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [M].[ID_MODULO], N'COMERCIAL.GESTIONAR', N'Gestionar clientes',
       N'Permite crear, editar y cambiar el estado de clientes y teléfonos.', N'ACTIVO', 1
FROM [CONFIGURACION].[MODULOS] AS [M]
WHERE [M].[CODIGO] = N'COMERCIAL'
  AND NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[PERMISOS] WHERE [CODIGO] = N'COMERCIAL.GESTIONAR');

INSERT INTO [SEGURIDAD].[PERMISOS]
    ([ID_MODULO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [M].[ID_MODULO], [P].[CODIGO], [P].[NOMBRE], [P].[DESCRIPCION], N'ACTIVO', 1
FROM (VALUES
    (N'CONFIGURACION', N'CONFIGURACION.GESTIONAR', N'Gestionar configuración', N'Permite administrar estructura, catálogos, parámetros y módulos.'),
    (N'AUDITORIA', N'AUDITORIA.GESTIONAR_ERRORES', N'Gestionar catálogo de errores', N'Permite crear y mantener códigos de error conocidos.'),
    (N'INVENTARIO', N'INVENTARIO.GESTIONAR', N'Gestionar inventario', N'Permite mantener maestros, mínimos y confirmar movimientos de stock.'),
    (N'COMERCIAL', N'COMERCIAL.VENTAS_GESTIONAR', N'Gestionar pedidos y ventas', N'Permite mantener listas, confirmar pedidos y registrar ventas internas.'),
    (N'COMPRAS', N'COMPRAS.GESTIONAR', N'Gestionar compras', N'Permite mantener proveedores y órdenes en borrador.'),
    (N'COMPRAS', N'COMPRAS.APROBAR', N'Aprobar compras', N'Permite aprobar órdenes de compra pendientes.'),
    (N'COMPRAS', N'COMPRAS.RECIBIR', N'Recibir compras', N'Permite confirmar recepciones y cerrar saldos pendientes.'),
    (N'FINANZAS', N'FINANZAS.COBRAR', N'Registrar cobros', N'Permite registrar cobros y aplicarlos a ventas internas.'),
    (N'FINANZAS', N'FINANZAS.CAJA_GESTIONAR', N'Gestionar caja', N'Permite abrir y cerrar la caja propia con arqueo.'),
    (N'FINANZAS', N'FINANZAS.REVERSAR', N'Reversar cobros', N'Permite realizar una reversión compensatoria auditada.'),
    (N'FINANZAS', N'FINANZAS.CONFIGURAR', N'Configurar finanzas', N'Permite mantener cajas físicas y medios de pago.')
) AS [P] ([MODULO], [CODIGO], [NOMBRE], [DESCRIPCION])
INNER JOIN [CONFIGURACION].[MODULOS] AS [M] ON [M].[CODIGO] = [P].[MODULO]
WHERE NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[PERMISOS] WHERE [CODIGO] = [P].[CODIGO]);

INSERT INTO [SEGURIDAD].[PERMISOS] ([ID_MODULO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [M].[ID_MODULO], CONCAT([M].[CODIGO], N'.CONSULTAR'), CONCAT(N'Consultar ', [M].[NOMBRE]),
       N'Permite consultar información del módulo.', N'ACTIVO', 1
FROM [CONFIGURACION].[MODULOS] AS [M]
WHERE NOT EXISTS
(
    SELECT 1 FROM [SEGURIDAD].[PERMISOS] AS [P]
    WHERE [P].[CODIGO] = CONCAT([M].[CODIGO], N'.CONSULTAR')
);

INSERT INTO [SEGURIDAD].[ROLES_PERMISOS] ([ID_ROL], [ID_PERMISO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [R].[ID_ROL], [P].[ID_PERMISO], N'ACTIVO', 1
FROM [SEGURIDAD].[ROLES] AS [R]
CROSS JOIN [SEGURIDAD].[PERMISOS] AS [P]
WHERE [R].[ID_EMPRESA] = @V_ID_EMPRESA
  AND
  (
      [R].[CODIGO] = N'ADMINISTRADOR'
      OR ([R].[CODIGO] = N'CONSULTA' AND [P].[CODIGO] LIKE N'%.CONSULTAR')
  )
  AND NOT EXISTS
  (
      SELECT 1 FROM [SEGURIDAD].[ROLES_PERMISOS] AS [RP]
      WHERE [RP].[ID_ROL] = [R].[ID_ROL] AND [RP].[ID_PERMISO] = [P].[ID_PERMISO]
        AND [RP].[CODIGO_ESTADO] = N'ACTIVO'
  );

INSERT INTO [SEGURIDAD].[ROLES_PERMISOS]
    ([ID_ROL], [ID_PERMISO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [R].[ID_ROL], [P].[ID_PERMISO], N'ACTIVO', 1
FROM [SEGURIDAD].[ROLES] AS [R]
INNER JOIN [SEGURIDAD].[PERMISOS] AS [P] ON [P].[CODIGO] = N'COMERCIAL.GESTIONAR'
WHERE [R].[ID_EMPRESA] = @V_ID_EMPRESA AND [R].[CODIGO] = N'ADMINISTRADOR'
  AND NOT EXISTS
  (
      SELECT 1 FROM [SEGURIDAD].[ROLES_PERMISOS] AS [RP]
      WHERE [RP].[ID_ROL] = [R].[ID_ROL] AND [RP].[ID_PERMISO] = [P].[ID_PERMISO]
        AND [RP].[CODIGO_ESTADO] = N'ACTIVO'
  );

-- INICIO: Permisos operativos de Logística Fase 8.
INSERT INTO [SEGURIDAD].[PERMISOS]
    ([ID_MODULO], [CODIGO], [NOMBRE], [DESCRIPCION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [M].[ID_MODULO], [P].[CODIGO], [P].[NOMBRE], [P].[DESCRIPCION], N'ACTIVO', 1
FROM (VALUES
    (N'LOGISTICA.GESTIONAR', N'Gestionar logística', N'Permite mantener domicilios, solicitudes y hojas planificadas.'),
    (N'LOGISTICA.DESPACHAR', N'Despachar logística', N'Permite despachar rutas y confirmar el resultado de sus paradas.')
) AS [P] ([CODIGO], [NOMBRE], [DESCRIPCION])
CROSS JOIN (SELECT [ID_MODULO] FROM [CONFIGURACION].[MODULOS] WHERE [CODIGO] = N'LOGISTICA') AS [M]
WHERE NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[PERMISOS] WHERE [CODIGO] = [P].[CODIGO]);

INSERT INTO [SEGURIDAD].[ROLES_PERMISOS] ([ID_ROL], [ID_PERMISO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [R].[ID_ROL], [P].[ID_PERMISO], N'ACTIVO', 1
FROM [SEGURIDAD].[ROLES] AS [R]
INNER JOIN [SEGURIDAD].[PERMISOS] AS [P] ON [P].[CODIGO] IN (N'LOGISTICA.GESTIONAR', N'LOGISTICA.DESPACHAR')
WHERE [R].[ID_EMPRESA] = @V_ID_EMPRESA AND [R].[CODIGO] = N'ADMINISTRADOR'
  AND NOT EXISTS (SELECT 1 FROM [SEGURIDAD].[ROLES_PERMISOS] AS [RP]
                  WHERE [RP].[ID_ROL] = [R].[ID_ROL] AND [RP].[ID_PERMISO] = [P].[ID_PERMISO]
                    AND [RP].[CODIGO_ESTADO] = N'ACTIVO');
-- FIN: Permisos operativos de Logística Fase 8.

INSERT INTO [SEGURIDAD].[ROLES_PERMISOS]
    ([ID_ROL], [ID_PERMISO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [R].[ID_ROL], [P].[ID_PERMISO], N'ACTIVO', 1
FROM [SEGURIDAD].[ROLES] AS [R]
INNER JOIN [SEGURIDAD].[PERMISOS] AS [P]
    ON [P].[CODIGO] IN (N'LOGISTICA.CONSULTAR', N'LOGISTICA.DESPACHAR')
WHERE [R].[ID_EMPRESA] = @V_ID_EMPRESA
  AND [R].[CODIGO] = N'TRANSPORTISTA'
  AND NOT EXISTS
  (
      SELECT 1 FROM [SEGURIDAD].[ROLES_PERMISOS] AS [RP]
      WHERE [RP].[ID_ROL] = [R].[ID_ROL]
        AND [RP].[ID_PERMISO] = [P].[ID_PERMISO]
        AND [RP].[CODIGO_ESTADO] = N'ACTIVO'
  );

-- INICIO: Un cajero consulta Finanzas, cobra y administra exclusivamente su apertura.
INSERT INTO [SEGURIDAD].[ROLES_PERMISOS]
    ([ID_ROL], [ID_PERMISO], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [R].[ID_ROL], [P].[ID_PERMISO], N'ACTIVO', 1
FROM [SEGURIDAD].[ROLES] AS [R]
INNER JOIN [SEGURIDAD].[PERMISOS] AS [P]
    ON [P].[CODIGO] IN (N'FINANZAS.CONSULTAR', N'FINANZAS.COBRAR', N'FINANZAS.CAJA_GESTIONAR')
WHERE [R].[ID_EMPRESA] = @V_ID_EMPRESA AND [R].[CODIGO] = N'CAJERO'
  AND NOT EXISTS
  (
      SELECT 1 FROM [SEGURIDAD].[ROLES_PERMISOS] AS [RP]
      WHERE [RP].[ID_ROL] = [R].[ID_ROL] AND [RP].[ID_PERMISO] = [P].[ID_PERMISO]
        AND [RP].[CODIGO_ESTADO] = N'ACTIVO'
  );
-- FIN: Un cajero consulta Finanzas, cobra y administra exclusivamente su apertura.
GO

-- Fuente versionada: database/09_Seeds/09_FINANZAS.sql
/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Catálogo financiero inicial
Archivo: 09_FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra medios de pago básicos sin credenciales ni proveedores externos.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
DECLARE @V_ID_EMPRESA BIGINT = (SELECT [ID_EMPRESA] FROM [CONFIGURACION].[EMPRESAS] WHERE [CODIGO] = N'OXITIGRE');

INSERT INTO [FINANZAS].[MEDIOS_PAGO]
    ([ID_EMPRESA], [CODIGO], [NOMBRE], [TIPO], [AFECTA_EFECTIVO], [REQUIERE_REFERENCIA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT @V_ID_EMPRESA, [DAT].[CODIGO], [DAT].[NOMBRE], [DAT].[TIPO], [DAT].[AFECTA_EFECTIVO],
       [DAT].[REQUIERE_REFERENCIA], N'ACTIVO', 1
FROM (VALUES
    (N'EFECTIVO', N'Efectivo', N'EFECTIVO', CONVERT(BIT, 1), CONVERT(BIT, 0)),
    (N'TRANSFERENCIA', N'Transferencia bancaria', N'TRANSFERENCIA', CONVERT(BIT, 0), CONVERT(BIT, 1)),
    (N'TARJETA', N'Tarjeta', N'TARJETA', CONVERT(BIT, 0), CONVERT(BIT, 1))
) AS [DAT] ([CODIGO], [NOMBRE], [TIPO], [AFECTA_EFECTIVO], [REQUIERE_REFERENCIA])
WHERE @V_ID_EMPRESA IS NOT NULL AND NOT EXISTS
(
    SELECT 1 FROM [FINANZAS].[MEDIOS_PAGO]
    WHERE [ID_EMPRESA] = @V_ID_EMPRESA AND [CODIGO] = [DAT].[CODIGO]
);

-- INICIO: Toda venta previa se incorpora una sola vez al saldo inicial.
INSERT INTO [FINANZAS].[MOVIMIENTOS_CUENTA]
    ([ID_EMPRESA], [ID_CLIENTE], [ID_VENTA], [TIPO_MOVIMIENTO], [ORIGEN],
     [FECHA_MOVIMIENTO_UTC], [MONEDA], [IMPORTE], [DESCRIPCION], [ID_USUARIO_ALTA])
SELECT [VEN].[ID_EMPRESA], [VEN].[ID_CLIENTE], [VEN].[ID_VENTA], N'DEBITO', N'VENTA',
       [VEN].[FECHA_VENTA_UTC], [VEN].[MONEDA], [VEN].[TOTAL], N'Venta interna ' + [VEN].[CODIGO], [VEN].[ID_USUARIO_ALTA]
FROM [COMERCIAL].[VENTAS] AS [VEN]
WHERE NOT EXISTS
(
    SELECT 1 FROM [FINANZAS].[MOVIMIENTOS_CUENTA]
    WHERE [ID_VENTA] = [VEN].[ID_VENTA] AND [ORIGEN] = N'VENTA'
);
-- FIN: Toda venta previa se incorpora una sola vez al saldo inicial.
GO

-- Fuente versionada: database/09_Seeds/10_FINANZAS_ERRORES.sql
/* Fase 11: errores funcionales estables de caja, cobros y cuenta corriente. */
INSERT INTO [AUDITORIA].[CATALOGO_ERRORES]
    ([ID_MODULO], [NUMERO_ERROR], [CODIGO_ERROR], [NOMBRE], [DESCRIPCION], [CAUSA_PROBABLE],
     [ACCION_RECOMENDADA], [SEVERIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
SELECT [MOD].[ID_MODULO], [ERR].[NUMERO], [ERR].[CODIGO], [ERR].[NOMBRE], [ERR].[DESCRIPCION],
       [ERR].[CAUSA], [ERR].[ACCION], [ERR].[SEVERIDAD], N'ACTIVO', 1
FROM (VALUES
    (CONVERT(SMALLINT, 1), CONVERT(BIGINT, 80001), N'VALIDACIÓN FINANCIERA',
     N'Los datos del movimiento financiero no son válidos.', N'Campos incompletos o importes inconsistentes.',
     N'Revisar cliente, moneda, importes y medios.', N'ADVERTENCIA'),
    (CONVERT(SMALLINT, 2), CONVERT(BIGINT, 80002), N'CONFLICTO DE CAJA',
     N'La caja o el registro cambió desde la consulta.', N'Apertura duplicada, caja cerrada o concurrencia.',
     N'Actualizar la pantalla y revisar la apertura vigente.', N'ADVERTENCIA'),
    (CONVERT(SMALLINT, 3), CONVERT(BIGINT, 80003), N'APLICACIÓN DE COBRO INVÁLIDA',
     N'El cobro no puede aplicarse a la venta indicada.', N'Saldo, cliente o moneda incompatible.',
     N'Revisar el saldo pendiente de las ventas seleccionadas.', N'ADVERTENCIA'),
    (CONVERT(SMALLINT, 4), CONVERT(BIGINT, 80004), N'REVERSIÓN NO DISPONIBLE',
     N'El cobro no puede revertirse en su estado actual.', N'Cobro ya revertido o caja cerrada.',
     N'Revisar el historial y registrar una corrección en una caja abierta.', N'ADVERTENCIA')
) AS [ERR] ([NUMERO], [CODIGO], [NOMBRE], [DESCRIPCION], [CAUSA], [ACCION], [SEVERIDAD])
CROSS JOIN (SELECT [ID_MODULO] FROM [CONFIGURACION].[MODULOS] WHERE [CODIGO] = N'FINANZAS') AS [MOD]
WHERE NOT EXISTS (SELECT 1 FROM [AUDITORIA].[CATALOGO_ERRORES] WHERE [CODIGO_ERROR] = [ERR].[CODIGO]);
GO

-- Fuente versionada: database/06_StoredProcedures/FINANZAS/Queries/SP_FINANZAS_GET.sql
/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_FINANZAS_GET
Archivo: SP_FINANZAS_GET.sql | Procedimiento: FINANZAS.SP_FINANZAS_GET | Tipo: QUERY
Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera cajas, cobros, deuda por venta y cuenta corriente de una empresa.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [FINANZAS].[SP_FINANZAS_GET]
    @I_ID_EMPRESA BIGINT,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;

    -- INICIO: Sucursales disponibles para asignar una caja física.
    SELECT [ID_SUCURSAL], [CODIGO], [NOMBRE]
    FROM [CONFIGURACION].[SUCURSALES]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [NOMBRE];
    -- FIN: Sucursales disponibles para asignar una caja física.

    -- INICIO: Clientes y su saldo contable actual por moneda.
    SELECT [CLI].[ID_CLIENTE], [CLI].[CODIGO],
           CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           COALESCE(SUM(CASE WHEN [MOV].[TIPO_MOVIMIENTO] = N'DEBITO' THEN [MOV].[IMPORTE] ELSE -[MOV].[IMPORTE] END), 0) AS [SALDO]
    FROM [COMERCIAL].[CLIENTES] AS [CLI]
    LEFT JOIN [FINANZAS].[MOVIMIENTOS_CUENTA] AS [MOV]
        ON [MOV].[ID_CLIENTE] = [CLI].[ID_CLIENTE]
       AND [MOV].[ID_EMPRESA] = @I_ID_EMPRESA
       AND [MOV].[MONEDA] = 'ARS'
       AND [MOV].[CODIGO_ESTADO] = N'CONFIRMADO'
    WHERE [CLI].[ID_EMPRESA] = @I_ID_EMPRESA AND [CLI].[CODIGO_ESTADO] = N'ACTIVO'
    GROUP BY [CLI].[ID_CLIENTE], [CLI].[CODIGO], [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]
    ORDER BY [CLIENTE];
    -- FIN: Clientes y su saldo contable actual por moneda.

    SELECT [ID_MEDIO_PAGO], [CODIGO], [NOMBRE], [TIPO], [AFECTA_EFECTIVO],
           [REQUIERE_REFERENCIA], [CODIGO_ESTADO], [ROW_VERSION]
    FROM [FINANZAS].[MEDIOS_PAGO]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [NOMBRE];

    SELECT [CAJ].[ID_CAJA], [CAJ].[ID_SUCURSAL], [CAJ].[CODIGO], [CAJ].[NOMBRE],
           [SUC].[NOMBRE] AS [SUCURSAL], [CAJ].[MONEDA], [CAJ].[CODIGO_ESTADO], [CAJ].[ROW_VERSION]
    FROM [FINANZAS].[CAJAS] AS [CAJ]
    INNER JOIN [CONFIGURACION].[SUCURSALES] AS [SUC] ON [SUC].[ID_SUCURSAL] = [CAJ].[ID_SUCURSAL]
    WHERE [CAJ].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [SUCURSAL], [CAJ].[NOMBRE];

    -- INICIO: Aperturas y cierres conservan los importes declarados y calculados.
    SELECT [SES].[ID_SESION_CAJA], [SES].[ID_CAJA], [CAJ].[NOMBRE] AS [CAJA],
           [SES].[ID_USUARIO_APERTURA], [USR].[NOMBRE_USUARIO] AS [USUARIO],
           [SES].[FECHA_APERTURA_UTC], [SES].[IMPORTE_APERTURA], [SES].[FECHA_CIERRE_UTC],
           [SES].[IMPORTE_ESPERADO], [SES].[IMPORTE_CONTADO], [SES].[DIFERENCIA],
           [SES].[OBSERVACION_APERTURA], [SES].[OBSERVACION_CIERRE],
           [SES].[CODIGO_ESTADO], [SES].[ROW_VERSION]
    FROM [FINANZAS].[SESIONES_CAJA] AS [SES]
    INNER JOIN [FINANZAS].[CAJAS] AS [CAJ] ON [CAJ].[ID_CAJA] = [SES].[ID_CAJA]
    INNER JOIN [SEGURIDAD].[USUARIOS] AS [USR] ON [USR].[ID_USUARIO] = [SES].[ID_USUARIO_APERTURA]
    WHERE [SES].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [SES].[FECHA_APERTURA_UTC] DESC;
    -- FIN: Aperturas y cierres conservan los importes declarados y calculados.

    -- INICIO: Ventas internas y saldo pendiente derivado de aplicaciones vigentes.
    SELECT [VEN].[ID_VENTA], [VEN].[ID_CLIENTE], [VEN].[CODIGO], [VEN].[FECHA_VENTA_UTC],
           CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [VEN].[MONEDA], [VEN].[TOTAL],
           [VEN].[TOTAL] - COALESCE(SUM(CASE WHEN [PAG].[CODIGO_ESTADO] = N'CONFIRMADO' AND [APL].[CODIGO_ESTADO] = N'APLICADA' THEN [APL].[IMPORTE] ELSE 0 END), 0) AS [SALDO_PENDIENTE],
           [VEN].[CODIGO_ESTADO]
    FROM [COMERCIAL].[VENTAS] AS [VEN]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [VEN].[ID_CLIENTE]
    LEFT JOIN [FINANZAS].[APLICACIONES_PAGO_VENTA] AS [APL] ON [APL].[ID_VENTA] = [VEN].[ID_VENTA]
    LEFT JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [APL].[ID_PAGO]
    WHERE [VEN].[ID_EMPRESA] = @I_ID_EMPRESA
    GROUP BY [VEN].[ID_VENTA], [VEN].[ID_CLIENTE], [VEN].[CODIGO], [VEN].[FECHA_VENTA_UTC],
             [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO], [VEN].[MONEDA], [VEN].[TOTAL], [VEN].[CODIGO_ESTADO]
    ORDER BY [VEN].[FECHA_VENTA_UTC] DESC;
    -- FIN: Ventas internas y saldo pendiente derivado de aplicaciones vigentes.

    SELECT [PAG].[ID_PAGO], [PAG].[ID_CLIENTE], [PAG].[ID_SESION_CAJA], [PAG].[CODIGO],
           [PAG].[FECHA_PAGO_UTC], CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [PAG].[MONEDA], [PAG].[TOTAL], [PAG].[OBSERVACION], [PAG].[MOTIVO_REVERSION],
           [PAG].[FECHA_REVERSION_UTC], [PAG].[CODIGO_ESTADO], [PAG].[ROW_VERSION]
    FROM [FINANZAS].[PAGOS] AS [PAG]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [PAG].[ID_CLIENTE]
    WHERE [PAG].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PAG].[FECHA_PAGO_UTC] DESC;

    SELECT [PM].[ID_PAGO_MEDIO], [PM].[ID_PAGO], [PM].[ID_MEDIO_PAGO], [MED].[NOMBRE] AS [MEDIO_PAGO],
           [PM].[IMPORTE], [PM].[REFERENCIA], [PM].[CODIGO_ESTADO]
    FROM [FINANZAS].[PAGOS_MEDIOS] AS [PM]
    INNER JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [PM].[ID_PAGO]
    INNER JOIN [FINANZAS].[MEDIOS_PAGO] AS [MED] ON [MED].[ID_MEDIO_PAGO] = [PM].[ID_MEDIO_PAGO]
    WHERE [PAG].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PM].[ID_PAGO], [PM].[ID_PAGO_MEDIO];

    SELECT [APL].[ID_APLICACION_PAGO_VENTA], [APL].[ID_PAGO], [APL].[ID_VENTA],
           [VEN].[CODIGO] AS [VENTA], [APL].[IMPORTE], [APL].[CODIGO_ESTADO]
    FROM [FINANZAS].[APLICACIONES_PAGO_VENTA] AS [APL]
    INNER JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [APL].[ID_PAGO]
    INNER JOIN [COMERCIAL].[VENTAS] AS [VEN] ON [VEN].[ID_VENTA] = [APL].[ID_VENTA]
    WHERE [PAG].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [APL].[ID_PAGO], [APL].[ID_APLICACION_PAGO_VENTA];

    SELECT TOP (1000) [MOV].[ID_MOVIMIENTO_CUENTA], [MOV].[ID_CLIENTE], [MOV].[ID_VENTA],
           [MOV].[ID_PAGO], [MOV].[TIPO_MOVIMIENTO], [MOV].[ORIGEN], [MOV].[FECHA_MOVIMIENTO_UTC],
           [MOV].[MONEDA], [MOV].[IMPORTE], [MOV].[DESCRIPCION], [MOV].[CORRELACION], [MOV].[CODIGO_ESTADO]
    FROM [FINANZAS].[MOVIMIENTOS_CUENTA] AS [MOV]
    WHERE [MOV].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [MOV].[FECHA_MOVIMIENTO_UTC] DESC, [MOV].[ID_MOVIMIENTO_CUENTA] DESC;
END;
GO

-- Fuente versionada: database/06_StoredProcedures/FINANZAS/Commands/SP_FINANZAS_COMMAND.sql
/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_FINANZAS_COMMAND
Archivo: SP_FINANZAS_COMMAND.sql | Procedimiento: FINANZAS.SP_FINANZAS_COMMAND | Tipo: COMMAND
Versión: 11.0.1 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Ejecuta acciones financieras no fiscales y conserva su trazabilidad.
Acciones admitidas mediante @I_ACCION:
- MEDIO_GUARDAR: crea o modifica un medio. Requiere código, nombre, tipo, indicadores y estado.
- CAJA_GUARDAR: crea o modifica una caja física. Requiere sucursal, código, nombre, moneda y estado.
- SESION_ABRIR: abre una caja activa. Requiere caja e importe inicial; un usuario y una caja solo admiten una apertura.
- SESION_CERRAR: cierra una apertura vigente. Requiere sesión, importe contado y rowversion.
- PAGO_REGISTRAR: registra un cobro. Requiere cliente, fecha, moneda, total, medios JSON y aplicaciones JSON opcionales.
- PAGO_REVERSAR: compensa un cobro confirmado. Requiere pago, motivo y rowversion; no elimina registros.
Uso: enviar únicamente los parámetros indicados para la acción elegida; los demás permanecen NULL.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 11.0.1 | 2026-08-27 | FABRICA | Rechazo explícito de medios y ventas inexistentes.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [FINANZAS].[SP_FINANZAS_COMMAND]
    @I_ACCION NVARCHAR(30),
    @I_ID_EMPRESA BIGINT,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @I_ID BIGINT = NULL,
    @I_ID_SUCURSAL BIGINT = NULL,
    @I_ID_CLIENTE BIGINT = NULL,
    @I_ID_SESION_CAJA BIGINT = NULL,
    @I_CODIGO NVARCHAR(30) = NULL,
    @I_NOMBRE NVARCHAR(100) = NULL,
    @I_TIPO NVARCHAR(30) = NULL,
    @I_MONEDA CHAR(3) = NULL,
    @I_FECHA_UTC DATETIME2(3) = NULL,
    @I_IMPORTE DECIMAL(19,4) = NULL,
    @I_IMPORTE_CONTADO DECIMAL(19,4) = NULL,
    @I_AFECTA_EFECTIVO BIT = NULL,
    @I_REQUIERE_REFERENCIA BIT = NULL,
    @I_CODIGO_ESTADO NVARCHAR(30) = NULL,
    @I_OBSERVACION NVARCHAR(500) = NULL,
    @I_JSON_MEDIOS NVARCHAR(MAX) = NULL,
    @I_JSON_APLICACIONES NVARCHAR(MAX) = NULL,
    @I_ROW_VERSION VARBINARY(8) = NULL,
    @O_ID BIGINT OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @O_ID = NULL;
    SET @O_FILAS_AFECTADAS = 0;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;

    BEGIN TRY
        IF @I_ACCION NOT IN (N'MEDIO_GUARDAR', N'CAJA_GUARDAR', N'SESION_ABRIR',
                             N'SESION_CERRAR', N'PAGO_REGISTRAR', N'PAGO_REVERSAR')
            THROW 52001, N'La acción financiera no es válida.', 1;

        BEGIN TRANSACTION;

        -- INICIO: Alta o edición del catálogo de medios de pago.
        IF @I_ACCION = N'MEDIO_GUARDAR'
        BEGIN
            SET @I_CODIGO = UPPER(TRIM(@I_CODIGO));
            SET @I_NOMBRE = TRIM(@I_NOMBRE);
            IF NULLIF(@I_CODIGO, N'') IS NULL OR NULLIF(@I_NOMBRE, N'') IS NULL OR
               @I_TIPO NOT IN (N'EFECTIVO', N'TRANSFERENCIA', N'TARJETA', N'CHEQUE', N'OTRO') OR
               @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO')
                THROW 52001, N'Completá código, nombre, tipo y estado válidos para el medio de pago.', 1;

            IF @I_ID IS NULL
            BEGIN
                INSERT INTO [FINANZAS].[MEDIOS_PAGO]
                    ([ID_EMPRESA], [CODIGO], [NOMBRE], [TIPO], [AFECTA_EFECTIVO],
                     [REQUIERE_REFERENCIA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
                VALUES
                    (@I_ID_EMPRESA, @I_CODIGO, @I_NOMBRE, @I_TIPO, COALESCE(@I_AFECTA_EFECTIVO, 0),
                     COALESCE(@I_REQUIERE_REFERENCIA, 0), @I_CODIGO_ESTADO, @S_ID_USUARIO);
                SET @O_ID = CONVERT(BIGINT, SCOPE_IDENTITY());
            END
            ELSE
            BEGIN
                UPDATE [FINANZAS].[MEDIOS_PAGO]
                SET [NOMBRE] = @I_NOMBRE,
                    [TIPO] = @I_TIPO,
                    [AFECTA_EFECTIVO] = COALESCE(@I_AFECTA_EFECTIVO, 0),
                    [REQUIERE_REFERENCIA] = COALESCE(@I_REQUIERE_REFERENCIA, 0),
                    [CODIGO_ESTADO] = @I_CODIGO_ESTADO,
                    [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(),
                    [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
                WHERE [ID_MEDIO_PAGO] = @I_ID AND [ID_EMPRESA] = @I_ID_EMPRESA
                  AND [CODIGO] = @I_CODIGO AND [ROW_VERSION] = @I_ROW_VERSION;
                IF @@ROWCOUNT = 0 THROW 52002, N'El medio de pago fue modificado o no existe.', 1;
                SET @O_ID = @I_ID;
            END;
            SET @O_FILAS_AFECTADAS = 1;
        END;
        -- FIN: Alta o edición del catálogo de medios de pago.

        -- INICIO: Alta o edición de una caja física vinculada a una sucursal.
        IF @I_ACCION = N'CAJA_GUARDAR'
        BEGIN
            SET @I_CODIGO = UPPER(TRIM(@I_CODIGO));
            SET @I_NOMBRE = TRIM(@I_NOMBRE);
            SET @I_MONEDA = UPPER(TRIM(@I_MONEDA));
            IF NULLIF(@I_CODIGO, N'') IS NULL OR NULLIF(@I_NOMBRE, N'') IS NULL OR
               LEN(@I_MONEDA) <> 3 OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO') OR
               NOT EXISTS (SELECT 1 FROM [CONFIGURACION].[SUCURSALES]
                           WHERE [ID_SUCURSAL] = @I_ID_SUCURSAL AND [ID_EMPRESA] = @I_ID_EMPRESA
                             AND [CODIGO_ESTADO] = N'ACTIVO')
                THROW 52001, N'Completá sucursal, código, nombre, moneda y estado válidos para la caja.', 1;

            IF @I_ID IS NULL
            BEGIN
                INSERT INTO [FINANZAS].[CAJAS]
                    ([ID_EMPRESA], [ID_SUCURSAL], [CODIGO], [NOMBRE], [MONEDA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
                VALUES
                    (@I_ID_EMPRESA, @I_ID_SUCURSAL, @I_CODIGO, @I_NOMBRE, @I_MONEDA, @I_CODIGO_ESTADO, @S_ID_USUARIO);
                SET @O_ID = CONVERT(BIGINT, SCOPE_IDENTITY());
            END
            ELSE
            BEGIN
                IF @I_CODIGO_ESTADO = N'INACTIVO' AND EXISTS
                    (SELECT 1 FROM [FINANZAS].[SESIONES_CAJA] WHERE [ID_CAJA] = @I_ID AND [CODIGO_ESTADO] = N'ABIERTA')
                    THROW 52002, N'No se puede inactivar una caja con una sesión abierta.', 1;

                UPDATE [FINANZAS].[CAJAS]
                SET [ID_SUCURSAL] = @I_ID_SUCURSAL, [NOMBRE] = @I_NOMBRE, [MONEDA] = @I_MONEDA,
                    [CODIGO_ESTADO] = @I_CODIGO_ESTADO, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(),
                    [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
                WHERE [ID_CAJA] = @I_ID AND [ID_EMPRESA] = @I_ID_EMPRESA
                  AND [CODIGO] = @I_CODIGO AND [ROW_VERSION] = @I_ROW_VERSION;
                IF @@ROWCOUNT = 0 THROW 52002, N'La caja fue modificada o no existe.', 1;
                SET @O_ID = @I_ID;
            END;
            SET @O_FILAS_AFECTADAS = 1;
        END;
        -- FIN: Alta o edición de una caja física vinculada a una sucursal.

        -- INICIO: Apertura de caja exclusiva para el punto físico y el usuario.
        IF @I_ACCION = N'SESION_ABRIR'
        BEGIN
            IF COALESCE(@I_IMPORTE, -1) < 0 OR NOT EXISTS
                (SELECT 1 FROM [FINANZAS].[CAJAS]
                 WHERE [ID_CAJA] = @I_ID AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO')
                THROW 52001, N'Seleccioná una caja activa e informá un importe inicial válido.', 1;
            IF EXISTS (SELECT 1 FROM [FINANZAS].[SESIONES_CAJA]
                       WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND
                             ([ID_CAJA] = @I_ID OR [ID_USUARIO_APERTURA] = @S_ID_USUARIO) AND [CODIGO_ESTADO] = N'ABIERTA')
                THROW 52002, N'La caja o el usuario ya posee una sesión abierta.', 1;

            INSERT INTO [FINANZAS].[SESIONES_CAJA]
                ([ID_EMPRESA], [ID_CAJA], [ID_USUARIO_APERTURA], [FECHA_APERTURA_UTC],
                 [IMPORTE_APERTURA], [OBSERVACION_APERTURA], [ID_USUARIO_ALTA])
            VALUES
                (@I_ID_EMPRESA, @I_ID, @S_ID_USUARIO, COALESCE(@I_FECHA_UTC, SYSUTCDATETIME()),
                 @I_IMPORTE, NULLIF(TRIM(@I_OBSERVACION), N''), @S_ID_USUARIO);
            SET @O_ID = CONVERT(BIGINT, SCOPE_IDENTITY());
            SET @O_FILAS_AFECTADAS = 1;
        END;
        -- FIN: Apertura de caja exclusiva para el punto físico y el usuario.

        -- INICIO: Cierre con cálculo autoritativo del efectivo esperado.
        IF @I_ACCION = N'SESION_CERRAR'
        BEGIN
            IF COALESCE(@I_IMPORTE_CONTADO, -1) < 0
                THROW 52001, N'El importe contado debe ser cero o mayor.', 1;

            DECLARE @V_ESPERADO DECIMAL(19,4);
            SELECT @V_ESPERADO = [SES].[IMPORTE_APERTURA] + COALESCE(SUM(
                CASE WHEN [MED].[AFECTA_EFECTIVO] = 1 AND [PAG].[CODIGO_ESTADO] = N'CONFIRMADO'
                     THEN [PM].[IMPORTE] ELSE 0 END), 0)
            FROM [FINANZAS].[SESIONES_CAJA] AS [SES]
            LEFT JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_SESION_CAJA] = [SES].[ID_SESION_CAJA]
            LEFT JOIN [FINANZAS].[PAGOS_MEDIOS] AS [PM] ON [PM].[ID_PAGO] = [PAG].[ID_PAGO]
            LEFT JOIN [FINANZAS].[MEDIOS_PAGO] AS [MED] ON [MED].[ID_MEDIO_PAGO] = [PM].[ID_MEDIO_PAGO]
            WHERE [SES].[ID_SESION_CAJA] = @I_ID AND [SES].[ID_EMPRESA] = @I_ID_EMPRESA
              AND [SES].[ID_USUARIO_APERTURA] = @S_ID_USUARIO AND [SES].[CODIGO_ESTADO] = N'ABIERTA'
              AND [SES].[ROW_VERSION] = @I_ROW_VERSION
            GROUP BY [SES].[IMPORTE_APERTURA];
            IF @V_ESPERADO IS NULL THROW 52002, N'La sesión fue modificada, no está abierta o pertenece a otro usuario.', 1;

            UPDATE [FINANZAS].[SESIONES_CAJA]
            SET [FECHA_CIERRE_UTC] = COALESCE(@I_FECHA_UTC, SYSUTCDATETIME()),
                [ID_USUARIO_CIERRE] = @S_ID_USUARIO,
                [IMPORTE_ESPERADO] = @V_ESPERADO,
                [IMPORTE_CONTADO] = @I_IMPORTE_CONTADO,
                [DIFERENCIA] = @I_IMPORTE_CONTADO - @V_ESPERADO,
                [OBSERVACION_CIERRE] = NULLIF(TRIM(@I_OBSERVACION), N''),
                [CODIGO_ESTADO] = N'CERRADA',
                [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(),
                [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
            WHERE [ID_SESION_CAJA] = @I_ID;
            SET @O_ID = @I_ID;
            SET @O_FILAS_AFECTADAS = 1;
        END;
        -- FIN: Cierre con cálculo autoritativo del efectivo esperado.

        -- INICIO: Cobro confirmado con medios y aplicaciones en una sola transacción.
        IF @I_ACCION = N'PAGO_REGISTRAR'
        BEGIN
            IF COALESCE(@I_IMPORTE, 0) <= 0 OR @I_FECHA_UTC IS NULL OR LEN(UPPER(TRIM(@I_MONEDA))) <> 3 OR
               NOT EXISTS (SELECT 1 FROM [COMERCIAL].[CLIENTES]
                           WHERE [ID_CLIENTE] = @I_ID_CLIENTE AND [ID_EMPRESA] = @I_ID_EMPRESA
                             AND [CODIGO_ESTADO] = N'ACTIVO')
                THROW 52001, N'Informá cliente activo, fecha, moneda y un total mayor que cero.', 1;

            DECLARE @V_MEDIOS TABLE
            (
                [ID_MEDIO_PAGO] BIGINT NOT NULL,
                [IMPORTE] DECIMAL(19,4) NOT NULL,
                [REFERENCIA] NVARCHAR(100) NULL
            );
            INSERT INTO @V_MEDIOS ([ID_MEDIO_PAGO], [IMPORTE], [REFERENCIA])
            SELECT [ID_MEDIO_PAGO], [IMPORTE], NULLIF(TRIM([REFERENCIA]), N'')
            FROM OPENJSON(COALESCE(@I_JSON_MEDIOS, N'[]')) WITH
            (
                [ID_MEDIO_PAGO] BIGINT '$.PaymentMethodId',
                [IMPORTE] DECIMAL(19,4) '$.Amount',
                [REFERENCIA] NVARCHAR(100) '$.Reference'
            );

            IF NOT EXISTS (SELECT 1 FROM @V_MEDIOS) OR EXISTS (SELECT 1 FROM @V_MEDIOS WHERE [IMPORTE] <= 0) OR
               ABS((SELECT SUM([IMPORTE]) FROM @V_MEDIOS) - @I_IMPORTE) > 0.0001
                THROW 52001, N'Los medios de pago deben sumar exactamente el total del cobro.', 1;
            IF EXISTS
            (
                SELECT 1 FROM @V_MEDIOS AS [ENT]
                LEFT JOIN [FINANZAS].[MEDIOS_PAGO] AS [MED] ON [MED].[ID_MEDIO_PAGO] = [ENT].[ID_MEDIO_PAGO]
                WHERE [MED].[ID_MEDIO_PAGO] IS NULL OR [MED].[ID_EMPRESA] <> @I_ID_EMPRESA OR
                      [MED].[CODIGO_ESTADO] <> N'ACTIVO' OR
                      ([MED].[REQUIERE_REFERENCIA] = 1 AND [ENT].[REFERENCIA] IS NULL)
            )
                THROW 52001, N'Existe un medio inactivo, ajeno o sin la referencia obligatoria.', 1;

            IF EXISTS (SELECT 1 FROM @V_MEDIOS AS [ENT] INNER JOIN [FINANZAS].[MEDIOS_PAGO] AS [MED]
                       ON [MED].[ID_MEDIO_PAGO] = [ENT].[ID_MEDIO_PAGO] WHERE [MED].[AFECTA_EFECTIVO] = 1)
               AND NOT EXISTS
               (SELECT 1 FROM [FINANZAS].[SESIONES_CAJA]
                WHERE [ID_SESION_CAJA] = @I_ID_SESION_CAJA AND [ID_EMPRESA] = @I_ID_EMPRESA
                  AND [ID_USUARIO_APERTURA] = @S_ID_USUARIO AND [CODIGO_ESTADO] = N'ABIERTA')
                THROW 52002, N'Para cobrar en efectivo debés seleccionar tu sesión de caja abierta.', 1;

            DECLARE @V_APLICACIONES TABLE ([ID_VENTA] BIGINT NOT NULL, [IMPORTE] DECIMAL(19,4) NOT NULL);
            INSERT INTO @V_APLICACIONES ([ID_VENTA], [IMPORTE])
            SELECT [ID_VENTA], [IMPORTE]
            FROM OPENJSON(COALESCE(@I_JSON_APLICACIONES, N'[]')) WITH
            (
                [ID_VENTA] BIGINT '$.SaleId',
                [IMPORTE] DECIMAL(19,4) '$.Amount'
            );
            IF EXISTS (SELECT 1 FROM @V_APLICACIONES WHERE [IMPORTE] <= 0) OR
               COALESCE((SELECT SUM([IMPORTE]) FROM @V_APLICACIONES), 0) > @I_IMPORTE OR
               EXISTS (SELECT [ID_VENTA] FROM @V_APLICACIONES GROUP BY [ID_VENTA] HAVING COUNT(*) > 1)
                THROW 52001, N'Las aplicaciones deben ser únicas, positivas y no superar el cobro.', 1;
            IF EXISTS
            (
                SELECT 1
                FROM @V_APLICACIONES AS [ENT]
                LEFT JOIN [COMERCIAL].[VENTAS] AS [VEN] ON [VEN].[ID_VENTA] = [ENT].[ID_VENTA]
                OUTER APPLY
                (
                    SELECT COALESCE(SUM([APL].[IMPORTE]), 0) AS [APLICADO]
                    FROM [FINANZAS].[APLICACIONES_PAGO_VENTA] AS [APL]
                    INNER JOIN [FINANZAS].[PAGOS] AS [PAG] ON [PAG].[ID_PAGO] = [APL].[ID_PAGO]
                    WHERE [APL].[ID_VENTA] = [ENT].[ID_VENTA] AND [APL].[CODIGO_ESTADO] = N'APLICADA'
                      AND [PAG].[CODIGO_ESTADO] = N'CONFIRMADO'
                ) AS [SAL]
                WHERE [VEN].[ID_VENTA] IS NULL OR [VEN].[ID_EMPRESA] <> @I_ID_EMPRESA OR
                      [VEN].[ID_CLIENTE] <> @I_ID_CLIENTE OR
                      [VEN].[MONEDA] <> UPPER(@I_MONEDA) OR [VEN].[CODIGO_ESTADO] <> N'CONFIRMADA' OR
                      [ENT].[IMPORTE] > [VEN].[TOTAL] - [SAL].[APLICADO]
            )
                THROW 52003, N'Una aplicación supera el saldo o no corresponde al cliente y moneda del cobro.', 1;

            DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [FINANZAS].[SEQ_PAGO_CODIGO];
            DECLARE @V_CODIGO NVARCHAR(30) = N'REC-' + CASE WHEN @V_NUMERO < 1000000
                THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6)
                ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;

            INSERT INTO [FINANZAS].[PAGOS]
                ([ID_EMPRESA], [ID_CLIENTE], [ID_SESION_CAJA], [CODIGO], [FECHA_PAGO_UTC],
                 [MONEDA], [TOTAL], [OBSERVACION], [ID_USUARIO_ALTA])
            VALUES
                (@I_ID_EMPRESA, @I_ID_CLIENTE, @I_ID_SESION_CAJA, @V_CODIGO, @I_FECHA_UTC,
                 UPPER(@I_MONEDA), @I_IMPORTE, NULLIF(TRIM(@I_OBSERVACION), N''), @S_ID_USUARIO);
            SET @O_ID = CONVERT(BIGINT, SCOPE_IDENTITY());

            INSERT INTO [FINANZAS].[PAGOS_MEDIOS]
                ([ID_PAGO], [ID_MEDIO_PAGO], [IMPORTE], [REFERENCIA], [ID_USUARIO_ALTA])
            SELECT @O_ID, [ID_MEDIO_PAGO], [IMPORTE], [REFERENCIA], @S_ID_USUARIO FROM @V_MEDIOS;

            INSERT INTO [FINANZAS].[APLICACIONES_PAGO_VENTA]
                ([ID_PAGO], [ID_VENTA], [IMPORTE], [ID_USUARIO_ALTA])
            SELECT @O_ID, [ID_VENTA], [IMPORTE], @S_ID_USUARIO FROM @V_APLICACIONES;

            INSERT INTO [FINANZAS].[MOVIMIENTOS_CUENTA]
                ([ID_EMPRESA], [ID_CLIENTE], [ID_PAGO], [TIPO_MOVIMIENTO], [ORIGEN],
                 [FECHA_MOVIMIENTO_UTC], [MONEDA], [IMPORTE], [DESCRIPCION], [ID_USUARIO_ALTA])
            VALUES
                (@I_ID_EMPRESA, @I_ID_CLIENTE, @O_ID, N'CREDITO', N'PAGO', @I_FECHA_UTC,
                 UPPER(@I_MONEDA), @I_IMPORTE, N'Cobro interno ' + @V_CODIGO, @S_ID_USUARIO);
            SET @O_FILAS_AFECTADAS = 2 + (SELECT COUNT(*) FROM @V_MEDIOS) + (SELECT COUNT(*) FROM @V_APLICACIONES);
        END;
        -- FIN: Cobro confirmado con medios y aplicaciones en una sola transacción.

        -- INICIO: Reversión compensatoria sin pérdida del movimiento original.
        IF @I_ACCION = N'PAGO_REVERSAR'
        BEGIN
            IF NULLIF(TRIM(@I_OBSERVACION), N'') IS NULL
                THROW 52001, N'El motivo de reversión es obligatorio.', 1;
            DECLARE @V_ID_CLIENTE BIGINT, @V_TOTAL DECIMAL(19,4), @V_MONEDA CHAR(3), @V_CODIGO_PAGO NVARCHAR(30);
            SELECT @V_ID_CLIENTE = [ID_CLIENTE], @V_TOTAL = [TOTAL], @V_MONEDA = [MONEDA], @V_CODIGO_PAGO = [CODIGO]
            FROM [FINANZAS].[PAGOS] WITH (UPDLOCK, HOLDLOCK)
            WHERE [ID_PAGO] = @I_ID AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'CONFIRMADO'
              AND [ROW_VERSION] = @I_ROW_VERSION
              AND ([ID_SESION_CAJA] IS NULL OR EXISTS
                  (SELECT 1 FROM [FINANZAS].[SESIONES_CAJA] WHERE [ID_SESION_CAJA] = [PAGOS].[ID_SESION_CAJA]
                                                               AND [CODIGO_ESTADO] = N'ABIERTA'));
            IF @V_ID_CLIENTE IS NULL
                THROW 52004, N'El cobro fue modificado, ya fue revertido o pertenece a una caja cerrada.', 1;

            UPDATE [FINANZAS].[PAGOS]
            SET [MOTIVO_REVERSION] = TRIM(@I_OBSERVACION), [FECHA_REVERSION_UTC] = SYSUTCDATETIME(),
                [ID_USUARIO_REVERSION] = @S_ID_USUARIO, [CODIGO_ESTADO] = N'REVERTIDO',
                [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
            WHERE [ID_PAGO] = @I_ID;
            UPDATE [FINANZAS].[APLICACIONES_PAGO_VENTA]
            SET [CODIGO_ESTADO] = N'REVERTIDA', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(),
                [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
            WHERE [ID_PAGO] = @I_ID AND [CODIGO_ESTADO] = N'APLICADA';
            INSERT INTO [FINANZAS].[MOVIMIENTOS_CUENTA]
                ([ID_EMPRESA], [ID_CLIENTE], [ID_PAGO], [TIPO_MOVIMIENTO], [ORIGEN],
                 [FECHA_MOVIMIENTO_UTC], [MONEDA], [IMPORTE], [DESCRIPCION], [ID_USUARIO_ALTA])
            VALUES
                (@I_ID_EMPRESA, @V_ID_CLIENTE, @I_ID, N'DEBITO', N'REVERSO_PAGO', SYSUTCDATETIME(),
                 @V_MONEDA, @V_TOTAL, N'Reversión del cobro ' + @V_CODIGO_PAGO + N': ' + TRIM(@I_OBSERVACION), @S_ID_USUARIO);
            SET @O_ID = @I_ID;
            SET @O_FILAS_AFECTADAS = 2 + @@ROWCOUNT;
        END;
        -- FIN: Reversión compensatoria sin pérdida del movimiento original.

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
        SET @O_CODIGO_ERROR = CASE WHEN ERROR_NUMBER() BETWEEN 52001 AND 52099
                                   THEN 80000 + ERROR_NUMBER() - 52000 ELSE 80001 END;
        SET @O_MENSAJE = ERROR_MESSAGE();
    END CATCH;
END;
GO

-- Fuente versionada: database/06_StoredProcedures/COMERCIAL/Commands/SP_VENTA_CREATE_FROM_PEDIDO.sql
/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_VENTA_CREATE_FROM_PEDIDO
Archivo: SP_VENTA_CREATE_FROM_PEDIDO.sql | Procedimiento: COMERCIAL.SP_VENTA_CREATE_FROM_PEDIDO | Tipo: COMMAND
Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Convierte un pedido confirmado en venta interna y descuenta el stock reservado.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Copia la fotografía promocional a la venta inmutable.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Débito automático e inmutable en cuenta corriente.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO]
    @I_ID_PEDIDO BIGINT, @I_ID_EMPRESA BIGINT, @I_FECHA_VENTA_UTC DATETIME2(3), @I_ROW_VERSION BINARY(8),
    @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT, @O_ID_VENTA BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_ID_VENTA = NULL; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_VENTA_UTC IS NULL THROW 50000, 'La fecha de venta es obligatoria.', 1;
    DECLARE @V_INICIO_TRANSACCION BIT = 0, @V_ID_MOVIMIENTO BIGINT, @V_CODIGO_MOVIMIENTO BIGINT, @V_MENSAJE_MOVIMIENTO NVARCHAR(4000), @V_FILAS_MOVIMIENTO INT;
    BEGIN TRY
        IF @@TRANCOUNT = 0 BEGIN BEGIN TRANSACTION; SET @V_INICIO_TRANSACCION = 1; END ELSE SAVE TRANSACTION [SP_VENTA_CREATE_SAVEPOINT];
        IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'CONFIRMADO' AND [ROW_VERSION] = @I_ROW_VERSION)
        BEGIN SET @O_CODIGO_ERROR = 40006; SET @O_MENSAJE = N'El pedido fue modificado o no está confirmado.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;
        IF EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET] WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO' AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[RESERVAS_STOCK] AS [RES] WHERE [RES].[ID_PEDIDO_DETALLE] = [DET].[ID_PEDIDO_DETALLE] AND [RES].[CODIGO_ESTADO] = N'RESERVADA' AND [RES].[CANTIDAD] = [DET].[CANTIDAD]))
        BEGIN SET @O_CODIGO_ERROR = 40005; SET @O_MENSAJE = N'El pedido no conserva todas sus reservas de stock.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;

        DECLARE @V_DETALLES_JSON NVARCHAR(MAX) = (SELECT [ID_PRODUCTO] AS [ProductId], [ID_DEPOSITO] AS [OriginWarehouseId], [CANTIDAD] AS [Quantity] FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO' FOR JSON PATH);
        DECLARE @V_OBSERVACION_MOVIMIENTO NVARCHAR(500) = N'Venta originada por pedido ' + CONVERT(NVARCHAR(30), @I_ID_PEDIDO);
        EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @I_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'SALIDA', @I_FECHA_MOVIMIENTO_UTC = @I_FECHA_VENTA_UTC,
            @I_OBSERVACION = @V_OBSERVACION_MOVIMIENTO, @I_DETALLES_JSON = @V_DETALLES_JSON, @I_ID_PEDIDO_RESERVADO = @I_ID_PEDIDO,
            @S_ID_SESION = @S_ID_SESION, @S_ID_USUARIO = @S_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_MOVIMIENTO OUTPUT,
            @O_MENSAJE = @V_MENSAJE_MOVIMIENTO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_MOVIMIENTO OUTPUT;
        IF @V_CODIGO_MOVIMIENTO IS NOT NULL BEGIN SET @O_CODIGO_ERROR = @V_CODIGO_MOVIMIENTO; SET @O_MENSAJE = @V_MENSAJE_MOVIMIENTO; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_VENTA_CREATE_SAVEPOINT]; RETURN; END;

        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMERCIAL].[SEQ_VENTA_CODIGO], @V_CODIGO NVARCHAR(30);
        SET @V_CODIGO = N'VEN-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;
        INSERT INTO [COMERCIAL].[VENTAS] ([ID_EMPRESA], [ID_PEDIDO], [ID_CLIENTE], [ID_MOVIMIENTO], [CODIGO], [FECHA_VENTA_UTC], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT [ID_EMPRESA], [ID_PEDIDO], [ID_CLIENTE], @V_ID_MOVIMIENTO, @V_CODIGO, @I_FECHA_VENTA_UTC, [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], N'CONFIRMADA', @S_ID_USUARIO FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        SET @O_ID_VENTA = CONVERT(BIGINT, SCOPE_IDENTITY());

        -- INICIO: La venta genera el débito base de la cuenta corriente sin duplicar saldos.
        INSERT INTO [FINANZAS].[MOVIMIENTOS_CUENTA]
        (
            [ID_EMPRESA], [ID_CLIENTE], [ID_VENTA], [TIPO_MOVIMIENTO], [ORIGEN],
            [FECHA_MOVIMIENTO_UTC], [MONEDA], [IMPORTE], [DESCRIPCION], [ID_USUARIO_ALTA]
        )
        SELECT [ID_EMPRESA], [ID_CLIENTE], [ID_VENTA], N'DEBITO', N'VENTA',
               [FECHA_VENTA_UTC], [MONEDA], [TOTAL], N'Venta interna ' + [CODIGO], @S_ID_USUARIO
        FROM [COMERCIAL].[VENTAS]
        WHERE [ID_VENTA] = @O_ID_VENTA;
        -- FIN: La venta genera el débito base de la cuenta corriente sin duplicar saldos.

        INSERT INTO [COMERCIAL].[VENTAS_DETALLES] ([ID_VENTA], [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_VENTA, [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], N'ACTIVO', @S_ID_USUARIO FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO';
        SET @O_FILAS_AFECTADAS = 2 + @@ROWCOUNT + COALESCE(@V_FILAS_MOVIMIENTO, 0);
        UPDATE [INVENTARIO].[RESERVAS_STOCK] SET [CODIGO_ESTADO] = N'APLICADA', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'RESERVADA';
        UPDATE [COMERCIAL].[PEDIDOS] SET [CODIGO_ESTADO] = N'VENDIDO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION; ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_VENTA_CREATE_SAVEPOINT]; SET @O_MENSAJE = ERROR_MESSAGE(); THROW;
    END CATCH;
END;
GO
