/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Migración comercial de servicios y activos por pedido
Archivo: 20260828_COMERCIAL_SERVICIOS_ACTIVOS.sql | Versión: 1.0.0 | Fecha: 2026-08-28 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Permite cobrar servicios sin stock y relacionar tubos concretos con cada pedido.
Precondición: Fases Comercial, Inventario, Finanzas y activos de clientes instaladas.
Validación posterior: tipos de ítem, depósitos opcionales, vínculos de activos y procedimientos actualizados.
Recuperación: restaurar el respaldo anterior; los cambios preservan pedidos y ventas existentes.
Historial: 1.0.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Implementación inicial.
===============================================================================
*/
IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'TIPO_ITEM') IS NULL
BEGIN
    ALTER TABLE [INVENTARIO].[PRODUCTOS]
        ADD [TIPO_ITEM] NVARCHAR(20) NOT NULL
            CONSTRAINT [DF_PRODUCTOS_TIPO_ITEM] DEFAULT (N'PRODUCTO');
END;

GO

IF OBJECT_ID(N'INVENTARIO.CK_PRODUCTOS_TIPO_ITEM', N'C') IS NULL
BEGIN
    ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD CONSTRAINT [CK_PRODUCTOS_TIPO_ITEM] CHECK
    (
        [TIPO_ITEM] IN (N'PRODUCTO', N'SERVICIO')
        AND ([TIPO_ITEM] = N'PRODUCTO' OR
             ([TIPO_TRAZABILIDAD] = N'NINGUNA' AND [ES_REUTILIZABLE] = 0 AND [ADMITE_PRESTAMO] = 0
              AND [REQUIERE_MANTENIMIENTO] = 0 AND [ADMITE_MEDICIONES] = 0))
    );
END;

IF COLUMNPROPERTY(OBJECT_ID(N'COMERCIAL.PEDIDOS_DETALLES'), N'ID_DEPOSITO', 'AllowsNull') = 0
    ALTER TABLE [COMERCIAL].[PEDIDOS_DETALLES] ALTER COLUMN [ID_DEPOSITO] BIGINT NULL;

IF COLUMNPROPERTY(OBJECT_ID(N'COMERCIAL.VENTAS'), N'ID_MOVIMIENTO', 'AllowsNull') = 0
    ALTER TABLE [COMERCIAL].[VENTAS] ALTER COLUMN [ID_MOVIMIENTO] BIGINT NULL;

IF COLUMNPROPERTY(OBJECT_ID(N'COMERCIAL.VENTAS_DETALLES'), N'ID_DEPOSITO', 'AllowsNull') = 0
    ALTER TABLE [COMERCIAL].[VENTAS_DETALLES] ALTER COLUMN [ID_DEPOSITO] BIGINT NULL;

IF OBJECT_ID(N'COMERCIAL.PEDIDOS_ACTIVOS', N'U') IS NULL
BEGIN
    CREATE TABLE [COMERCIAL].[PEDIDOS_ACTIVOS]
    (
        [ID_PEDIDO_ACTIVO] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_PEDIDOS_ACTIVOS] PRIMARY KEY,
        [ID_PEDIDO] BIGINT NOT NULL,
        [ID_ACTIVO] BIGINT NOT NULL,
        [ID_PRODUCTO_RENGLON] BIGINT NOT NULL,
        [TIPO_VINCULO] NVARCHAR(30) NOT NULL,
        [MODALIDAD_RETORNO] NVARCHAR(30) NOT NULL,
        [OBSERVACION] NVARCHAR(500) NOT NULL,
        [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PEDIDOS_ACTIVOS_ESTADO] DEFAULT (N'ACTIVO'),
        [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PEDIDOS_ACTIVOS_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
        [ID_USUARIO_ALTA] BIGINT NOT NULL,
        [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
        [ID_USUARIO_MODIFICACION] BIGINT NULL,
        [ROW_VERSION] ROWVERSION NOT NULL,
        CONSTRAINT [FK_PEDIDOS_ACTIVOS_PEDIDOS] FOREIGN KEY ([ID_PEDIDO]) REFERENCES [COMERCIAL].[PEDIDOS] ([ID_PEDIDO]),
        CONSTRAINT [FK_PEDIDOS_ACTIVOS_ACTIVOS] FOREIGN KEY ([ID_ACTIVO]) REFERENCES [INVENTARIO].[ACTIVOS] ([ID_ACTIVO]),
        CONSTRAINT [FK_PEDIDOS_ACTIVOS_PRODUCTOS] FOREIGN KEY ([ID_PRODUCTO_RENGLON]) REFERENCES [INVENTARIO].[PRODUCTOS] ([ID_PRODUCTO]),
        CONSTRAINT [CK_PEDIDOS_ACTIVOS_VALORES] CHECK
        (
            [TIPO_VINCULO] IN (N'CLIENTE_SERVICIO', N'VENTA_ACTIVO', N'PRESTAMO', N'INTERCAMBIO')
            AND [MODALIDAD_RETORNO] IN (N'RETIRO_CLIENTE', N'ENTREGA_OXITIGRE', N'NO_APLICA')
            AND NULLIF(LTRIM(RTRIM([OBSERVACION])), N'') IS NOT NULL
            AND [CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO')
        )
    );

    CREATE UNIQUE INDEX [UX_PEDIDOS_ACTIVOS_ACTIVOS]
        ON [COMERCIAL].[PEDIDOS_ACTIVOS] ([ID_PEDIDO], [ID_ACTIVO], [ID_PRODUCTO_RENGLON], [TIPO_VINCULO])
        WHERE [CODIGO_ESTADO] = N'ACTIVO';

    CREATE INDEX [IX_PEDIDOS_ACTIVOS_ACTIVO]
        ON [COMERCIAL].[PEDIDOS_ACTIVOS] ([ID_ACTIVO], [CODIGO_ESTADO])
        INCLUDE ([ID_PEDIDO], [TIPO_VINCULO]);
END;

IF NOT EXISTS (SELECT 1 FROM [AUDITORIA].[CATALOGO_ERRORES] WHERE [CODIGO_ERROR] = 40010)
BEGIN
    INSERT INTO [AUDITORIA].[CATALOGO_ERRORES]
    ([ID_MODULO], [NUMERO_ERROR], [CODIGO_ERROR], [NOMBRE], [DESCRIPCION], [CAUSA_PROBABLE], [ACCION_RECOMENDADA], [SEVERIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT [ID_MODULO], 10, 40010, N'ACTIVO NO APLICABLE AL PEDIDO',
           N'El tubo o activo no puede vincularse al cliente, renglón o finalidad indicada.',
           N'Propietario incorrecto, activo inexistente o renglón eliminado.',
           N'Actualizar el pedido y revisar propietario, finalidad, retiro o entrega y observación.',
           N'ADVERTENCIA', N'ACTIVO', 1
    FROM [CONFIGURACION].[MODULOS] WHERE [CODIGO] = N'COMERCIAL';
END;

GO
:r "database\06_StoredProcedures\INVENTARIO\Commands\SP_PRODUCTO_SAVE.sql"
GO
:r "database\06_StoredProcedures\INVENTARIO\Queries\SP_INVENTARIO_GET.sql"
GO
:r "database\06_StoredProcedures\COMERCIAL\Commands\SP_PEDIDO_SAVE.sql"
GO
:r "database\06_StoredProcedures\COMERCIAL\Commands\SP_PEDIDO_CONFIRM.sql"
GO
:r "database\06_StoredProcedures\COMERCIAL\Commands\SP_VENTA_CREATE_FROM_PEDIDO.sql"
GO
:r "database\06_StoredProcedures\COMERCIAL\Queries\SP_VENTAS_GET.sql"
GO

IF COL_LENGTH(N'INVENTARIO.PRODUCTOS', N'TIPO_ITEM') IS NULL
   OR OBJECT_ID(N'COMERCIAL.PEDIDOS_ACTIVOS', N'U') IS NULL
   OR OBJECT_ID(N'COMERCIAL.SP_PEDIDO_SAVE', N'P') IS NULL
BEGIN
    THROW 50000, 'No se completó la migración comercial de servicios y activos.', 1;
END;
