/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Migración de integridad documental de Compras
Archivo: 20260826_PURCHASES_USABILITY_AND_REVERSAL.sql | Versión: 1.0.0 | Fecha: 2026-08-26 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Conserva la foto del proveedor en cada orden y habilita la reversión auditada de recepciones.
Historial: 1.0.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH(N'COMPRAS.ORDENES_COMPRA',N'PROVEEDOR_RAZON_SOCIAL') IS NULL
BEGIN
    ALTER TABLE [COMPRAS].[ORDENES_COMPRA] ADD [PROVEEDOR_RAZON_SOCIAL] NVARCHAR(200) NULL,
        [PROVEEDOR_CUIT] NVARCHAR(30) NULL, [PROVEEDOR_CONDICION_PAGO] NVARCHAR(150) NULL;
    EXEC sys.sp_executesql N'
        UPDATE [ORD] SET [PROVEEDOR_RAZON_SOCIAL]=[PRO].[RAZON_SOCIAL], [PROVEEDOR_CUIT]=[PRO].[CUIT],
            [PROVEEDOR_CONDICION_PAGO]=[PRO].[CONDICION_PAGO]
        FROM [COMPRAS].[ORDENES_COMPRA] AS [ORD]
        INNER JOIN [COMPRAS].[PROVEEDORES] AS [PRO] ON [PRO].[ID_PROVEEDOR]=[ORD].[ID_PROVEEDOR];
        ALTER TABLE [COMPRAS].[ORDENES_COMPRA] ALTER COLUMN [PROVEEDOR_RAZON_SOCIAL] NVARCHAR(200) NOT NULL;
        ALTER TABLE [COMPRAS].[ORDENES_COMPRA] ALTER COLUMN [PROVEEDOR_CUIT] NVARCHAR(30) NOT NULL;';
END;

IF COL_LENGTH(N'COMPRAS.RECEPCIONES_COMPRA',N'ID_MOVIMIENTO_REVERSION') IS NULL
    ALTER TABLE [COMPRAS].[RECEPCIONES_COMPRA] ADD [ID_MOVIMIENTO_REVERSION] BIGINT NULL,
        [MOTIVO_REVERSION] NVARCHAR(500) NULL, [FECHA_REVERSION_UTC] DATETIME2(3) NULL,
        [ID_USUARIO_REVERSION] BIGINT NULL;

IF OBJECT_ID(N'COMPRAS.FK_RECEPCIONES_MOVIMIENTOS_REVERSION',N'F') IS NULL
    ALTER TABLE [COMPRAS].[RECEPCIONES_COMPRA] ADD CONSTRAINT [FK_RECEPCIONES_MOVIMIENTOS_REVERSION]
        FOREIGN KEY ([ID_MOVIMIENTO_REVERSION]) REFERENCES [INVENTARIO].[MOVIMIENTOS] ([ID_MOVIMIENTO]);

COMMIT;
