/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Migración Fase 6 - Promociones
Archivo: 20260821_FASE6_PROMOCIONES.sql | Versión: 1.0.1 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Incorpora promociones y sus fotografías a una base existente sin perder pedidos ni ventas.
Precondiciones: Esquemas COMERCIAL, CONFIGURACION, INVENTARIO y AUDITORIA de Fase 6 instalados.
Validación posterior: Tabla, columnas, relaciones, índices y códigos 40008/40009 presentes.
Recuperación: El cambio estructural es transaccional y los procedimientos son idempotentes; ante interrupción se vuelve a ejecutar el archivo.
Historial: 1.0.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI persistentes para despliegues ejecutados con sqlcmd.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'[COMERCIAL].[PROMOCIONES]', N'U') IS NULL
    BEGIN
        CREATE TABLE [COMERCIAL].[PROMOCIONES]
        (
            [ID_PROMOCION] BIGINT IDENTITY(1,1) NOT NULL,
            [ID_EMPRESA] BIGINT NOT NULL,
            [ID_PRODUCTO] BIGINT NOT NULL,
            [CODIGO] NVARCHAR(30) NOT NULL,
            [NOMBRE] NVARCHAR(150) NOT NULL,
            [DESCRIPCION] NVARCHAR(500) NULL,
            [TIPO_PROMOCION] NVARCHAR(30) NOT NULL,
            [CANTIDAD_REQUERIDA] DECIMAL(19,4) NOT NULL,
            [CANTIDAD_PAGADA] DECIMAL(19,4) NULL,
            [CANTIDAD_BONIFICADA] DECIMAL(19,4) NULL,
            [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NULL,
            [PRECIO_PAQUETE] DECIMAL(19,4) NULL,
            [FECHA_VIGENCIA_DESDE] DATE NULL,
            [FECHA_VIGENCIA_HASTA] DATE NULL,
            [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PROMOCIONES_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
            [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PROMOCIONES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
            [ID_USUARIO_ALTA] BIGINT NOT NULL,
            [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
            [ID_USUARIO_MODIFICACION] BIGINT NULL,
            [ROW_VERSION] ROWVERSION NOT NULL,
            CONSTRAINT [PK_PROMOCIONES] PRIMARY KEY CLUSTERED ([ID_PROMOCION])
        );
    END;

    IF COL_LENGTH(N'COMERCIAL.PEDIDOS_DETALLES', N'ID_PROMOCION') IS NULL ALTER TABLE [COMERCIAL].[PEDIDOS_DETALLES] ADD [ID_PROMOCION] BIGINT NULL;
    IF COL_LENGTH(N'COMERCIAL.PEDIDOS_DETALLES', N'CODIGO_PROMOCION') IS NULL ALTER TABLE [COMERCIAL].[PEDIDOS_DETALLES] ADD [CODIGO_PROMOCION] NVARCHAR(30) NULL;
    IF COL_LENGTH(N'COMERCIAL.PEDIDOS_DETALLES', N'NOMBRE_PROMOCION') IS NULL ALTER TABLE [COMERCIAL].[PEDIDOS_DETALLES] ADD [NOMBRE_PROMOCION] NVARCHAR(150) NULL;
    IF COL_LENGTH(N'COMERCIAL.VENTAS_DETALLES', N'ID_PROMOCION') IS NULL ALTER TABLE [COMERCIAL].[VENTAS_DETALLES] ADD [ID_PROMOCION] BIGINT NULL;
    IF COL_LENGTH(N'COMERCIAL.VENTAS_DETALLES', N'CODIGO_PROMOCION') IS NULL ALTER TABLE [COMERCIAL].[VENTAS_DETALLES] ADD [CODIGO_PROMOCION] NVARCHAR(30) NULL;
    IF COL_LENGTH(N'COMERCIAL.VENTAS_DETALLES', N'NOMBRE_PROMOCION') IS NULL ALTER TABLE [COMERCIAL].[VENTAS_DETALLES] ADD [NOMBRE_PROMOCION] NVARCHAR(150) NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_PROMOCIONES_EMPRESAS') ALTER TABLE [COMERCIAL].[PROMOCIONES] ADD CONSTRAINT [FK_PROMOCIONES_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_PROMOCIONES_PRODUCTOS') ALTER TABLE [COMERCIAL].[PROMOCIONES] ADD CONSTRAINT [FK_PROMOCIONES_PRODUCTOS] FOREIGN KEY ([ID_PRODUCTO]) REFERENCES [INVENTARIO].[PRODUCTOS] ([ID_PRODUCTO]);
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_PEDIDOS_DETALLES_PROMOCIONES') ALTER TABLE [COMERCIAL].[PEDIDOS_DETALLES] ADD CONSTRAINT [FK_PEDIDOS_DETALLES_PROMOCIONES] FOREIGN KEY ([ID_PROMOCION]) REFERENCES [COMERCIAL].[PROMOCIONES] ([ID_PROMOCION]);
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_VENTAS_DETALLES_PROMOCIONES') ALTER TABLE [COMERCIAL].[VENTAS_DETALLES] ADD CONSTRAINT [FK_VENTAS_DETALLES_PROMOCIONES] FOREIGN KEY ([ID_PROMOCION]) REFERENCES [COMERCIAL].[PROMOCIONES] ([ID_PROMOCION]);

    IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE [name] = N'CK_PROMOCIONES_REGLA')
    BEGIN
        ALTER TABLE [COMERCIAL].[PROMOCIONES] ADD CONSTRAINT [CK_PROMOCIONES_REGLA] CHECK
        (
            [CANTIDAD_REQUERIDA] > 0
            AND [CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO')
            AND ([FECHA_VIGENCIA_HASTA] IS NULL OR [FECHA_VIGENCIA_DESDE] IS NULL OR [FECHA_VIGENCIA_HASTA] >= [FECHA_VIGENCIA_DESDE])
            AND
            (
                ([TIPO_PROMOCION] = N'CANTIDAD_PAGADA' AND [CANTIDAD_PAGADA] >= 0 AND [CANTIDAD_PAGADA] < [CANTIDAD_REQUERIDA] AND [CANTIDAD_BONIFICADA] IS NULL AND [PORCENTAJE_DESCUENTO] IS NULL AND [PRECIO_PAQUETE] IS NULL)
                OR ([TIPO_PROMOCION] = N'PORCENTAJE_UNIDADES' AND [CANTIDAD_PAGADA] IS NULL AND [CANTIDAD_BONIFICADA] > 0 AND [CANTIDAD_BONIFICADA] <= [CANTIDAD_REQUERIDA] AND [PORCENTAJE_DESCUENTO] > 0 AND [PORCENTAJE_DESCUENTO] <= 1 AND [PRECIO_PAQUETE] IS NULL)
                OR ([TIPO_PROMOCION] = N'PRECIO_PAQUETE' AND [CANTIDAD_PAGADA] IS NULL AND [CANTIDAD_BONIFICADA] IS NULL AND [PORCENTAJE_DESCUENTO] IS NULL AND [PRECIO_PAQUETE] >= 0)
            )
        );
    END;

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[COMERCIAL].[PROMOCIONES]') AND [name] = N'UX_PROMOCIONES_EMPRESA_CODIGO') CREATE UNIQUE INDEX [UX_PROMOCIONES_EMPRESA_CODIGO] ON [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [CODIGO]);
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[COMERCIAL].[PROMOCIONES]') AND [name] = N'IX_PROMOCIONES_APLICABLES') CREATE INDEX [IX_PROMOCIONES_APLICABLES] ON [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO_ESTADO], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA]);

    DECLARE @V_ID_MODULO_COMERCIAL BIGINT = (SELECT [ID_MODULO] FROM [CONFIGURACION].[MODULOS] WHERE [CODIGO] = N'COMERCIAL');
    IF @V_ID_MODULO_COMERCIAL IS NULL THROW 50000, 'No existe el módulo COMERCIAL requerido por los errores de promociones.', 1;

    INSERT INTO [AUDITORIA].[CATALOGO_ERRORES] ([ID_MODULO], [NUMERO_ERROR], [CODIGO_ERROR], [NOMBRE], [DESCRIPCION], [CAUSA_PROBABLE], [ACCION_RECOMENDADA], [SEVERIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
    SELECT @V_ID_MODULO_COMERCIAL, [ERR].[NUMERO_ERROR], [ERR].[CODIGO_ERROR], [ERR].[NOMBRE], [ERR].[DESCRIPCION], [ERR].[CAUSA], [ERR].[ACCION], N'ADVERTENCIA', N'ACTIVO', 1
    FROM (VALUES
        (CONVERT(SMALLINT, 8), CONVERT(BIGINT, 40008), N'REGLA PROMOCIONAL INVÁLIDA', N'La definición o combinación de descuentos de la promoción no es válida.', N'Parámetros incompatibles, código duplicado o descuento manual combinado con promoción.', N'Revisar el tipo de promoción y completar únicamente los valores que le corresponden.'),
        (CONVERT(SMALLINT, 9), CONVERT(BIGINT, 40009), N'PROMOCIÓN NO APLICABLE', N'La promoción seleccionada no puede aplicarse al renglón y fecha del pedido.', N'Promoción inactiva, fuera de vigencia, de otro producto o de otra empresa.', N'Actualizar promociones y seleccionar una vigente para el producto del pedido.')
    ) AS [ERR] ([NUMERO_ERROR], [CODIGO_ERROR], [NOMBRE], [DESCRIPCION], [CAUSA], [ACCION])
    WHERE NOT EXISTS (SELECT 1 FROM [AUDITORIA].[CATALOGO_ERRORES] WHERE [CODIGO_ERROR] = [ERR].[CODIGO_ERROR]);

    IF OBJECT_ID(N'[COMERCIAL].[PROMOCIONES]', N'U') IS NULL
       OR COL_LENGTH(N'COMERCIAL.PEDIDOS_DETALLES', N'ID_PROMOCION') IS NULL
       OR COL_LENGTH(N'COMERCIAL.VENTAS_DETALLES', N'ID_PROMOCION') IS NULL
       OR (SELECT COUNT(*) FROM [AUDITORIA].[CATALOGO_ERRORES] WHERE [CODIGO_ERROR] IN (40008, 40009)) <> 2
        THROW 50001, 'La validación posterior de la migración de promociones falló.', 1;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

GO

/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PROMOCION_SAVE
Archivo: SP_PROMOCION_SAVE.sql | Procedimiento: COMERCIAL.SP_PROMOCION_SAVE | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o modifica una promoción por producto con vigencia, concurrencia y baja lógica.
Historial: 1.0.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Creación inicial para Fase 6.
Historial: 1.0.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_PROMOCION_SAVE]
    @I_ID_PROMOCION BIGINT = NULL,
    @I_ID_EMPRESA BIGINT,
    @I_ID_PRODUCTO BIGINT,
    @I_CODIGO NVARCHAR(30),
    @I_NOMBRE NVARCHAR(150),
    @I_DESCRIPCION NVARCHAR(500) = NULL,
    @I_TIPO_PROMOCION NVARCHAR(30),
    @I_CANTIDAD_REQUERIDA DECIMAL(19,4),
    @I_CANTIDAD_PAGADA DECIMAL(19,4) = NULL,
    @I_CANTIDAD_BONIFICADA DECIMAL(19,4) = NULL,
    @I_PORCENTAJE_DESCUENTO DECIMAL(9,6) = NULL,
    @I_PRECIO_PAQUETE DECIMAL(19,4) = NULL,
    @I_FECHA_VIGENCIA_DESDE DATE = NULL,
    @I_FECHA_VIGENCIA_HASTA DATE = NULL,
    @I_CODIGO_ESTADO NVARCHAR(30),
    @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_PROMOCION BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_ID_PROMOCION = @I_ID_PROMOCION;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;
    SET @O_FILAS_AFECTADAS = 0;
    SET @I_CODIGO = UPPER(LTRIM(RTRIM(@I_CODIGO)));
    SET @I_NOMBRE = LTRIM(RTRIM(@I_NOMBRE));
    SET @I_TIPO_PROMOCION = UPPER(LTRIM(RTRIM(@I_TIPO_PROMOCION)));

    -- INICIO: Validación completa de la regla antes de conservarla.
    IF NULLIF(@I_CODIGO, N'') IS NULL OR NULLIF(@I_NOMBRE, N'') IS NULL
       OR @I_TIPO_PROMOCION NOT IN (N'CANTIDAD_PAGADA', N'PORCENTAJE_UNIDADES', N'PRECIO_PAQUETE')
       OR @I_CANTIDAD_REQUERIDA IS NULL OR @I_CANTIDAD_REQUERIDA <= 0
       OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO')
       OR (@I_FECHA_VIGENCIA_DESDE IS NOT NULL AND @I_FECHA_VIGENCIA_HASTA IS NOT NULL AND @I_FECHA_VIGENCIA_HASTA < @I_FECHA_VIGENCIA_DESDE)
       OR (@I_TIPO_PROMOCION = N'CANTIDAD_PAGADA' AND (@I_CANTIDAD_PAGADA IS NULL OR @I_CANTIDAD_PAGADA < 0 OR @I_CANTIDAD_PAGADA >= @I_CANTIDAD_REQUERIDA OR @I_CANTIDAD_BONIFICADA IS NOT NULL OR @I_PORCENTAJE_DESCUENTO IS NOT NULL OR @I_PRECIO_PAQUETE IS NOT NULL))
       OR (@I_TIPO_PROMOCION = N'PORCENTAJE_UNIDADES' AND (@I_CANTIDAD_PAGADA IS NOT NULL OR @I_CANTIDAD_BONIFICADA IS NULL OR @I_CANTIDAD_BONIFICADA <= 0 OR @I_CANTIDAD_BONIFICADA > @I_CANTIDAD_REQUERIDA OR @I_PORCENTAJE_DESCUENTO IS NULL OR @I_PORCENTAJE_DESCUENTO <= 0 OR @I_PORCENTAJE_DESCUENTO > 1 OR @I_PRECIO_PAQUETE IS NOT NULL))
       OR (@I_TIPO_PROMOCION = N'PRECIO_PAQUETE' AND (@I_CANTIDAD_PAGADA IS NOT NULL OR @I_CANTIDAD_BONIFICADA IS NOT NULL OR @I_PORCENTAJE_DESCUENTO IS NOT NULL OR @I_PRECIO_PAQUETE IS NULL OR @I_PRECIO_PAQUETE < 0))
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'La definición de la promoción no es válida para el tipo seleccionado.';
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_PRODUCTO] = @I_ID_PRODUCTO AND [ID_EMPRESA] = @I_ID_EMPRESA)
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'El producto de la promoción no pertenece a la empresa.';
        RETURN;
    END;

    IF EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO] = @I_CODIGO AND (@I_ID_PROMOCION IS NULL OR [ID_PROMOCION] <> @I_ID_PROMOCION))
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'Ya existe una promoción con ese código en la empresa.';
        RETURN;
    END;
    -- FIN: Validación completa de la regla antes de conservarla.

    BEGIN TRY
        IF @I_ID_PROMOCION IS NULL
        BEGIN
            INSERT INTO [COMERCIAL].[PROMOCIONES]
                ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_PAGADA], [CANTIDAD_BONIFICADA], [PORCENTAJE_DESCUENTO], [PRECIO_PAQUETE], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
            VALUES
                (@I_ID_EMPRESA, @I_ID_PRODUCTO, @I_CODIGO, @I_NOMBRE, NULLIF(LTRIM(RTRIM(@I_DESCRIPCION)), N''), @I_TIPO_PROMOCION, @I_CANTIDAD_REQUERIDA, @I_CANTIDAD_PAGADA, @I_CANTIDAD_BONIFICADA, @I_PORCENTAJE_DESCUENTO, @I_PRECIO_PAQUETE, @I_FECHA_VIGENCIA_DESDE, @I_FECHA_VIGENCIA_HASTA, @I_CODIGO_ESTADO, @S_ID_USUARIO);
            SET @O_ID_PROMOCION = CONVERT(BIGINT, SCOPE_IDENTITY());
            SET @O_FILAS_AFECTADAS = 1;
            RETURN;
        END;

    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_PROMOCION] = @I_ID_PROMOCION AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ID_PRODUCTO] = @I_ID_PRODUCTO AND [CODIGO] = @I_CODIGO)
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'El código y el producto de una promoción existente no se pueden reemplazar.';
        RETURN;
    END;

    UPDATE [COMERCIAL].[PROMOCIONES]
    SET [NOMBRE] = @I_NOMBRE,
        [DESCRIPCION] = NULLIF(LTRIM(RTRIM(@I_DESCRIPCION)), N''),
        [TIPO_PROMOCION] = @I_TIPO_PROMOCION,
        [CANTIDAD_REQUERIDA] = @I_CANTIDAD_REQUERIDA,
        [CANTIDAD_PAGADA] = @I_CANTIDAD_PAGADA,
        [CANTIDAD_BONIFICADA] = @I_CANTIDAD_BONIFICADA,
        [PORCENTAJE_DESCUENTO] = @I_PORCENTAJE_DESCUENTO,
        [PRECIO_PAQUETE] = @I_PRECIO_PAQUETE,
        [FECHA_VIGENCIA_DESDE] = @I_FECHA_VIGENCIA_DESDE,
        [FECHA_VIGENCIA_HASTA] = @I_FECHA_VIGENCIA_HASTA,
        [CODIGO_ESTADO] = @I_CODIGO_ESTADO,
        [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(),
        [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
    WHERE [ID_PROMOCION] = @I_ID_PROMOCION AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;

        SET @O_FILAS_AFECTADAS = @@ROWCOUNT;
        IF @O_FILAS_AFECTADAS = 0
        BEGIN
            SET @O_CODIGO_ERROR = 40007;
            SET @O_MENSAJE = N'La promoción fue modificada por otro usuario o ya no pertenece a la empresa.';
        END;
    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() IN (2601, 2627)
        BEGIN
            SET @O_CODIGO_ERROR = 40008;
            SET @O_MENSAJE = N'Ya existe una promoción con ese código en la empresa.';
            RETURN;
        END;
        THROW;
    END CATCH;
END;
GO

/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PEDIDO_SAVE
Archivo: SP_PEDIDO_SAVE.sql | Procedimiento: COMERCIAL.SP_PEDIDO_SAVE | Tipo: COMMAND
Versión: 1.2.0 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o reemplaza un pedido en borrador, acumula renglones compatibles y calcula sus promociones en el servidor.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Motor promocional 2x1/4x3, porcentaje por unidades y precio de paquete.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
Historial: 1.2.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Validaciones bloqueadas y suma amplia de cantidades compatibles.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_PEDIDO_SAVE]
    @I_ID_PEDIDO BIGINT = NULL, @I_ID_EMPRESA BIGINT, @I_ID_CLIENTE BIGINT, @I_ID_LISTA_PRECIO BIGINT = NULL,
    @I_FECHA_PEDIDO_UTC DATETIME2(3), @I_MONEDA CHAR(3), @I_OBSERVACION NVARCHAR(500) = NULL,
    @I_DETALLES_JSON NVARCHAR(MAX), @I_ROW_VERSION BINARY(8) = NULL, @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT,
    @O_ID_PEDIDO BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_ID_PEDIDO = @I_ID_PEDIDO; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_PEDIDO_UTC IS NULL OR @I_MONEDA NOT LIKE '[A-Z][A-Z][A-Z]' OR ISJSON(@I_DETALLES_JSON) <> 1 THROW 50000, 'Cliente, fecha, moneda y renglones válidos son obligatorios.', 1;

    -- INICIO: Normalización de la entrada; ningún importe de descuento se acepta desde el cliente.
    DECLARE @T_ENTRADAS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NOT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL
    );

    INSERT INTO @T_ENTRADAS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO])
    SELECT [J].[ID_PRODUCTO], [J].[ID_DEPOSITO], [J].[ID_PROMOCION], [J].[CANTIDAD], [J].[PRECIO_UNITARIO], COALESCE([J].[PORCENTAJE_DESCUENTO], 0), COALESCE([J].[PORCENTAJE_IMPUESTO], 0)
    FROM OPENJSON(@I_DETALLES_JSON) WITH
    (
        [ID_PRODUCTO] BIGINT '$.ProductId',
        [ID_DEPOSITO] BIGINT '$.WarehouseId',
        [ID_PROMOCION] BIGINT '$.PromotionId',
        [CANTIDAD] DECIMAL(19,4) '$.Quantity',
        [PRECIO_UNITARIO] DECIMAL(19,4) '$.UnitPrice',
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) '$.DiscountRate',
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) '$.TaxRate'
    ) AS [J];

    IF NOT EXISTS (SELECT 1 FROM @T_ENTRADAS) OR (SELECT COUNT(*) FROM @T_ENTRADAS) > 100 OR EXISTS (SELECT 1 FROM @T_ENTRADAS WHERE [CANTIDAD] <= 0 OR [PRECIO_UNITARIO] < 0 OR [PORCENTAJE_DESCUENTO] NOT BETWEEN 0 AND 1 OR [PORCENTAJE_IMPUESTO] NOT BETWEEN 0 AND 1) THROW 50003, 'El pedido debe tener entre 1 y 100 renglones con cantidades, precios y porcentajes válidos.', 1;
    DECLARE @V_INICIO_TRANSACCION BIT = 0;
    BEGIN TRY
        IF @@TRANCOUNT = 0 BEGIN BEGIN TRANSACTION; SET @V_INICIO_TRANSACCION = 1; END ELSE SAVE TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];

        -- INICIO: Los catálogos usados permanecen bloqueados hasta persistir el pedido.
        IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[CLIENTES] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_CLIENTE] = @I_ID_CLIENTE AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO')
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'El cliente no está activo o no pertenece a la empresa.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        IF @I_ID_LISTA_PRECIO IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [MONEDA] = @I_MONEDA AND [CODIGO_ESTADO] = N'ACTIVO' AND ([FECHA_VIGENCIA_DESDE] IS NULL OR [FECHA_VIGENCIA_DESDE] <= CONVERT(DATE, @I_FECHA_PEDIDO_UTC)) AND ([FECHA_VIGENCIA_HASTA] IS NULL OR [FECHA_VIGENCIA_HASTA] >= CONVERT(DATE, @I_FECHA_PEDIDO_UTC)))
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'La lista no está vigente para la fecha y moneda del pedido.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        IF EXISTS (SELECT 1 FROM @T_ENTRADAS AS [DET] WHERE NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] AS [PRO] WITH (UPDLOCK, HOLDLOCK) INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] WITH (UPDLOCK, HOLDLOCK) ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA] WHERE [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO] AND [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO' AND ([UNI].[PERMITE_DECIMALES] = 1 OR [DET].[CANTIDAD] = FLOOR([DET].[CANTIDAD]))))
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'Un producto no pertenece a la empresa, está inactivo o no admite cantidades decimales.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        IF EXISTS (SELECT 1 FROM @T_ENTRADAS AS [DET] WHERE NOT EXISTS (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_DEPOSITO] = [DET].[ID_DEPOSITO] AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO'))
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'Un depósito no está activo o no pertenece a la empresa.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        -- FIN: Los catálogos usados permanecen bloqueados hasta persistir el pedido.

        IF EXISTS (SELECT 1 FROM @T_ENTRADAS WHERE [ID_PROMOCION] IS NOT NULL AND [PORCENTAJE_DESCUENTO] > 0)
        BEGIN
            SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'Un renglón no puede combinar promoción y descuento manual.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
    IF EXISTS
    (
        SELECT 1
        FROM @T_ENTRADAS AS [DET]
        LEFT JOIN [COMERCIAL].[PROMOCIONES] AS [PRO] WITH (UPDLOCK, HOLDLOCK)
            ON [PRO].[ID_PROMOCION] = [DET].[ID_PROMOCION]
           AND [PRO].[ID_EMPRESA] = @I_ID_EMPRESA
           AND [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
           AND [PRO].[CODIGO_ESTADO] = N'ACTIVO'
           AND ([PRO].[FECHA_VIGENCIA_DESDE] IS NULL OR [PRO].[FECHA_VIGENCIA_DESDE] <= CONVERT(DATE, @I_FECHA_PEDIDO_UTC))
           AND ([PRO].[FECHA_VIGENCIA_HASTA] IS NULL OR [PRO].[FECHA_VIGENCIA_HASTA] >= CONVERT(DATE, @I_FECHA_PEDIDO_UTC))
        WHERE [DET].[ID_PROMOCION] IS NOT NULL AND [PRO].[ID_PROMOCION] IS NULL
    )
    BEGIN
        SET @O_CODIGO_ERROR = 40009; SET @O_MENSAJE = N'Una promoción no está vigente, no pertenece al producto o no corresponde a la empresa.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    DECLARE @T_AGREGADOS_AMPLIOS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NOT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CANTIDAD] DECIMAL(38,8) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL
    );

    INSERT INTO @T_AGREGADOS_AMPLIOS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], SUM(CONVERT(DECIMAL(38,8), [CANTIDAD])), [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO]
    FROM @T_ENTRADAS
    GROUP BY [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO];

    IF EXISTS (SELECT 1 FROM @T_AGREGADOS_AMPLIOS WHERE [CANTIDAD] > CONVERT(DECIMAL(38,8), 999999999999999.9999))
    BEGIN
        SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'La cantidad acumulada del renglón supera el límite admitido.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    DECLARE @T_AGREGADOS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NOT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL
    );

    INSERT INTO @T_AGREGADOS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], CONVERT(DECIMAL(19,4), [CANTIDAD]), [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO]
    FROM @T_AGREGADOS_AMPLIOS;
    -- FIN: Normalización de la entrada; ningún importe de descuento se acepta desde el cliente.

    -- INICIO: Cálculo único y auditable de importes y promociones.
    DECLARE @T_DETALLES TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NOT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CODIGO_PROMOCION] NVARCHAR(30) NULL,
        [NOMBRE_PROMOCION] NVARCHAR(150) NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL,
        [SUBTOTAL] DECIMAL(19,4) NOT NULL,
        [IMPORTE_DESCUENTO] DECIMAL(19,4) NOT NULL,
        [IMPORTE_IMPUESTO] DECIMAL(19,4) NOT NULL,
        [TOTAL] DECIMAL(19,4) NOT NULL
    );

    DECLARE @T_CALCULADOS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NOT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CODIGO_PROMOCION] NVARCHAR(30) NULL,
        [NOMBRE_PROMOCION] NVARCHAR(150) NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL,
        [SUBTOTAL] DECIMAL(38,8) NOT NULL,
        [IMPORTE_DESCUENTO] DECIMAL(38,8) NOT NULL,
        [IMPORTE_IMPUESTO] DECIMAL(38,8) NOT NULL,
        [TOTAL] DECIMAL(38,8) NOT NULL
    );

    ;WITH [CALCULO_BASE] AS
    (
        SELECT [AGR].*, [PRO].[CODIGO] AS [CODIGO_PROMOCION], [PRO].[NOMBRE] AS [NOMBRE_PROMOCION], [PRO].[TIPO_PROMOCION],
               [PRO].[CANTIDAD_REQUERIDA], [PRO].[CANTIDAD_PAGADA], [PRO].[CANTIDAD_BONIFICADA], [PRO].[PORCENTAJE_DESCUENTO] AS [PORCENTAJE_PROMOCION], [PRO].[PRECIO_PAQUETE],
               CONVERT(DECIMAL(38,8), ROUND(CONVERT(DECIMAL(38,8), [AGR].[CANTIDAD]) * CONVERT(DECIMAL(38,8), [AGR].[PRECIO_UNITARIO]), 4)) AS [SUBTOTAL]
        FROM @T_AGREGADOS AS [AGR]
        LEFT JOIN [COMERCIAL].[PROMOCIONES] AS [PRO] ON [PRO].[ID_PROMOCION] = [AGR].[ID_PROMOCION]
    ),
    [CALCULO] AS
    (
        SELECT [BAS].*, CONVERT(DECIMAL(38,8), ROUND
               (
                   CASE
                       WHEN [BAS].[ID_PROMOCION] IS NULL THEN [BAS].[SUBTOTAL] * CONVERT(DECIMAL(38,8), [BAS].[PORCENTAJE_DESCUENTO])
                       WHEN [BAS].[TIPO_PROMOCION] = N'CANTIDAD_PAGADA' THEN FLOOR(CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD]) / CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA])) * (CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA]) - CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_PAGADA])) * CONVERT(DECIMAL(38,8), [BAS].[PRECIO_UNITARIO])
                       WHEN [BAS].[TIPO_PROMOCION] = N'PORCENTAJE_UNIDADES' THEN FLOOR(CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD]) / CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA])) * CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_BONIFICADA]) * CONVERT(DECIMAL(38,8), [BAS].[PRECIO_UNITARIO]) * CONVERT(DECIMAL(38,8), [BAS].[PORCENTAJE_PROMOCION])
                       WHEN [BAS].[TIPO_PROMOCION] = N'PRECIO_PAQUETE' THEN FLOOR(CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD]) / CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA])) * ((CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA]) * CONVERT(DECIMAL(38,8), [BAS].[PRECIO_UNITARIO])) - CONVERT(DECIMAL(38,8), [BAS].[PRECIO_PAQUETE]))
                       ELSE 0
                   END, 4
               )) AS [DESCUENTO_BRUTO]
        FROM [CALCULO_BASE] AS [BAS]
    ),
    [CALCULO_ACOTADO] AS
    (
        SELECT [CAL].*, CONVERT(DECIMAL(38,8), CASE WHEN [CAL].[DESCUENTO_BRUTO] < 0 THEN 0 WHEN [CAL].[DESCUENTO_BRUTO] > [CAL].[SUBTOTAL] THEN [CAL].[SUBTOTAL] ELSE [CAL].[DESCUENTO_BRUTO] END) AS [IMPORTE_DESCUENTO]
        FROM [CALCULO] AS [CAL]
    )
    INSERT INTO @T_CALCULADOS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO],
           [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO],
           CONVERT(DECIMAL(38,8), ROUND(([SUBTOTAL] - [IMPORTE_DESCUENTO]) * CONVERT(DECIMAL(38,8), [PORCENTAJE_IMPUESTO]), 4)),
           CONVERT(DECIMAL(38,8), ROUND(([SUBTOTAL] - [IMPORTE_DESCUENTO]) * (1 + CONVERT(DECIMAL(38,8), [PORCENTAJE_IMPUESTO])), 4))
    FROM [CALCULO_ACOTADO];

    DECLARE @V_LIMITE_IMPORTE DECIMAL(19,4) = 999999999999999.9999;
    IF EXISTS (SELECT 1 FROM @T_CALCULADOS WHERE [SUBTOTAL] > @V_LIMITE_IMPORTE OR [IMPORTE_DESCUENTO] > @V_LIMITE_IMPORTE OR [IMPORTE_IMPUESTO] > @V_LIMITE_IMPORTE OR [TOTAL] > @V_LIMITE_IMPORTE)
    BEGIN
        SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'Los importes calculados superan el límite monetario admitido.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    DECLARE @V_SUBTOTAL_CALCULADO DECIMAL(38,8) = (SELECT SUM([SUBTOTAL]) FROM @T_CALCULADOS),
            @V_DESCUENTO_CALCULADO DECIMAL(38,8) = (SELECT SUM([IMPORTE_DESCUENTO]) FROM @T_CALCULADOS),
            @V_IMPUESTO_CALCULADO DECIMAL(38,8) = (SELECT SUM([IMPORTE_IMPUESTO]) FROM @T_CALCULADOS),
            @V_TOTAL_CALCULADO DECIMAL(38,8) = (SELECT SUM([TOTAL]) FROM @T_CALCULADOS);
    IF @V_SUBTOTAL_CALCULADO > @V_LIMITE_IMPORTE OR @V_DESCUENTO_CALCULADO > @V_LIMITE_IMPORTE OR @V_IMPUESTO_CALCULADO > @V_LIMITE_IMPORTE OR @V_TOTAL_CALCULADO > @V_LIMITE_IMPORTE
    BEGIN
        SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'Los totales del pedido superan el límite monetario admitido.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    INSERT INTO @T_DETALLES ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO],
           CONVERT(DECIMAL(9,6), CASE WHEN [SUBTOTAL] = 0 THEN 0 ELSE ROUND([IMPORTE_DESCUENTO] / [SUBTOTAL], 6) END), [PORCENTAJE_IMPUESTO],
           CONVERT(DECIMAL(19,4), [SUBTOTAL]), CONVERT(DECIMAL(19,4), [IMPORTE_DESCUENTO]), CONVERT(DECIMAL(19,4), [IMPORTE_IMPUESTO]), CONVERT(DECIMAL(19,4), [TOTAL])
    FROM @T_CALCULADOS;
    -- FIN: Cálculo único y auditable de importes y promociones.

    DECLARE @V_SUBTOTAL DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_SUBTOTAL_CALCULADO), @V_DESCUENTO DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_DESCUENTO_CALCULADO), @V_IMPUESTO DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_IMPUESTO_CALCULADO), @V_TOTAL DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_TOTAL_CALCULADO);
        IF @I_ID_PEDIDO IS NULL
        BEGIN
            DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMERCIAL].[SEQ_PEDIDO_CODIGO]; DECLARE @V_CODIGO NVARCHAR(30) = N'PED-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;
            INSERT INTO [COMERCIAL].[PEDIDOS] ([ID_EMPRESA], [ID_CLIENTE], [ID_LISTA_PRECIO], [CODIGO], [FECHA_PEDIDO_UTC], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_EMPRESA, @I_ID_CLIENTE, @I_ID_LISTA_PRECIO, @V_CODIGO, @I_FECHA_PEDIDO_UTC, @I_MONEDA, @V_SUBTOTAL, @V_DESCUENTO, @V_IMPUESTO, @V_TOTAL, @I_OBSERVACION, N'BORRADOR', @S_ID_USUARIO);
            SET @O_ID_PEDIDO = CONVERT(BIGINT, SCOPE_IDENTITY());
        END
        ELSE
        BEGIN
            UPDATE [COMERCIAL].[PEDIDOS] SET [ID_CLIENTE] = @I_ID_CLIENTE, [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO, [FECHA_PEDIDO_UTC] = @I_FECHA_PEDIDO_UTC, [MONEDA] = @I_MONEDA, [SUBTOTAL] = @V_SUBTOTAL, [TOTAL_DESCUENTO] = @V_DESCUENTO, [TOTAL_IMPUESTO] = @V_IMPUESTO, [TOTAL] = @V_TOTAL, [OBSERVACION] = @I_OBSERVACION, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'BORRADOR' AND [ROW_VERSION] = @I_ROW_VERSION;
            IF @@ROWCOUNT = 0 BEGIN SET @O_CODIGO_ERROR = 40007; SET @O_MENSAJE = N'El pedido fue modificado, ya no es borrador o no pertenece a la empresa.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT]; RETURN; END;
            UPDATE [COMERCIAL].[PEDIDOS_DETALLES] SET [CODIGO_ESTADO] = N'INACTIVO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO';
        END;
        INSERT INTO [COMERCIAL].[PEDIDOS_DETALLES] ([ID_PEDIDO], [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_PEDIDO, [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], N'ACTIVO', @S_ID_USUARIO FROM @T_DETALLES;
        SET @O_FILAS_AFECTADAS = 1 + (SELECT COUNT(*) FROM @T_DETALLES); IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION; ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT]; SET @O_MENSAJE = ERROR_MESSAGE(); THROW;
    END CATCH;
END;
GO

/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_VENTA_CREATE_FROM_PEDIDO
Archivo: SP_VENTA_CREATE_FROM_PEDIDO.sql | Procedimiento: COMERCIAL.SP_VENTA_CREATE_FROM_PEDIDO | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Convierte un pedido confirmado en venta interna y descuenta el stock reservado.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Copia la fotografía promocional a la venta inmutable.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO]
    @I_ID_PEDIDO BIGINT, @I_ID_EMPRESA BIGINT, @I_FECHA_VENTA_UTC DATETIME2(3), @I_ROW_VERSION BINARY(8),
    @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT, @O_ID_VENTA BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_ID_VENTA = NULL; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_VENTA_UTC IS NULL THROW 50000, 'La fecha de venta es obligatoria.', 1;
    DECLARE @V_INICIO_TRANSACCION BIT = 0, @V_ID_MOVIMIENTO BIGINT, @V_CODIGO_MOVIMIENTO BIGINT, @V_MENSAJE_MOVIMIENTO NVARCHAR(4000), @V_FILAS_MOVIMIENTO INT;
    BEGIN TRY
        IF @@TRANCOUNT = 0 BEGIN BEGIN TRANSACTION; SET @V_INICIO_TRANSACCION = 1; END ELSE SAVE TRANSACTION [SP_VENTA_CREATE_SAVEPOINT];
        IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'CONFIRMADO' AND [ROW_VERSION] = @I_ROW_VERSION)
        BEGIN SET @O_CODIGO_ERROR = 40006; SET @O_MENSAJE = N'El pedido fue modificado o no está confirmado.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;
        IF EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET] WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO' AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[RESERVAS_STOCK] AS [RES] WHERE [RES].[ID_PEDIDO_DETALLE] = [DET].[ID_PEDIDO_DETALLE] AND [RES].[CODIGO_ESTADO] = N'RESERVADA' AND [RES].[CANTIDAD] = [DET].[CANTIDAD]))
        BEGIN SET @O_CODIGO_ERROR = 40005; SET @O_MENSAJE = N'El pedido no conserva todas sus reservas de stock.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;

        DECLARE @V_DETALLES_JSON NVARCHAR(MAX) = (SELECT [ID_PRODUCTO] AS [ProductId], [ID_DEPOSITO] AS [OriginWarehouseId], [CANTIDAD] AS [Quantity] FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO' FOR JSON PATH);
        DECLARE @V_OBSERVACION_MOVIMIENTO NVARCHAR(500) = N'Venta originada por pedido ' + CONVERT(NVARCHAR(30), @I_ID_PEDIDO);
        EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @I_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'SALIDA', @I_FECHA_MOVIMIENTO_UTC = @I_FECHA_VENTA_UTC,
            @I_OBSERVACION = @V_OBSERVACION_MOVIMIENTO, @I_DETALLES_JSON = @V_DETALLES_JSON, @I_ID_PEDIDO_RESERVADO = @I_ID_PEDIDO,
            @S_ID_SESION = @S_ID_SESION, @S_ID_USUARIO = @S_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_MOVIMIENTO OUTPUT,
            @O_MENSAJE = @V_MENSAJE_MOVIMIENTO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_MOVIMIENTO OUTPUT;
        IF @V_CODIGO_MOVIMIENTO IS NOT NULL BEGIN SET @O_CODIGO_ERROR = @V_CODIGO_MOVIMIENTO; SET @O_MENSAJE = @V_MENSAJE_MOVIMIENTO; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_VENTA_CREATE_SAVEPOINT]; RETURN; END;

        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMERCIAL].[SEQ_VENTA_CODIGO], @V_CODIGO NVARCHAR(30);
        SET @V_CODIGO = N'VEN-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;
        INSERT INTO [COMERCIAL].[VENTAS] ([ID_EMPRESA], [ID_PEDIDO], [ID_CLIENTE], [ID_MOVIMIENTO], [CODIGO], [FECHA_VENTA_UTC], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT [ID_EMPRESA], [ID_PEDIDO], [ID_CLIENTE], @V_ID_MOVIMIENTO, @V_CODIGO, @I_FECHA_VENTA_UTC, [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], N'CONFIRMADA', @S_ID_USUARIO FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        SET @O_ID_VENTA = CONVERT(BIGINT, SCOPE_IDENTITY());
        INSERT INTO [COMERCIAL].[VENTAS_DETALLES] ([ID_VENTA], [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_VENTA, [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], N'ACTIVO', @S_ID_USUARIO FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO';
        SET @O_FILAS_AFECTADAS = 2 + @@ROWCOUNT + COALESCE(@V_FILAS_MOVIMIENTO, 0);
        UPDATE [INVENTARIO].[RESERVAS_STOCK] SET [CODIGO_ESTADO] = N'APLICADA', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'RESERVADA';
        UPDATE [COMERCIAL].[PEDIDOS] SET [CODIGO_ESTADO] = N'VENDIDO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION; ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_VENTA_CREATE_SAVEPOINT]; SET @O_MENSAJE = ERROR_MESSAGE(); THROW;
    END CATCH;
END;
GO

/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_VENTAS_GET
Archivo: SP_VENTAS_GET.sql | Procedimiento: COMERCIAL.SP_VENTAS_GET | Tipo: QUERY
Versión: 1.1.1 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera catálogos, precios, pedidos, reservas y ventas de la empresa autenticada.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Catálogo y fotografía de promociones para pedidos y ventas.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_VENTAS_GET]
    @I_ID_EMPRESA BIGINT, @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL;

    SELECT [ID_CLIENTE], [CODIGO], CONCAT([NOMBRE_RAZON_SOCIAL], CASE WHEN [APELLIDO] IS NULL THEN N'' ELSE N' ' + [APELLIDO] END) AS [NOMBRE]
    FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [NOMBRE_RAZON_SOCIAL], [APELLIDO];

    SELECT [ID_LISTA_PRECIO], [CODIGO], [NOMBRE], [MONEDA], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA], [CODIGO_ESTADO], [ROW_VERSION]
    FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [NOMBRE];

    SELECT [LPP].[ID_LISTA_PRECIO_PRODUCTO], [LPP].[ID_LISTA_PRECIO], [LPP].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO], [LPP].[PRECIO_UNITARIO], [LPP].[CODIGO_ESTADO], [LPP].[ROW_VERSION]
    FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] AS [LPP]
    INNER JOIN [COMERCIAL].[LISTAS_PRECIOS] AS [LIS] ON [LIS].[ID_LISTA_PRECIO] = [LPP].[ID_LISTA_PRECIO]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [LPP].[ID_PRODUCTO]
    WHERE [LIS].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [LIS].[NOMBRE], [PRO].[CODIGO];

    SELECT [PRO].[ID_PRODUCTO], [PRO].[CODIGO], [PRO].[NOMBRE], [UNI].[SIMBOLO]
    FROM [INVENTARIO].[PRODUCTOS] AS [PRO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    WHERE [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO' ORDER BY [PRO].[CODIGO];

    SELECT [ID_DEPOSITO], [CODIGO], [NOMBRE] FROM [INVENTARIO].[DEPOSITOS]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [NOMBRE];

    SELECT [PRM].[ID_PROMOCION], [PRM].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO],
           [PRM].[CODIGO], [PRM].[NOMBRE], [PRM].[DESCRIPCION], [PRM].[TIPO_PROMOCION], [PRM].[CANTIDAD_REQUERIDA],
           [PRM].[CANTIDAD_PAGADA], [PRM].[CANTIDAD_BONIFICADA], [PRM].[PORCENTAJE_DESCUENTO], [PRM].[PRECIO_PAQUETE],
           [PRM].[FECHA_VIGENCIA_DESDE], [PRM].[FECHA_VIGENCIA_HASTA], [PRM].[CODIGO_ESTADO], [PRM].[ROW_VERSION]
    FROM [COMERCIAL].[PROMOCIONES] AS [PRM]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [PRM].[ID_PRODUCTO]
    WHERE [PRM].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PRM].[NOMBRE], [PRO].[CODIGO];

    SELECT [PED].[ID_PEDIDO], [PED].[ID_CLIENTE], [PED].[ID_LISTA_PRECIO], [PED].[CODIGO], [PED].[FECHA_PEDIDO_UTC], [CLI].[NOMBRE_RAZON_SOCIAL] AS [CLIENTE], [PED].[MONEDA],
           [PED].[SUBTOTAL], [PED].[TOTAL_DESCUENTO], [PED].[TOTAL_IMPUESTO], [PED].[TOTAL], [PED].[OBSERVACION], [PED].[CODIGO_ESTADO], [PED].[ROW_VERSION],
           [DET].[ID_PEDIDO_DETALLE], [DET].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO], [DET].[ID_DEPOSITO], [DEP].[NOMBRE] AS [DEPOSITO],
           [DET].[ID_PROMOCION], [DET].[CODIGO_PROMOCION], [DET].[NOMBRE_PROMOCION],
           [DET].[CANTIDAD], [DET].[PRECIO_UNITARIO], [DET].[PORCENTAJE_DESCUENTO], [DET].[PORCENTAJE_IMPUESTO], [DET].[SUBTOTAL] AS [SUBTOTAL_RENGLON],
           [DET].[IMPORTE_DESCUENTO], [DET].[IMPORTE_IMPUESTO], [DET].[TOTAL] AS [TOTAL_RENGLON], [UNI].[SIMBOLO]
    FROM [COMERCIAL].[PEDIDOS] AS [PED]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [PED].[ID_CLIENTE]
    INNER JOIN [COMERCIAL].[PEDIDOS_DETALLES] AS [DET] ON [DET].[ID_PEDIDO] = [PED].[ID_PEDIDO] AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    INNER JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [DET].[ID_DEPOSITO]
    WHERE [PED].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [PED].[FECHA_PEDIDO_UTC] DESC, [DET].[ID_PEDIDO_DETALLE];

    SELECT [VEN].[ID_VENTA], [VEN].[ID_PEDIDO], [VEN].[ID_CLIENTE], [VEN].[ID_MOVIMIENTO], [VEN].[CODIGO], [VEN].[FECHA_VENTA_UTC], [CLI].[NOMBRE_RAZON_SOCIAL] AS [CLIENTE], [VEN].[MONEDA],
           [VEN].[SUBTOTAL], [VEN].[TOTAL_DESCUENTO], [VEN].[TOTAL_IMPUESTO], [VEN].[TOTAL], [VEN].[OBSERVACION], [VEN].[CODIGO_ESTADO],
           [DET].[ID_VENTA_DETALLE], [DET].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO], [DET].[ID_DEPOSITO], [DEP].[NOMBRE] AS [DEPOSITO],
           [DET].[ID_PROMOCION], [DET].[CODIGO_PROMOCION], [DET].[NOMBRE_PROMOCION],
           [DET].[CANTIDAD], [DET].[PRECIO_UNITARIO], [DET].[PORCENTAJE_DESCUENTO], [DET].[PORCENTAJE_IMPUESTO], [DET].[SUBTOTAL] AS [SUBTOTAL_RENGLON],
           [DET].[IMPORTE_DESCUENTO], [DET].[IMPORTE_IMPUESTO], [DET].[TOTAL] AS [TOTAL_RENGLON], [UNI].[SIMBOLO]
    FROM [COMERCIAL].[VENTAS] AS [VEN]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [VEN].[ID_CLIENTE]
    INNER JOIN [COMERCIAL].[VENTAS_DETALLES] AS [DET] ON [DET].[ID_VENTA] = [VEN].[ID_VENTA]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    INNER JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [DET].[ID_DEPOSITO]
    WHERE [VEN].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [VEN].[FECHA_VENTA_UTC] DESC, [DET].[ID_VENTA_DETALLE];
END;
GO

IF OBJECT_ID(N'[COMERCIAL].[SP_PROMOCION_SAVE]', N'P') IS NULL OR OBJECT_ID(N'[COMERCIAL].[SP_PEDIDO_SAVE]', N'P') IS NULL OR OBJECT_ID(N'[COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO]', N'P') IS NULL OR OBJECT_ID(N'[COMERCIAL].[SP_VENTAS_GET]', N'P') IS NULL
    THROW 50002, 'La actualización de procedimientos de promociones no quedó completa.', 1;
