/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Índices AUDITORIA
Archivo:               IX_AUDITORIA.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Asegura códigos de error y agiliza diagnóstico y trazabilidad.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
CREATE UNIQUE INDEX [UX_CATALOGO_ERRORES_CODIGO] ON [AUDITORIA].[CATALOGO_ERRORES] ([CODIGO_ERROR]);
CREATE UNIQUE INDEX [UX_CATALOGO_ERRORES_MODULO_NUMERO] ON [AUDITORIA].[CATALOGO_ERRORES] ([ID_MODULO], [NUMERO_ERROR]);
CREATE INDEX [IX_ERRORES_APLICACION_CORRELACION_FECHA] ON [AUDITORIA].[ERRORES_APLICACION] ([ID_CORRELACION], [FECHA_OCURRENCIA_UTC]);
CREATE INDEX [IX_ERRORES_APLICACION_CODIGO_FECHA] ON [AUDITORIA].[ERRORES_APLICACION] ([CODIGO_ERROR], [FECHA_OCURRENCIA_UTC]);
CREATE UNIQUE INDEX [UX_SOLUCIONES_ERROR_PREFERIDA] ON [AUDITORIA].[SOLUCIONES_ERROR] ([ID_CATALOGO_ERROR]) WHERE [ES_PREFERIDA] = 1 AND [CODIGO_ESTADO] = N'ACTIVO';
CREATE INDEX [IX_LOGUEO_FUNCIONALIDADES_CORRELACION] ON [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ([ID_CORRELACION], [FECHA_INICIO_UTC]);
CREATE INDEX [IX_LOGUEO_FUNCIONALIDADES_SP_FECHA] ON [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ([SCHEMA_SP], [NOMBRE_SP], [FECHA_INICIO_UTC]);
CREATE INDEX [IX_BITACORA_CAMBIOS_ESTADO_ENTIDAD_PKEY] ON [AUDITORIA].[BITACORA_CAMBIOS_ESTADO] ([ENTIDAD], [PKEY], [FECHA_CAMBIO_UTC]);
