/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Índices CONFIGURACION y COMERCIAL
Archivo:               IX_CONFIGURACION_COMERCIAL.sql
Versión:               1.1.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Protege códigos naturales y acelera relaciones operativas.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
1.1.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Unicidad de preferencias y traducciones.
===============================================================================
*/
CREATE UNIQUE INDEX [UX_EMPRESAS_CODIGO] ON [CONFIGURACION].[EMPRESAS] ([CODIGO]);
CREATE UNIQUE INDEX [UX_EMPRESAS_CUIT] ON [CONFIGURACION].[EMPRESAS] ([CUIT]) WHERE [CUIT] IS NOT NULL;
CREATE UNIQUE INDEX [UX_SUCURSALES_EMPRESA_CODIGO] ON [CONFIGURACION].[SUCURSALES] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_UNIDADES_OPERATIVAS_SUCURSAL_CODIGO] ON [CONFIGURACION].[UNIDADES_OPERATIVAS] ([ID_SUCURSAL], [CODIGO]);
CREATE UNIQUE INDEX [UX_MODULOS_NUMERO] ON [CONFIGURACION].[MODULOS] ([NUMERO_MODULO]);
CREATE UNIQUE INDEX [UX_MODULOS_CODIGO] ON [CONFIGURACION].[MODULOS] ([CODIGO]);
CREATE UNIQUE INDEX [UX_PARAMETROS_SISTEMA_MODULO_CLAVE] ON [CONFIGURACION].[PARAMETROS_SISTEMA] ([ID_MODULO], [CLAVE]);
CREATE UNIQUE INDEX [UX_USUARIOS_PREFERENCIAS_USUARIO] ON [CONFIGURACION].[USUARIOS_PREFERENCIAS] ([ID_USUARIO]);
CREATE UNIQUE INDEX [UX_TRADUCCIONES_CATALOGO_ENTIDAD_CODIGO_CULTURA]
    ON [CONFIGURACION].[TRADUCCIONES_CATALOGO] ([ENTIDAD], [CODIGO], [CULTURA]);
CREATE UNIQUE INDEX [UX_CLIENTES_EMPRESA_CODIGO] ON [COMERCIAL].[CLIENTES] ([ID_EMPRESA], [CODIGO]);
CREATE INDEX [IX_CLIENTES_EMPRESA_ESTADO] ON [COMERCIAL].[CLIENTES] ([ID_EMPRESA], [CODIGO_ESTADO]);
