/* Proyecto: Sistema Modular de Gestión OxiTigre | Componente: Índices Pedidos y Ventas | Archivo: IX_COMERCIAL_VENTAS.sql | Versión: 1.1.0 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com | Descripción funcional: Asegura unicidad y consultas comerciales y promocionales. | Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial. | Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Unicidad y búsqueda de promociones aplicables. */
CREATE UNIQUE INDEX [UX_LISTAS_PRECIOS_EMPRESA_CODIGO] ON [COMERCIAL].[LISTAS_PRECIOS] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_LISTAS_PRECIOS_PRODUCTOS] ON [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO]);
CREATE UNIQUE INDEX [UX_PROMOCIONES_EMPRESA_CODIGO] ON [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [CODIGO]);
CREATE INDEX [IX_PROMOCIONES_APLICABLES] ON [COMERCIAL].[PROMOCIONES] ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO_ESTADO], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA]);
CREATE UNIQUE INDEX [UX_PEDIDOS_EMPRESA_CODIGO] ON [COMERCIAL].[PEDIDOS] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_VENTAS_EMPRESA_CODIGO] ON [COMERCIAL].[VENTAS] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_VENTAS_PEDIDO] ON [COMERCIAL].[VENTAS] ([ID_PEDIDO]);
CREATE UNIQUE INDEX [UX_PEDIDOS_ACTIVOS_ACTIVOS] ON [COMERCIAL].[PEDIDOS_ACTIVOS] ([ID_PEDIDO], [ID_ACTIVO], [ID_PRODUCTO_RENGLON], [TIPO_VINCULO]) WHERE [CODIGO_ESTADO] = N'ACTIVO';
CREATE INDEX [IX_PEDIDOS_ACTIVOS_ACTIVO] ON [COMERCIAL].[PEDIDOS_ACTIVOS] ([ID_ACTIVO], [CODIGO_ESTADO]) INCLUDE ([ID_PEDIDO], [TIPO_VINCULO]);
CREATE UNIQUE INDEX [UX_RESERVAS_STOCK_PEDIDO_DETALLE] ON [INVENTARIO].[RESERVAS_STOCK] ([ID_PEDIDO_DETALLE]) WHERE [CODIGO_ESTADO] = N'RESERVADA';
CREATE INDEX [IX_RESERVAS_STOCK_DISPONIBLE] ON [INVENTARIO].[RESERVAS_STOCK] ([ID_PRODUCTO], [ID_DEPOSITO], [CODIGO_ESTADO]) INCLUDE ([CANTIDAD], [ID_PEDIDO]);
