/* Proyecto: Sistema Modular de Gestión OxiTigre | Componente: Índices Fase 7 | Archivo: IX_FASE7_COMPRAS_TRAZABILIDAD.sql | Versión: 1.0.0 | Fecha: 2026-08-24 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com | Descripción funcional: Asegura unicidad y búsquedas de Compras y trazabilidad. | Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial. */
CREATE UNIQUE INDEX [UX_PROVEEDORES_EMPRESA_CODIGO] ON [COMPRAS].[PROVEEDORES] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_PROVEEDORES_EMPRESA_CUIT] ON [COMPRAS].[PROVEEDORES] ([ID_EMPRESA], [CUIT]);
CREATE UNIQUE INDEX [UX_PROVEEDORES_CONTACTOS_PRINCIPAL] ON [COMPRAS].[PROVEEDORES_CONTACTOS] ([ID_PROVEEDOR]) WHERE [ES_PRINCIPAL] = 1 AND [CODIGO_ESTADO] = N'ACTIVO';
CREATE UNIQUE INDEX [UX_ORDENES_COMPRA_EMPRESA_CODIGO] ON [COMPRAS].[ORDENES_COMPRA] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_ORDENES_COMPRA_DETALLE_PRODUCTO] ON [COMPRAS].[ORDENES_COMPRA_DETALLES] ([ID_ORDEN_COMPRA], [ID_PRODUCTO]);
CREATE UNIQUE INDEX [UX_RECEPCIONES_EMPRESA_CODIGO] ON [COMPRAS].[RECEPCIONES_COMPRA] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_RECEPCIONES_EMPRESA_REMITO] ON [COMPRAS].[RECEPCIONES_COMPRA] ([ID_EMPRESA], [NUMERO_DOCUMENTO_PROVEEDOR]) WHERE [NUMERO_DOCUMENTO_PROVEEDOR] IS NOT NULL;
CREATE UNIQUE INDEX [UX_LOTES_EMPRESA_CODIGO] ON [INVENTARIO].[LOTES] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_LOTES_EXISTENCIAS_POSICION] ON [INVENTARIO].[LOTES_EXISTENCIAS] ([ID_LOTE], [ID_DEPOSITO], [ID_UBICACION]) WHERE [ID_UBICACION] IS NOT NULL;
CREATE UNIQUE INDEX [UX_LOTES_EXISTENCIAS_DEPOSITO] ON [INVENTARIO].[LOTES_EXISTENCIAS] ([ID_LOTE], [ID_DEPOSITO]) WHERE [ID_UBICACION] IS NULL;
CREATE UNIQUE INDEX [UX_ACTIVOS_EMPRESA_CODIGO] ON [INVENTARIO].[ACTIVOS] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_ACTIVOS_EMPRESA_SERIE] ON [INVENTARIO].[ACTIVOS] ([ID_EMPRESA], [NUMERO_SERIE]);
CREATE INDEX [IX_ACTIVOS_CLIENTE_PROPIETARIO] ON [INVENTARIO].[ACTIVOS] ([ID_EMPRESA], [ID_CLIENTE_PROPIETARIO], [CODIGO_ESTADO]) WHERE [ID_CLIENTE_PROPIETARIO] IS NOT NULL;
CREATE UNIQUE INDEX [UX_ACTIVOS_CONTENIDO_ACTIVO] ON [INVENTARIO].[ACTIVOS_CONTENIDOS] ([ID_ACTIVO]) WHERE [CODIGO_ESTADO] = N'ACTIVO';
CREATE UNIQUE INDEX [UX_MOVIMIENTOS_DETALLES_LOTES] ON [INVENTARIO].[MOVIMIENTOS_DETALLES_LOTES] ([ID_MOVIMIENTO_DETALLE], [ID_LOTE]);
CREATE UNIQUE INDEX [UX_MOVIMIENTOS_DETALLES_ACTIVOS] ON [INVENTARIO].[MOVIMIENTOS_DETALLES_ACTIVOS] ([ID_MOVIMIENTO_DETALLE], [ID_ACTIVO]);
CREATE INDEX [IX_MEDICIONES_ACTIVO_FECHA] ON [INVENTARIO].[MEDICIONES_ACTIVOS] ([ID_ACTIVO], [FECHA_MEDICION_UTC] DESC);
CREATE INDEX [IX_EVENTOS_ACTIVO_FECHA] ON [INVENTARIO].[ACTIVOS_EVENTOS] ([ID_ACTIVO], [FECHA_EVENTO_UTC] DESC);
CREATE UNIQUE INDEX [UX_PRESTAMOS_ACTIVO_ABIERTO] ON [INVENTARIO].[PRESTAMOS_DETALLES] ([ID_ACTIVO]) WHERE [CODIGO_ESTADO] = N'PRESTADO';
