/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Índices financieros
Archivo: IX_FASE11_FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Garantiza unicidad operativa y acelera consultas de cobros y saldos.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[MEDIOS_PAGO]') AND [name] = N'UX_MEDIOS_PAGO_EMPRESA_CODIGO')
BEGIN
    CREATE UNIQUE INDEX [UX_MEDIOS_PAGO_EMPRESA_CODIGO] ON [FINANZAS].[MEDIOS_PAGO] ([ID_EMPRESA], [CODIGO]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[CAJAS]') AND [name] = N'UX_CAJAS_EMPRESA_CODIGO')
BEGIN
    CREATE UNIQUE INDEX [UX_CAJAS_EMPRESA_CODIGO] ON [FINANZAS].[CAJAS] ([ID_EMPRESA], [CODIGO]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[SESIONES_CAJA]') AND [name] = N'UX_SESIONES_CAJA_CAJA_ABIERTA')
BEGIN
    CREATE UNIQUE INDEX [UX_SESIONES_CAJA_CAJA_ABIERTA] ON [FINANZAS].[SESIONES_CAJA] ([ID_CAJA]) WHERE [CODIGO_ESTADO] = N'ABIERTA';
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[SESIONES_CAJA]') AND [name] = N'UX_SESIONES_CAJA_USUARIO_ABIERTA')
BEGIN
    CREATE UNIQUE INDEX [UX_SESIONES_CAJA_USUARIO_ABIERTA] ON [FINANZAS].[SESIONES_CAJA] ([ID_EMPRESA], [ID_USUARIO_APERTURA]) WHERE [CODIGO_ESTADO] = N'ABIERTA';
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[PAGOS]') AND [name] = N'UX_PAGOS_EMPRESA_CODIGO')
BEGIN
    CREATE UNIQUE INDEX [UX_PAGOS_EMPRESA_CODIGO] ON [FINANZAS].[PAGOS] ([ID_EMPRESA], [CODIGO]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[APLICACIONES_PAGO_VENTA]') AND [name] = N'UX_APLICACIONES_PAGO_VENTA')
BEGIN
    CREATE UNIQUE INDEX [UX_APLICACIONES_PAGO_VENTA] ON [FINANZAS].[APLICACIONES_PAGO_VENTA] ([ID_PAGO], [ID_VENTA]);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[MOVIMIENTOS_CUENTA]') AND [name] = N'UX_MOVIMIENTO_CUENTA_VENTA')
BEGIN
    CREATE UNIQUE INDEX [UX_MOVIMIENTO_CUENTA_VENTA] ON [FINANZAS].[MOVIMIENTOS_CUENTA] ([ID_VENTA]) WHERE [ID_VENTA] IS NOT NULL AND [ORIGEN] = N'VENTA';
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[PAGOS]') AND [name] = N'IX_PAGOS_CLIENTE_FECHA')
BEGIN
    CREATE INDEX [IX_PAGOS_CLIENTE_FECHA] ON [FINANZAS].[PAGOS] ([ID_CLIENTE], [FECHA_PAGO_UTC] DESC);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [object_id] = OBJECT_ID(N'[FINANZAS].[MOVIMIENTOS_CUENTA]') AND [name] = N'IX_MOVIMIENTOS_CUENTA_CLIENTE_FECHA')
BEGIN
    CREATE INDEX [IX_MOVIMIENTOS_CUENTA_CLIENTE_FECHA] ON [FINANZAS].[MOVIMIENTOS_CUENTA] ([ID_CLIENTE], [FECHA_MOVIMIENTO_UTC] DESC);
END;
