/* Proyecto: Sistema Modular de Gestión OxiTigre | Componente: Índices Inventario | Archivo: IX_INVENTARIO.sql | Versión: 1.0.0 | Fecha: 2026-08-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com | Descripción funcional: Asegura unicidad y búsquedas del inventario. | Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial. */
CREATE UNIQUE INDEX [UX_UNIDADES_MEDIDA_CODIGO] ON [CONFIGURACION].[UNIDADES_MEDIDA] ([CODIGO]);
CREATE UNIQUE INDEX [UX_CATEGORIAS_PRODUCTO_CODIGO] ON [INVENTARIO].[CATEGORIAS_PRODUCTO] ([CODIGO]);
CREATE UNIQUE INDEX [UX_PRODUCTOS_EMPRESA_CODIGO] ON [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_PRODUCTOS_EMPRESA_BARRAS] ON [INVENTARIO].[PRODUCTOS] ([ID_EMPRESA], [CODIGO_BARRAS]) WHERE [CODIGO_BARRAS] IS NOT NULL;
CREATE UNIQUE INDEX [UX_DEPOSITOS_EMPRESA_CODIGO] ON [INVENTARIO].[DEPOSITOS] ([ID_EMPRESA], [CODIGO]);
CREATE UNIQUE INDEX [UX_UBICACIONES_DEPOSITO_CODIGO] ON [INVENTARIO].[UBICACIONES] ([ID_DEPOSITO], [CODIGO]);
CREATE UNIQUE INDEX [UX_EXISTENCIAS_PRODUCTO_DEPOSITO] ON [INVENTARIO].[EXISTENCIAS] ([ID_PRODUCTO], [ID_DEPOSITO]);
CREATE UNIQUE INDEX [UX_MOVIMIENTOS_EMPRESA_CODIGO] ON [INVENTARIO].[MOVIMIENTOS] ([ID_EMPRESA], [CODIGO]);
CREATE INDEX [IX_MOVIMIENTOS_EMPRESA_FECHA] ON [INVENTARIO].[MOVIMIENTOS] ([ID_EMPRESA], [FECHA_MOVIMIENTO_UTC] DESC);
