/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Índices SEGURIDAD
Archivo:               IX_SEGURIDAD.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Impide identidades duplicadas y optimiza autenticación y autorización.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
CREATE UNIQUE INDEX [UX_USUARIOS_EMPRESA_NOMBRE_USUARIO] ON [SEGURIDAD].[USUARIOS] ([ID_EMPRESA], [NOMBRE_USUARIO]);
CREATE UNIQUE INDEX [UX_USUARIOS_EMPRESA_EMAIL] ON [SEGURIDAD].[USUARIOS] ([ID_EMPRESA], [EMAIL]);
CREATE UNIQUE INDEX [UX_ROLES_EMPRESA_CODIGO] ON [SEGURIDAD].[ROLES] ([ID_EMPRESA], [CODIGO]) WHERE [ID_EMPRESA] IS NOT NULL;
CREATE UNIQUE INDEX [UX_ROLES_SISTEMA_CODIGO] ON [SEGURIDAD].[ROLES] ([CODIGO]) WHERE [ID_EMPRESA] IS NULL;
CREATE UNIQUE INDEX [UX_PERMISOS_CODIGO] ON [SEGURIDAD].[PERMISOS] ([CODIGO]);
CREATE UNIQUE INDEX [UX_USUARIOS_ROLES_ACTIVOS] ON [SEGURIDAD].[USUARIOS_ROLES] ([ID_USUARIO], [ID_ROL]) WHERE [CODIGO_ESTADO] = N'ACTIVO';
CREATE UNIQUE INDEX [UX_ROLES_PERMISOS_ACTIVOS] ON [SEGURIDAD].[ROLES_PERMISOS] ([ID_ROL], [ID_PERMISO]) WHERE [CODIGO_ESTADO] = N'ACTIVO';
CREATE UNIQUE INDEX [UX_DISPOSITIVOS_IDENTIFICADOR] ON [SEGURIDAD].[DISPOSITIVOS_ACCESO] ([IDENTIFICADOR_DISPOSITIVO]);
CREATE UNIQUE INDEX [UX_SESIONES_HASH_TOKEN] ON [SEGURIDAD].[SESIONES] ([HASH_TOKEN]);
CREATE INDEX [IX_SESIONES_USUARIO_ESTADO_EXPIRACION] ON [SEGURIDAD].[SESIONES] ([ID_USUARIO], [CODIGO_ESTADO], [FECHA_EXPIRACION_UTC]);
CREATE UNIQUE INDEX [UX_RECUPERACIONES_CLAVE_HASH_TOKEN] ON [SEGURIDAD].[RECUPERACIONES_CLAVE] ([HASH_TOKEN]);
