/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Restricciones de dominio del núcleo
Archivo:               CK_CORE.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Impide valores incoherentes en configuración, seguridad y auditoría.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
ALTER TABLE [CONFIGURACION].[ESTADOS] ADD CONSTRAINT [CK_ESTADOS_ORDEN]
    CHECK ([ORDEN] >= 0 AND ([FECHA_VIGENCIA_HASTA_UTC] IS NULL OR [FECHA_VIGENCIA_HASTA_UTC] > [FECHA_VIGENCIA_DESDE_UTC]));
ALTER TABLE [CONFIGURACION].[MODULOS] ADD CONSTRAINT [CK_MODULOS_NUMERO_ORDEN]
    CHECK ([NUMERO_MODULO] BETWEEN 1 AND 999 AND [ORDEN] >= 0);
ALTER TABLE [CONFIGURACION].[PARAMETROS_SISTEMA] ADD CONSTRAINT [CK_PARAMETROS_SISTEMA_SECRETO]
    CHECK (([ES_SECRETO] = 0) OR ([ES_SECRETO] = 1 AND [VALOR] IS NULL AND [REFERENCIA_SECRETO] IS NOT NULL));
ALTER TABLE [COMERCIAL].[CLIENTES] ADD CONSTRAINT [CK_CLIENTES_TIPO_PERSONA]
    CHECK ([TIPO_PERSONA] IN ('F', 'J'));
ALTER TABLE [SEGURIDAD].[USUARIOS] ADD CONSTRAINT [CK_USUARIOS_CREDENCIAL]
    CHECK ([ITERACIONES_CLAVE] >= 100000 AND [INTENTOS_FALLIDOS] >= 0);
ALTER TABLE [SEGURIDAD].[USUARIOS_ROLES] ADD CONSTRAINT [CK_USUARIOS_ROLES_VIGENCIA]
    CHECK ([FECHA_VIGENCIA_HASTA_UTC] IS NULL OR [FECHA_VIGENCIA_HASTA_UTC] > [FECHA_VIGENCIA_DESDE_UTC]);
ALTER TABLE [SEGURIDAD].[SESIONES] ADD CONSTRAINT [CK_SESIONES_VIGENCIA]
    CHECK ([FECHA_EXPIRACION_UTC] > [FECHA_INICIO_UTC] AND ([FECHA_CIERRE_UTC] IS NULL OR [FECHA_CIERRE_UTC] >= [FECHA_INICIO_UTC]));
ALTER TABLE [SEGURIDAD].[RECUPERACIONES_CLAVE] ADD CONSTRAINT [CK_RECUPERACIONES_CLAVE_VIGENCIA]
    CHECK ([FECHA_EXPIRACION_UTC] > [FECHA_SOLICITUD_UTC] AND ([FECHA_USO_UTC] IS NULL OR [FECHA_USO_UTC] >= [FECHA_SOLICITUD_UTC]));
ALTER TABLE [AUDITORIA].[CATALOGO_ERRORES] ADD CONSTRAINT [CK_CATALOGO_ERRORES_CODIGO]
    CHECK ([NUMERO_ERROR] BETWEEN 1 AND 9999 AND [CODIGO_ERROR] BETWEEN 10001 AND 9999999 AND [CODIGO_ERROR] % 10000 = [NUMERO_ERROR]);
ALTER TABLE [AUDITORIA].[CATALOGO_ERRORES] ADD CONSTRAINT [CK_CATALOGO_ERRORES_SEVERIDAD]
    CHECK ([SEVERIDAD] IN (N'INFORMATIVO', N'ADVERTENCIA', N'ERROR', N'CRITICO'));
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [CK_LOGUEO_FUNCIONALIDADES_RESULTADO]
    CHECK ([RESULTADO] IN (N'EXITOSO', N'ERROR', N'CANCELADO') AND ([DURACION_MS] IS NULL OR [DURACION_MS] >= 0) AND ([FILAS_AFECTADAS] IS NULL OR [FILAS_AFECTADAS] >= 0));
