/* Proyecto: Sistema Modular de Gestión OxiTigre | Componente: Restricciones Pedidos y Ventas | Archivo: CK_COMERCIAL_VENTAS.sql | Versión: 1.1.0 | Fecha: 2026-08-21 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com | Descripción funcional: Impide importes, porcentajes, vigencias y reglas promocionales inválidas. | Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial. | Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Validación física de los tres tipos de promoción. */
ALTER TABLE [COMERCIAL].[LISTAS_PRECIOS] ADD CONSTRAINT [CK_LISTAS_PRECIOS_VIGENCIA] CHECK ([FECHA_VIGENCIA_HASTA] IS NULL OR [FECHA_VIGENCIA_DESDE] IS NULL OR [FECHA_VIGENCIA_HASTA] >= [FECHA_VIGENCIA_DESDE]);
ALTER TABLE [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ADD CONSTRAINT [CK_LISTAS_PRECIOS_PRODUCTOS_PRECIO] CHECK ([PRECIO_UNITARIO] >= 0);
ALTER TABLE [COMERCIAL].[PROMOCIONES] ADD CONSTRAINT [CK_PROMOCIONES_REGLA] CHECK
(
    [CANTIDAD_REQUERIDA] > 0
    AND [CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO')
    AND ([FECHA_VIGENCIA_HASTA] IS NULL OR [FECHA_VIGENCIA_DESDE] IS NULL OR [FECHA_VIGENCIA_HASTA] >= [FECHA_VIGENCIA_DESDE])
    AND
    (
        ([TIPO_PROMOCION] = N'CANTIDAD_PAGADA' AND [CANTIDAD_PAGADA] >= 0 AND [CANTIDAD_PAGADA] < [CANTIDAD_REQUERIDA] AND [CANTIDAD_BONIFICADA] IS NULL AND [PORCENTAJE_DESCUENTO] IS NULL AND [PRECIO_PAQUETE] IS NULL)
        OR ([TIPO_PROMOCION] = N'PORCENTAJE_UNIDADES' AND [CANTIDAD_PAGADA] IS NULL AND [CANTIDAD_BONIFICADA] > 0 AND [CANTIDAD_BONIFICADA] <= [CANTIDAD_REQUERIDA] AND [PORCENTAJE_DESCUENTO] > 0 AND [PORCENTAJE_DESCUENTO] <= 1 AND [PRECIO_PAQUETE] IS NULL)
        OR ([TIPO_PROMOCION] = N'PRECIO_PAQUETE' AND [CANTIDAD_PAGADA] IS NULL AND [CANTIDAD_BONIFICADA] IS NULL AND [PORCENTAJE_DESCUENTO] IS NULL AND [PRECIO_PAQUETE] >= 0)
    )
);
ALTER TABLE [COMERCIAL].[PEDIDOS_DETALLES] ADD CONSTRAINT [CK_PEDIDOS_DETALLES_VALORES] CHECK ([CANTIDAD] > 0 AND [PRECIO_UNITARIO] >= 0 AND [PORCENTAJE_DESCUENTO] BETWEEN 0 AND 1 AND [PORCENTAJE_IMPUESTO] BETWEEN 0 AND 1);
ALTER TABLE [COMERCIAL].[VENTAS_DETALLES] ADD CONSTRAINT [CK_VENTAS_DETALLES_VALORES] CHECK ([CANTIDAD] > 0 AND [PRECIO_UNITARIO] >= 0 AND [PORCENTAJE_DESCUENTO] BETWEEN 0 AND 1 AND [PORCENTAJE_IMPUESTO] BETWEEN 0 AND 1);
ALTER TABLE [COMERCIAL].[PEDIDOS_ACTIVOS] ADD CONSTRAINT [CK_PEDIDOS_ACTIVOS_VALORES] CHECK
(
    [TIPO_VINCULO] IN (N'CLIENTE_SERVICIO', N'VENTA_ACTIVO', N'PRESTAMO', N'INTERCAMBIO')
    AND [MODALIDAD_RETORNO] IN (N'RETIRO_CLIENTE', N'ENTREGA_OXITIGRE', N'NO_APLICA')
    AND NULLIF(LTRIM(RTRIM([OBSERVACION])), N'') IS NOT NULL
    AND [CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO')
);
ALTER TABLE [INVENTARIO].[RESERVAS_STOCK] ADD CONSTRAINT [CK_RESERVAS_STOCK_CANTIDAD] CHECK ([CANTIDAD] > 0);
