/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Validaciones financieras
Archivo: CK_FASE11_FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Restringe estados, importes, monedas y tipos financieros válidos.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF OBJECT_ID(N'[FINANZAS].[CK_MEDIOS_PAGO_TIPO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MEDIOS_PAGO] ADD CONSTRAINT [CK_MEDIOS_PAGO_TIPO] CHECK ([TIPO] IN (N'EFECTIVO', N'TRANSFERENCIA', N'TARJETA', N'CHEQUE', N'OTRO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_MEDIOS_PAGO_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MEDIOS_PAGO] ADD CONSTRAINT [CK_MEDIOS_PAGO_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_CAJAS_MONEDA]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [CK_CAJAS_MONEDA] CHECK ([MONEDA] = UPPER([MONEDA]) AND LEN([MONEDA]) = 3);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_CAJAS_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [CK_CAJAS_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_SESIONES_CAJA_IMPORTES]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [CK_SESIONES_CAJA_IMPORTES] CHECK ([IMPORTE_APERTURA] >= 0 AND ([IMPORTE_CONTADO] IS NULL OR [IMPORTE_CONTADO] >= 0));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_SESIONES_CAJA_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [CK_SESIONES_CAJA_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ABIERTA', N'CERRADA'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_PAGOS_TOTAL]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [CK_PAGOS_TOTAL] CHECK ([TOTAL] > 0);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_PAGOS_ESTADO]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [CK_PAGOS_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'CONFIRMADO', N'REVERTIDO'));
END;
IF OBJECT_ID(N'[FINANZAS].[CK_PAGOS_MEDIOS_IMPORTE]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS_MEDIOS] ADD CONSTRAINT [CK_PAGOS_MEDIOS_IMPORTE] CHECK ([IMPORTE] > 0);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_APLICACIONES_PAGO_IMPORTE]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA] ADD CONSTRAINT [CK_APLICACIONES_PAGO_IMPORTE] CHECK ([IMPORTE] > 0);
END;
IF OBJECT_ID(N'[FINANZAS].[CK_MOVIMIENTOS_CUENTA]', N'C') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [CK_MOVIMIENTOS_CUENTA] CHECK ([TIPO_MOVIMIENTO] IN (N'DEBITO', N'CREDITO') AND [IMPORTE] > 0);
END;
