/* Proyecto: Sistema Modular de Gestión OxiTigre | Componente: Restricciones Inventario | Archivo: CK_INVENTARIO.sql | Versión: 1.0.0 | Fecha: 2026-08-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com | Descripción funcional: Impide cantidades y tipos inválidos. | Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial. */
ALTER TABLE [INVENTARIO].[EXISTENCIAS] ADD CONSTRAINT [CK_EXISTENCIAS_CANTIDAD] CHECK ([CANTIDAD] >= 0 AND [STOCK_MINIMO] >= 0);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS] ADD CONSTRAINT [CK_MOVIMIENTOS_TIPO] CHECK ([TIPO_MOVIMIENTO] IN (N'ENTRADA', N'SALIDA', N'TRANSFERENCIA', N'AJUSTE_ENTRADA', N'AJUSTE_SALIDA'));
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [CK_MOVIMIENTOS_DETALLES_CANTIDAD] CHECK ([CANTIDAD] > 0);
ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD CONSTRAINT [CK_PRODUCTOS_TIPO_ITEM] CHECK
(
    [TIPO_ITEM] IN (N'PRODUCTO', N'SERVICIO')
    AND ([TIPO_ITEM] = N'PRODUCTO' OR
         ([TIPO_TRAZABILIDAD] = N'NINGUNA' AND [ES_REUTILIZABLE] = 0 AND [ADMITE_PRESTAMO] = 0
          AND [REQUIERE_MANTENIMIENTO] = 0 AND [ADMITE_MEDICIONES] = 0))
);
