/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Relaciones AUDITORIA
Archivo:               FK_AUDITORIA.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Relaciona catálogo, ocurrencias, soluciones y trazabilidad.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
ALTER TABLE [AUDITORIA].[CATALOGO_ERRORES] ADD CONSTRAINT [FK_CATALOGO_ERRORES_MODULOS]
    FOREIGN KEY ([ID_MODULO]) REFERENCES [CONFIGURACION].[MODULOS] ([ID_MODULO]);
ALTER TABLE [AUDITORIA].[ERRORES_APLICACION] ADD CONSTRAINT [FK_ERRORES_APLICACION_CATALOGO]
    FOREIGN KEY ([ID_CATALOGO_ERROR]) REFERENCES [AUDITORIA].[CATALOGO_ERRORES] ([ID_CATALOGO_ERROR]);
ALTER TABLE [AUDITORIA].[ERRORES_APLICACION] ADD CONSTRAINT [FK_ERRORES_APLICACION_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
ALTER TABLE [AUDITORIA].[ERRORES_APLICACION] ADD CONSTRAINT [FK_ERRORES_APLICACION_SESIONES]
    FOREIGN KEY ([ID_SESION]) REFERENCES [SEGURIDAD].[SESIONES] ([ID_SESION]);
ALTER TABLE [AUDITORIA].[ERRORES_APLICACION] ADD CONSTRAINT [FK_ERRORES_APLICACION_DISPOSITIVOS]
    FOREIGN KEY ([ID_DISPOSITIVO_ACCESO]) REFERENCES [SEGURIDAD].[DISPOSITIVOS_ACCESO] ([ID_DISPOSITIVO_ACCESO]);
ALTER TABLE [AUDITORIA].[SOLUCIONES_ERROR] ADD CONSTRAINT [FK_SOLUCIONES_ERROR_CATALOGO]
    FOREIGN KEY ([ID_CATALOGO_ERROR]) REFERENCES [AUDITORIA].[CATALOGO_ERRORES] ([ID_CATALOGO_ERROR]);
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [FK_LOGUEO_FUNCIONALIDADES_EMPRESAS]
    FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [FK_LOGUEO_FUNCIONALIDADES_MODULOS]
    FOREIGN KEY ([ID_MODULO]) REFERENCES [CONFIGURACION].[MODULOS] ([ID_MODULO]);
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [FK_LOGUEO_FUNCIONALIDADES_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [FK_LOGUEO_FUNCIONALIDADES_SESIONES]
    FOREIGN KEY ([ID_SESION]) REFERENCES [SEGURIDAD].[SESIONES] ([ID_SESION]);
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [FK_LOGUEO_FUNCIONALIDADES_DISPOSITIVOS]
    FOREIGN KEY ([ID_DISPOSITIVO_ACCESO]) REFERENCES [SEGURIDAD].[DISPOSITIVOS_ACCESO] ([ID_DISPOSITIVO_ACCESO]);
ALTER TABLE [AUDITORIA].[LOGUEO_FUNCIONALIDADES] ADD CONSTRAINT [FK_LOGUEO_FUNCIONALIDADES_ERRORES]
    FOREIGN KEY ([ID_ERROR_APLICACION]) REFERENCES [AUDITORIA].[ERRORES_APLICACION] ([ID_ERROR_APLICACION]);
ALTER TABLE [AUDITORIA].[BITACORA_CAMBIOS_ESTADO] ADD CONSTRAINT [FK_BITACORA_CAMBIOS_ESTADO_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
ALTER TABLE [AUDITORIA].[BITACORA_CAMBIOS_ESTADO] ADD CONSTRAINT [FK_BITACORA_CAMBIOS_ESTADO_SESIONES]
    FOREIGN KEY ([ID_SESION]) REFERENCES [SEGURIDAD].[SESIONES] ([ID_SESION]);
