/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Relaciones financieras
Archivo: FK_FASE11_FINANZAS.sql | Versión: 11.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Conserva integridad entre cajas, cobros, ventas, clientes y empresas.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF OBJECT_ID(N'[FINANZAS].[FK_MEDIOS_PAGO_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MEDIOS_PAGO] ADD CONSTRAINT [FK_MEDIOS_PAGO_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_CAJAS_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [FK_CAJAS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_CAJAS_SUCURSALES]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[CAJAS] ADD CONSTRAINT [FK_CAJAS_SUCURSALES] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [CONFIGURACION].[SUCURSALES] ([ID_SUCURSAL]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_SESIONES_CAJA_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [FK_SESIONES_CAJA_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_SESIONES_CAJA_CAJAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[SESIONES_CAJA] ADD CONSTRAINT [FK_SESIONES_CAJA_CAJAS] FOREIGN KEY ([ID_CAJA]) REFERENCES [FINANZAS].[CAJAS] ([ID_CAJA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [FK_PAGOS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_CLIENTES]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [FK_PAGOS_CLIENTES] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [COMERCIAL].[CLIENTES] ([ID_CLIENTE]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_SESIONES_CAJA]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS] ADD CONSTRAINT [FK_PAGOS_SESIONES_CAJA] FOREIGN KEY ([ID_SESION_CAJA]) REFERENCES [FINANZAS].[SESIONES_CAJA] ([ID_SESION_CAJA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_MEDIOS_PAGOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS_MEDIOS] ADD CONSTRAINT [FK_PAGOS_MEDIOS_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [FINANZAS].[PAGOS] ([ID_PAGO]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_PAGOS_MEDIOS_MEDIOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[PAGOS_MEDIOS] ADD CONSTRAINT [FK_PAGOS_MEDIOS_MEDIOS] FOREIGN KEY ([ID_MEDIO_PAGO]) REFERENCES [FINANZAS].[MEDIOS_PAGO] ([ID_MEDIO_PAGO]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_APLICACIONES_PAGO_PAGOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA] ADD CONSTRAINT [FK_APLICACIONES_PAGO_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [FINANZAS].[PAGOS] ([ID_PAGO]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_APLICACIONES_PAGO_VENTAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[APLICACIONES_PAGO_VENTA] ADD CONSTRAINT [FK_APLICACIONES_PAGO_VENTAS] FOREIGN KEY ([ID_VENTA]) REFERENCES [COMERCIAL].[VENTAS] ([ID_VENTA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_EMPRESAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_CLIENTES]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_CLIENTES] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [COMERCIAL].[CLIENTES] ([ID_CLIENTE]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_VENTAS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_VENTAS] FOREIGN KEY ([ID_VENTA]) REFERENCES [COMERCIAL].[VENTAS] ([ID_VENTA]);
END;
IF OBJECT_ID(N'[FINANZAS].[FK_MOVIMIENTOS_CUENTA_PAGOS]', N'F') IS NULL
BEGIN
    ALTER TABLE [FINANZAS].[MOVIMIENTOS_CUENTA] ADD CONSTRAINT [FK_MOVIMIENTOS_CUENTA_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [FINANZAS].[PAGOS] ([ID_PAGO]);
END;
