/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Relaciones de transporte de Logística Fase 8
Archivo: FK_FASE8_TRANSPORTE.sql | Versión: 1.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Asegura propiedad y asignación histórica de transportistas y vehículos.
Historial: 1.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial idempotente.
===============================================================================
*/
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_LOG_TRANSPORTISTA_EMPRESA')
    ALTER TABLE [LOGISTICA].[TRANSPORTISTAS] ADD CONSTRAINT [FK_LOG_TRANSPORTISTA_EMPRESA]
        FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_LOG_TRANSPORTISTA_USUARIO')
    ALTER TABLE [LOGISTICA].[TRANSPORTISTAS] ADD CONSTRAINT [FK_LOG_TRANSPORTISTA_USUARIO]
        FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_LOG_VEHICULO_EMPRESA')
    ALTER TABLE [LOGISTICA].[VEHICULOS] ADD CONSTRAINT [FK_LOG_VEHICULO_EMPRESA]
        FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_LOG_VEHICULO_PROPIETARIO')
    ALTER TABLE [LOGISTICA].[VEHICULOS] ADD CONSTRAINT [FK_LOG_VEHICULO_PROPIETARIO]
        FOREIGN KEY ([ID_TRANSPORTISTA_PROPIETARIO]) REFERENCES [LOGISTICA].[TRANSPORTISTAS] ([ID_TRANSPORTISTA]);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_LOG_HOJA_TRANSPORTISTA')
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA] ADD CONSTRAINT [FK_LOG_HOJA_TRANSPORTISTA]
        FOREIGN KEY ([ID_TRANSPORTISTA]) REFERENCES [LOGISTICA].[TRANSPORTISTAS] ([ID_TRANSPORTISTA]);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE [name] = N'FK_LOG_HOJA_VEHICULO')
    ALTER TABLE [LOGISTICA].[HOJAS_RUTA] ADD CONSTRAINT [FK_LOG_HOJA_VEHICULO]
        FOREIGN KEY ([ID_VEHICULO]) REFERENCES [LOGISTICA].[VEHICULOS] ([ID_VEHICULO]);
