/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Relaciones de Logística Fase 8
Archivo: FK_FASE8_LOGISTICA.sql | Versión: 1.0.0 | Fecha: 2026-08-26 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Asegura pertenencia y trazabilidad entre clientes, solicitudes, rutas y activos.
Historial: 1.0.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
ALTER TABLE [LOGISTICA].[CLIENTES_DIRECCIONES]
ADD CONSTRAINT [FK_LOG_DIRECCION_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);

ALTER TABLE [LOGISTICA].[CLIENTES_DIRECCIONES]
ADD CONSTRAINT [FK_LOG_DIRECCION_CLIENTE]
    FOREIGN KEY ([ID_CLIENTE])
    REFERENCES [COMERCIAL].[CLIENTES] ([ID_CLIENTE]);

ALTER TABLE [LOGISTICA].[SOLICITUDES]
ADD CONSTRAINT [FK_LOG_SOLICITUD_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);

ALTER TABLE [LOGISTICA].[SOLICITUDES]
ADD CONSTRAINT [FK_LOG_SOLICITUD_CLIENTE]
    FOREIGN KEY ([ID_CLIENTE])
    REFERENCES [COMERCIAL].[CLIENTES] ([ID_CLIENTE]);

ALTER TABLE [LOGISTICA].[SOLICITUDES]
ADD CONSTRAINT [FK_LOG_SOLICITUD_DIRECCION]
    FOREIGN KEY ([ID_DIRECCION])
    REFERENCES [LOGISTICA].[CLIENTES_DIRECCIONES] ([ID_DIRECCION]);

ALTER TABLE [LOGISTICA].[SOLICITUDES]
ADD CONSTRAINT [FK_LOG_SOLICITUD_PEDIDO]
    FOREIGN KEY ([ID_PEDIDO])
    REFERENCES [COMERCIAL].[PEDIDOS] ([ID_PEDIDO]);

ALTER TABLE [LOGISTICA].[SOLICITUDES_ACTIVOS]
ADD CONSTRAINT [FK_LOG_SOLICITUD_ACTIVO_SOLICITUD]
    FOREIGN KEY ([ID_SOLICITUD])
    REFERENCES [LOGISTICA].[SOLICITUDES] ([ID_SOLICITUD]);

ALTER TABLE [LOGISTICA].[SOLICITUDES_ACTIVOS]
ADD CONSTRAINT [FK_LOG_SOLICITUD_ACTIVO_ACTIVO]
    FOREIGN KEY ([ID_ACTIVO])
    REFERENCES [INVENTARIO].[ACTIVOS] ([ID_ACTIVO]);

ALTER TABLE [LOGISTICA].[HOJAS_RUTA]
ADD CONSTRAINT [FK_LOG_HOJA_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);

ALTER TABLE [LOGISTICA].[HOJAS_RUTA_PARADAS]
ADD CONSTRAINT [FK_LOG_PARADA_HOJA]
    FOREIGN KEY ([ID_HOJA_RUTA])
    REFERENCES [LOGISTICA].[HOJAS_RUTA] ([ID_HOJA_RUTA]);

ALTER TABLE [LOGISTICA].[HOJAS_RUTA_PARADAS]
ADD CONSTRAINT [FK_LOG_PARADA_SOLICITUD]
    FOREIGN KEY ([ID_SOLICITUD])
    REFERENCES [LOGISTICA].[SOLICITUDES] ([ID_SOLICITUD]);

ALTER TABLE [LOGISTICA].[EVENTOS]
ADD CONSTRAINT [FK_LOG_EVENTO_SOLICITUD]
    FOREIGN KEY ([ID_SOLICITUD])
    REFERENCES [LOGISTICA].[SOLICITUDES] ([ID_SOLICITUD]);

ALTER TABLE [LOGISTICA].[EVENTOS]
ADD CONSTRAINT [FK_LOG_EVENTO_HOJA]
    FOREIGN KEY ([ID_HOJA_RUTA])
    REFERENCES [LOGISTICA].[HOJAS_RUTA] ([ID_HOJA_RUTA]);

ALTER TABLE [LOGISTICA].[EVENTOS]
ADD CONSTRAINT [FK_LOG_EVENTO_PARADA]
    FOREIGN KEY ([ID_PARADA])
    REFERENCES [LOGISTICA].[HOJAS_RUTA_PARADAS] ([ID_PARADA]);

ALTER TABLE [LOGISTICA].[NOTIFICACIONES]
ADD CONSTRAINT [FK_LOG_NOTIFICACION_SOLICITUD]
    FOREIGN KEY ([ID_SOLICITUD])
    REFERENCES [LOGISTICA].[SOLICITUDES] ([ID_SOLICITUD]);

ALTER TABLE [LOGISTICA].[NOTIFICACIONES]
ADD CONSTRAINT [FK_LOG_NOTIFICACION_HOJA]
    FOREIGN KEY ([ID_HOJA_RUTA])
    REFERENCES [LOGISTICA].[HOJAS_RUTA] ([ID_HOJA_RUTA]);
