/* Proyecto: Sistema Modular de Gestión OxiTigre | Componente: Relaciones Inventario | Archivo: FK_INVENTARIO.sql | Versión: 1.0.0 | Fecha: 2026-08-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com | Descripción funcional: Relaciona productos, depósitos, ubicaciones, saldos y movimientos. | Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial. */
ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD CONSTRAINT [FK_PRODUCTOS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD CONSTRAINT [FK_PRODUCTOS_CATEGORIAS] FOREIGN KEY ([ID_CATEGORIA_PRODUCTO]) REFERENCES [INVENTARIO].[CATEGORIAS_PRODUCTO] ([ID_CATEGORIA_PRODUCTO]);
ALTER TABLE [INVENTARIO].[PRODUCTOS] ADD CONSTRAINT [FK_PRODUCTOS_UNIDADES] FOREIGN KEY ([ID_UNIDAD_MEDIDA]) REFERENCES [CONFIGURACION].[UNIDADES_MEDIDA] ([ID_UNIDAD_MEDIDA]);
ALTER TABLE [INVENTARIO].[DEPOSITOS] ADD CONSTRAINT [FK_DEPOSITOS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [INVENTARIO].[DEPOSITOS] ADD CONSTRAINT [FK_DEPOSITOS_SUCURSALES] FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [CONFIGURACION].[SUCURSALES] ([ID_SUCURSAL]);
ALTER TABLE [INVENTARIO].[UBICACIONES] ADD CONSTRAINT [FK_UBICACIONES_DEPOSITOS] FOREIGN KEY ([ID_DEPOSITO]) REFERENCES [INVENTARIO].[DEPOSITOS] ([ID_DEPOSITO]);
ALTER TABLE [INVENTARIO].[EXISTENCIAS] ADD CONSTRAINT [FK_EXISTENCIAS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [INVENTARIO].[EXISTENCIAS] ADD CONSTRAINT [FK_EXISTENCIAS_PRODUCTOS] FOREIGN KEY ([ID_PRODUCTO]) REFERENCES [INVENTARIO].[PRODUCTOS] ([ID_PRODUCTO]);
ALTER TABLE [INVENTARIO].[EXISTENCIAS] ADD CONSTRAINT [FK_EXISTENCIAS_DEPOSITOS] FOREIGN KEY ([ID_DEPOSITO]) REFERENCES [INVENTARIO].[DEPOSITOS] ([ID_DEPOSITO]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS] ADD CONSTRAINT [FK_MOVIMIENTOS_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [FK_MOVIMIENTOS_DETALLES_MOVIMIENTOS] FOREIGN KEY ([ID_MOVIMIENTO]) REFERENCES [INVENTARIO].[MOVIMIENTOS] ([ID_MOVIMIENTO]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [FK_MOVIMIENTOS_DETALLES_PRODUCTOS] FOREIGN KEY ([ID_PRODUCTO]) REFERENCES [INVENTARIO].[PRODUCTOS] ([ID_PRODUCTO]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [FK_MOVIMIENTOS_DETALLES_DEPOSITO_ORIGEN] FOREIGN KEY ([ID_DEPOSITO_ORIGEN]) REFERENCES [INVENTARIO].[DEPOSITOS] ([ID_DEPOSITO]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [FK_MOVIMIENTOS_DETALLES_UBICACION_ORIGEN] FOREIGN KEY ([ID_UBICACION_ORIGEN]) REFERENCES [INVENTARIO].[UBICACIONES] ([ID_UBICACION]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [FK_MOVIMIENTOS_DETALLES_DEPOSITO_DESTINO] FOREIGN KEY ([ID_DEPOSITO_DESTINO]) REFERENCES [INVENTARIO].[DEPOSITOS] ([ID_DEPOSITO]);
ALTER TABLE [INVENTARIO].[MOVIMIENTOS_DETALLES] ADD CONSTRAINT [FK_MOVIMIENTOS_DETALLES_UBICACION_DESTINO] FOREIGN KEY ([ID_UBICACION_DESTINO]) REFERENCES [INVENTARIO].[UBICACIONES] ([ID_UBICACION]);
