/*
===============================================================================
Proyecto:              Sistema Modular de Gestión OxiTigre
Componente:            Relaciones SEGURIDAD
Archivo:               FK_SEGURIDAD.sql
Versión:               1.0.0
Fecha:                 2026-08-19
ID pedido:             FABRICA
Desarrollador:         Agustin Omar Cauzi
Correo:                agustincauzi10@hotmail.com
Descripción funcional: Garantiza la integridad de usuarios, roles, permisos y sesiones.
Historial de modificaciones:
1.0.0 | 2026-08-19 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
ALTER TABLE [SEGURIDAD].[USUARIOS] ADD CONSTRAINT [FK_USUARIOS_EMPRESAS]
    FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [SEGURIDAD].[ROLES] ADD CONSTRAINT [FK_ROLES_EMPRESAS]
    FOREIGN KEY ([ID_EMPRESA]) REFERENCES [CONFIGURACION].[EMPRESAS] ([ID_EMPRESA]);
ALTER TABLE [SEGURIDAD].[PERMISOS] ADD CONSTRAINT [FK_PERMISOS_MODULOS]
    FOREIGN KEY ([ID_MODULO]) REFERENCES [CONFIGURACION].[MODULOS] ([ID_MODULO]);
ALTER TABLE [SEGURIDAD].[USUARIOS_ROLES] ADD CONSTRAINT [FK_USUARIOS_ROLES_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
ALTER TABLE [SEGURIDAD].[USUARIOS_ROLES] ADD CONSTRAINT [FK_USUARIOS_ROLES_ROLES]
    FOREIGN KEY ([ID_ROL]) REFERENCES [SEGURIDAD].[ROLES] ([ID_ROL]);
ALTER TABLE [SEGURIDAD].[ROLES_PERMISOS] ADD CONSTRAINT [FK_ROLES_PERMISOS_ROLES]
    FOREIGN KEY ([ID_ROL]) REFERENCES [SEGURIDAD].[ROLES] ([ID_ROL]);
ALTER TABLE [SEGURIDAD].[ROLES_PERMISOS] ADD CONSTRAINT [FK_ROLES_PERMISOS_PERMISOS]
    FOREIGN KEY ([ID_PERMISO]) REFERENCES [SEGURIDAD].[PERMISOS] ([ID_PERMISO]);
ALTER TABLE [SEGURIDAD].[DISPOSITIVOS_ACCESO] ADD CONSTRAINT [FK_DISPOSITIVOS_ACCESO_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
ALTER TABLE [SEGURIDAD].[SESIONES] ADD CONSTRAINT [FK_SESIONES_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
ALTER TABLE [SEGURIDAD].[SESIONES] ADD CONSTRAINT [FK_SESIONES_SUCURSALES]
    FOREIGN KEY ([ID_SUCURSAL]) REFERENCES [CONFIGURACION].[SUCURSALES] ([ID_SUCURSAL]);
ALTER TABLE [SEGURIDAD].[SESIONES] ADD CONSTRAINT [FK_SESIONES_DISPOSITIVOS_ACCESO]
    FOREIGN KEY ([ID_DISPOSITIVO_ACCESO]) REFERENCES [SEGURIDAD].[DISPOSITIVOS_ACCESO] ([ID_DISPOSITIVO_ACCESO]);
ALTER TABLE [SEGURIDAD].[RECUPERACIONES_CLAVE] ADD CONSTRAINT [FK_RECUPERACIONES_CLAVE_USUARIOS]
    FOREIGN KEY ([ID_USUARIO]) REFERENCES [SEGURIDAD].[USUARIOS] ([ID_USUARIO]);
