/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: Tablas de Compras Fase 7
Archivo: FASE7_COMPRAS.sql | Versión: 1.1.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Almacena proveedores, contactos, órdenes y recepciones parciales e inmutables.
Historial: 1.0.0 | 2026-08-24 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Integración de snapshots y reversión en instalaciones nuevas.
===============================================================================
*/
CREATE TABLE [COMPRAS].[PROVEEDORES]
(
    [ID_PROVEEDOR] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [RAZON_SOCIAL] NVARCHAR(200) NOT NULL,
    [NOMBRE_COMERCIAL] NVARCHAR(200) NULL,
    [CUIT] NVARCHAR(30) NOT NULL,
    [CORREO] NVARCHAR(254) NULL,
    [TELEFONO] NVARCHAR(50) NULL,
    [CONDICION_PAGO] NVARCHAR(150) NULL,
    [OBSERVACION] NVARCHAR(1000) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PROVEEDORES_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PROVEEDORES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PROVEEDORES] PRIMARY KEY CLUSTERED ([ID_PROVEEDOR])
);

CREATE TABLE [COMPRAS].[PROVEEDORES_CONTACTOS]
(
    [ID_PROVEEDOR_CONTACTO] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_PROVEEDOR] BIGINT NOT NULL,
    [NOMBRE] NVARCHAR(200) NOT NULL,
    [CARGO] NVARCHAR(100) NULL,
    [EMAIL] NVARCHAR(254) NULL,
    [TELEFONO] NVARCHAR(50) NULL,
    [ES_PRINCIPAL] BIT NOT NULL CONSTRAINT [DF_PROVEEDORES_CONTACTOS_ES_PRINCIPAL] DEFAULT (0),
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_PROVEEDORES_CONTACTOS_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_PROVEEDORES_CONTACTOS_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_PROVEEDORES_CONTACTOS] PRIMARY KEY CLUSTERED ([ID_PROVEEDOR_CONTACTO])
);

CREATE TABLE [COMPRAS].[ORDENES_COMPRA]
(
    [ID_ORDEN_COMPRA] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_PROVEEDOR] BIGINT NOT NULL,
    [PROVEEDOR_RAZON_SOCIAL] NVARCHAR(200) NOT NULL,
    [PROVEEDOR_CUIT] NVARCHAR(30) NOT NULL,
    [PROVEEDOR_CONDICION_PAGO] NVARCHAR(150) NULL,
    [ID_DEPOSITO] BIGINT NOT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [FECHA_ORDEN_UTC] DATETIME2(3) NOT NULL,
    [FECHA_ENTREGA_ESPERADA] DATE NULL,
    [MONEDA] CHAR(3) NOT NULL,
    [SUBTOTAL] DECIMAL(19,4) NOT NULL,
    [TOTAL_DESCUENTO] DECIMAL(19,4) NOT NULL,
    [TOTAL_IMPUESTO] DECIMAL(19,4) NOT NULL,
    [TOTAL] DECIMAL(19,4) NOT NULL,
    [OBSERVACION] NVARCHAR(1000) NULL,
    [FECHA_APROBACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_APROBACION] BIGINT NULL,
    [MOTIVO_CIERRE] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_ORDENES_COMPRA_CODIGO_ESTADO] DEFAULT (N'BORRADOR'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_ORDENES_COMPRA_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_ORDENES_COMPRA] PRIMARY KEY CLUSTERED ([ID_ORDEN_COMPRA])
);

CREATE TABLE [COMPRAS].[ORDENES_COMPRA_DETALLES]
(
    [ID_ORDEN_COMPRA_DETALLE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_ORDEN_COMPRA] BIGINT NOT NULL,
    [ID_PRODUCTO] BIGINT NOT NULL,
    [CANTIDAD_PEDIDA] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_RECIBIDA] DECIMAL(19,4) NOT NULL CONSTRAINT [DF_ORDENES_COMPRA_DETALLES_RECIBIDA] DEFAULT (0),
    [CANTIDAD_CERRADA] DECIMAL(19,4) NOT NULL CONSTRAINT [DF_ORDENES_COMPRA_DETALLES_CERRADA] DEFAULT (0),
    [COSTO_UNITARIO] DECIMAL(19,4) NOT NULL,
    [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
    [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL,
    [SUBTOTAL_RENGLON] DECIMAL(19,4) NOT NULL,
    [IMPORTE_DESCUENTO] DECIMAL(19,4) NOT NULL,
    [IMPORTE_IMPUESTO] DECIMAL(19,4) NOT NULL,
    [TOTAL_RENGLON] DECIMAL(19,4) NOT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_ORDENES_COMPRA_DETALLES_CODIGO_ESTADO] DEFAULT (N'PENDIENTE'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_ORDENES_COMPRA_DETALLES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_ORDENES_COMPRA_DETALLES] PRIMARY KEY CLUSTERED ([ID_ORDEN_COMPRA_DETALLE])
);

CREATE TABLE [COMPRAS].[RECEPCIONES_COMPRA]
(
    [ID_RECEPCION] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_EMPRESA] BIGINT NOT NULL,
    [ID_ORDEN_COMPRA] BIGINT NOT NULL,
    [ID_MOVIMIENTO] BIGINT NULL,
    [ID_MOVIMIENTO_REVERSION] BIGINT NULL,
    [CODIGO] NVARCHAR(30) NOT NULL,
    [FECHA_RECEPCION_UTC] DATETIME2(3) NOT NULL,
    [NUMERO_DOCUMENTO_PROVEEDOR] NVARCHAR(80) NULL,
    [OBSERVACION] NVARCHAR(1000) NULL,
    [MOTIVO_REVERSION] NVARCHAR(500) NULL,
    [FECHA_REVERSION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_REVERSION] BIGINT NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_RECEPCIONES_COMPRA_CODIGO_ESTADO] DEFAULT (N'CONFIRMADA'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_RECEPCIONES_COMPRA_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_RECEPCIONES_COMPRA] PRIMARY KEY CLUSTERED ([ID_RECEPCION])
);

CREATE TABLE [COMPRAS].[RECEPCIONES_COMPRA_DETALLES]
(
    [ID_RECEPCION_DETALLE] BIGINT IDENTITY(1,1) NOT NULL,
    [ID_RECEPCION] BIGINT NOT NULL,
    [ID_ORDEN_COMPRA_DETALLE] BIGINT NOT NULL,
    [ID_PRODUCTO] BIGINT NOT NULL,
    [CANTIDAD_ACEPTADA] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_RECHAZADA] DECIMAL(19,4) NOT NULL,
    [CANTIDAD_DANADA] DECIMAL(19,4) NOT NULL,
    [MOTIVO_DIFERENCIA] NVARCHAR(500) NULL,
    [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_RECEPCIONES_COMPRA_DETALLES_CODIGO_ESTADO] DEFAULT (N'ACTIVO'),
    [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_RECEPCIONES_COMPRA_DETALLES_FECHA_ALTA_UTC] DEFAULT (SYSUTCDATETIME()),
    [ID_USUARIO_ALTA] BIGINT NOT NULL,
    [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
    [ID_USUARIO_MODIFICACION] BIGINT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,
    CONSTRAINT [PK_RECEPCIONES_COMPRA_DETALLES] PRIMARY KEY CLUSTERED ([ID_RECEPCION_DETALLE])
);
