/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_VENTAS_GET
Archivo: SP_VENTAS_GET.sql | Procedimiento: COMERCIAL.SP_VENTAS_GET | Tipo: QUERY
Versión: 1.2.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera catálogos, precios, pedidos, reservas y ventas de la empresa autenticada.
Parámetros de entrada: @I_ID_EMPRESA, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_MENSAJE.
Retorno: Devuelve los conjuntos de filas definidos por sus SELECT finales.
Tablas utilizadas: COMERCIAL.CLIENTES - SELECT; COMERCIAL.LISTAS_PRECIOS - SELECT; COMERCIAL.LISTAS_PRECIOS_PRODUCTOS - SELECT; COMERCIAL.PEDIDOS - SELECT; COMERCIAL.PEDIDOS_ACTIVOS - SELECT; COMERCIAL.PEDIDOS_DETALLES - SELECT; COMERCIAL.PROMOCIONES - SELECT; COMERCIAL.VENTAS - SELECT; COMERCIAL.VENTAS_DETALLES - SELECT; CONFIGURACION.UNIDADES_MEDIDA - SELECT; INVENTARIO.ACTIVOS - SELECT; INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.PRODUCTOS - SELECT.
Transacción: No abre una transacción explícita; realiza operaciones de lectura.
Auditoría: No registra auditoría explícita porque no modifica estado.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Catálogo y fotografía de promociones para pedidos y ventas.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
Historial: 1.2.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Servicios y modalidades de activos visibles para operación logística.
Historial: 1.2.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_VENTAS_GET]
    @I_ID_EMPRESA BIGINT, @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL;

    SELECT [ID_CLIENTE], [CODIGO], CONCAT([NOMBRE_RAZON_SOCIAL], CASE WHEN [APELLIDO] IS NULL THEN N'' ELSE N' ' + [APELLIDO] END) AS [NOMBRE]
    FROM [COMERCIAL].[CLIENTES] WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [NOMBRE_RAZON_SOCIAL], [APELLIDO];

    SELECT [ID_LISTA_PRECIO], [CODIGO], [NOMBRE], [MONEDA], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA], [CODIGO_ESTADO], [ROW_VERSION]
    FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [NOMBRE];

    SELECT [LPP].[ID_LISTA_PRECIO_PRODUCTO], [LPP].[ID_LISTA_PRECIO], [LPP].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO], [LPP].[PRECIO_UNITARIO], [LPP].[CODIGO_ESTADO], [LPP].[ROW_VERSION]
    FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] AS [LPP]
    INNER JOIN [COMERCIAL].[LISTAS_PRECIOS] AS [LIS] ON [LIS].[ID_LISTA_PRECIO] = [LPP].[ID_LISTA_PRECIO]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [LPP].[ID_PRODUCTO]
    WHERE [LIS].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [LIS].[NOMBRE], [PRO].[CODIGO];

    SELECT [PRO].[ID_PRODUCTO], [PRO].[CODIGO], [PRO].[NOMBRE], [UNI].[SIMBOLO], [PRO].[TIPO_ITEM]
    FROM [INVENTARIO].[PRODUCTOS] AS [PRO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    WHERE [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO' ORDER BY [PRO].[CODIGO];

    SELECT [ID_DEPOSITO], [CODIGO], [NOMBRE] FROM [INVENTARIO].[DEPOSITOS]
    WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO' ORDER BY [NOMBRE];

    SELECT [PRM].[ID_PROMOCION], [PRM].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO],
           [PRM].[CODIGO], [PRM].[NOMBRE], [PRM].[DESCRIPCION], [PRM].[TIPO_PROMOCION], [PRM].[CANTIDAD_REQUERIDA],
           [PRM].[CANTIDAD_PAGADA], [PRM].[CANTIDAD_BONIFICADA], [PRM].[PORCENTAJE_DESCUENTO], [PRM].[PRECIO_PAQUETE],
           [PRM].[FECHA_VIGENCIA_DESDE], [PRM].[FECHA_VIGENCIA_HASTA], [PRM].[CODIGO_ESTADO], [PRM].[ROW_VERSION]
    FROM [COMERCIAL].[PROMOCIONES] AS [PRM]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [PRM].[ID_PRODUCTO]
    WHERE [PRM].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [PRM].[NOMBRE], [PRO].[CODIGO];

    SELECT [PED].[ID_PEDIDO], [PED].[ID_CLIENTE], [PED].[ID_LISTA_PRECIO], [PED].[CODIGO], [PED].[FECHA_PEDIDO_UTC], [CLI].[NOMBRE_RAZON_SOCIAL] AS [CLIENTE], [PED].[MONEDA],
           [PED].[SUBTOTAL], [PED].[TOTAL_DESCUENTO], [PED].[TOTAL_IMPUESTO], [PED].[TOTAL], [PED].[OBSERVACION], [PED].[CODIGO_ESTADO], [PED].[ROW_VERSION],
           [DET].[ID_PEDIDO_DETALLE], [DET].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO], [DET].[ID_DEPOSITO], [DEP].[NOMBRE] AS [DEPOSITO],
           [DET].[ID_PROMOCION], [DET].[CODIGO_PROMOCION], [DET].[NOMBRE_PROMOCION],
           [DET].[CANTIDAD], [DET].[PRECIO_UNITARIO], [DET].[PORCENTAJE_DESCUENTO], [DET].[PORCENTAJE_IMPUESTO], [DET].[SUBTOTAL] AS [SUBTOTAL_RENGLON],
           [DET].[IMPORTE_DESCUENTO], [DET].[IMPORTE_IMPUESTO], [DET].[TOTAL] AS [TOTAL_RENGLON], [UNI].[SIMBOLO]
    FROM [COMERCIAL].[PEDIDOS] AS [PED]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [PED].[ID_CLIENTE]
    INNER JOIN [COMERCIAL].[PEDIDOS_DETALLES] AS [DET] ON [DET].[ID_PEDIDO] = [PED].[ID_PEDIDO] AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    LEFT JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [DET].[ID_DEPOSITO]
    WHERE [PED].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [PED].[FECHA_PEDIDO_UTC] DESC, [DET].[ID_PEDIDO_DETALLE];

    SELECT [VEN].[ID_VENTA], [VEN].[ID_PEDIDO], [VEN].[ID_CLIENTE], [VEN].[ID_MOVIMIENTO], [VEN].[CODIGO], [VEN].[FECHA_VENTA_UTC], [CLI].[NOMBRE_RAZON_SOCIAL] AS [CLIENTE], [VEN].[MONEDA],
           [VEN].[SUBTOTAL], [VEN].[TOTAL_DESCUENTO], [VEN].[TOTAL_IMPUESTO], [VEN].[TOTAL], [VEN].[OBSERVACION], [VEN].[CODIGO_ESTADO],
           [DET].[ID_VENTA_DETALLE], [DET].[ID_PRODUCTO], [PRO].[CODIGO] AS [CODIGO_PRODUCTO], [PRO].[NOMBRE] AS [PRODUCTO], [DET].[ID_DEPOSITO], [DEP].[NOMBRE] AS [DEPOSITO],
           [DET].[ID_PROMOCION], [DET].[CODIGO_PROMOCION], [DET].[NOMBRE_PROMOCION],
           [DET].[CANTIDAD], [DET].[PRECIO_UNITARIO], [DET].[PORCENTAJE_DESCUENTO], [DET].[PORCENTAJE_IMPUESTO], [DET].[SUBTOTAL] AS [SUBTOTAL_RENGLON],
           [DET].[IMPORTE_DESCUENTO], [DET].[IMPORTE_IMPUESTO], [DET].[TOTAL] AS [TOTAL_RENGLON], [UNI].[SIMBOLO]
    FROM [COMERCIAL].[VENTAS] AS [VEN]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [VEN].[ID_CLIENTE]
    INNER JOIN [COMERCIAL].[VENTAS_DETALLES] AS [DET] ON [DET].[ID_VENTA] = [VEN].[ID_VENTA]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
    INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA]
    LEFT JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [DET].[ID_DEPOSITO]
    WHERE [VEN].[ID_EMPRESA] = @I_ID_EMPRESA ORDER BY [VEN].[FECHA_VENTA_UTC] DESC, [DET].[ID_VENTA_DETALLE];

    SELECT [ACT].[ID_ACTIVO], [ACT].[ID_CLIENTE_PROPIETARIO], [ACT].[CODIGO], [ACT].[NUMERO_SERIE],
           [PRO].[NOMBRE] AS [PRODUCTO],
           COALESCE([CLI].[NOMBRE_RAZON_SOCIAL] + COALESCE(N' ' + [CLI].[APELLIDO], N''), N'OxiTigre') AS [PROPIETARIO],
           [ACT].[CONDICION_ACTUAL], [ACT].[CODIGO_ESTADO]
    FROM [INVENTARIO].[ACTIVOS] AS [ACT]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [ACT].[ID_PRODUCTO]
    LEFT JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [ACT].[ID_CLIENTE_PROPIETARIO]
    WHERE [ACT].[ID_EMPRESA] = @I_ID_EMPRESA AND [ACT].[CODIGO_ESTADO] <> N'BAJA'
    ORDER BY [PROPIETARIO], [ACT].[CODIGO];

    SELECT [VINC].[ID_PEDIDO_ACTIVO], [VINC].[ID_PEDIDO], [VINC].[ID_ACTIVO], [VINC].[ID_PRODUCTO_RENGLON],
           [ACT].[CODIGO] AS [ACTIVO], [ACT].[NUMERO_SERIE], [PRO].[NOMBRE] AS [PRODUCTO_RENGLON],
           [VINC].[TIPO_VINCULO], [VINC].[MODALIDAD_RETORNO], [VINC].[OBSERVACION],
           [VINC].[MODALIDAD_INGRESO], [VINC].[FECHA_DEVOLUCION_PREVISTA]
    FROM [COMERCIAL].[PEDIDOS_ACTIVOS] AS [VINC]
    INNER JOIN [COMERCIAL].[PEDIDOS] AS [PED] ON [PED].[ID_PEDIDO] = [VINC].[ID_PEDIDO]
    INNER JOIN [INVENTARIO].[ACTIVOS] AS [ACT] ON [ACT].[ID_ACTIVO] = [VINC].[ID_ACTIVO]
    INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [VINC].[ID_PRODUCTO_RENGLON]
    WHERE [PED].[ID_EMPRESA] = @I_ID_EMPRESA AND [VINC].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [VINC].[ID_PEDIDO], [VINC].[ID_PEDIDO_ACTIVO];
END;
