/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_LISTA_PRECIO_PRODUCTO_SAVE
Archivo: SP_LISTA_PRECIO_PRODUCTO_SAVE.sql | Procedimiento: COMERCIAL.SP_LISTA_PRECIO_PRODUCTO_SAVE | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o modifica el precio de un producto dentro de una lista propia.
Parámetros de entrada: @I_CODIGO_ESTADO, @I_ID_EMPRESA, @I_ID_LISTA_PRECIO, @I_ID_LISTA_PRECIO_PRODUCTO, @I_ID_PRODUCTO, @I_PRECIO_UNITARIO, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_LISTA_PRECIO_PRODUCTO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMERCIAL.LISTAS_PRECIOS - SELECT; COMERCIAL.LISTAS_PRECIOS_PRODUCTOS - INSERT/SELECT; INVENTARIO.PRODUCTOS - SELECT.
Transacción: No abre una transacción explícita.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Homogeneiza el contexto de sesión auditada.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_LISTA_PRECIO_PRODUCTO_SAVE]
    @I_ID_LISTA_PRECIO_PRODUCTO BIGINT = NULL, @I_ID_EMPRESA BIGINT, @I_ID_LISTA_PRECIO BIGINT, @I_ID_PRODUCTO BIGINT, @I_PRECIO_UNITARIO DECIMAL(19,4), @I_CODIGO_ESTADO NVARCHAR(30), @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT, @O_ID_LISTA_PRECIO_PRODUCTO BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_PRECIO_UNITARIO < 0 OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO') THROW 50000, 'El precio y el estado deben ser válidos.', 1;
    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS] WHERE [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO AND [ID_EMPRESA] = @I_ID_EMPRESA) OR NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_PRODUCTO] = @I_ID_PRODUCTO AND [ID_EMPRESA] = @I_ID_EMPRESA) THROW 50001, 'La lista o el producto no pertenece a la empresa.', 1;
    IF @I_ID_LISTA_PRECIO_PRODUCTO IS NULL BEGIN INSERT INTO [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] ([ID_LISTA_PRECIO], [ID_PRODUCTO], [PRECIO_UNITARIO], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_LISTA_PRECIO, @I_ID_PRODUCTO, @I_PRECIO_UNITARIO, @I_CODIGO_ESTADO, @S_ID_USUARIO); SET @O_ID_LISTA_PRECIO_PRODUCTO = CONVERT(BIGINT, SCOPE_IDENTITY()); SET @O_FILAS_AFECTADAS = 1; RETURN; END;
    UPDATE [LPP] SET [PRECIO_UNITARIO] = @I_PRECIO_UNITARIO, [CODIGO_ESTADO] = @I_CODIGO_ESTADO, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO FROM [COMERCIAL].[LISTAS_PRECIOS_PRODUCTOS] AS [LPP] INNER JOIN [COMERCIAL].[LISTAS_PRECIOS] AS [LIS] ON [LIS].[ID_LISTA_PRECIO] = [LPP].[ID_LISTA_PRECIO] WHERE [LPP].[ID_LISTA_PRECIO_PRODUCTO] = @I_ID_LISTA_PRECIO_PRODUCTO AND [LIS].[ID_EMPRESA] = @I_ID_EMPRESA AND [LPP].[ROW_VERSION] = @I_ROW_VERSION;
    SET @O_FILAS_AFECTADAS = @@ROWCOUNT; SET @O_ID_LISTA_PRECIO_PRODUCTO = @I_ID_LISTA_PRECIO_PRODUCTO; IF @O_FILAS_AFECTADAS = 0 BEGIN SET @O_CODIGO_ERROR = 40007; SET @O_MENSAJE = N'El precio fue modificado por otro usuario o no pertenece a la empresa.'; END;
END;
