/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_LISTA_PRECIO_SAVE
Archivo: SP_LISTA_PRECIO_SAVE.sql | Procedimiento: COMERCIAL.SP_LISTA_PRECIO_SAVE | Tipo: COMMAND
Versión: 1.1.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o modifica una lista de precios con vigencia y concurrencia.
Parámetros de entrada: @I_CODIGO, @I_CODIGO_ESTADO, @I_FECHA_VIGENCIA_DESDE, @I_FECHA_VIGENCIA_HASTA, @I_ID_EMPRESA, @I_ID_LISTA_PRECIO, @I_MONEDA, @I_NOMBRE, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_LISTA_PRECIO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMERCIAL.LISTAS_PRECIOS - INSERT/UPDATE; COMERCIAL.PEDIDOS - SELECT.
Transacción: No abre una transacción explícita.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Homogeneiza el contexto de sesión auditada.
Historial: 1.1.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_LISTA_PRECIO_SAVE]
    @I_ID_LISTA_PRECIO BIGINT = NULL, @I_ID_EMPRESA BIGINT, @I_CODIGO NVARCHAR(30), @I_NOMBRE NVARCHAR(150), @I_MONEDA CHAR(3),
    @I_FECHA_VIGENCIA_DESDE DATE = NULL, @I_FECHA_VIGENCIA_HASTA DATE = NULL, @I_CODIGO_ESTADO NVARCHAR(30), @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT, @O_ID_LISTA_PRECIO BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF NULLIF(LTRIM(RTRIM(@I_CODIGO)), N'') IS NULL OR NULLIF(LTRIM(RTRIM(@I_NOMBRE)), N'') IS NULL OR @I_MONEDA NOT LIKE '[A-Z][A-Z][A-Z]' OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO') OR (@I_FECHA_VIGENCIA_HASTA IS NOT NULL AND @I_FECHA_VIGENCIA_DESDE IS NOT NULL AND @I_FECHA_VIGENCIA_HASTA < @I_FECHA_VIGENCIA_DESDE) THROW 50000, 'Código, nombre, moneda, vigencia y estado deben ser válidos.', 1;
    IF @I_ID_LISTA_PRECIO IS NULL BEGIN INSERT INTO [COMERCIAL].[LISTAS_PRECIOS] ([ID_EMPRESA], [CODIGO], [NOMBRE], [MONEDA], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_EMPRESA, @I_CODIGO, @I_NOMBRE, @I_MONEDA, @I_FECHA_VIGENCIA_DESDE, @I_FECHA_VIGENCIA_HASTA, @I_CODIGO_ESTADO, @S_ID_USUARIO); SET @O_ID_LISTA_PRECIO = CONVERT(BIGINT, SCOPE_IDENTITY()); SET @O_FILAS_AFECTADAS = 1; RETURN; END;
    IF @I_CODIGO_ESTADO = N'INACTIVO' AND EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WHERE [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO AND [CODIGO_ESTADO] IN (N'BORRADOR', N'CONFIRMADO')) THROW 50001, 'No se puede inactivar una lista utilizada por pedidos abiertos.', 1;
    UPDATE [COMERCIAL].[LISTAS_PRECIOS] SET [NOMBRE] = @I_NOMBRE, [MONEDA] = @I_MONEDA, [FECHA_VIGENCIA_DESDE] = @I_FECHA_VIGENCIA_DESDE, [FECHA_VIGENCIA_HASTA] = @I_FECHA_VIGENCIA_HASTA, [CODIGO_ESTADO] = @I_CODIGO_ESTADO, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;
    SET @O_FILAS_AFECTADAS = @@ROWCOUNT; SET @O_ID_LISTA_PRECIO = @I_ID_LISTA_PRECIO; IF @O_FILAS_AFECTADAS = 0 BEGIN SET @O_CODIGO_ERROR = 40007; SET @O_MENSAJE = N'La lista fue modificada por otro usuario o no pertenece a la empresa.'; END;
END;
