/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PEDIDO_SAVE
Archivo: SP_PEDIDO_SAVE.sql | Procedimiento: COMERCIAL.SP_PEDIDO_SAVE | Tipo: COMMAND
Versión: 1.3.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o reemplaza un pedido en borrador, acumula renglones compatibles y calcula sus promociones en el servidor.
Parámetros de entrada: @I_ACTIVOS_JSON, @I_DETALLES_JSON, @I_FECHA_PEDIDO_UTC, @I_ID_CLIENTE, @I_ID_EMPRESA, @I_ID_LISTA_PRECIO, @I_ID_PEDIDO, @I_MONEDA, @I_OBSERVACION, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_PEDIDO, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMERCIAL.CLIENTES - SELECT; COMERCIAL.LISTAS_PRECIOS - SELECT; COMERCIAL.PEDIDOS - INSERT/UPDATE; COMERCIAL.PEDIDOS_ACTIVOS - INSERT/UPDATE; COMERCIAL.PEDIDOS_DETALLES - INSERT/UPDATE; COMERCIAL.PROMOCIONES - SELECT; CONFIGURACION.UNIDADES_MEDIDA - SELECT; INVENTARIO.ACTIVOS - SELECT; INVENTARIO.DEPOSITOS - SELECT; INVENTARIO.PRODUCTOS - SELECT.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Motor promocional 2x1/4x3, porcentaje por unidades y precio de paquete.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
Historial: 1.2.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Validaciones bloqueadas y suma amplia de cantidades compatibles.
Historial: 1.3.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Servicios, activos y modalidades logísticas trazables por pedido.
Historial: 1.3.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_PEDIDO_SAVE]
    @I_ID_PEDIDO BIGINT = NULL, @I_ID_EMPRESA BIGINT, @I_ID_CLIENTE BIGINT, @I_ID_LISTA_PRECIO BIGINT = NULL,
    @I_FECHA_PEDIDO_UTC DATETIME2(3), @I_MONEDA CHAR(3), @I_OBSERVACION NVARCHAR(500) = NULL,
    @I_DETALLES_JSON NVARCHAR(MAX), @I_ACTIVOS_JSON NVARCHAR(MAX) = N'[]', @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT,
    @O_ID_PEDIDO BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_ID_PEDIDO = @I_ID_PEDIDO; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_PEDIDO_UTC IS NULL OR @I_MONEDA NOT LIKE '[A-Z][A-Z][A-Z]'
       OR ISJSON(@I_DETALLES_JSON) <> 1 OR ISJSON(COALESCE(@I_ACTIVOS_JSON, N'[]')) <> 1
        THROW 50000, 'Cliente, fecha, moneda, renglones y activos válidos son obligatorios.', 1;

    -- INICIO: Normalización de la entrada; ningún importe de descuento se acepta desde el cliente.
    DECLARE @T_ENTRADAS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL
    );

    INSERT INTO @T_ENTRADAS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO])
    SELECT [J].[ID_PRODUCTO], [J].[ID_DEPOSITO], [J].[ID_PROMOCION], [J].[CANTIDAD], [J].[PRECIO_UNITARIO], COALESCE([J].[PORCENTAJE_DESCUENTO], 0), COALESCE([J].[PORCENTAJE_IMPUESTO], 0)
    FROM OPENJSON(@I_DETALLES_JSON) WITH
    (
        [ID_PRODUCTO] BIGINT '$.ProductId',
        [ID_DEPOSITO] BIGINT '$.WarehouseId',
        [ID_PROMOCION] BIGINT '$.PromotionId',
        [CANTIDAD] DECIMAL(19,4) '$.Quantity',
        [PRECIO_UNITARIO] DECIMAL(19,4) '$.UnitPrice',
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) '$.DiscountRate',
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) '$.TaxRate'
    ) AS [J];

    IF NOT EXISTS (SELECT 1 FROM @T_ENTRADAS) OR (SELECT COUNT(*) FROM @T_ENTRADAS) > 100 OR EXISTS (SELECT 1 FROM @T_ENTRADAS WHERE [CANTIDAD] <= 0 OR [PRECIO_UNITARIO] < 0 OR [PORCENTAJE_DESCUENTO] NOT BETWEEN 0 AND 1 OR [PORCENTAJE_IMPUESTO] NOT BETWEEN 0 AND 1) THROW 50003, 'El pedido debe tener entre 1 y 100 renglones con cantidades, precios y porcentajes válidos.', 1;

    DECLARE @T_ACTIVOS TABLE
    (
        [ID_ACTIVO] BIGINT NOT NULL,
        [ID_PRODUCTO_RENGLON] BIGINT NOT NULL,
        [TIPO_VINCULO] NVARCHAR(30) NOT NULL,
        [MODALIDAD_INGRESO] NVARCHAR(30) NOT NULL,
        [MODALIDAD_RETORNO] NVARCHAR(30) NOT NULL,
        [FECHA_DEVOLUCION_PREVISTA] DATE NULL,
        [OBSERVACION] NVARCHAR(500) NOT NULL
    );

    INSERT INTO @T_ACTIVOS
    (
        [ID_ACTIVO],
        [ID_PRODUCTO_RENGLON],
        [TIPO_VINCULO],
        [MODALIDAD_INGRESO],
        [MODALIDAD_RETORNO],
        [FECHA_DEVOLUCION_PREVISTA],
        [OBSERVACION]
    )
    SELECT [ID_ACTIVO], [ID_PRODUCTO_RENGLON], UPPER(LTRIM(RTRIM([TIPO_VINCULO]))),
           UPPER(LTRIM(RTRIM([MODALIDAD_INGRESO]))), UPPER(LTRIM(RTRIM([MODALIDAD_RETORNO]))),
           [FECHA_DEVOLUCION_PREVISTA], LTRIM(RTRIM([OBSERVACION]))
    FROM OPENJSON(COALESCE(@I_ACTIVOS_JSON, N'[]')) WITH
    (
        [ID_ACTIVO] BIGINT '$.AssetId',
        [ID_PRODUCTO_RENGLON] BIGINT '$.ProductLineId',
        [TIPO_VINCULO] NVARCHAR(30) '$.LinkType',
        [MODALIDAD_INGRESO] NVARCHAR(30) '$.InboundMode',
        [MODALIDAD_RETORNO] NVARCHAR(30) '$.ReturnMode',
        [FECHA_DEVOLUCION_PREVISTA] DATE '$.ExpectedReturnDate',
        [OBSERVACION] NVARCHAR(500) '$.Observation'
    );

    IF (SELECT COUNT(*) FROM @T_ACTIVOS) > 100 OR EXISTS
    (
        SELECT 1 FROM @T_ACTIVOS
        WHERE [ID_ACTIVO] <= 0 OR [ID_PRODUCTO_RENGLON] <= 0
           OR [TIPO_VINCULO] NOT IN (N'CLIENTE_SERVICIO', N'VENTA_ACTIVO', N'PRESTAMO', N'INTERCAMBIO')
           OR [MODALIDAD_INGRESO] NOT IN (N'ENTREGA_CLIENTE', N'RETIRO_OXITIGRE', N'NO_APLICA')
           OR [MODALIDAD_RETORNO] NOT IN (N'RETIRO_CLIENTE', N'ENTREGA_OXITIGRE', N'NO_APLICA')
           OR ([TIPO_VINCULO] = N'PRESTAMO' AND [FECHA_DEVOLUCION_PREVISTA] IS NULL)
           OR [FECHA_DEVOLUCION_PREVISTA] < CONVERT(DATE, @I_FECHA_PEDIDO_UTC)
           OR NULLIF([OBSERVACION], N'') IS NULL
    )
        THROW 50003, 'Cada activo debe indicar renglón, finalidad, ingreso, regreso y observación; un préstamo requiere devolución prevista.', 1;

    IF EXISTS
    (
        SELECT 1 FROM @T_ACTIVOS
        GROUP BY [ID_ACTIVO], [ID_PRODUCTO_RENGLON], [TIPO_VINCULO]
        HAVING COUNT(*) > 1
    )
        THROW 50003, 'Un mismo activo y finalidad no pueden repetirse en el pedido.', 1;
    DECLARE @V_INICIO_TRANSACCION BIT = 0;
    BEGIN TRY
        IF @@TRANCOUNT = 0 BEGIN BEGIN TRANSACTION; SET @V_INICIO_TRANSACCION = 1; END ELSE SAVE TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];

        -- INICIO: Los catálogos usados permanecen bloqueados hasta persistir el pedido.
        IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[CLIENTES] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_CLIENTE] = @I_ID_CLIENTE AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO')
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'El cliente no está activo o no pertenece a la empresa.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        IF @I_ID_LISTA_PRECIO IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [COMERCIAL].[LISTAS_PRECIOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [MONEDA] = @I_MONEDA AND [CODIGO_ESTADO] = N'ACTIVO' AND ([FECHA_VIGENCIA_DESDE] IS NULL OR [FECHA_VIGENCIA_DESDE] <= CONVERT(DATE, @I_FECHA_PEDIDO_UTC)) AND ([FECHA_VIGENCIA_HASTA] IS NULL OR [FECHA_VIGENCIA_HASTA] >= CONVERT(DATE, @I_FECHA_PEDIDO_UTC)))
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'La lista no está vigente para la fecha y moneda del pedido.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        IF EXISTS (SELECT 1 FROM @T_ENTRADAS AS [DET] WHERE NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] AS [PRO] WITH (UPDLOCK, HOLDLOCK) INNER JOIN [CONFIGURACION].[UNIDADES_MEDIDA] AS [UNI] WITH (UPDLOCK, HOLDLOCK) ON [UNI].[ID_UNIDAD_MEDIDA] = [PRO].[ID_UNIDAD_MEDIDA] WHERE [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO] AND [PRO].[ID_EMPRESA] = @I_ID_EMPRESA AND [PRO].[CODIGO_ESTADO] = N'ACTIVO' AND ([UNI].[PERMITE_DECIMALES] = 1 OR [DET].[CANTIDAD] = FLOOR([DET].[CANTIDAD]))))
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'Un producto no pertenece a la empresa, está inactivo o no admite cantidades decimales.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        IF EXISTS
        (
            SELECT 1
            FROM @T_ENTRADAS AS [DET]
            INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
            WHERE ([PRO].[TIPO_ITEM] = N'PRODUCTO' AND NOT EXISTS
                  (SELECT 1 FROM [INVENTARIO].[DEPOSITOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_DEPOSITO] = [DET].[ID_DEPOSITO] AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'ACTIVO'))
               OR ([PRO].[TIPO_ITEM] = N'SERVICIO' AND [DET].[ID_DEPOSITO] IS NOT NULL)
        )
        BEGIN
            SET @O_CODIGO_ERROR = 40004; SET @O_MENSAJE = N'Los productos requieren un depósito activo y los servicios no utilizan depósito.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;

        IF EXISTS
        (
            SELECT 1
            FROM @T_ACTIVOS AS [VINC]
            LEFT JOIN [INVENTARIO].[ACTIVOS] AS [ACT] WITH (UPDLOCK, HOLDLOCK)
                ON [ACT].[ID_ACTIVO] = [VINC].[ID_ACTIVO] AND [ACT].[ID_EMPRESA] = @I_ID_EMPRESA
            WHERE [ACT].[ID_ACTIVO] IS NULL
               OR NOT EXISTS (SELECT 1 FROM @T_ENTRADAS AS [DET] WHERE [DET].[ID_PRODUCTO] = [VINC].[ID_PRODUCTO_RENGLON])
               OR ([VINC].[TIPO_VINCULO] = N'CLIENTE_SERVICIO' AND [ACT].[ID_CLIENTE_PROPIETARIO] <> @I_ID_CLIENTE)
               OR ([VINC].[TIPO_VINCULO] IN (N'VENTA_ACTIVO', N'PRESTAMO') AND [ACT].[ID_CLIENTE_PROPIETARIO] IS NOT NULL)
        )
        BEGIN
            SET @O_CODIGO_ERROR = 40010; SET @O_MENSAJE = N'Un activo no pertenece al cliente o a OxiTigre, o no corresponde a un renglón del pedido.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
        -- FIN: Los catálogos usados permanecen bloqueados hasta persistir el pedido.

        IF EXISTS (SELECT 1 FROM @T_ENTRADAS WHERE [ID_PROMOCION] IS NOT NULL AND [PORCENTAJE_DESCUENTO] > 0)
        BEGIN
            SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'Un renglón no puede combinar promoción y descuento manual.';
            IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
            RETURN;
        END;
    IF EXISTS
    (
        SELECT 1
        FROM @T_ENTRADAS AS [DET]
        LEFT JOIN [COMERCIAL].[PROMOCIONES] AS [PRO] WITH (UPDLOCK, HOLDLOCK)
            ON [PRO].[ID_PROMOCION] = [DET].[ID_PROMOCION]
           AND [PRO].[ID_EMPRESA] = @I_ID_EMPRESA
           AND [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
           AND [PRO].[CODIGO_ESTADO] = N'ACTIVO'
           AND ([PRO].[FECHA_VIGENCIA_DESDE] IS NULL OR [PRO].[FECHA_VIGENCIA_DESDE] <= CONVERT(DATE, @I_FECHA_PEDIDO_UTC))
           AND ([PRO].[FECHA_VIGENCIA_HASTA] IS NULL OR [PRO].[FECHA_VIGENCIA_HASTA] >= CONVERT(DATE, @I_FECHA_PEDIDO_UTC))
        WHERE [DET].[ID_PROMOCION] IS NOT NULL AND [PRO].[ID_PROMOCION] IS NULL
    )
    BEGIN
        SET @O_CODIGO_ERROR = 40009; SET @O_MENSAJE = N'Una promoción no está vigente, no pertenece al producto o no corresponde a la empresa.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    DECLARE @T_AGREGADOS_AMPLIOS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CANTIDAD] DECIMAL(38,8) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL
    );

    INSERT INTO @T_AGREGADOS_AMPLIOS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], SUM(CONVERT(DECIMAL(38,8), [CANTIDAD])), [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO]
    FROM @T_ENTRADAS
    GROUP BY [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO];

    IF EXISTS (SELECT 1 FROM @T_AGREGADOS_AMPLIOS WHERE [CANTIDAD] > CONVERT(DECIMAL(38,8), 999999999999999.9999))
    BEGIN
        SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'La cantidad acumulada del renglón supera el límite admitido.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    DECLARE @T_AGREGADOS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL
    );

    INSERT INTO @T_AGREGADOS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], CONVERT(DECIMAL(19,4), [CANTIDAD]), [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO]
    FROM @T_AGREGADOS_AMPLIOS;
    -- FIN: Normalización de la entrada; ningún importe de descuento se acepta desde el cliente.

    -- INICIO: Cálculo único y auditable de importes y promociones.
    DECLARE @T_DETALLES TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CODIGO_PROMOCION] NVARCHAR(30) NULL,
        [NOMBRE_PROMOCION] NVARCHAR(150) NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_DESCUENTO] DECIMAL(9,6) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL,
        [SUBTOTAL] DECIMAL(19,4) NOT NULL,
        [IMPORTE_DESCUENTO] DECIMAL(19,4) NOT NULL,
        [IMPORTE_IMPUESTO] DECIMAL(19,4) NOT NULL,
        [TOTAL] DECIMAL(19,4) NOT NULL
    );

    DECLARE @T_CALCULADOS TABLE
    (
        [ID_PRODUCTO] BIGINT NOT NULL,
        [ID_DEPOSITO] BIGINT NULL,
        [ID_PROMOCION] BIGINT NULL,
        [CODIGO_PROMOCION] NVARCHAR(30) NULL,
        [NOMBRE_PROMOCION] NVARCHAR(150) NULL,
        [CANTIDAD] DECIMAL(19,4) NOT NULL,
        [PRECIO_UNITARIO] DECIMAL(19,4) NOT NULL,
        [PORCENTAJE_IMPUESTO] DECIMAL(9,6) NOT NULL,
        [SUBTOTAL] DECIMAL(38,8) NOT NULL,
        [IMPORTE_DESCUENTO] DECIMAL(38,8) NOT NULL,
        [IMPORTE_IMPUESTO] DECIMAL(38,8) NOT NULL,
        [TOTAL] DECIMAL(38,8) NOT NULL
    );

    ;WITH [CALCULO_BASE] AS
    (
        SELECT [AGR].*, [PRO].[CODIGO] AS [CODIGO_PROMOCION], [PRO].[NOMBRE] AS [NOMBRE_PROMOCION], [PRO].[TIPO_PROMOCION],
               [PRO].[CANTIDAD_REQUERIDA], [PRO].[CANTIDAD_PAGADA], [PRO].[CANTIDAD_BONIFICADA], [PRO].[PORCENTAJE_DESCUENTO] AS [PORCENTAJE_PROMOCION], [PRO].[PRECIO_PAQUETE],
               CONVERT(DECIMAL(38,8), ROUND(CONVERT(DECIMAL(38,8), [AGR].[CANTIDAD]) * CONVERT(DECIMAL(38,8), [AGR].[PRECIO_UNITARIO]), 4)) AS [SUBTOTAL]
        FROM @T_AGREGADOS AS [AGR]
        LEFT JOIN [COMERCIAL].[PROMOCIONES] AS [PRO] ON [PRO].[ID_PROMOCION] = [AGR].[ID_PROMOCION]
    ),
    [CALCULO] AS
    (
        SELECT [BAS].*, CONVERT(DECIMAL(38,8), ROUND
               (
                   CASE
                       WHEN [BAS].[ID_PROMOCION] IS NULL THEN [BAS].[SUBTOTAL] * CONVERT(DECIMAL(38,8), [BAS].[PORCENTAJE_DESCUENTO])
                       WHEN [BAS].[TIPO_PROMOCION] = N'CANTIDAD_PAGADA' THEN FLOOR(CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD]) / CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA])) * (CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA]) - CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_PAGADA])) * CONVERT(DECIMAL(38,8), [BAS].[PRECIO_UNITARIO])
                       WHEN [BAS].[TIPO_PROMOCION] = N'PORCENTAJE_UNIDADES' THEN FLOOR(CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD]) / CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA])) * CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_BONIFICADA]) * CONVERT(DECIMAL(38,8), [BAS].[PRECIO_UNITARIO]) * CONVERT(DECIMAL(38,8), [BAS].[PORCENTAJE_PROMOCION])
                       WHEN [BAS].[TIPO_PROMOCION] = N'PRECIO_PAQUETE' THEN FLOOR(CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD]) / CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA])) * ((CONVERT(DECIMAL(38,8), [BAS].[CANTIDAD_REQUERIDA]) * CONVERT(DECIMAL(38,8), [BAS].[PRECIO_UNITARIO])) - CONVERT(DECIMAL(38,8), [BAS].[PRECIO_PAQUETE]))
                       ELSE 0
                   END, 4
               )) AS [DESCUENTO_BRUTO]
        FROM [CALCULO_BASE] AS [BAS]
    ),
    [CALCULO_ACOTADO] AS
    (
        SELECT [CAL].*, CONVERT(DECIMAL(38,8), CASE WHEN [CAL].[DESCUENTO_BRUTO] < 0 THEN 0 WHEN [CAL].[DESCUENTO_BRUTO] > [CAL].[SUBTOTAL] THEN [CAL].[SUBTOTAL] ELSE [CAL].[DESCUENTO_BRUTO] END) AS [IMPORTE_DESCUENTO]
        FROM [CALCULO] AS [CAL]
    )
    INSERT INTO @T_CALCULADOS ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO],
           [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO],
           CONVERT(DECIMAL(38,8), ROUND(([SUBTOTAL] - [IMPORTE_DESCUENTO]) * CONVERT(DECIMAL(38,8), [PORCENTAJE_IMPUESTO]), 4)),
           CONVERT(DECIMAL(38,8), ROUND(([SUBTOTAL] - [IMPORTE_DESCUENTO]) * (1 + CONVERT(DECIMAL(38,8), [PORCENTAJE_IMPUESTO])), 4))
    FROM [CALCULO_ACOTADO];

    DECLARE @V_LIMITE_IMPORTE DECIMAL(19,4) = 999999999999999.9999;
    IF EXISTS (SELECT 1 FROM @T_CALCULADOS WHERE [SUBTOTAL] > @V_LIMITE_IMPORTE OR [IMPORTE_DESCUENTO] > @V_LIMITE_IMPORTE OR [IMPORTE_IMPUESTO] > @V_LIMITE_IMPORTE OR [TOTAL] > @V_LIMITE_IMPORTE)
    BEGIN
        SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'Los importes calculados superan el límite monetario admitido.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    DECLARE @V_SUBTOTAL_CALCULADO DECIMAL(38,8) = (SELECT SUM([SUBTOTAL]) FROM @T_CALCULADOS),
            @V_DESCUENTO_CALCULADO DECIMAL(38,8) = (SELECT SUM([IMPORTE_DESCUENTO]) FROM @T_CALCULADOS),
            @V_IMPUESTO_CALCULADO DECIMAL(38,8) = (SELECT SUM([IMPORTE_IMPUESTO]) FROM @T_CALCULADOS),
            @V_TOTAL_CALCULADO DECIMAL(38,8) = (SELECT SUM([TOTAL]) FROM @T_CALCULADOS);
    IF @V_SUBTOTAL_CALCULADO > @V_LIMITE_IMPORTE OR @V_DESCUENTO_CALCULADO > @V_LIMITE_IMPORTE OR @V_IMPUESTO_CALCULADO > @V_LIMITE_IMPORTE OR @V_TOTAL_CALCULADO > @V_LIMITE_IMPORTE
    BEGIN
        SET @O_CODIGO_ERROR = 40008; SET @O_MENSAJE = N'Los totales del pedido superan el límite monetario admitido.';
        IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT];
        RETURN;
    END;

    INSERT INTO @T_DETALLES ([ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL])
    SELECT [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO],
           CONVERT(DECIMAL(9,6), CASE WHEN [SUBTOTAL] = 0 THEN 0 ELSE ROUND([IMPORTE_DESCUENTO] / [SUBTOTAL], 6) END), [PORCENTAJE_IMPUESTO],
           CONVERT(DECIMAL(19,4), [SUBTOTAL]), CONVERT(DECIMAL(19,4), [IMPORTE_DESCUENTO]), CONVERT(DECIMAL(19,4), [IMPORTE_IMPUESTO]), CONVERT(DECIMAL(19,4), [TOTAL])
    FROM @T_CALCULADOS;
    -- FIN: Cálculo único y auditable de importes y promociones.

    DECLARE @V_SUBTOTAL DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_SUBTOTAL_CALCULADO), @V_DESCUENTO DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_DESCUENTO_CALCULADO), @V_IMPUESTO DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_IMPUESTO_CALCULADO), @V_TOTAL DECIMAL(19,4) = CONVERT(DECIMAL(19,4), @V_TOTAL_CALCULADO);
        IF @I_ID_PEDIDO IS NULL
        BEGIN
            DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMERCIAL].[SEQ_PEDIDO_CODIGO]; DECLARE @V_CODIGO NVARCHAR(30) = N'PED-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;
            INSERT INTO [COMERCIAL].[PEDIDOS] ([ID_EMPRESA], [ID_CLIENTE], [ID_LISTA_PRECIO], [CODIGO], [FECHA_PEDIDO_UTC], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA]) VALUES (@I_ID_EMPRESA, @I_ID_CLIENTE, @I_ID_LISTA_PRECIO, @V_CODIGO, @I_FECHA_PEDIDO_UTC, @I_MONEDA, @V_SUBTOTAL, @V_DESCUENTO, @V_IMPUESTO, @V_TOTAL, @I_OBSERVACION, N'BORRADOR', @S_ID_USUARIO);
            SET @O_ID_PEDIDO = CONVERT(BIGINT, SCOPE_IDENTITY());
        END
        ELSE
        BEGIN
            UPDATE [COMERCIAL].[PEDIDOS] SET [ID_CLIENTE] = @I_ID_CLIENTE, [ID_LISTA_PRECIO] = @I_ID_LISTA_PRECIO, [FECHA_PEDIDO_UTC] = @I_FECHA_PEDIDO_UTC, [MONEDA] = @I_MONEDA, [SUBTOTAL] = @V_SUBTOTAL, [TOTAL_DESCUENTO] = @V_DESCUENTO, [TOTAL_IMPUESTO] = @V_IMPUESTO, [TOTAL] = @V_TOTAL, [OBSERVACION] = @I_OBSERVACION, [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'BORRADOR' AND [ROW_VERSION] = @I_ROW_VERSION;
            IF @@ROWCOUNT = 0 BEGIN SET @O_CODIGO_ERROR = 40007; SET @O_MENSAJE = N'El pedido fue modificado, ya no es borrador o no pertenece a la empresa.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT]; RETURN; END;
            UPDATE [COMERCIAL].[PEDIDOS_DETALLES] SET [CODIGO_ESTADO] = N'INACTIVO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO';
            UPDATE [COMERCIAL].[PEDIDOS_ACTIVOS] SET [CODIGO_ESTADO] = N'INACTIVO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO';
        END;
        INSERT INTO [COMERCIAL].[PEDIDOS_DETALLES] ([ID_PEDIDO], [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_PEDIDO, [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], N'ACTIVO', @S_ID_USUARIO FROM @T_DETALLES;
        INSERT INTO [COMERCIAL].[PEDIDOS_ACTIVOS]
        (
            [ID_PEDIDO],
            [ID_ACTIVO],
            [ID_PRODUCTO_RENGLON],
            [TIPO_VINCULO],
            [MODALIDAD_INGRESO],
            [MODALIDAD_RETORNO],
            [FECHA_DEVOLUCION_PREVISTA],
            [OBSERVACION],
            [ID_USUARIO_ALTA]
        )
        SELECT @O_ID_PEDIDO, [ID_ACTIVO], [ID_PRODUCTO_RENGLON], [TIPO_VINCULO],
               [MODALIDAD_INGRESO], [MODALIDAD_RETORNO], [FECHA_DEVOLUCION_PREVISTA],
               [OBSERVACION], @S_ID_USUARIO
        FROM @T_ACTIVOS;

        SET @O_FILAS_AFECTADAS = 1 + (SELECT COUNT(*) FROM @T_DETALLES) + (SELECT COUNT(*) FROM @T_ACTIVOS);
        IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION; ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_PEDIDO_SAVE_SAVEPOINT]; SET @O_MENSAJE = ERROR_MESSAGE(); THROW;
    END CATCH;
END;
