/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PEDIDO_CONFIRM
Archivo: SP_PEDIDO_CONFIRM.sql | Procedimiento: COMERCIAL.SP_PEDIDO_CONFIRM | Tipo: COMMAND
Versión: 1.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Confirma un pedido borrador y reserva su stock sin alterar el saldo físico.
Parámetros de entrada: @I_ID_EMPRESA, @I_ID_PEDIDO, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMERCIAL.PEDIDOS - SELECT/UPDATE; COMERCIAL.PEDIDOS_DETALLES - SELECT; INVENTARIO.EXISTENCIAS - SELECT; INVENTARIO.PRODUCTOS - SELECT; INVENTARIO.RESERVAS_STOCK - INSERT/SELECT.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_PEDIDO_CONFIRM]
    @I_ID_PEDIDO BIGINT, @I_ID_EMPRESA BIGINT, @I_ROW_VERSION BINARY(8), @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT, @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    DECLARE @V_INICIO_TRANSACCION BIT = 0;
    BEGIN TRY
        IF @@TRANCOUNT = 0 BEGIN BEGIN TRANSACTION; SET @V_INICIO_TRANSACCION = 1; END ELSE SAVE TRANSACTION [SP_PEDIDO_CONFIRM_SAVEPOINT];
        IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'BORRADOR' AND [ROW_VERSION] = @I_ROW_VERSION)
        BEGIN SET @O_CODIGO_ERROR = 40007; SET @O_MENSAJE = N'El pedido fue modificado, no está en borrador o no pertenece a la empresa.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;

        IF EXISTS
        (
            SELECT 1
            FROM
            (
                SELECT [DET].[ID_PRODUCTO], [DET].[ID_DEPOSITO], SUM([DET].[CANTIDAD]) AS [CANTIDAD]
                FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET]
                INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
                WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
                  AND [PRO].[TIPO_ITEM] = N'PRODUCTO'
                GROUP BY [DET].[ID_PRODUCTO], [DET].[ID_DEPOSITO]
            ) AS [PED]
            LEFT JOIN [INVENTARIO].[EXISTENCIAS] AS [EXI] WITH (UPDLOCK, HOLDLOCK) ON [EXI].[ID_EMPRESA] = @I_ID_EMPRESA AND [EXI].[ID_PRODUCTO] = [PED].[ID_PRODUCTO] AND [EXI].[ID_DEPOSITO] = [PED].[ID_DEPOSITO]
            OUTER APPLY (SELECT SUM([RES].[CANTIDAD]) AS [CANTIDAD] FROM [INVENTARIO].[RESERVAS_STOCK] AS [RES] WITH (UPDLOCK, HOLDLOCK) WHERE [RES].[ID_EMPRESA] = @I_ID_EMPRESA AND [RES].[ID_PRODUCTO] = [PED].[ID_PRODUCTO] AND [RES].[ID_DEPOSITO] = [PED].[ID_DEPOSITO] AND [RES].[CODIGO_ESTADO] = N'RESERVADA') AS [RES]
            WHERE COALESCE([EXI].[CANTIDAD], 0) - COALESCE([RES].[CANTIDAD], 0) < [PED].[CANTIDAD]
        )
        BEGIN SET @O_CODIGO_ERROR = 40005; SET @O_MENSAJE = N'No existe stock disponible suficiente para reservar el pedido.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;

        INSERT INTO [INVENTARIO].[RESERVAS_STOCK] ([ID_EMPRESA], [ID_PEDIDO], [ID_PEDIDO_DETALLE], [ID_PRODUCTO], [ID_DEPOSITO], [CANTIDAD], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @I_ID_EMPRESA, @I_ID_PEDIDO, [DET].[ID_PEDIDO_DETALLE], [DET].[ID_PRODUCTO], [DET].[ID_DEPOSITO], [DET].[CANTIDAD], N'RESERVADA', @S_ID_USUARIO
        FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET]
        INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
        WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
          AND [PRO].[TIPO_ITEM] = N'PRODUCTO';
        SET @O_FILAS_AFECTADAS = @@ROWCOUNT;
        UPDATE [COMERCIAL].[PEDIDOS] SET [CODIGO_ESTADO] = N'CONFIRMADO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        SET @O_FILAS_AFECTADAS += 1;
        IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION; ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_PEDIDO_CONFIRM_SAVEPOINT]; SET @O_MENSAJE = ERROR_MESSAGE(); THROW;
    END CATCH;
END;
