/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_PROMOCION_SAVE
Archivo: SP_PROMOCION_SAVE.sql | Procedimiento: COMERCIAL.SP_PROMOCION_SAVE | Tipo: COMMAND
Versión: 1.0.2 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Crea o modifica una promoción por producto con vigencia, concurrencia y baja lógica.
Parámetros de entrada: @I_CANTIDAD_BONIFICADA, @I_CANTIDAD_PAGADA, @I_CANTIDAD_REQUERIDA, @I_CODIGO, @I_CODIGO_ESTADO, @I_DESCRIPCION, @I_FECHA_VIGENCIA_DESDE, @I_FECHA_VIGENCIA_HASTA, @I_ID_EMPRESA, @I_ID_PRODUCTO, @I_ID_PROMOCION, @I_NOMBRE, @I_PORCENTAJE_DESCUENTO, @I_PRECIO_PAQUETE, @I_ROW_VERSION, @I_TIPO_PROMOCION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_PROMOCION, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMERCIAL.PROMOCIONES - INSERT/SELECT/UPDATE; INVENTARIO.PRODUCTOS - SELECT.
Transacción: No abre una transacción explícita.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Creación inicial para Fase 6.
Historial: 1.0.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
Historial: 1.0.2 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_PROMOCION_SAVE]
    @I_ID_PROMOCION BIGINT = NULL,
    @I_ID_EMPRESA BIGINT,
    @I_ID_PRODUCTO BIGINT,
    @I_CODIGO NVARCHAR(30),
    @I_NOMBRE NVARCHAR(150),
    @I_DESCRIPCION NVARCHAR(500) = NULL,
    @I_TIPO_PROMOCION NVARCHAR(30),
    @I_CANTIDAD_REQUERIDA DECIMAL(19,4),
    @I_CANTIDAD_PAGADA DECIMAL(19,4) = NULL,
    @I_CANTIDAD_BONIFICADA DECIMAL(19,4) = NULL,
    @I_PORCENTAJE_DESCUENTO DECIMAL(9,6) = NULL,
    @I_PRECIO_PAQUETE DECIMAL(19,4) = NULL,
    @I_FECHA_VIGENCIA_DESDE DATE = NULL,
    @I_FECHA_VIGENCIA_HASTA DATE = NULL,
    @I_CODIGO_ESTADO NVARCHAR(30),
    @I_ROW_VERSION BINARY(8) = NULL,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_ID_PROMOCION BIGINT OUTPUT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT,
    @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_ID_PROMOCION = @I_ID_PROMOCION;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;
    SET @O_FILAS_AFECTADAS = 0;
    SET @I_CODIGO = UPPER(LTRIM(RTRIM(@I_CODIGO)));
    SET @I_NOMBRE = LTRIM(RTRIM(@I_NOMBRE));
    SET @I_TIPO_PROMOCION = UPPER(LTRIM(RTRIM(@I_TIPO_PROMOCION)));

    -- INICIO: Validación completa de la regla antes de conservarla.
    IF NULLIF(@I_CODIGO, N'') IS NULL OR NULLIF(@I_NOMBRE, N'') IS NULL
       OR @I_TIPO_PROMOCION NOT IN (N'CANTIDAD_PAGADA', N'PORCENTAJE_UNIDADES', N'PRECIO_PAQUETE')
       OR @I_CANTIDAD_REQUERIDA IS NULL OR @I_CANTIDAD_REQUERIDA <= 0
       OR @I_CODIGO_ESTADO NOT IN (N'ACTIVO', N'INACTIVO')
       OR (@I_FECHA_VIGENCIA_DESDE IS NOT NULL AND @I_FECHA_VIGENCIA_HASTA IS NOT NULL AND @I_FECHA_VIGENCIA_HASTA < @I_FECHA_VIGENCIA_DESDE)
       OR (@I_TIPO_PROMOCION = N'CANTIDAD_PAGADA' AND (@I_CANTIDAD_PAGADA IS NULL OR @I_CANTIDAD_PAGADA < 0 OR @I_CANTIDAD_PAGADA >= @I_CANTIDAD_REQUERIDA OR @I_CANTIDAD_BONIFICADA IS NOT NULL OR @I_PORCENTAJE_DESCUENTO IS NOT NULL OR @I_PRECIO_PAQUETE IS NOT NULL))
       OR (@I_TIPO_PROMOCION = N'PORCENTAJE_UNIDADES' AND (@I_CANTIDAD_PAGADA IS NOT NULL OR @I_CANTIDAD_BONIFICADA IS NULL OR @I_CANTIDAD_BONIFICADA <= 0 OR @I_CANTIDAD_BONIFICADA > @I_CANTIDAD_REQUERIDA OR @I_PORCENTAJE_DESCUENTO IS NULL OR @I_PORCENTAJE_DESCUENTO <= 0 OR @I_PORCENTAJE_DESCUENTO > 1 OR @I_PRECIO_PAQUETE IS NOT NULL))
       OR (@I_TIPO_PROMOCION = N'PRECIO_PAQUETE' AND (@I_CANTIDAD_PAGADA IS NOT NULL OR @I_CANTIDAD_BONIFICADA IS NOT NULL OR @I_PORCENTAJE_DESCUENTO IS NOT NULL OR @I_PRECIO_PAQUETE IS NULL OR @I_PRECIO_PAQUETE < 0))
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'La definición de la promoción no es válida para el tipo seleccionado.';
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM [INVENTARIO].[PRODUCTOS] WHERE [ID_PRODUCTO] = @I_ID_PRODUCTO AND [ID_EMPRESA] = @I_ID_EMPRESA)
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'El producto de la promoción no pertenece a la empresa.';
        RETURN;
    END;

    IF EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO] = @I_CODIGO AND (@I_ID_PROMOCION IS NULL OR [ID_PROMOCION] <> @I_ID_PROMOCION))
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'Ya existe una promoción con ese código en la empresa.';
        RETURN;
    END;
    -- FIN: Validación completa de la regla antes de conservarla.

    BEGIN TRY
        IF @I_ID_PROMOCION IS NULL
        BEGIN
            INSERT INTO [COMERCIAL].[PROMOCIONES]
                ([ID_EMPRESA], [ID_PRODUCTO], [CODIGO], [NOMBRE], [DESCRIPCION], [TIPO_PROMOCION], [CANTIDAD_REQUERIDA], [CANTIDAD_PAGADA], [CANTIDAD_BONIFICADA], [PORCENTAJE_DESCUENTO], [PRECIO_PAQUETE], [FECHA_VIGENCIA_DESDE], [FECHA_VIGENCIA_HASTA], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
            VALUES
                (@I_ID_EMPRESA, @I_ID_PRODUCTO, @I_CODIGO, @I_NOMBRE, NULLIF(LTRIM(RTRIM(@I_DESCRIPCION)), N''), @I_TIPO_PROMOCION, @I_CANTIDAD_REQUERIDA, @I_CANTIDAD_PAGADA, @I_CANTIDAD_BONIFICADA, @I_PORCENTAJE_DESCUENTO, @I_PRECIO_PAQUETE, @I_FECHA_VIGENCIA_DESDE, @I_FECHA_VIGENCIA_HASTA, @I_CODIGO_ESTADO, @S_ID_USUARIO);
            SET @O_ID_PROMOCION = CONVERT(BIGINT, SCOPE_IDENTITY());
            SET @O_FILAS_AFECTADAS = 1;
            RETURN;
        END;

    IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PROMOCIONES] WHERE [ID_PROMOCION] = @I_ID_PROMOCION AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ID_PRODUCTO] = @I_ID_PRODUCTO AND [CODIGO] = @I_CODIGO)
    BEGIN
        SET @O_CODIGO_ERROR = 40008;
        SET @O_MENSAJE = N'El código y el producto de una promoción existente no se pueden reemplazar.';
        RETURN;
    END;

    UPDATE [COMERCIAL].[PROMOCIONES]
    SET [NOMBRE] = @I_NOMBRE,
        [DESCRIPCION] = NULLIF(LTRIM(RTRIM(@I_DESCRIPCION)), N''),
        [TIPO_PROMOCION] = @I_TIPO_PROMOCION,
        [CANTIDAD_REQUERIDA] = @I_CANTIDAD_REQUERIDA,
        [CANTIDAD_PAGADA] = @I_CANTIDAD_PAGADA,
        [CANTIDAD_BONIFICADA] = @I_CANTIDAD_BONIFICADA,
        [PORCENTAJE_DESCUENTO] = @I_PORCENTAJE_DESCUENTO,
        [PRECIO_PAQUETE] = @I_PRECIO_PAQUETE,
        [FECHA_VIGENCIA_DESDE] = @I_FECHA_VIGENCIA_DESDE,
        [FECHA_VIGENCIA_HASTA] = @I_FECHA_VIGENCIA_HASTA,
        [CODIGO_ESTADO] = @I_CODIGO_ESTADO,
        [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(),
        [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO
    WHERE [ID_PROMOCION] = @I_ID_PROMOCION AND [ID_EMPRESA] = @I_ID_EMPRESA AND [ROW_VERSION] = @I_ROW_VERSION;

        SET @O_FILAS_AFECTADAS = @@ROWCOUNT;
        IF @O_FILAS_AFECTADAS = 0
        BEGIN
            SET @O_CODIGO_ERROR = 40007;
            SET @O_MENSAJE = N'La promoción fue modificada por otro usuario o ya no pertenece a la empresa.';
        END;
    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() IN (2601, 2627)
        BEGIN
            SET @O_CODIGO_ERROR = 40008;
            SET @O_MENSAJE = N'Ya existe una promoción con ese código en la empresa.';
            RETURN;
        END;
        THROW;
    END CATCH;
END;
