/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_VENTA_CREATE_FROM_PEDIDO
Archivo: SP_VENTA_CREATE_FROM_PEDIDO.sql | Procedimiento: COMERCIAL.SP_VENTA_CREATE_FROM_PEDIDO | Tipo: COMMAND
Versión: 11.0.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Convierte un pedido confirmado en venta interna y descuenta el stock reservado.
Parámetros de entrada: @I_FECHA_VENTA_UTC, @I_ID_EMPRESA, @I_ID_PEDIDO, @I_ROW_VERSION, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_FILAS_AFECTADAS, @O_ID_VENTA, @O_MENSAJE.
Retorno: Informa el resultado mediante los parámetros de salida declarados.
Tablas utilizadas: COMERCIAL.PEDIDOS - SELECT/UPDATE; COMERCIAL.PEDIDOS_DETALLES - SELECT; COMERCIAL.VENTAS - INSERT/SELECT; COMERCIAL.VENTAS_DETALLES - INSERT; FINANZAS.MOVIMIENTOS_CUENTA - INSERT; INVENTARIO.PRODUCTOS - SELECT; INVENTARIO.RESERVAS_STOCK - SELECT/UPDATE.
Transacción: Abre una transacción explícita para agrupar sus escrituras.
Auditoría: No registra auditoría explícita dentro del procedimiento.
Historial: 1.0.0 | 2026-08-20 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Copia la fotografía promocional a la venta inmutable.
Historial: 1.1.1 | 2026-08-21 | FABRICA | Agustin Omar Cauzi | Opciones ANSI explícitas para un despliegue SQL consistente.
Historial: 11.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Débito automático e inmutable en cuenta corriente.
Historial: 11.0.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [COMERCIAL].[SP_VENTA_CREATE_FROM_PEDIDO]
    @I_ID_PEDIDO BIGINT, @I_ID_EMPRESA BIGINT, @I_FECHA_VENTA_UTC DATETIME2(3), @I_ROW_VERSION BINARY(8),
    @S_ID_SESION BIGINT, @S_ID_USUARIO BIGINT, @O_ID_VENTA BIGINT OUTPUT, @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT, @O_FILAS_AFECTADAS INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON; SET @O_ID_VENTA = NULL; SET @O_CODIGO_ERROR = NULL; SET @O_MENSAJE = NULL; SET @O_FILAS_AFECTADAS = 0;
    IF @I_FECHA_VENTA_UTC IS NULL THROW 50000, 'La fecha de venta es obligatoria.', 1;
    DECLARE @V_INICIO_TRANSACCION BIT = 0, @V_ID_MOVIMIENTO BIGINT, @V_CODIGO_MOVIMIENTO BIGINT, @V_MENSAJE_MOVIMIENTO NVARCHAR(4000), @V_FILAS_MOVIMIENTO INT;
    BEGIN TRY
        IF @@TRANCOUNT = 0 BEGIN BEGIN TRANSACTION; SET @V_INICIO_TRANSACCION = 1; END ELSE SAVE TRANSACTION [SP_VENTA_CREATE_SAVEPOINT];
        IF NOT EXISTS (SELECT 1 FROM [COMERCIAL].[PEDIDOS] WITH (UPDLOCK, HOLDLOCK) WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [ID_EMPRESA] = @I_ID_EMPRESA AND [CODIGO_ESTADO] = N'CONFIRMADO' AND [ROW_VERSION] = @I_ROW_VERSION)
        BEGIN SET @O_CODIGO_ERROR = 40006; SET @O_MENSAJE = N'El pedido fue modificado o no está confirmado.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;
        IF EXISTS
        (
            SELECT 1
            FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET]
            INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
            WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
              AND [PRO].[TIPO_ITEM] = N'PRODUCTO'
              AND NOT EXISTS (SELECT 1 FROM [INVENTARIO].[RESERVAS_STOCK] AS [RES] WHERE [RES].[ID_PEDIDO_DETALLE] = [DET].[ID_PEDIDO_DETALLE] AND [RES].[CODIGO_ESTADO] = N'RESERVADA' AND [RES].[CANTIDAD] = [DET].[CANTIDAD])
        )
        BEGIN SET @O_CODIGO_ERROR = 40005; SET @O_MENSAJE = N'El pedido no conserva todas sus reservas de stock.'; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; RETURN; END;

        IF EXISTS
        (
            SELECT 1 FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET]
            INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
            WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
              AND [PRO].[TIPO_ITEM] = N'PRODUCTO'
        )
        BEGIN
            DECLARE @V_DETALLES_JSON NVARCHAR(MAX) =
            (
                SELECT [DET].[ID_PRODUCTO] AS [ProductId], [DET].[ID_DEPOSITO] AS [OriginWarehouseId], [DET].[CANTIDAD] AS [Quantity]
                FROM [COMERCIAL].[PEDIDOS_DETALLES] AS [DET]
                INNER JOIN [INVENTARIO].[PRODUCTOS] AS [PRO] ON [PRO].[ID_PRODUCTO] = [DET].[ID_PRODUCTO]
                WHERE [DET].[ID_PEDIDO] = @I_ID_PEDIDO AND [DET].[CODIGO_ESTADO] = N'ACTIVO'
                  AND [PRO].[TIPO_ITEM] = N'PRODUCTO'
                FOR JSON PATH
            );
            DECLARE @V_OBSERVACION_MOVIMIENTO NVARCHAR(500) = N'Venta originada por pedido ' + CONVERT(NVARCHAR(30), @I_ID_PEDIDO);
            EXEC [INVENTARIO].[SP_MOVIMIENTO_CREATE] @I_ID_EMPRESA = @I_ID_EMPRESA, @I_TIPO_MOVIMIENTO = N'SALIDA', @I_FECHA_MOVIMIENTO_UTC = @I_FECHA_VENTA_UTC,
                @I_OBSERVACION = @V_OBSERVACION_MOVIMIENTO, @I_DETALLES_JSON = @V_DETALLES_JSON, @I_ID_PEDIDO_RESERVADO = @I_ID_PEDIDO,
                @S_ID_SESION = @S_ID_SESION, @S_ID_USUARIO = @S_ID_USUARIO, @O_ID_MOVIMIENTO = @V_ID_MOVIMIENTO OUTPUT, @O_CODIGO_ERROR = @V_CODIGO_MOVIMIENTO OUTPUT,
                @O_MENSAJE = @V_MENSAJE_MOVIMIENTO OUTPUT, @O_FILAS_AFECTADAS = @V_FILAS_MOVIMIENTO OUTPUT;
            IF @V_CODIGO_MOVIMIENTO IS NOT NULL BEGIN SET @O_CODIGO_ERROR = @V_CODIGO_MOVIMIENTO; SET @O_MENSAJE = @V_MENSAJE_MOVIMIENTO; IF @V_INICIO_TRANSACCION = 1 ROLLBACK TRANSACTION; ELSE ROLLBACK TRANSACTION [SP_VENTA_CREATE_SAVEPOINT]; RETURN; END;
        END;

        DECLARE @V_NUMERO BIGINT = NEXT VALUE FOR [COMERCIAL].[SEQ_VENTA_CODIGO], @V_CODIGO NVARCHAR(30);
        SET @V_CODIGO = N'VEN-' + CASE WHEN @V_NUMERO < 1000000 THEN RIGHT(REPLICATE(N'0', 6) + CONVERT(NVARCHAR(20), @V_NUMERO), 6) ELSE CONVERT(NVARCHAR(20), @V_NUMERO) END;
        INSERT INTO [COMERCIAL].[VENTAS] ([ID_EMPRESA], [ID_PEDIDO], [ID_CLIENTE], [ID_MOVIMIENTO], [CODIGO], [FECHA_VENTA_UTC], [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT [ID_EMPRESA], [ID_PEDIDO], [ID_CLIENTE], @V_ID_MOVIMIENTO, @V_CODIGO, @I_FECHA_VENTA_UTC, [MONEDA], [SUBTOTAL], [TOTAL_DESCUENTO], [TOTAL_IMPUESTO], [TOTAL], [OBSERVACION], N'CONFIRMADA', @S_ID_USUARIO FROM [COMERCIAL].[PEDIDOS] WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        SET @O_ID_VENTA = CONVERT(BIGINT, SCOPE_IDENTITY());

        -- INICIO: La venta genera el débito base de la cuenta corriente sin duplicar saldos.
        INSERT INTO [FINANZAS].[MOVIMIENTOS_CUENTA]
        (
            [ID_EMPRESA], [ID_CLIENTE], [ID_VENTA], [TIPO_MOVIMIENTO], [ORIGEN],
            [FECHA_MOVIMIENTO_UTC], [MONEDA], [IMPORTE], [DESCRIPCION], [ID_USUARIO_ALTA]
        )
        SELECT [ID_EMPRESA], [ID_CLIENTE], [ID_VENTA], N'DEBITO', N'VENTA',
               [FECHA_VENTA_UTC], [MONEDA], [TOTAL], N'Venta interna ' + [CODIGO], @S_ID_USUARIO
        FROM [COMERCIAL].[VENTAS]
        WHERE [ID_VENTA] = @O_ID_VENTA;
        -- FIN: La venta genera el débito base de la cuenta corriente sin duplicar saldos.

        INSERT INTO [COMERCIAL].[VENTAS_DETALLES] ([ID_VENTA], [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], [CODIGO_ESTADO], [ID_USUARIO_ALTA])
        SELECT @O_ID_VENTA, [ID_PRODUCTO], [ID_DEPOSITO], [ID_PROMOCION], [CODIGO_PROMOCION], [NOMBRE_PROMOCION], [CANTIDAD], [PRECIO_UNITARIO], [PORCENTAJE_DESCUENTO], [PORCENTAJE_IMPUESTO], [SUBTOTAL], [IMPORTE_DESCUENTO], [IMPORTE_IMPUESTO], [TOTAL], N'ACTIVO', @S_ID_USUARIO FROM [COMERCIAL].[PEDIDOS_DETALLES] WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'ACTIVO';
        SET @O_FILAS_AFECTADAS = 2 + @@ROWCOUNT + COALESCE(@V_FILAS_MOVIMIENTO, 0);
        UPDATE [INVENTARIO].[RESERVAS_STOCK] SET [CODIGO_ESTADO] = N'APLICADA', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO AND [CODIGO_ESTADO] = N'RESERVADA';
        UPDATE [COMERCIAL].[PEDIDOS] SET [CODIGO_ESTADO] = N'VENDIDO', [FECHA_MODIFICACION_UTC] = SYSUTCDATETIME(), [ID_USUARIO_MODIFICACION] = @S_ID_USUARIO WHERE [ID_PEDIDO] = @I_ID_PEDIDO;
        IF @V_INICIO_TRANSACCION = 1 COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @V_INICIO_TRANSACCION = 1 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION; ELSE IF XACT_STATE() = 1 ROLLBACK TRANSACTION [SP_VENTA_CREATE_SAVEPOINT]; SET @O_MENSAJE = ERROR_MESSAGE(); THROW;
    END CATCH;
END;
