/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: SP_LOGISTICA_GET
Archivo: SP_LOGISTICA_GET.sql | Procedimiento: LOGISTICA.SP_LOGISTICA_GET | Tipo: QUERY
Versión: 1.2.1 | Fecha: 2026-09-20 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Recupera agenda, custodia, hojas históricas, eventos y avisos de la empresa autenticada.
Parámetros de entrada: @I_ID_EMPRESA, @S_ID_SESION, @S_ID_USUARIO.
Parámetros de salida: @O_CODIGO_ERROR, @O_MENSAJE.
Retorno: Devuelve los conjuntos de filas definidos por sus SELECT finales.
Tablas utilizadas: COMERCIAL.CLIENTES - SELECT; COMERCIAL.PEDIDOS - SELECT; COMERCIAL.PEDIDOS_ACTIVOS - SELECT; COMERCIAL.VENTAS - SELECT; FINANZAS.APLICACIONES_PAGO_VENTA - SELECT; FINANZAS.PAGOS - SELECT; INVENTARIO.DEPOSITOS - SELECT; LOGISTICA.CLIENTES_DIRECCIONES - SELECT; LOGISTICA.EVENTOS - SELECT; LOGISTICA.HOJAS_RUTA - SELECT; LOGISTICA.HOJAS_RUTA_PARADAS - SELECT; LOGISTICA.NOTIFICACIONES - SELECT; LOGISTICA.SOLICITUDES - SELECT; LOGISTICA.SOLICITUDES_ACTIVOS - SELECT; LOGISTICA.TRANSPORTISTAS - SELECT; LOGISTICA.VEHICULOS - SELECT; SEGURIDAD.ROLES - SELECT; SEGURIDAD.USUARIOS - SELECT; SEGURIDAD.USUARIOS_ROLES - SELECT.
Transacción: No abre una transacción explícita; realiza operaciones de lectura.
Auditoría: No registra auditoría explícita porque no modifica estado.
Historial: 1.0.0 | 2026-08-26 | FABRICA | Agustin Omar Cauzi | Creación inicial.
Historial: 1.1.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Maestros de transporte y vínculos históricos de ruta.
Historial: 1.2.0 | 2026-08-28 | FABRICA | Agustin Omar Cauzi | Pedidos candidatos, estado de pago, depósitos y custodia formal.
Historial: 1.2.1 | 2026-09-20 | FABRICA | Agustin Omar Cauzi | Documentación técnica completa del procedimiento.
===============================================================================
*/
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [LOGISTICA].[SP_LOGISTICA_GET]
    @I_ID_EMPRESA BIGINT,
    @S_ID_SESION BIGINT,
    @S_ID_USUARIO BIGINT,
    @O_CODIGO_ERROR BIGINT OUTPUT,
    @O_MENSAJE NVARCHAR(4000) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @O_CODIGO_ERROR = NULL;
    SET @O_MENSAJE = NULL;

    -- INICIO: Direcciones y ventanas de atención configuradas.
    SELECT [DIR].[ID_DIRECCION], [DIR].[ID_CLIENTE], [DIR].[CODIGO], [DIR].[NOMBRE],
           CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [DIR].[DOMICILIO], [DIR].[LOCALIDAD], [DIR].[PROVINCIA], [DIR].[CODIGO_POSTAL],
           [DIR].[LATITUD], [DIR].[LONGITUD], [DIR].[CONTACTO], [DIR].[TELEFONO], [DIR].[CORREO],
           [DIR].[HORA_DESDE], [DIR].[HORA_HASTA], [DIR].[MINUTOS_SERVICIO], [DIR].[RESTRICCIONES],
           [DIR].[INSTRUCCIONES], [DIR].[CODIGO_ESTADO], [DIR].[ROW_VERSION]
    FROM [LOGISTICA].[CLIENTES_DIRECCIONES] AS [DIR]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [DIR].[ID_CLIENTE]
    WHERE [DIR].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [CLIENTE], [DIR].[NOMBRE];
    -- FIN: Direcciones y ventanas de atención configuradas.

    -- INICIO: Solicitudes pendientes e históricas.
    SELECT [SOL].[ID_SOLICITUD], [SOL].[ID_CLIENTE], [SOL].[ID_DIRECCION], [SOL].[ID_PEDIDO],
           [SOL].[CODIGO], CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [DIR].[DOMICILIO], [SOL].[TIPO_SERVICIO], [SOL].[PRIORIDAD], [SOL].[FECHA_SOLICITADA],
           [SOL].[HORA_DESDE], [SOL].[HORA_HASTA], [SOL].[INSTRUCCIONES], [SOL].[OBSERVACION],
           [SOL].[CODIGO_ESTADO], [SOL].[ROW_VERSION], [SOL].[ID_DEPOSITO_DESTINO],
           [DEP].[NOMBRE] AS [DEPOSITO_DESTINO]
    FROM [LOGISTICA].[SOLICITUDES] AS [SOL]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [SOL].[ID_CLIENTE]
    INNER JOIN [LOGISTICA].[CLIENTES_DIRECCIONES] AS [DIR] ON [DIR].[ID_DIRECCION] = [SOL].[ID_DIRECCION]
    LEFT JOIN [INVENTARIO].[DEPOSITOS] AS [DEP] ON [DEP].[ID_DEPOSITO] = [SOL].[ID_DEPOSITO_DESTINO]
    WHERE [SOL].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [SOL].[FECHA_SOLICITADA] DESC, [SOL].[PRIORIDAD] DESC, [SOL].[ID_SOLICITUD] DESC;
    -- FIN: Solicitudes pendientes e históricas.

    SELECT [ACT].[ID_SOLICITUD_ACTIVO], [ACT].[ID_SOLICITUD], [ACT].[ID_ACTIVO], [ACT].[PROPIETARIO],
           [ACT].[ROL], [ACT].[NUMERO_SERIE], [ACT].[PRODUCTO], [ACT].[CANTIDAD_CONTENIDO], [ACT].[UNIDAD],
           [ACT].[CONDICION], [ACT].[OBSERVACION], [ACT].[CODIGO_ESTADO],
           [ACT].[FECHA_DEVOLUCION_PREVISTA], [ACT].[ID_PRESTAMO]
    FROM [LOGISTICA].[SOLICITUDES_ACTIVOS] AS [ACT]
    INNER JOIN [LOGISTICA].[SOLICITUDES] AS [SOL] ON [SOL].[ID_SOLICITUD] = [ACT].[ID_SOLICITUD]
    WHERE [SOL].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [ACT].[ID_SOLICITUD], [ACT].[ID_SOLICITUD_ACTIVO];

    -- INICIO: Hojas de ruta; nunca se eliminan para conservar el historial.
    SELECT [HOJ].[ID_HOJA_RUTA], [HOJ].[ID_TRANSPORTISTA], [HOJ].[ID_VEHICULO],
           [HOJ].[CODIGO], [HOJ].[FECHA_RUTA], [HOJ].[TIPO_RUTA], [HOJ].[TIPO_ASIGNACION],
           [HOJ].[CHOFER], [HOJ].[PATENTE], [HOJ].[OBSERVACION], [HOJ].[FECHA_ASIGNACION_UTC],
           [HOJ].[FECHA_SALIDA_UTC], [HOJ].[FECHA_CIERRE_UTC], [HOJ].[CODIGO_ESTADO], [HOJ].[ROW_VERSION]
    FROM [LOGISTICA].[HOJAS_RUTA] AS [HOJ]
    WHERE [HOJ].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [HOJ].[FECHA_RUTA] DESC, [HOJ].[ID_HOJA_RUTA] DESC;

    SELECT [PAR].[ID_PARADA], [PAR].[ID_HOJA_RUTA], [PAR].[ID_SOLICITUD], [PAR].[ORDEN], [PAR].[CLIENTE],
           [PAR].[DOMICILIO], [PAR].[CONTACTO], [PAR].[TELEFONO], [PAR].[HORA_DESDE], [PAR].[HORA_HASTA],
           [PAR].[PRIORIDAD], [PAR].[INSTRUCCIONES], [PAR].[FECHA_LLEGADA_UTC], [PAR].[FECHA_SALIDA_UTC],
           [PAR].[RESULTADO], [PAR].[OBSERVACION_RESULTADO], [PAR].[CODIGO_ESTADO], [PAR].[ROW_VERSION]
    FROM [LOGISTICA].[HOJAS_RUTA_PARADAS] AS [PAR]
    INNER JOIN [LOGISTICA].[HOJAS_RUTA] AS [HOJ] ON [HOJ].[ID_HOJA_RUTA] = [PAR].[ID_HOJA_RUTA]
    WHERE [HOJ].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [HOJ].[FECHA_RUTA] DESC, [PAR].[ORDEN];
    -- FIN: Hojas de ruta; nunca se eliminan para conservar el historial.

    SELECT TOP (1000) [EVE].[ID_EVENTO], [EVE].[ID_SOLICITUD], [EVE].[ID_HOJA_RUTA], [EVE].[ID_PARADA],
           [EVE].[TIPO_EVENTO], [EVE].[ESTADO_ANTERIOR], [EVE].[ESTADO_NUEVO], [EVE].[OBSERVACION],
           [EVE].[ID_USUARIO], [EVE].[ID_SESION], [EVE].[CORRELACION], [EVE].[FECHA_UTC]
    FROM [LOGISTICA].[EVENTOS] AS [EVE]
    WHERE [EVE].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [EVE].[FECHA_UTC] DESC;

    SELECT TOP (1000) [NOT].[ID_NOTIFICACION], [NOT].[ID_SOLICITUD], [NOT].[ID_HOJA_RUTA],
           [NOT].[TIPO_EVENTO], [NOT].[CANAL], [NOT].[DESTINATARIO], [NOT].[MENSAJE], [NOT].[INTENTOS],
           [NOT].[CODIGO_ESTADO], [NOT].[FECHA_ALTA_UTC], [NOT].[FECHA_ENVIO_UTC]
    FROM [LOGISTICA].[NOTIFICACIONES] AS [NOT]
    WHERE [NOT].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [NOT].[FECHA_ALTA_UTC] DESC;

    SELECT [CLI].[ID_CLIENTE], [CLI].[CODIGO], CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE]
    FROM [COMERCIAL].[CLIENTES] AS [CLI]
    WHERE [CLI].[ID_EMPRESA] = @I_ID_EMPRESA AND [CLI].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [CLIENTE];

    -- INICIO: Perfiles transportistas vinculados a usuarios de aplicación.
    SELECT [TRA].[ID_TRANSPORTISTA], [TRA].[ID_USUARIO], [TRA].[CODIGO], [USR].[NOMBRE_USUARIO],
           CONCAT_WS(N' ', [USR].[NOMBRES], [USR].[APELLIDO]) AS [NOMBRE_COMPLETO],
           [TRA].[TIPO_VINCULO], [TRA].[DOCUMENTO], [TRA].[TELEFONO], [TRA].[LICENCIA],
           [TRA].[CATEGORIA_LICENCIA], [TRA].[VENCIMIENTO_LICENCIA], [TRA].[OBSERVACION],
           [TRA].[CODIGO_ESTADO], [TRA].[ROW_VERSION]
    FROM [LOGISTICA].[TRANSPORTISTAS] AS [TRA]
    INNER JOIN [SEGURIDAD].[USUARIOS] AS [USR] ON [USR].[ID_USUARIO] = [TRA].[ID_USUARIO]
    WHERE [TRA].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [NOMBRE_COMPLETO];

    SELECT [VEH].[ID_VEHICULO], [VEH].[ID_TRANSPORTISTA_PROPIETARIO], [VEH].[CODIGO], [VEH].[PATENTE],
           [VEH].[TIPO_VEHICULO], [VEH].[TIPO_PROPIEDAD],
           CONCAT_WS(N' ', [USR].[NOMBRES], [USR].[APELLIDO]) AS [PROPIETARIO],
           [VEH].[MARCA], [VEH].[MODELO], [VEH].[ANIO], [VEH].[CAPACIDAD_CARGA_KG],
           [VEH].[POLIZA_SEGURO], [VEH].[VENCIMIENTO_SEGURO], [VEH].[VENCIMIENTO_REVISION],
           [VEH].[OBSERVACION], [VEH].[CODIGO_ESTADO], [VEH].[ROW_VERSION]
    FROM [LOGISTICA].[VEHICULOS] AS [VEH]
    LEFT JOIN [LOGISTICA].[TRANSPORTISTAS] AS [TRA]
        ON [TRA].[ID_TRANSPORTISTA] = [VEH].[ID_TRANSPORTISTA_PROPIETARIO]
    LEFT JOIN [SEGURIDAD].[USUARIOS] AS [USR] ON [USR].[ID_USUARIO] = [TRA].[ID_USUARIO]
    WHERE [VEH].[ID_EMPRESA] = @I_ID_EMPRESA
    ORDER BY [VEH].[PATENTE];

    SELECT DISTINCT [USR].[ID_USUARIO], [USR].[NOMBRE_USUARIO],
           CONCAT_WS(N' ', [USR].[NOMBRES], [USR].[APELLIDO]) AS [NOMBRE_COMPLETO]
    FROM [SEGURIDAD].[USUARIOS] AS [USR]
    INNER JOIN [SEGURIDAD].[USUARIOS_ROLES] AS [UR]
        ON [UR].[ID_USUARIO] = [USR].[ID_USUARIO] AND [UR].[CODIGO_ESTADO] = N'ACTIVO'
    INNER JOIN [SEGURIDAD].[ROLES] AS [ROL]
        ON [ROL].[ID_ROL] = [UR].[ID_ROL] AND [ROL].[CODIGO] = N'TRANSPORTISTA'
    WHERE [USR].[ID_EMPRESA] = @I_ID_EMPRESA AND [USR].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [NOMBRE_COMPLETO];
    -- FIN: Perfiles transportistas vinculados a usuarios de aplicación.

    -- INICIO: Retiros y entregas pendientes derivados del pedido, sin duplicar la carga comercial.
    ;WITH [SALDOS] AS
    (
        SELECT [VEN].[ID_PEDIDO], [VEN].[TOTAL],
               [VEN].[TOTAL] - COALESCE(SUM(CASE
                   WHEN [PAG].[CODIGO_ESTADO] = N'CONFIRMADO'
                    AND [APL].[CODIGO_ESTADO] = N'APLICADA'
                   THEN [APL].[IMPORTE]
                   ELSE 0
               END), 0) AS [SALDO_PENDIENTE]
        FROM [COMERCIAL].[VENTAS] AS [VEN]
        LEFT JOIN [FINANZAS].[APLICACIONES_PAGO_VENTA] AS [APL]
            ON [APL].[ID_VENTA] = [VEN].[ID_VENTA]
        LEFT JOIN [FINANZAS].[PAGOS] AS [PAG]
            ON [PAG].[ID_PAGO] = [APL].[ID_PAGO]
        WHERE [VEN].[ID_EMPRESA] = @I_ID_EMPRESA
        GROUP BY [VEN].[ID_PEDIDO], [VEN].[TOTAL]
    )
    SELECT [PED].[ID_PEDIDO], [PED].[ID_CLIENTE], [PED].[CODIGO] AS [PEDIDO],
           CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO]) AS [CLIENTE],
           [OPE].[OPERACION], [OPE].[TIPO_SERVICIO], CONVERT(DATE, [PED].[FECHA_PEDIDO_UTC]) AS [FECHA_PEDIDO],
           [PED].[TOTAL], [SAL].[SALDO_PENDIENTE],
           CASE
               WHEN [SAL].[ID_PEDIDO] IS NULL THEN N'VENTA_PENDIENTE'
               WHEN [SAL].[SALDO_PENDIENTE] <= 0 THEN N'PAGADO'
               WHEN [SAL].[SALDO_PENDIENTE] < [SAL].[TOTAL] THEN N'PAGO_PARCIAL'
               ELSE N'PENDIENTE'
           END AS [ESTADO_PAGO],
           (SELECT COUNT(*)
            FROM [COMERCIAL].[PEDIDOS_ACTIVOS] AS [ACT]
            WHERE [ACT].[ID_PEDIDO] = [PED].[ID_PEDIDO]
              AND [ACT].[CODIGO_ESTADO] = N'ACTIVO'
              AND
              (
                  [OPE].[OPERACION] = N'RETIRO' AND [ACT].[MODALIDAD_INGRESO] = N'RETIRO_OXITIGRE'
                  OR [OPE].[OPERACION] = N'ENTREGA' AND [ACT].[MODALIDAD_RETORNO] = N'ENTREGA_OXITIGRE'
              )) AS [CANTIDAD_ACTIVOS],
           (SELECT MAX([ACT].[FECHA_DEVOLUCION_PREVISTA])
            FROM [COMERCIAL].[PEDIDOS_ACTIVOS] AS [ACT]
            WHERE [ACT].[ID_PEDIDO] = [PED].[ID_PEDIDO]
              AND [ACT].[CODIGO_ESTADO] = N'ACTIVO') AS [FECHA_DEVOLUCION_PREVISTA],
           CONCAT([PED].[CODIGO], N' · ', [OPE].[OPERACION], N' · ',
                  CONCAT_WS(N' ', [CLI].[NOMBRE_RAZON_SOCIAL], [CLI].[APELLIDO])) AS [RESUMEN]
    FROM [COMERCIAL].[PEDIDOS] AS [PED]
    INNER JOIN [COMERCIAL].[CLIENTES] AS [CLI] ON [CLI].[ID_CLIENTE] = [PED].[ID_CLIENTE]
    CROSS APPLY
    (
        VALUES
            (N'RETIRO', N'RETIRO_RECARGA'),
            (N'ENTREGA', N'ENTREGA_PEDIDO')
    ) AS [OPE] ([OPERACION], [TIPO_SERVICIO])
    LEFT JOIN [SALDOS] AS [SAL] ON [SAL].[ID_PEDIDO] = [PED].[ID_PEDIDO]
    WHERE [PED].[ID_EMPRESA] = @I_ID_EMPRESA
      AND [PED].[CODIGO_ESTADO] IN (N'CONFIRMADO', N'VENDIDO')
      AND EXISTS
      (
          SELECT 1
          FROM [COMERCIAL].[PEDIDOS_ACTIVOS] AS [ACT]
          WHERE [ACT].[ID_PEDIDO] = [PED].[ID_PEDIDO]
            AND [ACT].[CODIGO_ESTADO] = N'ACTIVO'
            AND
            (
                [OPE].[OPERACION] = N'RETIRO' AND [ACT].[MODALIDAD_INGRESO] = N'RETIRO_OXITIGRE'
                OR [OPE].[OPERACION] = N'ENTREGA' AND [ACT].[MODALIDAD_RETORNO] = N'ENTREGA_OXITIGRE'
            )
      )
      AND NOT EXISTS
      (
          SELECT 1
          FROM [LOGISTICA].[SOLICITUDES] AS [SOL]
          WHERE [SOL].[ID_PEDIDO] = [PED].[ID_PEDIDO]
            AND [SOL].[TIPO_SERVICIO] = [OPE].[TIPO_SERVICIO]
            AND [SOL].[CODIGO_ESTADO] <> N'CANCELADA'
      )
    ORDER BY [PED].[FECHA_PEDIDO_UTC], [PED].[ID_PEDIDO], [OPE].[OPERACION] DESC;
    -- FIN: Retiros y entregas pendientes derivados del pedido, sin duplicar la carga comercial.

    SELECT [DEP].[ID_DEPOSITO], [DEP].[CODIGO], [DEP].[NOMBRE]
    FROM [INVENTARIO].[DEPOSITOS] AS [DEP]
    WHERE [DEP].[ID_EMPRESA] = @I_ID_EMPRESA
      AND [DEP].[CODIGO_ESTADO] = N'ACTIVO'
    ORDER BY [DEP].[NOMBRE];
END;
