/*
===============================================================================
Proyecto: Sistema Modular de Gestión OxiTigre
Componente: PLATAFORMA.EMPRESAS_BASES
Archivo: EMPRESAS_BASES.sql | Versión: 1.0.0 | Fecha: 2026-08-27 | ID pedido: FABRICA
Desarrollador: Agustin Omar Cauzi | Correo: agustincauzi10@hotmail.com
Descripción funcional: Registra ubicación, empresa local y versión de cada base operativa aislada.
Historial: 1.0.0 | 2026-08-27 | FABRICA | Agustin Omar Cauzi | Creación inicial.
===============================================================================
*/
IF OBJECT_ID(N'PLATAFORMA.EMPRESAS_BASES', N'U') IS NULL
BEGIN
    CREATE TABLE [PLATAFORMA].[EMPRESAS_BASES]
    (
        [ID_EMPRESA_PLATAFORMA] BIGINT IDENTITY(1,1) NOT NULL,
        [CODIGO] NVARCHAR(30) NOT NULL,
        [RAZON_SOCIAL] NVARCHAR(200) NOT NULL,
        [SERVIDOR_SQL] NVARCHAR(200) NOT NULL,
        [BASE_DATOS] SYSNAME NOT NULL,
        [ID_EMPRESA_LOCAL] BIGINT NOT NULL,
        [VERSION_ESQUEMA] NVARCHAR(30) NOT NULL,
        [CIFRAR_CONEXION] BIT NOT NULL CONSTRAINT [DF_EMPRESAS_BASES_CIFRAR] DEFAULT (1),
        [CONFIAR_CERTIFICADO] BIT NOT NULL CONSTRAINT [DF_EMPRESAS_BASES_CONFIAR] DEFAULT (0),
        [SECRETO_REFERENCIA] NVARCHAR(300) NULL,
        [CODIGO_ESTADO] NVARCHAR(30) NOT NULL CONSTRAINT [DF_EMPRESAS_BASES_ESTADO] DEFAULT (N'ACTIVO'),
        [FECHA_ALTA_UTC] DATETIME2(3) NOT NULL CONSTRAINT [DF_EMPRESAS_BASES_FECHA_ALTA] DEFAULT (SYSUTCDATETIME()),
        [FECHA_MODIFICACION_UTC] DATETIME2(3) NULL,
        [ROW_VERSION] ROWVERSION NOT NULL,
        CONSTRAINT [PK_EMPRESAS_BASES] PRIMARY KEY CLUSTERED ([ID_EMPRESA_PLATAFORMA]),
        CONSTRAINT [UX_EMPRESAS_BASES_CODIGO] UNIQUE ([CODIGO]),
        CONSTRAINT [UX_EMPRESAS_BASES_DESTINO] UNIQUE ([SERVIDOR_SQL], [BASE_DATOS]),
        CONSTRAINT [CK_EMPRESAS_BASES_ESTADO] CHECK ([CODIGO_ESTADO] IN (N'ACTIVO', N'INACTIVO')),
        CONSTRAINT [CK_EMPRESAS_BASES_SECRETO] CHECK ([SECRETO_REFERENCIA] IS NULL OR LEN([SECRETO_REFERENCIA]) > 0)
    );
END;
